### ISSUE TITLE
Test are failing on windows again

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1014]
```
======================================================================
FAIL: test_tools.test_executables_in
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mel\Documents\xonsh\tests\test_tools.py", line 512, in test_executables_in
    assert_equal(expected, result)
AssertionError: Items in the second set but not the first:
'120'
'26'
'158'
'84'
'30'
'126'
'55'
'115'
'69'
'82'
'3'
'44'
'90'
'155'
'161'
'35'
'134'
'163'
'138'
'157'
'106'
'6'
'149'
'110'
'13'
'53'
'62'
'50'
'81'

----------------------------------------------------------------------
Ran 132617 tests in 29.080s

FAILED (SKIP=8, failures=1)

[x] C:\Users\mel\Documents\xonsh>
```

**Comment by scopatz** [comment]
I saw this error earlier today. I thought I fixed it.

**Comment by scopatz** [comment]
Also - I wised Appveyor didn't hate us :(  Maybe we should email them.

**Comment by scopatz** [comment]
Yeah, I thought I fixed this in #1010

**Comment by melund** [comment]
Oh. This is not a way to write tests. Can we please come up with something simpler and more straight forward. It is breaking on Windows, and my mind is breaking just reading it. 

```
def test_executables_in():
    import pdb;pdb.set_trace()
    expected = set()
    with TemporaryDirectory() as test_path:
        for i in range(random.randint(100, 200)):
            _type = random.choice(('none', 'file', 'file', 'directory'))
            if _type == 'none':
                continue
            executable = random.choice((True, True, False))
            if _type == 'file' and executable:
                expected.add(str(i))
            path = os.path.join(test_path, str(i))
            if _type == 'file':
                open(path, 'w').close()
            elif _type == 'directory':
                os.mkdir(path)
            if executable:
                os.chmod(path, stat.S_IXUSR | stat.S_IRUSR | stat.S_IWUSR)

        result = set(executables_in(test_path))
        assert_equal(expected, result)
```

PEP20 clause 3: "Simple is better than complex". 

Also, I don't think tests should use `random` without a very good reason, and then always with a fixed seed.

**Comment by scopatz** [comment]
I agree that  this test is a little much.  @funkyfuture, would you mind revising it given @melund's feedback? We'd really appreciate it!

**Comment by funkyfuture** [comment]
sorry, i will not have the time soon, neither am i capable on dealing with windows stuff.

**Comment by melund** [comment]
Well. Just fix it when you have the time. I  think it should be quick to write a few simple test cases while you have the code you added in fresh memory. I will help you test it on Windows.

**Comment by scopatz** [comment]
@funkyfuture, also note that I have been experiencing this at random times on linux as well, so this isn't just a windows issue.  Any help you could provide would really be appreciated!

**Comment by scopatz** [comment]
See #1030
