### ISSUE TITLE
SyntaxError shows completely unrelated line

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1090]
Don't know if this is fixable. At https://github.com/asmeurer/dotfiles/commit/c8425a189387633f1f86faa349857eac6c5c644e, I added a syntax error (unclosed `!(`) on line 210. The error given by xonsh is `".xonshrc:171:8: ('code: @(',)").`, that is, a completely unrelated line well above the one with the error. The `@(` in the error message is closed on the same line.

**Comment by scopatz** [comment]
It is not obvious why this is happening.  Thanks for reporting @asmeurer! If you have a simpler example, please post it.

**Comment by asmeurer** [comment]
It's the only instance I've seen.

**Comment by scopatz** [comment]
Ok, so the full traceback on this now appears to be:

```console
scopatz@artemis ~/temp $ xonsh bad.xsh
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19003, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 335, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2694, in p_error
    column=p.lexpos))
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 466, in _parse_error
    raise err
SyntaxError: bad.xsh:214:0: ('code: ![',)
![aliases['it'] = 'git']
^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scopatz/.local/bin/xonsh", line 3, in <module>
    main()
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19525, in main
    _failback_to_other_shells(args, err)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19489, in _failback_to_other_shells
    raise err
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19523, in main
    return main_xonsh(args)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19567, in main_xonsh
    loc=None, mode='exec')
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2164, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2125, in compile_code
    filename=filename)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 18948, in compile
    transform=transform)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 18918, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19061, in _parse_ctx_free
    raise original_error
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19003, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 335, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2694, in p_error
    column=p.lexpos))
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 466, in _parse_error
    raise err
SyntaxError: bad.xsh:171:8: ('code: @(',)
    ssh @(args) < @(stdin)
```

Note that the full traceback does report the error occurring on line 214, the next non-whitespace and non-comment line in the file. This is what one would expect for an unbalanced parentheses. In light of it appearing to work now, I am going to close this issue. Please feel free to reopen if the issue persists.
