### ISSUE TITLE
SyntaxError with xargs Replacement String -I

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1092]
First it works fine with normal cases, e.g. 
`seq 3 | xargs -I"{}" echo "{}"` 
or
 `seq 3 | xargs -Iz echo z`

But when using `{}` as replacement string and without the quotes, it breaks. Do we want to fix issues like this?

```
$ seq 3 | xargs -I{} echo "{}"
..............
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 139, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 288, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/ply/yacc.py", line 325, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/ply/yacc.py", line 1175, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/ply/yacc.py", line 187, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2314, in p_error
    column=p.lexpos))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 383, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:18: ('code: {',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/base_shell.py", line 194, in push
    locs=None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 96, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 71, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 197, in _parse_ctx_free
    raise original_error
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 139, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 288, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/ply/yacc.py", line 325, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/ply/yacc.py", line 1175, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/ply/yacc.py", line 187, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2314, in p_error
    column=p.lexpos))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 383, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:4: ('code: 3',)
```

```
$ xonfig
+------------------+-------+
| xonsh            | 0.3.2 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | None  |
| pygments         | 2.0.2 |
| on posix         | True  |
| on linux         | False |
| on darwin        | True  |
| on windows       | False |
| is superuser     | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by adqm** [comment]
I can't remember if there was a good reason why we didn't let `{}()[]` be treated as part of a "name" in subprocess mode, but that would be what is causing this problem.  Right now, those characters can only be used if they are inside a string.

The question is whether making this change breaks anything else; IIRC, there was a reason they have to be quoted...

**Comment by scopatz** [comment]
I also vaguely recall that there was a reson for not including them, but it may have been a precedence issue with `$[]` and `$()`.

**Comment by scopatz** [comment]
I guess we could always try it, and see if it breaks anything :)

**Comment by scopatz** [comment]
This is related to #2092

**Comment by scopatz** [comment]
I think this is going to be a case where you have to quote.
