### ISSUE TITLE
Deleting a literal in ptk shell breaks xonsh

### ISSUE THREAD

**Issue by adqm** [xonsh/xonsh#1127]
As mentioned in #1124, running, e.g., `del "hello.txt"` breaks xonsh completely when using the prompt toolkit shell.  Seems to be true of `del`-ing any literal value (rather than a variable).

Traceback from @klonuo copied below:
```
klonuo@home C:\temp $ del "test.txt"
Traceback (most recent call last):
  File "C:\Python35\Scripts\xonsh-script.py", line 9, in <module>
    load_entry_point('xonsh==0.3.2', 'console_scripts', 'xonsh')()
  File "c:\python35\lib\site-packages\xonsh\main.py", line 254, in main
    shell.cmdloop()
  File "c:\python35\lib\site-packages\xonsh\ptk\shell.py", line 115, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "c:\python35\lib\site-packages\xonsh\ptk\shell.py", line 84, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "c:\python35\lib\site-packages\xonsh\ptk\shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "c:\python35\lib\site-packages\prompt_toolkit\interface.py", line 387, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "c:\python35\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 78, in run
    callbacks.feed_key(k)
  File "c:\python35\lib\site-packages\prompt_toolkit\interface.py", line 916, in feed_key
    self._active_cli.input_processor.feed_key(key_press)
  File "c:\python35\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 174, in feed_key
    self._process_coroutine.send(key_press)
  File "c:\python35\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 146, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "c:\python35\lib\site-packages\prompt_toolkit\key_binding\input_processor.py", line 190, in _call_handler
    handler.call(event)
  File "c:\python35\lib\site-packages\prompt_toolkit\key_binding\registry.py", line 32, in call
    return self.handler(event)
  File "c:\python35\lib\site-packages\xonsh\ptk\key_bindings.py", line 132, in multiline_carriage_return
    carriage_return(b, event.cli)
  File "c:\python35\lib\site-packages\xonsh\ptk\key_bindings.py", line 55, in carriage_return
    elif not current_line_blank and not can_compile(b.document.text):
  File "c:\python35\lib\site-packages\xonsh\ptk\key_bindings.py", line 102, in can_compile
    locs=builtins.__xonsh_ctx__)
  File "c:\python35\lib\site-packages\xonsh\execer.py", line 99, in compile
    code = compile(tree, filename, mode)
ValueError: expression which can't be assigned to in Del context
```

**Comment by adqm** [comment]
This has been resolved in #1139.  Closing.
