### ISSUE TITLE
ssh ProxyCommand failing

### ISSUE THREAD

**Issue by gregmccoy** [xonsh/xonsh#1133]
I'm getting an error when trying to ssh in using a ProxyCommand

the error I'm getting is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 536, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'exec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 233, in main
    run_code_with_cache(args.command, shell.execer, mode='single')
  File "/usr/local/lib/python3.4/dist-packages/xonsh/codecache.py", line 182, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/codecache.py", line 57, in run_compiled_code
    func(code, glb, loc)
  File "88b2d5e0de871cc045f7d4d4f95b5bd4", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 671, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 546, in run_subproc
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: exec
```

My ssh config is:
```
HostName mysite.org
ForwardAgent yes
User user
ProxyCommand ssh user@server nc %h %p
```
I have added `aliases['exec'] = aliases['xexec']` in my .xonshrc.

Any Idea what the problem is?

**Comment by adqm** [comment]
I have had similar problems when trying to run mosh in the past.  There, the workaround was to `del $SHELL` before running.  Can you try that and see whether that fixes this issue as well?

**Comment by gregmccoy** [comment]
Yes that workaround does work for me thank you!

**Comment by adqm** [comment]
Great!  I'm going to go ahead and close this issue, then.  If you feel like it hasn't been properly addressed, feel free to reopen!

**Comment by feanil** [comment]
Hello, this workaround is fine but is the underlying issue going to be fixed, is there a github issue tracking the underlying problem?

**Comment by scopatz** [comment]
@feanil do you have xonsh as your default shell?

**Comment by feanil** [comment]
Yes.

**Comment by scopatz** [comment]
@feanil See #1302 and #1361 the underlying problem is that both sh and Python define exec and it isn't entirely clear how safe it is for both to be defined.

**Comment by feanil** [comment]
Cool, thanks for the pointers.
