### ISSUE TITLE
Cannot enter a Python virtualenv

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1153]
This should not be the same as #108 which seems have been fixed. Here is the tracebacks:

```
hugo@mbp: ~$ pyvenv .local/share/xonsh_pyvenv_test
hugo@mbp: ~$ source .local/share/xonsh_pyvenv_test/bin/activate
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 147, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 289, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2326, in p_error
    self.xonsh_code)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 390, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:4:14: ('code: ![',)
deactivate () ![{]
              ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 335, in wrapped_simple_command
    r = f(args, i)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/aliases.py", line 262, in source_alias
    builtins.execx(fp.read(), 'exec', builtins.__xonsh_ctx__)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 133, in exec
    wrap_subprocs=wrap_subprocs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 100, in compile
    tree = self.parse(input, ctx, mode=mode, wrap_subprocs=wrap_subprocs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 72, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 205, in _parse_ctx_free
    raise original_error
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/execer.py", line 147, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 289, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2326, in p_error
    self.xonsh_code)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/parsers/base.py", line 390, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:4:14: ('code: {',)
deactivate () {
              ^
hugo@mbp: ~$
```

EDIT: here's my prompt:

```
$ $PROMPT
'{user}@mbp: {BOLD_BLUE}{cwd_base}{prompt_end}{NO_COLOR} '
```

**Comment by Siecje** [comment]
You need to use ```source-bash``` since activate is a bash script.

**Comment by mitnk** [comment]
Thanks @Siecje, good to know!
