### ISSUE TITLE
Fails to start on windows

### ISSUE THREAD

**Issue by badders** [xonsh/xonsh#1168]
Fresh install from conda forge, crashes with the following (tested on both python 3.5 and 3.4):

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\xonsh-script.py", line 5, in <module>
    sys.exit(xonsh.main.main())
  File "C:\Anaconda3\lib\site-packages\xonsh\main.py", line 236, in main
    args = premain(argv)
  File "C:\Anaconda3\lib\site-packages\xonsh\main.py", line 223, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "C:\Anaconda3\lib\site-packages\xonsh\shell.py", line 74, in __init__
    ctx=self.ctx, **kwargs)
  File "C:\Anaconda3\lib\site-packages\xonsh\ptk\shell.py", line 30, in __init__
    super().__init__(**kwargs)
  File "C:\Anaconda3\lib\site-packages\xonsh\base_shell.py", line 118, in __init__
    self.completer = Completer()
  File "C:\Anaconda3\lib\site-packages\xonsh\completer.py", line 13, in __init__
    update_bash_completion()
  File "C:\Anaconda3\lib\site-packages\xonsh\completers\bash.py", line 57, in update_bash_completion
    _load_bash_complete_funcs()
  File "C:\Anaconda3\lib\site-packages\xonsh\completers\bash.py", line 127, in _load_bash_complete_funcs
    out = _source_completions(inp)
  File "C:\Anaconda3\lib\site-packages\xonsh\completers\bash.py", line 166, in _source_completions
    env=builtins.__xonsh_env__.detype(), stderr=subprocess.DEVNULL)
  File "C:\Anaconda3\lib\subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "C:\Anaconda3\lib\subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Anaconda3\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by badders** [comment]
To be more specific, thats on windows 7 enterprise, anaconda python 4, all packages up to date.

**Comment by melund** [comment]
Some things are broken in 0.3.3 on windows when 'bash.exe' is not on PATH. 

There are a couple of fixes for this which have been merged into Master. 
https://github.com/xonsh/xonsh/pull/1158
https://github.com/xonsh/xonsh/pull/1132

Can you try if they work for you? 

Since you use conda you can install a developer version with
````cmd
conda install -c xonsh/channel/dev xonsh
```

**Comment by melund** [comment]
Ohh. Wait. Developer builds stopped working yesterday when the repository moved from scropatz/xonsh to its own github organization. I will try to fix

**Comment by badders** [comment]
Ok, let me know when the developer builds are working agian, and ill give it a try

Thanks

**Comment by melund** [comment]
I fixed them right after my last comment. Let me know if it doesn't work for you. 
Sorry for letting you know.

**Comment by badders** [comment]
Dev version starts up and runs ok, closing the issue
