### ISSUE TITLE
Can't start process in background and redirect its streams

### ISSUE THREAD

**Issue by cryzed** [xonsh/xonsh#1174]
I am trying to run the following script:

``` python
#!/usr/bin/env xonsh

import os
import time


def main():
    killall plasmashell 2>&1 > /dev/null
    nohup plasmashell 2>&1 & > /dev/null

    while not os.path.exists('nohup.out'):
        time.sleep(0.1)

    os.remove('nohup.out')


if __name__ == '__main__':
    main()
```

However, I get the following traceback when executing it:

``` python-traceback
cryzed@arch ~ $ restart-plasmashell
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/execer.py", line 147, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 289, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2326, in p_error
    self.xonsh_code)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 390, in _parse_error
    raise err
SyntaxError: /home/cryzed/bin/restart-plasmashell:9:31: ('code: >',)
    ![nohup plasmashell 2>&1 & > /dev/null]
                               ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.3', 'console_scripts', 'xonsh')()
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 247, in main
    run_script_with_cache(args.file, shell.execer, glb=shell.ctx, loc=None, mode='exec')
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 135, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 96, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode)
  File "/usr/lib/python3.5/site-packages/xonsh/execer.py", line 100, in compile
    tree = self.parse(input, ctx, mode=mode, wrap_subprocs=wrap_subprocs)
  File "/usr/lib/python3.5/site-packages/xonsh/execer.py", line 72, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/usr/lib/python3.5/site-packages/xonsh/execer.py", line 205, in _parse_ctx_free
    raise original_error
  File "/usr/lib/python3.5/site-packages/xonsh/execer.py", line 147, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 289, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2326, in p_error
    self.xonsh_code)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 390, in _parse_error
    raise err
SyntaxError: /home/cryzed/bin/restart-plasmashell:8:12: ('code: plasmashell',)
    killall plasmashell 2>&1 > /dev/null
            ^
```

When appending the `&` to the very end of the line the script executes, but the process doesn't seem to start in the background and blocks:

``` python-traceback
cryzed@arch ~ $ restart-plasmashell
[1] running: nohup plasmashell 2>&1 > /dev/null & (7365)
^CTraceback (most recent call last):
  File "/usr/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.3', 'console_scripts', 'xonsh')()
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 247, in main
    run_script_with_cache(args.file, shell.execer, glb=shell.ctx, loc=None, mode='exec')
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 137, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.5/site-packages/xonsh/codecache.py", line 57, in run_compiled_code
    func(code, glb, loc)
  File "/home/cryzed/bin/restart-plasmashell", line 18, in <module>
    main()
  File "/home/cryzed/bin/restart-plasmashell", line 268, in main
KeyboardInterrupt
```

**Comment by adqm** [comment]
Thanks for reporting, @cryzed!

I think this is actually at least two bugs in one:
* a bug in the parser: the `AMPERSAND` token shouldn't have to be the last element in the subprocess arguments
* the message about a process being run in the background probably shouldn't be printed if we aren't running interactively

That said, I am unable to reproduce the issue with the script not dying until a keyboard interrupt with the other examples I have tried.

**Comment by scopatz** [comment]
See #2247 for a fix to the interactive mode part. 

However, the docs state that the ampersand must come at the end of the command: http://xon.sh/tutorial.html#background-jobs I don't think we should consider that part a bug, but rather a feature request.

**Comment by scopatz** [comment]
Happy to have this!

**Comment by scopatz** [comment]
But it needs some effort
