### ISSUE TITLE
asyncio/stdin/subprocess crash

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1191]
i have these two snippets (minimized to the point i could reproduce the crash):

```
# ainput.py
import asyncio                                                                     
import os                                                                          
import sys

os.set_blocking(sys.stdin.fileno(), False)

def handle_key():                                                                  
    key = sys.stdin.read()                                                         

loop = asyncio.get_event_loop()                                                    

loop.add_reader(sys.stdin, handle_key)                                             

loop.run_forever()
```

```
# test_ainput.py
import subprocess 
p = subprocess.Popen(['python3.5', 'ainput.py']) 
```

i know its completely nuts but when i run `python3.5 test_ainput.py`
i get a nasty recursion and xonsh crashes
(bash somehow gets away with this)

log from terminator Logger plugin

```
py test_ainput.py 
...
Exception in callback handle_key() at ainput.py:27
handle: <Handle handle_key() at ainput.py:27>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
OSError: [Errno 5] Input/output error
Exception in callback handle_key() at ainput.py:27
handle: <Handle handle_key() at ainput.py:27>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
OSError: [Errno 5] Input/output error
Exception in callback handle_key() at ainput.py:27
handle: <Handle handle_key() at ainput.py:27>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
OSError: [Errno 5] Input/output error

laerus@_ai1337_ 6% ~/lab/textio                                                                      Thu Jun  9 23:06:33 2016
laerus@_ai1337_ 6% ~/lab/textio                                                                      Thu Jun  9 23:06:33 2016
$                                                                                                                            
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.4', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 267, in main
    shell.cmdloop()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ptk/shell.py", line 116, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ptk/shell.py", line 85, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/interface.py", line 385, in run
    self._redraw()
Exception in callback handle_key() at ainput.py:27
handle: <Handle handle_key() at ainput.py:27>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
OSError: [Errno 5] Input/output error--- Logging error ---
Exception in callback handle_key() at ainput.py:27
handle: <Handle handle_key() at ainput.py:27>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
OSError: [Errno 5] Input/output error--- Logging error ---
Exception in callback handle_key() at ainput.py:27
handle: <Handle handle_key() at ainput.py:27>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
OSError: --- Logging error ---
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/interface.py", line 344, in _redraw
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
BlockingIOError: [Errno 11] write could not complete without blocking
Call stack:
  File "ainput.py", line 55, in <module>
    loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1295, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 136, in _run
    self._loop.call_exception_handler(context)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1154, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1131, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
Message: 'Exception in callback handle_key() at ainput.py:27\nhandle: <Handle handle_key() at ainput.py:27>'
Arguments: ()
Exception in callback handle_key() at ainput.py:27
handle: <Handle handle_key() at ainput.py:27>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
OSError: [Errno 5] Input/output error
Exception in callback handle_key() at ainput.py:27
handle: <Handle handle_key() at ainput.py:27>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "ainput.py", line 28, in handle_key
    key = sys.stdin.read()
...
```

**Comment by scopatz** [comment]
Thanks for reporting this @laerus. I am not sure what to think about this yet, but if anyone happens upon a fix, please PR it!

**Comment by gforsyth** [comment]
Hey @laerus -- I can't reproduce this on current master, is it still an issue on your end?

**Comment by laerus** [comment]
yep this doesn't seem to happen anymore
