### ISSUE TITLE
pip install error on Windows

### ISSUE THREAD

**Issue by klonuo** [xonsh/xonsh#1200]
Trying to update xonsh raised this error:

```shell
>pip install -U xonsh
Collecting xonsh
  Using cached xonsh-0.3.4.tar.gz
Installing collected packages: xonsh
  Found existing installation: xonsh 0.3.2
    Uninstalling xonsh-0.3.2:
      Successfully uninstalled xonsh-0.3.2
  Running setup.py install for xonsh ... error
    Complete output from command c:\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Temp\\pip-build-57pi877i\\xonsh\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Temp\pip-s3ldhy49-record\install-record.txt --single-version-externally-managed --compile:
    running install
    Building lexer and parser tables.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Temp\pip-build-57pi877i\xonsh\setup.py", line 194, in <module>
        main()
      File "C:\Temp\pip-build-57pi877i\xonsh\setup.py", line 190, in main
        setup(**skw)
      File "c:\python35\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python35\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\python35\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Temp\pip-build-57pi877i\xonsh\setup.py", line 95, in run
        build_tables()
      File "C:\Temp\pip-build-57pi877i\xonsh\setup.py", line 53, in build_tables
        from xonsh.parser import Parser
      File "c:\temp\pip-build-57pi877i\xonsh\xonsh\parser.py", line 3, in <module>
        from xonsh.platform import PYTHON_VERSION_INFO
      File "c:\temp\pip-build-57pi877i\xonsh\xonsh\platform.py", line 207, in <module>
        stderr=subprocess.PIPE)
      File "c:\python35\lib\subprocess.py", line 584, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['bash', '--version']' returned non-zero exit status 4294967295
    ----------------------------------------
```

So problem seems to be at: https://github.com/xonsh/xonsh/blob/master/xonsh/platform.py#L205

I run Windows 10 insider, and in case you are not familiar, Windows 10 introduced [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about).
As a result I have `bash` (from WSL) on my path, while you maybe expect bash emulator from Git for Windows.

Trying the offender code in interpreter, tips problem with stdout pipe, while there doesn't seem that piping on that line is needed at all, as try/except block just checks for FileNotFoundError.

**Comment by melund** [comment]
Interesting. I have been trying to get that insider build for a long time, so I could test these things. But the updater is stuck in some weird state where it never reports new builds :(

Anyway. Do you have any idea why `bash --version` would return a non-zero exist code? 

We could add a `CalledProcessError` to the exceptions beeing caught. That would treat the symptom. Maybe it doesn't make sense to use Bash from WSL in normal winodws mode.

**Comment by klonuo** [comment]
> Interesting. I have been trying to get that insider build for a long time, so I could test these things. But the updater is stuck in some weird state where it never reports new builds :(

If you want it badly, you can always download iso image from slowring (at this moment build 14342), mount it and update manually.

> Anyway. Do you have any idea why bash --version would return a non-zero exist code?
The command will execute fine stdout is not piped, i.e. this executes fine:

```pytb
In [1]: import subprocess

In [2]: print(subprocess.check_call(['bash', '--version']))
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
0

In [3]: print(subprocess.check_call(['bash', '--version'], stderr=subprocess.PIPE))
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
0

In [4]: print(subprocess.check_call(['bash', '--version'], stdout=subprocess.PIPE, stderr=subprocess.PIPE))
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-4-b02a9b83e299> in <module>()
----> 1 print(subprocess.check_call(['bash', '--version'], stdout=subprocess.PIPE, stderr=subprocess.PIPE))

c:\python35\lib\subprocess.py in check_call(*popenargs, **kwargs)
    582         if cmd is None:
    583             cmd = popenargs[0]
--> 584         raise CalledProcessError(retcode, cmd)
    585     return 0
    586

CalledProcessError: Command '['bash', '--version']' returned non-zero exit status 4294967295
```

There are some open issues about it, i.e. https://github.com/Microsoft/BashOnWindows/issues/2

> We could add a CalledProcessError to the exceptions beeing caught. That would treat the symptom. Maybe it doesn't make sense to use Bash from WSL in normal winodws mode.

That makes sense to me, but I'm not familiar with xonsh's code.

**Comment by melund** [comment]
@klonuo Can you test this #1202 ?

**Comment by klonuo** [comment]
`CalledProcessError` is in `subprocess` namespace, so just change it to `subprocess.CalledProcessError`

**Comment by klonuo** [comment]
Great, thanks!

```
>pip install git+https://github.com/xonsh/xonsh.git@fix_for_bash_wsl
Collecting git+https://github.com/xonsh/xonsh.git@fix_for_bash_wsl
  Cloning https://github.com/xonsh/xonsh.git (to fix_for_bash_wsl) to c:\temp\pip-xeleswri-build
Installing collected packages: xonsh
  Found existing installation: xonsh 0.3.2
    Uninstalling xonsh-0.3.2:
      Successfully uninstalled xonsh-0.3.2
  Running setup.py install for xonsh ... done
Successfully installed xonsh-0.3.4
```
