### ISSUE TITLE
Amalgamate build on Anaconda.org fails

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1257]
It builds fine on my machine so I am not really sure what is going on here: 

https://anaconda.org/xonsh/xonsh/builds/403/0

```bash
+ python setup.py install --single-version-externally-managed --record=record.txt
Traceback (most recent call last):
  File "setup.py", line 210, in <module>
    main()
  File "setup.py", line 206, in main
    setup(**skw)
  File "/opt/miniconda/envs/_build/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/miniconda/envs/_build/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/miniconda/envs/_build/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 99, in run
    build_tables()
  File "setup.py", line 59, in build_tables
    amalgamate.main(['amalgamate', '--debug=XONSH_DEBUG', 'xonsh'])
  File "/opt/miniconda/conda-bld/work/amalgamate.py", line 369, in main
    graph = make_graph(pkg, exclude=exclude)
  File "/opt/miniconda/conda-bld/work/amalgamate.py", line 94, in make_graph
    graph[base] = make_node(base, pkg, allowed)
  File "/opt/miniconda/conda-bld/work/amalgamate.py", line 54, in make_node
    raw = SOURCES[pkg, name]
  File "/opt/miniconda/conda-bld/work/amalgamate.py", line 39, in __getitem__
    raw = f.read()
  File "/opt/miniconda/envs/_build/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc7 in position 2102: ordinal not in range(128)
Command failed: /bin/bash -x -e /opt/miniconda/conda-bld/work/conda_build.sh
discarding /home/dev/env/bin from PATH

```

**Comment by scopatz** [comment]
Thanks for reporting!  I found the issue and I think the fix is in at #1265

**Comment by melund** [comment]
Sorry. It didn't fix completely. New error in another place :(

https://anaconda.org/xonsh/xonsh/builds/412/0
´´´
+ python setup.py install --single-version-externally-managed --record=record.txt
Traceback (most recent call last):
  File "setup.py", line 210, in <module>
    main()
  File "setup.py", line 206, in main
    setup(**skw)
  File "/opt/miniconda/envs/_build/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/miniconda/envs/_build/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/miniconda/envs/_build/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 99, in run
    build_tables()
  File "setup.py", line 59, in build_tables
    amalgamate.main(['amalgamate', '--debug=XONSH_DEBUG', 'xonsh'])
  File "/opt/miniconda/conda-bld/work/amalgamate.py", line 372, in main
    write_amalgam(src, pkg)
  File "/opt/miniconda/conda-bld/work/amalgamate.py", line 297, in write_amalgam
    f.write(src)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 48128: ordinal not in range(128)
Command failed: /bin/bash -x -e /opt/miniconda/conda-bld/work/conda_build.sh
discarding /home/dev/env/bin from PATH

```

**Comment by scopatz** [comment]
I think we finally found all of the little issues.
