### ISSUE TITLE
xonfig broken on current master

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1259]
```
$ xonfig
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\proc.py", line 336, in wrapped_simple_command
    r = f(args, i)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\aliases.py", line 453, in xonfig
    from xonsh.xonfig import main  # lazy import
ImportError: cannot import name 'main'
```

**Comment by gforsyth** [comment]
Yikes.  Also this:

```console
$ xonfig
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 10001, in wrapped_simple_command
    r = f(args, i)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13880, in xonfig
    return main(args)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15893, in main
    args = premain(argv)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15880, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15625, in __init__
    kwargs.get('cacheall', False))
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15667, in _init_environ
    debug_level=debug)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15311, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15197, in load_builtins
    resetting_signal_handle(sig, _lastflush)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 14550, in resetting_signal_handle
    signal.signal(sig, newh)
  File "/home/gil/anaconda/lib/python3.5/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**Comment by laerus** [comment]
running xonfig twice gets even crazier :(

**Comment by gforsyth** [comment]
ooo, yikes.  yes it does

**Comment by scopatz** [comment]
On it now.

**Comment by scopatz** [comment]
See #1264

**Comment by scopatz** [comment]
Sorry about this @melund!

**Comment by melund** [comment]
Don't be sorry. I merged it in. I couldn't wait :)
