### ISSUE TITLE
xonsh fails to start if prompt_toolkit is present.

### ISSUE THREAD

**Issue by vsajip** [xonsh/xonsh#1261]
Tested using xonsh 0.3.4 in a venv with Python 3.4.3:

First run works as expected:

```
(venv) vinay@theta-rosa ~ $ xonsh
(venv) vinay@theta-rosa ~ $
```

After exiting `xonsh`, installed `prompt-toolkit`:

```
(venv) vinay@theta-rosa ~ $ pip install prompt-toolkit
Collecting prompt-toolkit
  Using cached prompt_toolkit-1.0.2-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): wcwidth in ./.local/share/virtualenvs/venv/lib/python3.4/site-packages (from prompt-toolkit)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in ./.local/share/virtualenvs/venv/lib/python3.4/site-packages (from prompt-toolkit)
Installing collected packages: prompt-toolkit
Successfully installed prompt-toolkit-1.0.2
```

Then, tried running `xonsh` again:

```
(venv) vinay@theta-rosa ~ $ xonsh
Traceback (most recent call last):
  File "/home/vinay/.local/share/virtualenvs/venv/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.4', 'console_scripts', 'xonsh')()
  File "/home/vinay/.local/share/virtualenvs/venv/lib/python3.4/site-packages/xonsh/main.py", line 236, in main
    args = premain(argv)
  File "/home/vinay/.local/share/virtualenvs/venv/lib/python3.4/site-packages/xonsh/main.py", line 223, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/home/vinay/.local/share/virtualenvs/venv/lib/python3.4/site-packages/xonsh/shell.py", line 67, in __init__
    from xonsh.ptk.shell import PromptToolkitShell as shell_class
  File "/home/vinay/.local/share/virtualenvs/venv/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 11, in <module>
    from pygments.styles import get_all_styles
ImportError: No module named 'pygments'
(venv) vinay@theta-rosa ~ $ 
```

**Comment by gforsyth** [comment]
Hey @vsajip , if you're using `prompt_toolkit` then `pygments` is also required.  A `pip install pygments` should take care of things for you.

**Comment by vsajip** [comment]
Fair enough. Of course `prompt_toolkit` should declare its dependencies correctly so that `pip` installs them, but I realise that's not a problem with `xonsh`. Thanks for the quick response.

**Comment by vsajip** [comment]
Oh, and by the by, thanks to the `xonsh` team for a really nice shell ! I just "got the memo" today via Anthony Scopatz's talk, and am planning to use it a lot ...

**Comment by adqm** [comment]
> Obviously the user wouldn't get syntax highlighting, but that may be a price they're willing to pay ...

True.  Syntax highlighting can already be enabled/disabled with `$COLOR_INPUT` and `$COLOR_RESULTS`.

AFAICT, there is no reason not just to disable those (and provide a warning) if pygments isn't present.

**Comment by scopatz** [comment]
We weren't really prepared for prompt-toolkit to drop pygments as a dependency.  We should decouple these two in xonsh since you can have either one without the other now.

**Comment by mitnk** [comment]
Encountered this issue today too. So we should make ptk and xonsh work without pygments, right?

**Comment by gforsyth** [comment]
@mitnk, yes. I've taken a couple cracks at it and always gotten derailed.

**Comment by astronouth7303** [comment]
The work-around is to install xonsh as `pip install xonsh[ptk]`.

**Comment by scopatz** [comment]
Yes, we should. Any help here would be most appreciated!

**Comment by scopatz** [comment]
I think this was finally fixed, right @gforsyth?

**Comment by gforsyth** [comment]
This is finally fixed. Reopen if any issues persist.  Thanks!

**Comment by mitnk** [comment]
Just checked, xonsh with PTK still breaks without pygments.

**Comment by gforsyth** [comment]
Is there a primal scream emoji?

**Comment by gforsyth** [comment]
Hey @mitnk -- sorry to do this, but can you double check? I have an environment with PTK and no pygments and it seems to work -- can you send a pastebin of the traceback?  Could be I missed something mac-specific?

**Comment by laerus** [comment]
hye @mitnk are you setting $XONSH_COLOR_STYLE in your `.xonshrc`?

**Comment by mitnk** [comment]
strange to me too. it works on my Mac. But on a Linux box I got these errors:

```
mitnk@lz: ~$ xonsh  # <-- with $SHELL_TYPE = 'best'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/main.py", line 337, in main
    return main_xonsh(args)
  File "/usr/local/lib/python3.6/site-packages/xonsh/main.py", line 366, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 150, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 78, in singleline
    self.styler.style_name = env.get('XONSH_COLOR_STYLE')
  File "/usr/local/lib/python3.6/site-packages/xonsh/base_shell.py", line 276, in styler
    from xonsh.pyghooks import XonshStyle
  File "/usr/local/lib/python3.6/site-packages/xonsh/pyghooks.py", line 14, in <module>
    from pygments.lexer import inherit, bygroups, include
ModuleNotFoundError: No module named 'pygments.lexer'
Xonsh encountered an issue during launch
Failback to /bin/sh
\u\[\e[0;32m\]@\[\e[m\]lz: \W\[\e[0;32m\]$\[\e[m\] exit
mitnk@lz: ~$ vim .xonshrc_local  # <-- change $SHELL_TYPE = 'readline'
mitnk@lz: ~$ xonsh
mitnk@lz: ~$ xonfig
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/proc.py", line 1333, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.6/site-packages/xonsh/proc.py", line 1162, in proxy_two
    return f(args, stdin)
  File "/usr/local/lib/python3.6/site-packages/xonsh/aliases.py", line 352, in xonfig
    return xonfig_main(args)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xonfig.py", line 502, in xonfig_main
    return _XONFIG_MAIN_ACTIONS[ns.action](ns)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xonfig.py", line 359, in _info
    ('pygments', pygments_version()),
  File "/usr/local/lib/python3.6/site-packages/xonsh/platform.py", line 98, in pygments_version
    v = pygments.__version__
AttributeError: module 'pygments' has no attribute '__version__'
mitnk@lz: ~$ $XONSH_COLOR_STYLE
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/base_shell.py", line 322, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/local/lib/python3.6/site-packages/xonsh/codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/xonsh/main.py", line 207, in _pprint_displayhook
    tokens = list(pygments.lex(printed_val, lexer=pyghooks.XonshLexer()))
  File "/usr/local/lib/python3.6/site-packages/xonsh/lazyasd.py", line 61, in __getattribute__
    return getattr(obj, name)
AttributeError: module 'pygments' has no attribute 'lex'
```

**Comment by scopatz** [comment]
This is probably no longer true
