### ISSUE TITLE
Windows tests failing again. 

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1284]
We have accumulated som e failing windows tests again. Feel free to tackle them as you please, otherwise I wll try  look at them an other day. 

```

xonsh: subprocess mode: command not found: the
Did you mean one of the following?
    tit:   Alias
    time:  Alias
    type:  Alias
KeyError: 'Unknown environment variable: $XONSH_INTERACTIVE'
C:\Users\mel\Documents\xonsh\xonsh\__amalgam__.py:10930: RuntimeWarning: Failed to set locale 'LC_MESSAGES' to 'C'
  RuntimeWarning)

xonsh: subprocess mode: command not found: the
Did you mean one of the following?
    tit:   Alias
    time:  Alias
    type:  Alias
KeyError: 'Unknown environment variable: $XONSH_INTERACTIVE'
C:\Users\mel\Documents\xonsh\xonsh\__amalgam__.py:10930: RuntimeWarning: Failed to set locale 'LC_MESSAGES' to 'C'
  RuntimeWarning)
KeyError: 'Unknown environment variable: $XONSH_INTERACTIVE'
xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be created.
xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be created.
xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be created.
xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be created.
xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be created.
======================================================================
ERROR: test_tools.test_executables_in
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mel\Documents\xonsh\tests\test_tools.py", line 795, in test_executables_in
    os.symlink(tmp_path, path)
OSError: symbolic link privilege not held

======================================================================
FAIL: Test the EnvPath class.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: Lists differ: ['/home/wakka'] != ['\\home\\wakka']

First differing element 0:
/home/wakka
\home\wakka

- ['/home/wakka']
?   ^    ^

+ ['\\home\\wakka']
?   ^^    ^^


======================================================================
FAIL: Test the EnvPath class.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: Lists differ: ['/home/wakka', '/home/jakka', 'C:\\Users\\mel/'] != ['/home/wakka', '\\home\\jakka', 'C:\\Users\\mel/']

First differing element 1:
/home/jakka
\home\jakka

- ['/home/wakka', '/home/jakka', 'C:\\Users\\mel/']
?                  ^    ^

+ ['/home/wakka', '\\home\\jakka', 'C:\\Users\\mel/']
?                  ^^    ^^


======================================================================
FAIL: test_tools.test_is_logfile_opt(True, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: True != False

======================================================================
FAIL: test_tools.test_to_logfile_opt('/dev/null', None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: '/dev/null' != None

----------------------------------------------------------------------
Ran 132902 tests in 31.393s
```

**Comment by scopatz** [comment]
I believe that these were introduced by the EnvPath changes by @VHarisop.  Would you mind cleaning these up, please? We'd really appreciate it!

**Comment by scopatz** [comment]
Also, @melund, do you think that  it is time to try appveyor again now that we have moved to the xonsh org?

**Comment by melund** [comment]
I think we should. And I promise to write them if we start having troubles again.

**Comment by gforsyth** [comment]
@melund are we good to close this now?

**Comment by melund** [comment]
Sure... Thanks
