### ISSUE TITLE
Error in jobs.py when piping history alias to grep/ack

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#1297]
Running on  e662673 on linux. 
```
+------------------+----------------+
| xonsh            | 0.3.4          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.0.2          |
| on posix         | True           |
| on linux         | True           |
| distro           | CentOS         |
| on darwin        | False          |
| on windows       | False          |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+
```

Not sure if this is related to #830.
```
└─> % history zsh | grep nvidia
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
   204: nvidia-smi -l
Traceback (most recent call last):
  File "/home/home51/lunz8748/usr/xonsh/xonsh/base_shell.py", line 167, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/home51/lunz8748/usr/xonsh/xonsh/codecache.py", line 66, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/home51/lunz8748/usr/xonsh/xonsh/built_ins.py", line 635, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/home51/lunz8748/usr/xonsh/xonsh/built_ins.py", line 517, in run_subproc
    'bg': background
  File "/home/home51/lunz8748/usr/xonsh/xonsh/jobs.py", line 260, in add_job
    _set_pgrp(info)
  File "/home/home51/lunz8748/usr/xonsh/xonsh/jobs.py", line 103, in _set_pgrp
    info['pgrp'] = os.getpgid(info['pids'][0])
TypeError: an integer is required (got type NoneType)
```
I feel like this used to work...

**Comment by scopatz** [comment]
Thanks for reporting @JohnLunzer. I have opened #1303 to try to fix this.

**Comment by laerus** [comment]
Solved!
