### ISSUE TITLE
Can't import Python package if isn't part of __amalgam__.py

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#1310]
I just tried to `import numpy` in my terminal session and get 

```console
gil@theo ~ $ import numpy
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/gil/git/xonsh/xonsh/__amalgam__.py", line 12868, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/gil/git/xonsh/xonsh/__amalgam__.py", line 2817, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
ImportError: No module named 'numpy'
```

**Comment by melund** [comment]
This works fine for me:
```
((x)) C:\Users\mel\Documents\xonsh>xonsh
snail@sea ~\Documents\xonsh $ import numpy
snail@sea ~\Documents\xonsh $ xonfig
+------------------+----------------+
| xonsh            | 0.3.4          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.1          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | False          |
| on linux         | False          |
| on darwin        | False          |
| on windows       | True           |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+
snail@sea ~\Documents\xonsh $
```

**Comment by gforsyth** [comment]
Hmm... and here, too now.  That's a weird one.  Ok, closing for now.

**Comment by scopatz** [comment]
Yep, also worked just fine for me
