### ISSUE TITLE
Error when starting xonsh from xonsh ($XONSH_HISTORY_SIZE)

### ISSUE THREAD

**Issue by BlaXpirit** [xonsh/xonsh#1355]
```
~⟫ xonsh
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16446, in main
    args = premain(argv)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16431, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16185, in __init__
    kwargs.get('cacheall', False))
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16227, in _init_environ
    debug_level=debug)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15871, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15711, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 11335, in __init__
    self[key] = val
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 11468, in __setitem__
    val = ensurer.convert(val)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 6186, in to_history_tuple
    return to_history_tuple((m.group(1), m.group(3)))
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 6189, in to_history_tuple
    units, converter = HISTORY_UNITS[x[1]]
TypeError: 'LazyObject' object is not subscriptable
~⟫ xonfig
+------------------+----------+
| xonsh            | 0.4.2    |
| Python           | 3.5.1    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | 2.1.3    |
| on posix         | True     |
| on linux         | True     |
| distro           | arch     |
| on darwin        | False    |
| on windows       | False    |
| on cygwin        | False    |
| is superuser     | False    |
| default encoding | utf-8    |
| git SHA          | None     |
+------------------+----------+
~⟫ $XONSH_HISTORY_SIZE
(10000, 'commands')
```

**Comment by laerus** [comment]
Hey, i can't seem to reproduce. Have you installed from current master? also my amalgam seems a little different as in miss-matching line number. Don't know if this will make a difference but you can try purging xonsh and reinstalling.

**Comment by BlaXpirit** [comment]
I run on release 0.4.2

To reproduce, this line must be in *.xonshrc*:
```
$XONSH_HISTORY_SIZE = (10000, 'commands')
```

**Comment by scopatz** [comment]
This is likely an error with LazyObject not loading itself on `__getitem__()` calls.

**Comment by BlaXpirit** [comment]
It also seems like `xonfig wizard` says "invalid value" no matter what I type.

```
$XONSH_HISTORY_SIZE
[...]
default value: (8128, 'commands') or '8128 commands'
current value: (8128, 'commands')
>>> 10000 commands
Invalid input '10000 commands', please retry.
>>> '10000 commands'
Invalid input "'10000 commands'", please retry.
>>> (8128, 'commands')
Invalid input "(8128, 'commands')", please retry.
>>> 10000
Invalid input '10000', please retry.
```

**Comment by scopatz** [comment]
@BlaXpirit - would you mind please trying out #1357?
