### ISSUE TITLE
Error with first command when some $PATH doesn't exist

### ISSUE THREAD

**Issue by Cheaterman** [xonsh/xonsh#1356]
Ohai buddies, I hope you're doing good ^__^

I just upgraded to latest git, and I seem to be having a systematic issue with the first command I'll type in any term/xonsh session (onwards it all works fine):
```
cheaterman@cmans-laptop ~ $ echo 'Owiii bliblibli ^__^'
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 13095, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 2876, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 15734, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 15515, in run_subproc
    binary_loc = locate_binary(cmd[0])
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 11592, in locate_binary
    return builtins.__xonsh_commands_cache__.locate_binary(name)
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 10761, in locate_binary
    _ = self.all_commands
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 10723, in all_commands
    for cmd in executables_in(path):
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 5567, in executables_in
    yield from func(path)
  File "/usr/lib64/python3.4/site-packages/xonsh/__amalgam__.py", line 5529, in _executables_in_posix
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bin'
cheaterman@cmans-laptop ~ $ 
```

Seems to be complaining about /opt/bin which is in my $PATH but doesn't exist. I think this shouldn't fail as I never had an issue with it before?

Thanks in advance ^__^

**Comment by scopatz** [comment]
@Cheaterman Thanks for reporting! I have put in  a potential fix in #1358
