### ISSUE TITLE
(tests) ImportError in xonsh.tools with XONSH_DEBUG=1

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1362]
@scopatz trying to run the tests on `test_replay.py` with `$XONSH_DEBUG=1` throws:
```
Traceback (most recent call last):
  File "/home/laerus/.local/lib/python3.5/site-packages/_pytest/config.py", line 283, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/laerus/projects/xonsh/tests/test_replay.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/laerus/.local/lib/python3.5/site-packages/_pytest/config.py", line 283, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/laerus/projects/xonsh/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/laerus/.local/lib/python3.5/site-packages/_pytest/config.py", line 314, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/laerus/projects/xonsh/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/laerus/.local/lib/python3.5/site-packages/_pytest/config.py", line 320, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/laerus/.local/lib/python3.5/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/home/laerus/projects/xonsh/tests/conftest.py", line 4, in <module>
    from xonsh.tools import ensure_list_of_strs
ImportError: cannot import name 'ensure_list_of_strs'
ERROR: could not load /home/laerus/projects/xonsh/tests/conftest.py
```
then if i set  `$XONSH_DEBUG=0` it throws the same error
i have to restart xonsh in order to get past this.

any idea what's wrong or what am i doing wrong?

**Comment by scopatz** [comment]
Hi @laerus, this function seems to have moved to `xonsh.built_ins`  So you should just need to change the import statement to `from xonsh.built_ins import ensure_list_of_strs`

**Comment by laerus** [comment]
thank you!

**Comment by scopatz** [comment]
no problem
