### ISSUE TITLE
$PATH with a non-existent directory

### ISSUE THREAD

**Issue by Kilte** [xonsh/xonsh#1370]
Hello! I have the following entry in my `$PATH`:
```
$PATH.append('./node_modules/.bin/')
```
This allows me to run something from `%current-working-directory%/node_modules/.bin/` without having to type a full path to executable. I've upgraded xonsh from 0.3.4 to 0.4.2 and now I get the following error while running a first command after startup:
```
~ $ cat .xonshrc
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 13037, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 2818, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 15672, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 15461, in run_subproc
    binary_loc = locate_binary(cmd[0])
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 11534, in locate_binary
    return builtins.__xonsh_commands_cache__.locate_binary(name)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 10703, in locate_binary
    _ = self.all_commands
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 10665, in all_commands
    for cmd in executables_in(path):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 5509, in executables_in
    yield from func(path)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/__amalgam__.py", line 5471, in _executables_in_posix
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: './node_modules/.bin/'

~ $ cat .xonshrc
$PROMPT = '{BOLD_BLUE}{cwd}{branch_color}{curr_branch}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR} '

$XONSH_SHOW_TRACEBACK = True

$PATH.append('/home/kilte/nodejs/bin')
$PATH.append('/home/kilte/bin/')
$PATH.append('/home/kilte/.cargo/bin')
$PATH.append('./node_modules/.bin/')

$PYTHONSTARTUP = '/home/kilte/.config/python/startup'

def __reset(args, stdin=None):
    print('\033\143')

aliases['reset'] = __reset

~ $ ls
Books  Desktop  Downloads  Music  Pictures  bin  nodejs  projects

~ $ 

```
As you can see, this only occurs at first time only.

**Comment by melund** [comment]
Hi @Kilte 
Thanks for reporting. I think this has been fixed on master a few days ago. https://github.com/xonsh/xonsh/commit/b49a6934b04f3086ccc78d367295c37444c1de5a

Maybe you can confirm?

**Comment by Kilte** [comment]
Yeah, it works. Thank you!
