### ISSUE TITLE
Can't launch xonsh on windows10

### ISSUE THREAD

**Issue by arpheno** [xonsh/xonsh#1384]
I heard about this awesome tool from the PyCon 16 recordings, however I'm running into problems on windows 10. No idea why. Any help appreciated.
```
user@FBI C:\Users\user                                                                                                   
$ which python                                                                                                           
/cygdrive/c/Users/user/Anaconda3/python                                                                                  
user@FBI C:\Users\user
$ which xonsh
which: no xonsh in (/cygdrive/c/Program Files/ConEmu/ConEmu/Scripts:/cygdrive/c/Program Files/ConEmu:/cygdrive/c/Program Files/ConEmu/ConEmu:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Intel/OpenCL SDK/3.0/bin/x86:/cygdrive/c/Program Files (x86)/Intel/OpenCL SDK/3.0/bin/x64:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common Files/Intel/WirelessCommon:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/MiKTeX 2.9/miktex/bin/x64:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Users/user/Anaconda3:/cygdrive/c/Users/user/Anaconda3/Scripts:/cygdrive/c/Users/user/Anaconda3/Library/bin:/cygdrive/c/PROGRA~2/Oracle/VirtualBox:/usr/bin:/cygdrive/c/Program Files (x86)/Texmaker:/cygdrive/c/tools/mingw64/bin)

user@FBI C:\Users\user
$ pip install git+https://github.com/xonsh/xonsh
Collecting git+https://github.com/xonsh/xonsh
  Cloning https://github.com/xonsh/xonsh to c:\users\user\appdata\local\temp\pip-xbnb9qph-build
                                                                                Installing collected packages: xonsh
  Running setup.py install for xonsh ... done
Successfully installed xonsh-0.4.3
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
                                                                                         
user@FBI C:\Users\user                                                                                                   
$ xonsh                                                                                                                  
Traceback (most recent call last):                                                                                       
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 170, in _run_module_as_main                                          
    "__main__", mod_spec)                                                                                                
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 85, in _run_code                                                     
    exec(code, run_globals)                                                                                              
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\main.py", line 262, in <module>                                  
    main()                                                                                                               
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\main.py", line 206, in main                                      
    args = premain(argv)                                                                                                 
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\main.py", line 191, in premain                                   
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)                                                             
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 16388, in __init__                         
    ctx=self.ctx, **kwargs)                                                                                              
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\ptk\shell.py", line 30, in __init__                              
    super().__init__(**kwargs)                                                                                           
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 13136, in __init__                         
    self.completer = Completer() if kwargs.get('completer', True) else None                                              
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 97, in __init__                            
    compbash.update_bash_completion()                                                                                    
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\completers\bash.py", line 64, in update_bash_completion          
    _load_bash_complete_funcs()                                                                                          
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\completers\bash.py", line 134, in _load_bash_complete_funcs      
    out = _source_completions(inp)                                                                                       
  File "C:\Users\user\Anaconda3\lib\site-packages\xonsh\completers\bash.py", line 174, in _source_completions            
    env=builtins.__xonsh_env__.detype(), stderr=subprocess.DEVNULL)                                                      
  File "C:\Users\user\Anaconda3\lib\subprocess.py", line 629, in check_output                                            
    **kwargs).stdout                                                                                                     
  File "C:\Users\user\Anaconda3\lib\subprocess.py", line 711, in run                                                     
    output=stdout, stderr=stderr)                                                                                        
subprocess.CalledProcessError: Command '['bash']' returned non-zero exit status 2                                        
```

**Comment by melund** [comment]
I don't know why this happens either. For me, this works well with default the default py35 anaconda on Windows. Maybe because you are calling it from Cygwin? Anyway, it is the bash-completer that somehow fails here: https://github.com/xonsh/xonsh/blob/aace5d77c01f982f75e010b680f0b9902bc04196/xonsh/completers/bash.py#L175

This shouldn't be fatal, and I guess it could be caught as we do on line 120. https://github.com/xonsh/xonsh/blob/aace5d77c01f982f75e010b680f0b9902bc04196/xonsh/completers/bash.py#L120

It would be great if you could test to see if it fixes the immediate problem. If it does a PR would very welcome. 

Then we can look at why bash returns an error later.
