### ISSUE TITLE
Error in .xonshrc causes error in first instance of pushd /before/ the error

### ISSUE THREAD

**Issue by Russell-Jones-OxPhys** [xonsh/xonsh#1390]
Maybe related to #1388 ?

Example contents of ~/.xonshrc:

```
pushd ~

print('hi')

echo (r'\\" '+' '.()+'\\"')
```

**Comment by scopatz** [comment]
Hi, thanks for reporting! Can you please post the traceback

**Comment by scopatz** [comment]
also the parentheses in the echo look strange to me

**Comment by Russell-Jones** [comment]
> also the parentheses in the echo look strange to me
I was rushing a bit as I posted it, I'll try to isolate it in something more valid, or at least simple...

`echo .(` is the simplest I could make it. Putting it in double quotes allows this to be displayed. The original line had an `@()` section missing the `@`. I've also tried `echo .\(` which is valid in bash (`echo .(` is not).

```
$ echo .\(
................................................. 
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 154, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 307, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 325, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 1175, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 187, in call_errorfunc
    r = errorfunc(token)
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 2340, in p_error
    self.xonsh_code)
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 408, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:9: ('code: (',)
![echo .\(]
         ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../python/35ve/src/xonsh/xonsh/ptk/shell.py", line 100, in push
    locs=None)
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 101, in compile
    tree = self.parse(input, ctx, mode=mode, transform=transform)
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 72, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 167, in _parse_ctx_free
    raise original_error
  File "/.../python/35ve/src/xonsh/xonsh/execer.py", line 154, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 307, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 325, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 1175, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/.../python/35ve/src/xonsh/xonsh/ply/yacc.py", line 187, in call_errorfunc
    r = errorfunc(token)
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 2334, in p_error
    self.xonsh_code)
  File "/.../python/35ve/src/xonsh/xonsh/parsers/base.py", line 408, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:6: \
echo .\(
```

**Comment by scopatz** [comment]
This seems like a parser bug that is unrelated to pushd.  Is there something that I am missing about pushd here?

**Comment by scopatz** [comment]
Also, as you discovered, you can fully avoid this bug by putting quotes around the token for the moment.

**Comment by Russell-Jones** [comment]
> Is there something that I am missing about pushd here?
Just that the parser stops at the point where I call it in .xonshrc (gtg now, but I guess the same happens in a .xsh file?) having got past other items, and well (many lines) before the `.(` bit.

I've found other cases where I've surprisingly needed quotes, I'll try to remember to make a note next time I see one. I think with some paths?

**Comment by scopatz** [comment]
Please do!  Thanks a ton!

**Comment by scopatz** [comment]
I think this is resolved with quoting and not trying to escape raw quotes with backslashes. Instead escape quotes with quotes, e.g. `"'"` Please feel free to reopen if needed.
