### ISSUE TITLE
TypeError: unorderable types: set() <= LazyObject()

### ISSUE THREAD

**Issue by PaulReiber** [xonsh/xonsh#1421]
Whereas prior builds were working, currently when I execute just-built xonsh from master I'm getting an error.

```
$ xonsh
Traceback (most recent call last):
  File "/home/pbr/xonsh/venv/bin/xonsh", line 3, in <module>
    main()
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16710, in main
    args = premain(argv)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16695, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16439, in __init__
    kwargs.get('cacheall', False))
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16483, in _init_environ
    debug_level=debug)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16125, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 15965, in load_builtins
    builtins.__xonsh_env__ = env = Env(default_env(config=config, login=login))
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 12368, in default_env
    issue_warning=False)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 8855, in load_foreign_envs
    shell = ensure_shell(shell)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 8770, in ensure_shell
    if not (shell_keys <= VALID_SHELL_PARAMS):
TypeError: unorderable types: set() <= LazyObject()
```

**Comment by ned2** [comment]
I just noticed this also. Seems to be from 4819eb7. When variable VALID_SHELL_PARAMS is changed back into a frozenset, instead of a LazyObject containing the frozenset, xonsh loads fine for me.

**Comment by laerus** [comment]
Thanks for reporting! this is prolly cause we never call the __getattribute__ of the LazyObject somehow before the ordering thus the frozenset object doesnt replace the LazyObject
