### ISSUE TITLE
OSError on strating xonsh from captured subprocess operator

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1428]
```
$ $(python3 -m xonsh)
Traceback (most recent call last):
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/interface.py", line 387, in run
    self._redraw()
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/renderer.py", line 398, in render
    size = output.get_size()
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/terminal/vt100_output.py", line 359, in get_size
    rows, columns = _get_size(stdout.fileno())
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/terminal/vt100_output.py", line 317, in _get_size
    fcntl.ioctl(fileno, termios.TIOCGWINSZ, buf, True)
OSError: [Errno 25] Inappropriate ioctl for device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/__main__.py", line 2, in <module>
    main()
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16767, in main
    shell.shell.cmdloop()
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 115, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 84, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/interface.py", line 399, in run
    self._redraw()
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/renderer.py", line 398, in render
    size = output.get_size()
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/terminal/vt100_output.py", line 359, in get_size
    rows, columns = _get_size(stdout.fileno())
  File "/home/laerus/.local/lib/python3.4/site-packages/prompt_toolkit/terminal/vt100_output.py", line 317, in _get_size
    fcntl.ioctl(fileno, termios.TIOCGWINSZ, buf, True)
OSError: [Errno 25] Inappropriate ioctl for device
'\x1b]2;laerus@_ai1337_: ~ | xonsh\x07\x1b[6n'
```

**Comment by scopatz** [comment]
This seems like it is a bug in prompt-toolkit.  Maybe @jonathanslenders has some ideas.  Maybe report this on the prompt-toolkit repo?

Also note the the readline background also fails but in another, exciting way.

I believe that xonsh is handing off the stdin, stdout, stderr file handles correctly because $(bash) works.

**Comment by jonathanslenders** [comment]
Hi @laerus,

I can see that this fails, and we can fix it by checking ``sys.stdin.isatty()``. (I should do that.)
However, what are you trying to achieve?
``$(python3 -m xonsh)`` seems meaningless, or was it just an experiment?

**Comment by jonathanslenders** [comment]
Actually, thinking about it. If the input is not a TTY, then prompt-toolkit doesn't work in any meaningful way. I can raise a better meaningful exception, but I can't handle it.

Can we test in Xonsh whether stdin is a tty, and if not, just execute whatever we read from the input? (as a raw stream)

**Comment by laerus** [comment]
Hey @jonathanslenders, this came up when trying to solve another issue and it was used when experimenting with the enviroment swap feature like this:

```
with ${...}.swap(XONSH_DEBUG=1):
    $(python3 -m xonsh)
```

**Comment by scopatz** [comment]
@jonathanslenders I agree that this doesn't make a lot of sense, and with our readline backend, this just hangs.  (For some reason, bash just works, though.)  I think a more meaningful error message on the prompt-toolkit side would be great!

Though, oddly the new IPython that uses prompt-toolkit also just hangs, so I am not sure what we are doing different.  

We can put in a TTY check too, but I think I would be happier with a better error message since this is not a meaningful action.

**Comment by scopatz** [comment]
This has been fixed on master, probably since the run subproc refactor. Please feel free to reopen if needed!
