### ISSUE TITLE
@ operator cannot be used without preceding whitespace

### ISSUE THREAD

**Issue by zrax** [xonsh/xonsh#1453]
For example:

``` python
branch = 'master'
![git rev-parse refs/heads/@(branch)]
```

Which produces:

```
Traceback (most recent call last):
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 13238, in push
    locs=None)
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16113, in compile
    tree = self.parse(input, ctx, mode=mode, transform=transform)
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16084, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16224, in _parse_ctx_free
    raise original_error
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16166, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/parsers/base.py", line 307, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/ply/yacc.py", line 325, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/ply/yacc.py", line 1175, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/ply/yacc.py", line 187, in call_errorfunc
    r = errorfunc(token)
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/parsers/base.py", line 2340, in p_error
    self.xonsh_code)
  File "/opt/python-3.4.4/lib/python3.4/site-packages/xonsh/parsers/base.py", line 408, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:27: ('code: @(',)
![git rev-parse refs/heads/@(branch)]
                           ^
```

Inserting a space before the `@(branch)` causes the substitution to succeed, but obviously produces an incorrect argument to the command.  And yes, I realize I can just put the whole string inside the `@()`, but it would be convenient to not be required to do so.

**Comment by scopatz** [comment]
Thanks for requesting this feature @zrax. I think this would be great to have. It is probably easiest to implement in expandpath(). I would be happy to review a PR to this effect.

**Comment by scopatz** [comment]
This has been implemented.
