### ISSUE TITLE
Completion in Jupyter Kernel no longer working

### ISSUE THREAD

**Issue by blink1073** [xonsh/xonsh#1474]
This affects the Calysto_Xonsh kernel as well.  It seems something has changed with the handling of the completion logic:

```python
Traceback (most recent call last):
  File "/Users/ssilvester/anaconda/lib/python3.4/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/ssilvester/anaconda/lib/python3.4/site-packages/ipykernel/kernelbase.py", line 426, in complete_request
    matches = self.do_complete(code, cursor_pos)
  File "/Users/ssilvester/anaconda/lib/python3.4/site-packages/xonsh/jupyter_kernel.py", line 98, in do_complete
    comps, beg, end = shell.completer.find_and_complete(code, pos, shell.ctx)
AttributeError: 'NoneType' object has no attribute 'find_and_complete'
```

**Comment by gforsyth** [comment]
Thanks for reporting, @blink1073 !  Yeah, `find_and_complete` is no more.  I'll add in the new completer stuff to the kernel now.

**Comment by blink1073** [comment]
The logic for selecting a completer appears to be different as well. In a live xonsh session, I see it as shell.shell.completer, which is the prompt toolkit completer by default.  When run in the kernel, shell.shell.completer is None.

**Comment by gforsyth** [comment]
@blink1073 , I've opened #1479 with a potential fix.  Would you mind trying that out?

**Comment by blink1073** [comment]
Verified, thanks!
