### ISSUE TITLE
Commands following '&' for backgrounding don't appear to execute in subprocess mode

### ISSUE THREAD

**Issue by dotsdl** [xonsh/xonsh#1477]
Issue started from [discussion on mailing list](https://groups.google.com/d/msg/xonsh/Szw5sacxwGM/cM2U9fa_AwAJ)

I have aliases for remote machines that look like this:

``` python
aliases['remotehost'] = 'gnome-terminal --profile=OrangeDark -x bash -c "ssh myuser@remotehost.ecorp.biz" & exit'
```

which on use (`remotehost`) will open a new terminal with a different color profile, connected to the remote machine through SSH, and close the launching terminal. This works fine under a shell like `bash`, but under `xonsh`, the launching terminal doesn't close.

From playing around it looks like `xonsh` doesn't know handle commands following `&` as bash would, but it's not clear to me how it's interpreting things. For example, doing

```
ls & exit
```

under bash will run `ls`, deliver its contents to STDOUT, then exit the shell. Doing this under `xonsh` gives:

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13086, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1937, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'ls' is not defined
```

which indicates it's being interpreted in Python-mode. If we try to force subprocess mode with !(ls & exit), we get:

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 100, in push
    locs=None)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15996, in compile
    tree = self.parse(input, ctx, mode=mode, transform=transform)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15967, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16107, in _parse_ctx_free
    raise original_error
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16049, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 310, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2343, in p_error
    self.xonsh_code)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 411, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:7: ('code: exit',)
![ls & exit]
       ^
```

 and the result is the same with `![ls & exit]`, so it's not obvious to me what a solution looks like here. Thoughts?

**Comment by dotsdl** [comment]
From @scopatz:

> We only have & implemented for background mode when it is the last token of a subproc command.  

> This is a little annoying, but a workaround is "cmd && exit || exit"

> To implement this we'd want to overload the bitwise operator `&`, ie the __and__() method on the CompletedCommand and HiddenCompletedCommand classes. There would also be a bunch of minor changes in the parser, tools and elsewhere.  Luckily, it basically follows the same implementation as &&, ||, and, or.  So the structure is already there.

> I'd welcome a PR to this effect and would be happy to help anyone interested in tackling it!

**Comment by dotsdl** [comment]
Closing as no longer important to reporting user.
