### ISSUE TITLE
Exception on xonsh master

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1530]
xonsh master fails on my system, in a way that xonsh 0.4.4 doesn't:

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/Users/santagada/devel/xonsh/xonsh/proc.py", line 349, in wrapped_simple_command
    r = f(args, i)
  File "/Users/santagada/devel/xonsh/xonsh/completers/_aliases.py", line 98, in completer_alias
    if len(args) == 0 or args[0] not in (VALID_ACTIONS | {'help'}):
TypeError: unsupported operand type(s) for |: 'LazyObject' and 'set'
```

**Comment by gforsyth** [comment]
Yeah, looks like that single | should be a double. Or better still, just `or`

**Comment by gforsyth** [comment]
Wait, nevermind. Ignore that.

**Comment by scopatz** [comment]
I think this is a deficiency in LazyObject.

**Comment by laerus** [comment]
maybe LazyObject needs the `__or__` special method too, or just all the operations special methods.
