### ISSUE TITLE
Error when running external commands inside vim

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1536]
in a vim session, `shift-v` to select multiple lines, then type: `:'<,'>!sort`, exceptions will raise:

<img width="1425" alt="screen shot 2016-08-07 at 12 20 15 pm" src="https://cloud.githubusercontent.com/assets/177049/17460450/bc03821c-5c99-11e6-8722-bac3abdcff58.png">

**Comment by laerus** [comment]
i can reproduce this, 
```
:'<,'>!sort
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/execer.py", line 153, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/home/laerus/projects/xonsh/xonsh/parsers/base.py", line 311, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/laerus/.local/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/laerus/.local/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/laerus/.local/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/laerus/projects/xonsh/xonsh/parsers/base.py", line 2344, in p_error
    self.xonsh_code)
  File "/home/laerus/projects/xonsh/xonsh/parsers/base.py", line 412, in _parse_error
    raise err
SyntaxError: f428f8a1f4989f95f6f19bed5b79d409:1:7: ('code: ![',)
(sort) ![< /tmp/nvim4klpJq/15 > /tmp/nvim4klpJq/16]
       ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laerus/.local/bin/xonsh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/laerus/projects/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/home/laerus/projects/xonsh/xonsh/main.py", line 222, in main
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "/home/laerus/projects/xonsh/xonsh/codecache.py", line 188, in run_code_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/home/laerus/projects/xonsh/xonsh/codecache.py", line 104, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode)
  File "/home/laerus/projects/xonsh/xonsh/execer.py", line 100, in compile
    tree = self.parse(input, ctx, mode=mode, transform=transform)
  File "/home/laerus/projects/xonsh/xonsh/execer.py", line 71, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/home/laerus/projects/xonsh/xonsh/execer.py", line 211, in _parse_ctx_free
    raise original_error
  File "/home/laerus/projects/xonsh/xonsh/execer.py", line 153, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/home/laerus/projects/xonsh/xonsh/parsers/base.py", line 311, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/laerus/.local/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/laerus/.local/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/laerus/.local/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/laerus/projects/xonsh/xonsh/parsers/base.py", line 2344, in p_error
    self.xonsh_code)
  File "/home/laerus/projects/xonsh/xonsh/parsers/base.py", line 412, in _parse_error
    raise err
SyntaxError: f428f8a1f4989f95f6f19bed5b79d409:1:9: ('code: /',)
(sort) < /tmp/nvim4klpJq/15 > /tmp/nvim4klpJq/16
         ^
shell returned 1

E485: Can't read file /tmp/nvim4klpJq/16
```

also this seems to happen with any command i.e:
`:'<,'>!ls`

**Comment by scopatz** [comment]
Is this still an issue?

**Comment by mitnk** [comment]
yes, issue still exists. seems not related with exec.

**Comment by scopatz** [comment]
looks like this is related to some redirection error

**Comment by scopatz** [comment]
Is there a vim user who can verify that this still occurs?

**Comment by mitnk** [comment]
yes, the issue is still there :)

**Comment by scopatz** [comment]
Ok, good to know. It seems like it is that redirection issue.

**Comment by mitnk** [comment]
not sure, the issue traceback keeps the same as reported in above threads.

**Comment by scopatz** [comment]
If you have a new traceback, please post it :)

**Comment by mitnk** [comment]
This is the traceback based on the latest codebase.
The command in vim is `:'<,'>!sort` (same as I mentioned at the top).
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/execer.py", line 164, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/parsers/base.py", line 336, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/parsers/base.py", line 2695, in p_error
    column=p.lexpos))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/parsers/base.py", line 467, in _parse_error
    raise err
SyntaxError: 831c6d7c47d756ae8ea9abf05adf1f5f:1:7: ('code: ![',)
(sort) ![< /var/folders/cr/34w13ttn31z70r9c3mc905600000gn/T/v3BdjgU/0 > /var/folders/cr/34w13ttn31z70r9c3mc905600000gn/T/v3BdjgU/1]
       ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/xonsh", line 3, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/main.py", line 339, in main
    _failback_to_other_shells(args, err)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/main.py", line 303, in _failback_to_other_shells
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/main.py", line 337, in main
    return main_xonsh(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/main.py", line 371, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/codecache.py", line 189, in run_code_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/codecache.py", line 105, in compile_code
    filename=filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/execer.py", line 109, in compile
    transform=transform)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/execer.py", line 79, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/execer.py", line 222, in _parse_ctx_free
    raise original_error
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/execer.py", line 164, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/parsers/base.py", line 336, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/parsers/base.py", line 2695, in p_error
    column=p.lexpos))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/parsers/base.py", line 467, in _parse_error
    raise err
SyntaxError: 831c6d7c47d756ae8ea9abf05adf1f5f:1:9: ('code: /',)
(sort) < /var/folders/cr/34w13ttn31z70r9c3mc905600000gn/T/v3BdjgU/0 > /var/folders/cr/34w13ttn31z70r9c3mc905600000gn/T/v3BdjgU/1
         ^

shell returned 1
```

**Comment by scopatz** [comment]
Thanks!

**Comment by scopatz** [comment]
Ok this has nothing to do with the redirections, but instead has to do with the parentheses around sort. Is there any way to have vim turn this off?

**Comment by scopatz** [comment]
See potential fix in #2260

**Comment by mitnk** [comment]
Thanks @scopatz #2260 did the job!

**Comment by scopatz** [comment]
great!
