### ISSUE TITLE
EOF in multi-line string (always; without EOF)

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#1558]
The second hit of return in a multiline string consistently results in a "SyntaxError: EOF in multiline string": 
```sh
$ a = """<CR>
<CR>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16049, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 310, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2337, in p_error
    self.xonsh_code)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 411, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:2:9: Unmatched "]" at line 2, column 9
![a = """]
         ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 100, in push
    locs=None)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15996, in compile
    tree = self.parse(input, ctx, mode=mode, transform=transform)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15967, in parse
    tree, input = self._parse_ctx_free(input, mode=mode)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16107, in _parse_ctx_free
    raise original_error
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16049, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 310, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2337, in p_error
    self.xonsh_code)
  File "/usr/lib/python3.5/site-packages/xonsh/parsers/base.py", line 411, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:0:0: EOF in multi-line string
a = """
^
$ xonsh --version
('xonsh/0.4.4',)
$ uname -r
4.7.0-1-ARCH
```

**Comment by laerus** [comment]
thanks for reporthing this @OJFord! i think this is annoying and definitely something we should fix.

**Comment by gkzsolt** [comment]
Was this fixed ? I have this problem in an `xonsh-x86_64.AppImage`:

```
xonsh $ for _ in range(10):
..................     print(random.randint(1000, 10000)
..................
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/tmp/.mount_xonsh-U8ITl5/opt/python3.8/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 14470, in _parse_ctx_free
    tree = self.parser.parse(
  File "/tmp/.mount_xonsh-U8ITl5/opt/python3.8/lib/python3.8/site-packages/xonsh/parsers/base.py", line 523, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/tmp/.mount_xonsh-U8ITl5/opt/python3.8/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/tmp/.mount_xonsh-U8ITl5/opt/python3.8/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/tmp/.mount_xonsh-U8ITl5/opt/python3.8/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/tmp/.mount_xonsh-U8ITl5/opt/python3.8/lib/python3.8/site-packages/xonsh/parsers/base.py", line 3459, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/tmp/.mount_xonsh-U8ITl5/opt/python3.8/lib/python3.8/site-packages/xonsh/parsers/base.py", line 650, in _parse_error
    raise_parse_error(msg, loc, self.xonsh_code, self.lines)
  File "/tmp/.mount_xonsh-U8ITl5/opt/python3.8/lib/python3.8/site-packages/xonsh/parsers/base.py", line 238, in raise_parse_error
    raise err
SyntaxError: <xonsh-code>:2:0: ('code: ![',)
![    print(random.randint(10]00, 10000)
^

$ xonsh --version
xonsh/0.11.0

$ uname -r
5.13.0-39-generic

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```
Unfortunately this prevents me in using xonsh at all. I didn't imagine such basic bugs exist after years of development :(

**Comment by gforsyth** [comment]
You are missing a closing parenthesis in your `print` statement.

**Comment by gkzsolt** [comment]
Oops, thank you very much. I am really sorry...

**Comment by gforsyth** [comment]
> Oops, thank you very much. I am really sorry...

No problem -- the traceback you are getting isn't the one I expect and should've been more helpful.  Feel free to ask usage questions in the "Discussions" tab, or you can come find the `xonsh` room on gitter / matrix (https://gitter.im/xonsh/xonsh)
