### ISSUE TITLE
UnboundLocalError when disabling script caching for s script that has already been run and cached once.

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#1589]
Maybe @adqm knows how to solve this off the top of his head? :)

```console
scopatz@artemis ~/temp $ $XONSH_CACHE_SCRIPTS = False
scopatz@artemis ~/temp $ env XONSH_DEBUG=1 xonsh t.xsh 
Traceback (most recent call last):
  File "/home/scopatz/.local/bin/xonsh", line 3, in <module>
    main()
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/main.py", line 233, in main
    loc=None, mode='exec')
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/codecache.py", line 144, in run_script_with_cache
    update_cache(ccode, cachefname)
UnboundLocalError: local variable 'cachefname' referenced before assignment
```

*edited*

**Comment by adqm** [comment]
Possibly!  Could you please make a traceback with amalgam turned off?

**Comment by adqm** [comment]
Nvm, found the relevant spot in the code.  Looking into it now.

**Comment by scopatz** [comment]
Edited in original post

**Comment by scopatz** [comment]
Thanks for looking into it!

**Comment by adqm** [comment]
Simple fix.  PR incoming.

**Comment by scopatz** [comment]
Amazing @adqm!
