### ISSUE TITLE
ssh-copy-id for xonsh user on the remote side

### ISSUE THREAD

**Issue by flavius** [xonsh/xonsh#1659]
Attempting to copy the ssh public key into the `authorized_keys` of a remote user having xonsh as a shell. Stderr:

```
⋊> ~ ssh-copy-id flav@xxx.xxx.xxx.xx                                                                                                                                                           22:26:17
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
flav@138.201.137.99's password: 
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15600, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'exec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16534, in main
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2062, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1937, in run_compiled_code
    func(code, glb, loc)
  File "74c9f1de0f9d47f6f60e067c2c822ae0", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15737, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15610, in run_subproc
    raise XonshError(e)
xonsh.__amalgam__.XonshError: xonsh: subprocess mode: command not found: exec
Did you mean one of the following?
    ex:      Command (/usr/bin/ex)
    xexec:   Alias
    exit:    Alias
    expr:    Command (/usr/bin/expr)
    expect:  Command (/usr/bin/expect)
```

Version on that remote server:

```
root@hwhost ~ # xonsh --version
('xonsh/0.4.4',)
```

**Comment by laerus** [comment]
hey @flavius! can you try updating on the latest version? either from PyPI or from master, i think this is solved.

**Comment by flavius** [comment]
@laerus Yes that fixes it, I'll close this issue.

A faster release cycle would be helpful.
