### ISSUE TITLE
Single-character `cd` produces IndexError on Windows

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1667]
```
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\site-packages\xonsh\proc.py", line 354, in wrapped_simple_command
    r = f(args, i)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\site-packages\xontrib\avox.py", line 149, in cd_handler
    rtn = _old_cd(args, stdin)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\site-packages\xonsh\dirstack.py", line 212, in cd
    if ON_WINDOWS and (d[0] == d[1]) and (d[0] in (os.sep, os.altsep)) \
IndexError: string index out of range
```

In cases where `d` is a single character (eg, `cd .`), the middle check fails because there is no `d[1]`.

**Comment by scopatz** [comment]
Thanks for reporting @astronouth7303!

**Comment by bobhy** [comment]
New PR #1684 includes a fix for index error when AUTO_PUSHD enabled.

**Comment by gforsyth** [comment]
has this been fixed on master, @astronouth7303 ?

**Comment by astronouth7303** [comment]
Yup, seems to be!
