### ISSUE TITLE
Generator expressions sometimes not properly recognized

### ISSUE THREAD

**Issue by cryzed** [xonsh/xonsh#1673]
This code snippet executes successfully using Python 3.5.2...

```python
import os

HOME_BIN = os.path.expanduser('~/.bin')


def get_all_paths(path):
    paths = [path]
    for root, dirs, files in os.walk(path):
        paths.extend(os.path.join(root, d) for d in dirs)
        paths.extend(os.path.join(root, f) for f in files)

    return paths


print(len(get_all_paths(HOME_BIN)))
```

 ...but fails when using xonsh/0.4.6.dev43:

```
cryzed@arch ~ $ python test.py
8
cryzed@arch ~ $ xonsh test.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16319, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'for'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17534, in main
    loc=None, mode='exec')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2041, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1961, in run_compiled_code
    func(code, glb, loc)
  File "test.py", line 15, in <module>
    print(len(get_all_paths(HOME_BIN)))
  File "test.py", line 9, in get_all_paths
    paths.extend(os.path.join(root, d) for d in dirs)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16456, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16329, in run_subproc
    raise XonshError(e)
xonsh.__amalgam__.XonshError: xonsh: subprocess mode: command not found: for
Did you mean one of the following?
    pr:   Command (/usr/bin/pr)
    EOF:  Alias
    tr:   Command (/usr/bin/tr)
    od:   Command (/usr/bin/od)
    fg:   Alias
```

I didn't manage to simplify the code snippet much more, because this works:

```python
import os

a = []
a.extend(os.path.join('/', str(b)) for b in range(10))
print(repr(a))
```

So I'm not exactly sure what's going on. The issue can be worked around by adding additional parenthesis to the `paths.extend` argument:

```python
paths.extend((os.path.join(root, d) for d in dirs))
paths.extend((os.path.join(root, f) for f in files))
```

I mentioned this in IRC and Gitter, but it seems to have been missed completely.

**Comment by scopatz** [comment]
Thanks for reporting @cryzed, and sorry about missing the earlier reports! We'll try to figure this out shortly.

**Comment by cryzed** [comment]
Sounds great, and no worries!

**Comment by blahgeek** [comment]
I found that it went wrong because `dirs` is a valid command in $PATH.

**Comment by scopatz** [comment]
That is strange.  I doubt it is that, because PATH is never checked when transforming the AST.  If anything it is that the multiple targets in the for-loop are not being added to the context.

**Comment by scopatz** [comment]
I have a potential fix in #1705, if you want to take it for a whirl!

**Comment by cryzed** [comment]
Works on my end, however the first time I run it and, I assume, the cached bytecode is generated it prints the AST. There might be left-over debug statements in the branch? Thanks for the fix @scopatz!

**Comment by scopatz** [comment]
Whoops! Thanks! I have now removed the dead code

**Comment by cryzed** [comment]
Thank you! :+1:
