### ISSUE TITLE
OS X | Error when clicking to open a file with MacVim

### ISSUE THREAD

**Issue by amitkot** [xonsh/xonsh#1677]
When I click a file in the Finder to open it with the associated app, MacVim, the MacVim app is started, or if already open - the focus is passed to it, but the file is not opened.

The odd thing is that the terminal which is open at the time (iTerm2) immediately prints the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.4.4/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15600, in run_subproc
    **subproc_kwargs)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'exec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.4.4/libexec/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/Cellar/xonsh/0.4.4/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16550, in main
    mode='exec')
  File "/usr/local/Cellar/xonsh/0.4.4/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2062, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/Cellar/xonsh/0.4.4/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1937, in run_compiled_code
    func(code, glb, loc)
  File "be098410c4cac50e8c360cd5a08fe62f", line 1, in <module>
  File "/usr/local/Cellar/xonsh/0.4.4/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15737, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/Cellar/xonsh/0.4.4/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15610, in run_subproc
    raise XonshError(e)
xonsh.__amalgam__.XonshError: xonsh: subprocess mode: command not found: exec
Did you mean one of the following?
    ex:     Command (/usr/bin/ex)
    xexec:  Alias
    xed:    Command (/usr/bin/xed)
    xjc:    Command (/usr/bin/xjc)
    expr:   Command (/bin/expr)
```

Is this a Xonsh issue, or is it a problem with the (Homebrew) version of MacVim I have installed?

**Comment by laerus** [comment]
hey @amitkot, thanks for reporting! Can you try updating xonsh to the latest version from PyPI or master? i think this exec issue has been solved.

**Comment by gforsyth** [comment]
Closing this.  Please ping if the issue persists.

**Comment by scopatz** [comment]
I also believe that this has been solved. Please reopen if needed

**Comment by amitkot** [comment]
Thanks, I haven't encountered this problem recently.
