### ISSUE TITLE
'cd' causes an error

### ISSUE THREAD

**Issue by grovesteyn** [xonsh/xonsh#1680]
When I change directories with 'cd' I get the following debug info:

grove@grove-UX302LG ~ $ cd
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xontrib/z.py", line 205, in cd_handler
    self.add(self.getpwd())
  File "/usr/local/lib/python3.4/dist-packages/xontrib/z.py", line 177, in add
    data = list(self.load_data())
  File "/usr/local/lib/python3.4/dist-packages/xontrib/z.py", line 85, in load_data
    with open(self.Z_DATA, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/grove/.z'

Any ideas?

**Comment by laerus** [comment]
hey @grovesteyn! this seems like a bug in xontrib-z, maybe @astronouth7303 can take a look.

**Comment by scopatz** [comment]
Agreed. This doesn't seem to be a bug in xonsh directly.   Thanks for reporting though!

**Comment by astronouth7303** [comment]
Confirmed. That file is used by xontrib-z. You can close this bug here.
