### ISSUE TITLE
PTK BrokenPipeError/OSError

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1710]
one out of 3-4 times on xonsh startup i'm getting 

```
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/ptk/shortcuts.py", line 108, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 153, in run
    t()
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 81, in read_from_stdin
    inputstream.feed(data)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 390, in feed
    self._input_parser.send(c)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 299, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 332, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 1019, in feed_key
    cli.input_processor.process_keys()
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 209, in process_keys
    cli.invalidate()
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 333, in invalidate
    self.eventloop.call_from_executor(redraw, _max_postpone_until=_max_postpone_until)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 236, in call_from_executor
    os.write(self._schedule_pipe[1], b'x')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laerus/.local/bin/xonsh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/laerus/projects/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/home/laerus/projects/xonsh/xonsh/main.py", line 221, in main
    shell.shell.cmdloop()
  File "/home/laerus/projects/xonsh/xonsh/ptk/shell.py", line 114, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/laerus/projects/xonsh/xonsh/ptk/shell.py", line 83, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/laerus/projects/xonsh/xonsh/ptk/shortcuts.py", line 113, in prompt
    eventloop.close()
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 252, in close
    os.close(schedule_pipe[0])
OSError: [Errno 9] Bad file descriptor
```

is this a bug in our end or should i open an issue on ptk?

**Comment by scopatz** [comment]
Hmm this is disconcerting

**Comment by scopatz** [comment]
Thanks for reporting @laerus!

**Comment by gforsyth** [comment]
Hey @laerus -- have you upgraded prompt_toolkit lately?  And what version are you on?

**Comment by laerus** [comment]
yes i'm on the latest ptk version `prompt-toolkit==1.0.7` on PyPI, i don't remember getting that before updating, maybe i should report upstream anyway.
