### ISSUE TITLE
'NoneType' object is not iterable error with a fresh new xonsh install in OSX via homebrew

### ISSUE THREAD

**Issue by paulhybryant** [xonsh/xonsh#1715]
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17472, in main
    args = premain(argv)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17457, in premain
    builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17203, in __init__
    kwargs.get('cacheall', False))
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17251, in _init_environ
    debug_level=debug)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16856, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16734, in load_builtins
    builtins.aliases.update(load_foreign_aliases(issue_warning=False))
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 8569, in load_foreign_aliases
    for alias in set(shaliases) & set(xonsh_aliases):
TypeError: 'NoneType' object is not iterable

**Comment by melund** [comment]
I think I see the bug and how to fix it. It is also a sign that the loading the `foreign_shell_data` somehow failed on your machine.

**Comment by laerus** [comment]
`shaliases` never seem to be None actually,  maybe it's the `xonsh_aliases` that is None that breaks this.

**Comment by melund** [comment]
Maybe that can also happen, but `shaliases` can be None if the `subproc` command  in `foreign_shell_data` somehow fail.

**Comment by melund** [comment]
See here: https://github.com/xonsh/xonsh/blob/420dc0bbf4744452518afeefc83437eaee2266e8/xonsh/foreign_shells.py#L281

**Comment by laerus** [comment]
oh right yea, missed that part, ty! maybe this should return two empty dicts instead of `None, None` then we won't have to check for either shaliases or xonsh_aliases

**Comment by laerus** [comment]
let's make sure we fixed this issue anyway, 

hey @paulhybryant can you give it a try on the latest master? thanks in advance.

**Comment by melund** [comment]
@laerus No, we can't just return empty dicts here. We need some way to know if the command failed. It could in principle return empty dicts even if it succeeded. It is used in [`source_foreign`](https://github.com/xonsh/xonsh/blob/master/xonsh/aliases.py#L229) so we now know if we can 'trust' the output and use it when updating/adding/removing xonsh environment variables.

**Comment by melund** [comment]
There might be a more elegant way of accomplishing the same, but it does serve a specific purpose.

**Comment by paulhybryant** [comment]
@laerus Thanks for the quick fix.
I can confirm that this error goes away on the latest master.

**Comment by laerus** [comment]
thanks for the feedback @paulhybryant!
