### ISSUE TITLE
Xonsh hangs when opening a new terminal

### ISSUE THREAD

**Issue by amitkot** [xonsh/xonsh#1729]
Using OS X, I have Xonsh setup as my default shell.
When opening a new terminal, it hangs and nothing happens.
When pressing Ctrl+C, I get:

```
Last login: Wed Sep 14 09:15:27 on ttys001
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17472, in main
    args = premain(argv)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17457, in premain
    builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17203, in __init__
    kwargs.get('cacheall', False))
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17251, in _init_environ
    debug_level=debug)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16856, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16692, in load_builtins
    builtins.__xonsh_env__ = env = Env(default_env(config=config, login=login))
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13572, in default_env
    issue_warning=False)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 8537, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 8263, in foreign_shell_data
    universal_newlines=True)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

Using a terminal I already have open:

```
$ xonfig 
+------------------+-----------------+
| xonsh            | 0.4.6           |
| Git SHA          | None            |
| Python           | 3.5.2           |
| PLY              | 3.7             |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by laerus** [comment]
hey @amitkot thanks for reporting!

Can you please post the output of `~/.config/xonsh/config.json` ?

**Comment by amitkot** [comment]
Sure, @laerus :

```
{
 "env": {
   "BASH_COMPLETIONS": [
     "/usr/local/etc/bash_completion", 
     "/opt/local/etc/profile.d/bash_completion.sh", 
     "/usr/local/etc/bash_completion.d" 
   ],
   "INDENT": "  ",
   "PATH": [
     "/usr/local/opt/android-sdk/build-tools/19.1.0",
     "/usr/local/opt/android-sdk/platform-tools",
     "/usr/local/opt/android-sdk/tools",
     "/usr/local/opt/gradle/bin",
     "/usr/local/opt/maven/bin",
     "/usr/local/bin",
     "/usr/bin",
     "/bin",
     "/usr/sbin",
     "/sbin",
     "~/bin"
   ],
   "PROMPT": "{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_YELLOW} {cwd} {branch_color}{curr_branch}{NO_COLOR} {BOLD_YELLOW}{prompt_end}{NO_COLOR} ",
   "SHELL_TYPE": "best",
   "VI_MODE": true,
   "XONSH_COLOR_STYLE": "vim",
   "HOMEBREW_GITHUB_API_TOKEN": "..."

 },
 "foreign_shells": [
   {
     "shell": "bash",
     "sourcer": "."
   }
 ]
}
```

**Comment by amitkot** [comment]
OK, @laerus, I solved it.
It was a problem with the ~/.bashrc script that Xonsh was sourcing.
It was waiting for some keyboard input.

Thanks!
