### ISSUE TITLE
Completion traceback on Windows

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#1763]
I am now seeing this on Windows on master (eff2626)

```
(Miniconda) scopa@DESKTOP-EACI0E4 ~ $ cd Exception in thread Thread-24:                                                                                                        Traceback (most recent call last):                                                                                                                                               File "C:\Users\scopa\Miniconda\lib\threading.py", line 914, in _bootstrap_inner                                                                                                  self.run()                                                                                                                                                                   File "C:\Users\scopa\Miniconda\lib\threading.py", line 862, in run                                                                                                               self._target(*self._args, **self._kwargs)                                                                                                                                    File "C:\Users\scopa\Miniconda\lib\site-packages\prompt_toolkit\interface.py", line 836, in run                                                                                  completions = list(buffer.completer.get_completions(document, complete_event))                                                                                               File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\ptk\completer.py", line 42, in get_completions                                                          self.ctx)                                                                                                                                                                    File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\__amalgam__.py", line 124, in complete                                                                  out = func(prefix, line, begidx, endidx, ctx)                                                                                                                                File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\completers\__amalgam__.py", line 1082, in complete_cd                                                   return complete_dir(prefix, line, start, end, ctx, True)                                                                                                                     File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\completers\__amalgam__.py", line 773, in complete_dir                                                   filtfunc=os.path.isdir)                                                                                                                                                      File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\completers\__amalgam__.py", line 765, in complete_path                                                  path_str_end)                                                                                                                                                                File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\completers\__amalgam__.py", line 616, in _quote_paths                                                   (re.search(PATTERN_NEED_QUOTES, s) is not None or                                                                                                                            File "C:\Users\scopa\Miniconda\lib\re.py", line 173, in search                                                                                                                   return _compile(pattern, flags).search(string)                                                                                                                               File "C:\Users\scopa\Miniconda\lib\re.py", line 281, in _compile                                                                                                                 p, loc = _cache[type(pattern), pattern, flags]                                                                                                                               File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\__amalgam__.py", line 250, in __hash__                                                                  obj = self._lazy_obj()                                                                                                                                                       File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\__amalgam__.py", line 190, in _lazy_obj                                                                 obj = d['load']()                                                                                                                                                            File "C:\Users\scopa\AppData\Roaming\Python\Python35\site-packages\xonsh\completers\__amalgam__.py", line 492, in PATTERN_NEED_QUOTES                                            pattern.append('%')                                                                                                                                                        AttributeError: 'str' object has no attribute 'append' 
```

**Comment by scopatz** [comment]
I see the problem, fix incomming.

**Comment by scopatz** [comment]
See #1764
