### ISSUE TITLE
ValueError: embedded null byte while running in single command mode

### ISSUE THREAD

**Issue by shahinism** [xonsh/xonsh#1771]
I'm using [spacemacs](/syl20bnr/spacemacs/) which uses [exec-path-from-shell](purcell/exec-path-from-shell) to retrieve and set environment variables from user shell. After switching to Xonsh, `exec-path-from-shell` returns following error whenever it's executing:

``` bash
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17176, in main
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2086, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1961, in run_compiled_code
    func(code, glb, loc)
  File "2564f9e42c844b4292bd10a7e66fb82f", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16093, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15956, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
ValueError: embedded null byte
```

I've searched through it's source code and find it [here](/purcell/exec-path-from-shell/blob/master/exec-path-from-shell.el#L130) that it tries to execute a command like this in `xonsh`:

```
$ /usr/bin/xonsh -l -i -c "/usr/bin/printf '__RESULT\\000'"
```

Which in the end causes it to raise `embedded null byte` error. The command executes with no problem when I try to run it directly from with xonsh shell anyway.

**Comment by gforsyth** [comment]
Hey @shahinism, thanks for reporting!  I can confirm this issue. I've disabled `exec-path-from-shell` in my setup to make emacs stop complaining but I recognize that's a less than satisfactory workaround.

**Comment by shahinism** [comment]
Line `15956` in `__amalgam__.py` is trying to execute a `Popen` like this:
```
subprocess.Popen(['/usr/bin/printf', '__RESULT\x00'])
```
That `\x` is causing the problem.

**Comment by scopatz** [comment]
So it is a unicode null :(

**Comment by gforsyth** [comment]
Ok, so I did a runaround on the null thing, but found a different problem.  
The `exec-path-from-shell.el` script has a special case for using either fish, tcsh or variants since they aren't posix compliant.  I added xonsh to the list of non-compliant shells and that gets rid of the null thing, but now it raises this:

```console
Error (use-package): exec-path-from-shell :init: Non-zero exit code from shell /home/gil/anaconda/bin/xonsh invoked with args ("-l" "-i" "-c" "sh -c /usr/bin/printf\\ \\'__RESULT\\\\000\\%s\\\\000\\%s\\'\\ \\\"\\$\\{PATH-bb854beec0ae32f0a5826af282a62545\\}\\\"\\ \\\"\\$\\{MANPATH-bb854beec0ae32f0a5826af282a62545\\}\\\"").  Output was:
"Traceback (most recent call last):
  File \"/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py\", line 16645, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File \"/home/gil/anaconda/lib/python3.5/site-packages/xonsh/parsers/base.py\", line 329, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File \"/home/gil/anaconda/lib/python3.5/site-packages/ply/yacc.py\", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File \"/home/gil/anaconda/lib/python3.5/site-packages/ply/yacc.py\", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File \"/home/gil/anaconda/lib/python3.5/site-packages/xonsh/parsers/base.py\", line 2679, in p_error
    column=p.lexpos))
  File \"/home/gil/anaconda/lib/python3.5/site-packages/xonsh/parsers/base.py\", line 460, in _parse_error
    raise err
SyntaxError: 8f3485ebb94608e9eb9a8dc5973fb48f:1:60: ('code: {',)
![sh -c /usr/bin/printf\\ \\'__RESULT\\\\000\\%s\\\\000\\%s\\'\\ \\\"\\$\\{PATH-bb854beec0ae32f0a5826af282a62545\\}\\\"\\ \\\"\\$\\{MANPATH-bb854beec0ae32f0a5826af282a62545\\}\\\"]
```

The fallback is to use `sh` if the main shell isn't compliant, but that presents a problem for us, since we don't use escape characters and this bit of code clearly does.

**Comment by scopatz** [comment]
Out of curiosity, what happens if you use `xon.sh`, rather than `xonsh`?  This might apply the escapes correctly...

**Comment by shahinism** [comment]
```
/usr/bin/xon.sh -c "/usr/bin/printf '__RESULT\\000'"           
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/xonsh/__main__.py", line 2, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17176, in main
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2086, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1961, in run_compiled_code
    func(code, glb, loc)
  File "2564f9e42c844b4292bd10a7e66fb82f", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 16093, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15956, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
ValueError: embedded null byte
```

**Comment by scopatz** [comment]
Is this still happening?

**Comment by gforsyth** [comment]
Afraid so

**Comment by shahinism** [comment]
```
(xonsh) ➜  Downloads xonsh --version
xonsh/0.5.6
(xonsh) ➜  Downloads /usr/bin/xon.sh -c "/usr/bin/printf '__RESULT\\000'"
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/xonsh/__main__.py", line 2, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 17854, in main
    _failback_to_other_shells(argv, err)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 17819, in _failback_to_other_shells
    raise err
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 17852, in main
    return main_xonsh(argv)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 17881, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2089, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 1964, in run_compiled_code
    func(code, glb, loc)
  File "2564f9e42c844b4292bd10a7e66fb82f", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16159, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16096, in run_subproc
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15823, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15833, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9762, in __init__
    **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
ValueError: embedded null byte
```

**Comment by shahinism** [comment]
```
(xonsh) ➜  Downloads xon.sh -c "/usr/bin/printf '__RESULT\\000'"                                                                                                        
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__main__.py", line 2, in <module>
    main()
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19737, in main
    _failback_to_other_shells(args, err)
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19701, in _failback_to_other_shells
    raise err
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19735, in main
    return main_xonsh(args)
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19769, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2211, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2085, in run_compiled_code
    func(code, glb, loc)
  File "2564f9e42c844b4292bd10a7e66fb82f", line 1, in <module>
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18503, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18439, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12941, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18141, in run
    p = self._run_binary(kwargs)
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18151, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/shahin/.virtualenvs/xonsh/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 11749, in __init__
    **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
ValueError: embedded null byte
(xonsh) ➜  Downloads xon.sh --version
xonsh/0.5.6
```

**Comment by scopatz** [comment]
Potential fix is now in #2267

**Comment by scopatz** [comment]
So is this closable with the recent changes @gforsyth?

**Comment by gforsyth** [comment]
Yes. It doesn't mean that `exec-path-from-shell` will work _well_, but it won't be our fault anymore.

**Comment by gforsyth** [comment]
@shahinism -- please reopen if you're still seeing problems related to this issue.  Thanks!

**Comment by shahinism** [comment]
@scopatz @gforsyth Thank you guys, the problem is solved on master branch :)

**Comment by scopatz** [comment]
Great!
