### ISSUE TITLE
#!/usr/bin/env python

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1789]
in `setup.py` causes `releash.xsh` to fail

```
release.xsh:303:        if ns.do_pip:

release.xsh:304:        pipify()

release.xsh:126:def pipify():

release.xsh:128:    ./setup.py sdist upload

xonsh currently requires Python 3.4+
Traceback (most recent call last):
  File "/home/laerus/.local/bin/xonsh", line 3, in <module>
    main()
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/main.py", line 233, in main
    loc=None, mode='exec')
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/codecache.py", line 145, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "release.xsh", line 314, in <module>
    main()
  File "release.xsh", line 304, in main
    pipify()
  File "release.xsh", line 128, in pipify
    ./setup.py sdist upload
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/built_ins.py", line 664, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/laerus/.local/lib/python3.4/site-packages/xonsh/built_ins.py", line 619, in run_subproc
    output=output)
subprocess.CalledProcessError: Command '['/usr/bin/env', 'python', './setup.py', 'sdist', 'upload']' returned non-zero exit status 1
```

debian-stable

**Comment by laerus** [comment]
the shebang on `setup.py` is where it goes wrong.
`#!/bin/env python`, debian uses the python2 version,
should i use virtual env?

**Comment by astronouth7303** [comment]
On my machine, `python3` is also aliased in venvs, so it should be safe to use in shebangs.

**Comment by laerus** [comment]
yep this is perfectly fine when i'm on a venv, the problem is when i'm not

**Comment by scopatz** [comment]
Oh yeah, we can change that to python 3
