### ISSUE TITLE
Using sudo downstream of pipe causes traceback to be issued

### ISSUE THREAD

**Issue by gotgenes** [xonsh/xonsh#1806]
As mentioned in #1801, using `sudo` downstream of a pipe causes a traceback to be emitted to the terminal.

```
clasher@clasher-MBP ~/development $ which xonsh | sudo tee -a /etc/shells
Password:Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9429, in run
    proc.terminate()
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1782, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1777, in send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted
```

Note that xonsh is still active, still awaiting input for the password prompt, and will allow the command to progress when the password is successfully input.

```
+------------------+-----------------+
| xonsh            | 0.4.7.dev175    |
| Git SHA          | 9e67c21         |
| Python           | 3.5.2           |
| PLY              | 3.8             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by scopatz** [comment]
Ahh ok, this is because xonsh is trying to end a process that because of sudo it doesn't have permissions to. Should be an easy fix

**Comment by gforsyth** [comment]
This was fixed somewhere along the way.  Please reopen if the issue persists.  Thanks!
