### ISSUE TITLE
streaming aliases fail with !(alias)

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1828]
I found an issue with the streaming aliases. 

```
def _test_stream(args, stdin, stdout, stderr):
    print('hallo on err', file=stderr)
    print('hallo on out', file=stdout)
    return 1

aliases['test-stream'] = _test_stream
```

The `![]` works fine:
```
$ ![test-stream] 
hallo on out
hallo on err
```

But `!()` gives me this error: 
```
$ !(test-stream)
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "c:\users\mel\documents\xonsh\xonsh\base_shell.py", line 267, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "c:\users\mel\documents\xonsh\xonsh\codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "c:\users\mel\documents\xonsh\xonsh\main.py", line 132, in _pprint_displayhook
    printed_val = pretty(value)
  File "c:\users\mel\documents\xonsh\xonsh\pretty.py", line 120, in pretty
    printer.pretty(obj)
  File "c:\users\mel\documents\xonsh\xonsh\pretty.py", line 375, in pretty
    return _default_pprint(obj, self, cycle)
  File "c:\users\mel\documents\xonsh\xonsh\pretty.py", line 494, in _default_pprint
    _repr_pprint(obj, p, cycle)
  File "c:\users\mel\documents\xonsh\xonsh\pretty.py", line 691, in _repr_pprint
    output = repr(obj)
  File "c:\users\mel\documents\xonsh\xonsh\proc.py", line 1397, in __repr__
    s += ', '.join(a + '=' + str(getattr(self, a)) for a in self.attrnames)
  File "c:\users\mel\documents\xonsh\xonsh\proc.py", line 1397, in <genexpr>
    s += ', '.join(a + '=' + str(getattr(self, a)) for a in self.attrnames)
  File "c:\users\mel\documents\xonsh\xonsh\proc.py", line 1704, in returncode
    self.end()
  File "c:\users\mel\documents\xonsh\xonsh\proc.py", line 1553, in end
    for _ in self.tee_stdout():
  File "c:\users\mel\documents\xonsh\xonsh\proc.py", line 1490, in tee_stdout
    for line in self.iterraw():
  File "c:\users\mel\documents\xonsh\xonsh\proc.py", line 1458, in iterraw
    self.stream_stderr(safe_readlines(stderr, 1024))
  File "c:\users\mel\documents\xonsh\xonsh\proc.py", line 1511, in stream_stderr
    b = b''.join(lines)
TypeError: sequence item 0: expected a bytes-like object, str found
```

**Comment by scopatz** [comment]
Potential fix, and tests, are available in #1848
