### ISSUE TITLE
Function aliases: stdout redirect causes OSError

### ISSUE THREAD

**Issue by blahgeek** [xonsh/xonsh#1836]
```
$ def _f(args, stdin=None):
..     print('hello')
..  
$ aliases['f'] = _f
$ f > /dev/null
Exception in thread Thread-66:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 10062, in run
    sp_stdout = io.TextIOWrapper(io.open(self.c2pwrite, 'wb', -1),
OSError: [Errno 9] Bad file descriptor
```

I'm on current master (6ee0c3c9)

**Comment by scopatz** [comment]
Thanks for reporting @blahgeek.  My guess is that this is a /dev/null issue, as I believe that redirecting to a concrete file works.

**Comment by blahgeek** [comment]
no, it doesn't....

```
BlahGeeks-MBP /p/tmp> def _f(args, stdin=None):
.....................     print('hello')
.....................     
BlahGeeks-MBP /p/tmp> aliases['f'] = _f
BlahGeeks-MBP /p/tmp> $XONSH_SHOW_TRACEBACK = True
BlahGeeks-MBP /p/tmp> f > tmp.txt
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 10092, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9915, in proxy_two
    return f(args, stdin)
  File "/usr/local/lib/python3.5/site-packages/xontrib/prompt_ret_code.xsh", line 2, in _f
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9803, in write
    h.flush()
OSError: [Errno 9] Bad file descriptor
```

**Comment by scopatz** [comment]
Oof, OK.

**Comment by scopatz** [comment]
Alright, @blahgeek - I think i have fix in #1840. Would you mind testing it out, please?

**Comment by blahgeek** [comment]
Thanks a lot @scopatz !

I tested this simple helloword function and it works great, but I have an alias called `gitignore`: `aliases['gitignore'] = lambda args, stdin=None: execx('curl -4 -s https://www.gitignore.io/api/' + args + '\n')`, running that alias would still fail occasionally:

```
for i in range(100):
     gitignore osx > /tmp/tmp
     
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 10092, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9915, in proxy_two
    return f(args, stdin)
  File "/Users/BlahGeek/.xonshrc", line 32, in <lambda>
    aliases['gitignore'] = lambda args, stdin=None: execx('curl -4 -s https://www.gitignore.io/api/' + args + '\n')
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17709, in exec
    return exec(code, glbs, locs)
  File "/usr/local/lib/python3.5/site-packages/xontrib/prompt_ret_code.xsh", line 1, in <module>
    from xonsh.tools import ON_WINDOWS as _ON_WINDOWS
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17163, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17131, in run_subproc
    command.end()
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 10607, in end
    for _ in self.tee_stdout():
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 10548, in tee_stdout
    sys.stdout.flush()
  File "/usr/local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9830, in flush
    return self.handle.flush()
OSError: [Errno 9] Bad file descriptor
```

I cannot seem to reproduce this issue on other aliases, weird.

**Comment by blahgeek** [comment]
@gforsyth hi I don't think this issue is completely resolved as I mentioned above... could you please reopen this issue or should I create a new one? Thanks!

**Comment by gforsyth** [comment]
Hey @blahgeek -- sure, sorry about that, it was an automatic close when I merged in the PR.

**Comment by scopatz** [comment]
Yeah, sorry about the text in that PR.

**Comment by scopatz** [comment]
Hi @blahgeek - can you try out #1846, please?

**Comment by blahgeek** [comment]
That works great for me! Many thanks!

**Comment by scopatz** [comment]
Sweet! We'll just wait for another core-dev to review and merge then
