### ISSUE TITLE
Crash when running any command in windows

### ISSUE THREAD

**Issue by derekbrokeit** [xonsh/xonsh#1838]
I am currently running the master build (7cbe9e7652b6b6b0962d8ee01101816db8b63eac) on a windows machine. Running any command (either subprocess or python) results in an exception being thrown and xonsh crashing:

```python
>>> 1+1
Traceback (most recent call last):
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\site-packages\xonsh\__main__.py", line 2, in <module>
    main()
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 18240, in main
    shell.shell.cmdloop()
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\site-packages\xonsh\ptk\shell.py", line 128, in cmdloop
    self.default(line)
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 11248, in default
    tee = Tee(encoding=enc, errors=err) if store_stdout else io.StringIO()
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 11162, in __init__
    self.stdout = _TeeStd('stdout', self.memory)
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 11066, in __init__
    self.buffer = _TeeStdBuf(std.buffer, mem.buffer)
AttributeError: 'TextTranscodingWrapper' object has no attribute 'buffer'
Exception ignored in: <bound method Tee.__del__ of <xonsh.__amalgam__.Tee object at 0x0000020443D64128>>
Traceback (most recent call last):
  File "C:\Users\derek\AppData\Local\Continuum\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 11170, in __del__
    del self.stdout, self.stderr
AttributeError: stdout
```

On a related note, are there tests in place to check if particular builds work on windows?

**Comment by scopatz** [comment]
This seems to be related to https://github.com/Drekin/win-unicode-console/issues/16 and also seems unlikely to be fixed, sadly.  I'll put in a robustness fix.

**Comment by scopatz** [comment]
See #1839

**Comment by derekbrokeit** [comment]
#1839 seems to do the charm
