### ISSUE TITLE
Tab completion fails on Python 3.6 due to PEP 519 changes

### ISSUE THREAD

**Issue by jonathanhogg** [xonsh/xonsh#1887]
One for the future: tab completion throws exceptions on Python 3.6b2 because of changes made in `os.path.commonprefix()` as part of PEP 519 (file system path-like objects). It appears that a `set()` is being passed into this somewhere (no stack trace handy, but will re-create and post one after this message) and `commonprefix()` now requires an indexable object – in fairness, the 3.5.2 docs do state that this function takes a list.

I opened a Python bug on the regression, but they don't seem to be interested.

http://bugs.python.org/issue28527

**Comment by jonathanhogg** [comment]
Promised traceback:

```
Traceback (most recent call last):
  File "/opt/python36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/python36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python36/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 841, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/opt/python36/lib/python3.6/site-packages/xonsh/ptk/completer.py", line 42, in get_completions
    self.ctx)
  File "/opt/python36/lib/python3.6/site-packages/xonsh/completer.py", line 36, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/opt/python36/lib/python3.6/site-packages/xonsh/completers/bash.py", line 85, in complete_from_bash
    commprefix = os.path.commonprefix(out)
  File "/opt/python36/lib/python3.6/genericpath.py", line 76, in commonprefix
    if not isinstance(m[0], (list, tuple)):
TypeError: 'set' object does not support indexing
```

**Comment by jonathanhogg** [comment]
Sufficient – but slightly displeasing – fix:

```
*** bash.py.orig	2016-10-25 14:54:26.440015117 +0100
--- bash.py	2016-10-25 14:53:36.120445475 +0100
***************
*** 82,88 ****
  
      # From GNU Bash document: The results of the expansion are prefix-matched
      # against the word being completed
!     commprefix = os.path.commonprefix(out)
      strip_len = 0
      while strip_len < len(prefix):
          if commprefix.startswith(prefix[strip_len:]):
--- 82,88 ----
  
      # From GNU Bash document: The results of the expansion are prefix-matched
      # against the word being completed
!     commprefix = os.path.commonprefix(list(out))
      strip_len = 0
      while strip_len < len(prefix):
          if commprefix.startswith(prefix[strip_len:]):
```

**Comment by jonathanhogg** [comment]
This code in `xonsh.ptk.PromptToolkitCompleter.get_completions` may also be a problem, but I'm not sure:

```
                completions, l = self.completer.complete(prefix,
                                                         line_ex,
                                                         begidx + expand_offset,
                                                         endidx + expand_offset,
                                                         self.ctx)
                if len(completions) <= 1:
                    pass
                elif len(os.path.commonprefix(completions)) <= len(prefix):
                    self.reserve_space()
```

**Comment by gforsyth** [comment]
Hey @jonathanhogg -- thanks a ton!  I especially appreciate your effort to get the behavior changed in Python 3.6, but I agree that that seems to be a non-mover.  Oh well.  
I think your slightly displeasing fix will be the way to go for the moment.  On my long todo list is a refactor of the completions framework to allow returning lists for when a non-alphabetical order is desired.

In any case, the hit from casting from set to list seems pretty minimal.  

```python
In [7]: a = set(range(4000))

In [8]: %timeit b = list(a)
10000 loops, best of 3: 21.9 µs per loop

In [9]: a = set(range(100))

In [10]: %timeit b = list(a)
1000000 loops, best of 3: 1.01 µs per loop
```

**Comment by jonathanhogg** [comment]
Ah. This has become more of a problem now: homebrew have upgraded to 3.6, so tab completion on my Mac has stopped working now with xonsh 0.5.1 from pypi. Will patch again for the moment, but might be worth a point release now that 3.6 is final.

**Comment by jonathanhogg** [comment]
Hi @scopatz, just done this now. Lemme know if I've missed any desired documentation or other steps. Happy New Year! 😃

**Comment by scopatz** [comment]
Thanks a ton.

**Comment by jonathanhogg** [comment]
Seems good! Thanks!
