### ISSUE TITLE
inspect code with stdlib inspect

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1939]
In a xonsh session:

```
$ def foo(): pass
$ import inspect
$ inspect.getsource(foo)
```

with a clean xonsh, got `OSError`:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 11676, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1965, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/inspect.py", line 944, in getsource
    lines, lnum = getsourcelines(object)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/inspect.py", line 931, in getsourcelines
    lines, lnum = findsource(object)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/inspect.py", line 762, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

With a xonshrc setup, I got:

```
$ inspect.getsource(foo)
'import os.path\n'
```
This is the first line of a local xsh file loaded when xonsh got launched, see [here](https://github.com/mitnk/dotfiles/blob/master/xonsh/xonshrc#L99).

super help??:

```
$ foo??
Type:         function
String form:  <function foo at 0x104099488>
File:         /Users/hugo/.local/share/xonsh_ext/xonshrc.xsh
Definition:   ()
Source:
import os.path
<function __main__.foo>
```

**Comment by astronouth7303** [comment]
Hm. I'm not sure this is related, but in stack traces, things get attributed to the `vox_autocomplete` xontrib that shouldn't be.
