### ISSUE TITLE
new mercurial error on master

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1956]
I have mercurial installed, but would prefer that it is not even called (I have maybe one mercurial repo) but anyway it fails on my machine

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/xonsh/prompt/__amalgam__.py", line 649, in _get_field_value
    value = field_value() if callable(field_value) else field_value
  File "/usr/local/lib/python3.5/site-packages/xonsh/prompt/__amalgam__.py", line 472, in current_branch
    branch = get_hg_branch()
  File "/usr/local/lib/python3.5/site-packages/xonsh/prompt/__amalgam__.py", line 406, in get_hg_branch
    stderr=subprocess.DEVNULL)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'hg'
```

**Comment by santagada** [comment]
I don't see it anymore on master.
