### ISSUE TITLE
OSError Bad file descriptor with history and head

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1965]
```
$ history show all | head
foo
bar
...
$ Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 1286, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 1126, in proxy_two
    return f(args, stdin)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/history.py", line 767, in history_main
    _HIST_MAIN_ACTIONS[ns.action](ns, hist)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/history.py", line 463, in _hist_show
    print(c)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 1014, in write
    h.flush()
OSError: [Errno 9] Bad file descriptor
```

**Comment by scopatz** [comment]
Thanks for reporting @mitnk! #1967 should fix this issue.
