### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#1980]
```
$ history show all -nt
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 1283, in run
    sp_stdout = io.TextIOWrapper(io.open(self.c2pwrite, 'wb', -1),
OSError: [Errno 9] Bad file descriptor
```

**Comment by scopatz** [comment]
Thanks for reporting @mitnk, I am not able to reproduce this....

**Comment by mitnk** [comment]
Cannot reproduce now, closing for now.
