### ISSUE TITLE
PTK completer error

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2034]
put this into rc file:
```
__xonsh_completers__.pop('python_mode')
__xonsh_completers__.pop('base')
```

will got errors when hit <TAB> (PTK only)

```
$ <TAB>
$ Exception in thread Thread-10:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 923, in _bootstr
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/prompt_toolkit/interfn
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/ptk/completer.ps
    self.ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/__amalgam__.py"e
    out = func(prefix, line, begidx, endidx, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/completers/__amt
    if ltoks[0] == 'import' and start == len('import '):
IndexError: list index out of range
```

**Comment by scopatz** [comment]
Thanks for reporting @mitnk. It looks like this is a one-line fix for checking that ltoks actually has a value.

**Comment by scopatz** [comment]
Can you check out #2037 please?
