### ISSUE TITLE
redirecting stderr/stdout breaks Xonsh

### ISSUE THREAD

**Issue by orbisvicis** [xonsh/xonsh#2067]
Test sample:

```
#!/usr/bin/env xonsh

import contextlib
import pymtp
import sys
import os

mtp = pymtp.MTP()

@contextlib.contextmanager
def redirect_stderr_fd(stream):
    stderr_fd = sys.stderr.fileno()
    stderr_fd_dup = os.dup(stderr_fd)
    sys.stderr.close()
    os.dup2(stream.fileno(), stderr_fd)
    sys.stderr = os.fdopen(stderr_fd, "w")
    try:
        yield
    finally:
        sys.stderr.close()
        os.dup2(stderr_fd_dup, stderr_fd)
        sys.stderr = os.fdopen(stderr_fd, "w")
        os.close(stderr_fd_dup)

def device_list():
    with open(os.devnull) as f:
        with redirect_stderr_fd(f):
            # Really?!?! C library writing to stderr. Really?!?!
            return mtp.detect_devices()

def action_sync(device):
    ls -lah /BAR

action_sync(device_list()[0])
```

Result:
```
$ xonsh test.xsh 
ls: cannot access '/BAR': No such file or directory
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 9813, in run
    self._read_write(procerr, stderr, sys.__stderr__)
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 9877, in _read_write
    stdbuf.flush()
ValueError: I/O operation on closed file.

^CTraceback (most recent call last):
  File "/tmp/TESTTEMPDELETE/venv/bin/xonsh", line 3, in <module>
    main()
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 17852, in main
    return main_xonsh(argv)
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 17890, in main_xonsh
    loc=None, mode='exec')
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 2044, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 1964, in run_compiled_code
    func(code, glb, loc)
  File "test.xsh", line 34, in <module>
    action_sync(device_list()[0])
  File "test.xsh", line 32, in action_sync
    ls -lah /BAR
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 16159, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 16127, in run_subproc
    command.end()
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 11116, in end
    for _ in self.tee_stdout():
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 11041, in tee_stdout
    for line in self.iterraw():
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 11004, in iterraw
    time.sleep(timeout * cnt)
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 9962, in _signal_int
    self._restore_sigint(frame=frame)
  File "/tmp/TESTTEMPDELETE/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 9973, in _restore_sigint
    old(signal.SIGINT, frame)
KeyboardInterrupt
```

This is with most recent git, 9949e2c.

**Comment by scopatz** [comment]
Thanks for reporting @orbisvicis. Do you have a elf-contained example that doesn't rely on external libraries that we can test with? 

My guess is that the close operation is inherently unsafe. Xonsh itself redirects output so have you verified that sys.stderr.fileno() is 2?

**Comment by orbisvicis** [comment]
Updated example. Last example used pymtp to prevent a valid use-case for redirecting stderr:

```
#!/usr/bin/env xonsh

import subprocess
import contextlib
import sys
import os

@contextlib.contextmanager
def redirect_stderr_fd(stream):
    print("sys.stderr.fileno(): {}".format(sys.stderr.fileno()))
    stderr_fd = sys.stderr.fileno()
    stderr_fd_dup = os.dup(stderr_fd)
    sys.stderr.close()
    os.dup2(stream.fileno(), stderr_fd)
    sys.stderr = os.fdopen(stderr_fd, "w")
    print("sys.stderr.fileno(): {}".format(sys.stderr.fileno()))
    try:
        yield
    finally:
        sys.stderr.close()
        os.dup2(stderr_fd_dup, stderr_fd)
        sys.stderr = os.fdopen(stderr_fd, "w")
        print("sys.stderr.fileno(): {}".format(sys.stderr.fileno()))
        os.close(stderr_fd_dup)

def device_list():
    with open(os.devnull) as f:
        with redirect_stderr_fd(f):
            return [1,2,3]

def action_sync(device):
    # works:
    subprocess.run(["ls","-lah","/BAR"])
    # works:
    subprocess.run("ls -lah /BAR", shell=True)
    # fails:
    ls -lah /BAR

device_list()

action_sync([])
```

Result:
```
$ xonsh test.xsh 
sys.stderr.fileno(): 2
sys.stderr.fileno(): 2
sys.stderr.fileno(): 2
ls: cannot access '/BAR': No such file or directory
ls: cannot access '/BAR': No such file or directory
ls: cannot access '/BAR': No such file or directory
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 9813, in run
    self._read_write(procerr, stderr, sys.__stderr__)
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 9877, in _read_write
    stdbuf.flush()
ValueError: I/O operation on closed file.

^CTraceback (most recent call last):
  File "/tmp/TESTDIR/venv/bin/xonsh", line 3, in <module>
    main()
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 17852, in main
    return main_xonsh(argv)
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 17890, in main_xonsh
    loc=None, mode='exec')
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 2044, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 1964, in run_compiled_code
    func(code, glb, loc)
  File "test.xsh", line 41, in <module>
    action_sync([])
  File "test.xsh", line 37, in action_sync
    ls -lah /BAR
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 16159, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 16127, in run_subproc
    command.end()
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 11116, in end
    for _ in self.tee_stdout():
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 11041, in tee_stdout
    for line in self.iterraw():
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 11004, in iterraw
    time.sleep(timeout * cnt)
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 9962, in _signal_int
    self._restore_sigint(frame=frame)
  File "/tmp/TESTDIR/venv/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 9973, in _restore_sigint
    old(signal.SIGINT, frame)
KeyboardInterrupt
```

**Comment by scopatz** [comment]
So the issue here is that you are replacing `sys.stderr` but not `sys.__stderr__`. Meanwhile, you are forcibly closing the descriptor that `sys.__stderr__` is attached to. Xonsh uses `sys.__stderr__` in certain cases [because it has stronger guarantees about redirection](https://docs.python.org/3/library/sys.html#sys.__stdin__).

The fix that works for me is:

```diff
- sys.stderr = os.fdopen(stderr_fd, "w")
+ sys.stderr = sys.__stderr__ = os.fdopen(stderr_fd, "w")
```

in the two places that this line is present.  That said, I still caution against using `os.close()` on fd < 3. The Python docs [have more information on why this is problematic](https://docs.python.org/3.6/faq/library.html#why-doesn-t-closing-sys-stdout-stdin-stderr-really-close-it).

Please let us know if there is anything else.

**Comment by laerus** [comment]
@scopatz any way we can protect xonsh against cases like this?
this doesn't seem like a big deal when in a python REPL but on a shell this can totally break it.

**Comment by scopatz** [comment]
@laerus yeah we could probably do something. However, anything that we do still won't make it safe. I'd like to stress that the [Python docs tell people not to call `os.close(fd<3)`.](https://docs.python.org/3.6/faq/library.html#why-doesn-t-closing-sys-stdout-stdin-stderr-really-close-it) And if they do, they should expect things to break.

I am open to PRs that address this from the xonsh side. However, I am also inclined to leave it as it is, so the break happens early. The exception that happens here is much better than getting a segfault or similar in a C-extension library, in my opinion :).

**Comment by scopatz** [comment]
Did this fix work for you @orbisvicis?

**Comment by orbisvicis** [comment]
Yes, worked fine. Thanks for looking into it.

For what its worth, my interpretation of that faq isn't "don't close fd 0-2" but more like "think long and hard before closing fd 0-2".

The problem isn't that the underlying descriptor has been closed, but that `sys.__stderr__` is invalid while `sys.stderr` is valid. The backing file descriptor (2) is always valid.

Probably the solution is to check which is valid, `stderr` or `__stderr__`, then use that one.

**Comment by scopatz** [comment]
OK, well feel free to close this issue if you feel it has been addressed.
