### ISSUE TITLE
failback shell should only work with interactive mode

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#2077]
atm if there a a `fail.xsh` script that raises any exception we run `sh`

```
# fail.xsh 
raise ValueError('just because')
```

```
$ xonsh fail.xsh 
Traceback (most recent call last):
  File "/home/laerus/src/xonsh/xonsh/main.py", line 298, in main
    return main_xonsh(argv)
  File "/home/laerus/src/xonsh/xonsh/main.py", line 336, in main_xonsh
    loc=None, mode='exec')
  File "/home/laerus/src/xonsh/xonsh/codecache.py", line 145, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/laerus/src/xonsh/xonsh/codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "fail.xsh", line 1, in <module>
    raise ValueError('just because')
ValueError: just because
Xonsh encountered an issue during launch
Failback to /bin/sh
$ 
```

**Comment by scopatz** [comment]
+1, I agree. This should only be a couple of line fix

**Comment by laerus** [comment]
the tests may need some tweaking too.

**Comment by mitnk** [comment]
+1 too, did realise that .. PR sent.
