### ISSUE TITLE
Glob set/range wildcards cause error

### ISSUE THREAD

**Issue by OJFord** [xonsh/xonsh#2092]
Bash:
```bash
bash-4.4$ echo file[1-6]
file1 file2 file3 file4 file5 file6
bash-4.4$ echo file[123]
file1 file2 file3
bash-4.4$ 
```

Xonsh:
```sh
>echo file[1-6]

xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16719, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/parsers/base.py", line 335, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/parsers/base.py", line 2694, in p_error
    column=p.lexpos))
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/parsers/base.py", line 466, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:11: ('code: [',)
![echo file[1-6]]
           ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 17465, in compile
    locs=None)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16658, in compile
    transform=transform)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16628, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16777, in _parse_ctx_free
    raise original_error
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16719, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/parsers/base.py", line 335, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/parsers/base.py", line 2694, in p_error
    column=p.lexpos))
  File "/usr/local/Cellar/xonsh/0.5.2/libexec/lib/python3.6/site-packages/xonsh/parsers/base.py", line 466, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: file',)
echo file[1-6]
     ^
>echo file[123]
[similar]
```

I realise the "it's not working like Bash!" bug reports are a little tedious, but I believe in this case the intended behaviour is [expected to work *even on Windows*](https://en.wikipedia.org/wiki/Glob_(programming)), so I just include the Bash snippet as an expected output.

I haven't dug into it, but I assume it's reading the wildcard as a Python-index; then choking.

**Comment by scopatz** [comment]
Hi @OJFord, thanks for reporting.  Yeah we haven't extended the parser to this kind of globbing/matching yet.  However, you can always use an explicit glob:

```console
$ echo g`file[1-6]`
file1 file2 file3 file4 file5 file6
```

See  http://xon.sh/tutorial.html#normal-globbing for more details.  Pull requests welcome for anyone who wants to see this go in sooner

**Comment by anki-code** [comment]
Duplicate #2302
