### ISSUE TITLE
Some jobs control issues

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2133]
1. On Mac, run background & fg:

```
$ tail -f /tmp/goixy.log &
[1]+ running: tail -f /tmp/some.log & & (30817)

$ fg
[1]+ running: tail -f /tmp/some.log & (30817)
(**Here fg seems brought something into foreground, but stuck, let's ^C it**)

^C
$ Exception in thread Thread-16:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py",n
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py",o
    return f(args, stdin)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/jobs.py",g
    wait_for_active_job()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/jobs.py",b
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
ChildProcessError: [Errno 10] No child processes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _r
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py",n
    print_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/tools.py"n
    traceback.print_exc()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/traceback.py", line 159, in pc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/traceback.py", line 101, in pn
    print(line, file=file, end="")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/base_shele
    self.std.write(std_s)
AttributeError: 'NoneType' object has no attribute 'write'
```

2. on Mac, run foreground & ^Z

`^Z` doesn't work.

3. on Linux, run background & fg

```
$ tail -f /tmp/some.log &
[1]+ running: tail -f /tmp/some.log & & (26278)
pi@pi3: ~$
pi@pi3: ~$ fg
[1]+ running: tail -f /tmp/some.log & (26278)
(Stuck here too)

^C

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/proc.py", line 1304, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.6/site-packages/xonsh/proc.py", line 1144, in proxy_two
    return f(args, stdin)
  File "/usr/local/lib/python3.6/site-packages/xonsh/jobs.py", line 385, in fg
    wait_for_active_job()
  File "/usr/local/lib/python3.6/site-packages/xonsh/jobs.py", line 198, in wait_for_active_job
    obj.signal = (os.WTERMSIG(wcode), os.WCOREDUMP(wcode))
AttributeError: can't set attribute
```

**Comment by scopatz** [comment]
Thanks for opening this @mitnk!  (3) does work for me on linux on the current master.  At least when I tested it with less. Can you try (1) and (2) on current master, please?

**Comment by mitnk** [comment]
for (3), less does work. But `tail -f` seems not.

**Comment by scopatz** [comment]
Yeah, you are right. `tail -f` does not seem to work with backgrounding like it should

**Comment by scopatz** [comment]
Ok this is tricky.  job control wans't really written for the CommandPipeline / PopenThread ideas.

**Comment by scopatz** [comment]
Is this closable now @mitnk?

**Comment by mitnk** [comment]
is these issues not reproducible on your side?

**Comment by mitnk** [comment]
just had some check, all these issue still exists.

**Comment by scopatz** [comment]
Ok #2286 fixes the linux part for me. Would you mind giving it a shot on mac please @mitnk?

**Comment by mitnk** [comment]
It fixed 1) and 3). I'll open a separated issue for 2). Thanks @scopatz , it is a better patch than I was thinking.

**Comment by scopatz** [comment]
Yeah it was simpler than I thought too! I was afraid of this one :). Thanks for the review!
