### ISSUE TITLE
Loading history fails with readline shell (on windows) 

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2141]
When I start xonsh with the readline shell on windows it fails 20 seconds after showing the prompt. 

Probably something to do with loading the history on a separate thread. It doesn't happen with the PTK shell.

```
snail@sea ~ $ Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 18968, in run
    if line == readline.get_history_item(i - 1):
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 154, in get_history_item
    return self.mode._history.get_history_item(index)
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\lineeditor\history.py", line 52, in get_history_item
    item = self.history[index - 1]
IndexError: list index out of range
```

**Comment by scopatz** [comment]
Thanks for opening this @melund. I think that this was a legitimate logic error. #2145 should fix this.
