### ISSUE TITLE
Display all ### possibilities? prompt fails on Windows

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2142]
Pressing tab on the readline shell brings up a prompt instead of printing all possible completions. 

Nice, but it fails on windows. Different tracebacks depending on whether I press yes or no.

```
snail@sea ~ $
Display all 1651 possibilities? (y or n)n

Readline internal error
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 571, in readline
    self._readline_from_keyboard()
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 536, in _readline_from_keyboard
    if self._readline_from_keyboard_poll():
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 556, in _readline_from_keyboard_poll
    result = self.mode.process_keyevent(event.keyinfo)
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\modes\emacs.py", line 243, in process_keyevent
    r = self.process_keyevent_queue[-1](keyinfo)
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\modes\emacs.py", line 286, in _process_keyevent
    r = dispatch_func(keyinfo)
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\modes\basemode.py", line 257, in complete
    completions = self._get_completions()
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\modes\basemode.py", line 200, in _get_completions
    r = self.completer(ensure_unicode(text), i)
  File "C:\Users\mel\Anaconda3\lib\cmd.py", line 275, in complete
    self.completion_matches = compfunc(text, line, begidx, endidx)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\readline_shell.py", line 342, in completedefault
    show_completions = self._querycompletions(completions, endidx - begidx)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\readline_shell.py", line 302, in _querycompletions
    rl_on_new_line()
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\lazyasd.py", line 85, in __call__
    return obj(*args, **kwargs)
TypeError: 'NoneType' object is not callable
```

and if I press `y`

```
snail@sea ~ $
Display all 1651 possibilities? (y or n)y
....
...
[list of all commands]
.....
Readline internal error
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 571, in readline
    self._readline_from_keyboard()
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 536, in _readline_from_keyboard
    if self._readline_from_keyboard_poll():
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 556, in _readline_from_keyboard_poll
    result = self.mode.process_keyevent(event.keyinfo)
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\modes\emacs.py", line 243, in process_keyevent
    r = self.process_keyevent_queue[-1](keyinfo)
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\modes\emacs.py", line 286, in _process_keyevent
    r = dispatch_func(keyinfo)
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\modes\basemode.py", line 257, in complete
    completions = self._get_completions()
  File "C:\Users\mel\Anaconda3\lib\site-packages\pyreadline\modes\basemode.py", line 200, in _get_completions
    r = self.completer(ensure_unicode(text), i)
  File "C:\Users\mel\Anaconda3\lib\cmd.py", line 275, in complete
    self.completion_matches = compfunc(text, line, begidx, endidx)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\readline_shell.py", line 342, in completedefault
    show_completions = self._querycompletions(completions, endidx - begidx)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\readline_shell.py", line 319, in _querycompletions
    rl_on_new_line()
TypeError: 'NoneType' object is not callable

```

**Comment by scopatz** [comment]
(py)readline just seems totally unusable on windows for me. I just get the following error repeated over and over.

```console
Traceback (most recent call last):
  File "C:\Users\scopa\Miniconda\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "C:\Users\scopa\Miniconda\lib\site-packages\pyreadline\rlmain.py", line 569, in readline
    self.readline_setup(prompt)
  File "C:\Users\scopa\Miniconda\lib\site-packages\pyreadline\rlmain.py", line 565, in readline_setup
    self._print_prompt()
  File "C:\Users\scopa\Miniconda\lib\site-packages\pyreadline\rlmain.py", line 466, in _print_prompt
    x, y = c.pos()
  File "C:\Users\scopa\Miniconda\lib\site-packages\pyreadline\console\console.py", line 269, in pos
    self.GetConsoleScreenBufferInfo(self.hout, byref(info))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO
```

Do you have some special setting that let's this work?

**Comment by melund** [comment]
I get that as well. Starts as soon as run a subproc. If I find time I can try bisect when it started to happen.

**Comment by scopatz** [comment]
Is there a reason to prefer pyreadline over ptk? Just curious....

**Comment by melund** [comment]
It is faster. PTK is just much slower on Windows. I guess it is because it uses the console API, but it is just a guess. I hope @jonathanslenders will consider the ANSI backend for windows 10 in PTK 2.0 :) 

But in general, if the readline shell is pain to support on Win, I would be in favor of officially dropping support it (on Windows).

**Comment by melund** [comment]
Crude startup timings: 
xonsh (readline)  < 0.5 s
xonsh (ptk)  around 2 s

**Comment by jonathanslenders** [comment]
Hi @melund, ANSI backends for Windows 10 are definitely coming. Should normally be part of 2.0 indeed.

About the timings. Is that something related to prompt_toolkit 1.0.10 or did you had similar performance in 1.0.9 as well?

**Comment by melund** [comment]
@jonathanslenders .  No. I haven't noticed any decrease in speed between the different versions.

I will try to compare how fast xonsh launches in the Windows and the in the 'Windows subsystem for linux'. on the same computer.
