### ISSUE TITLE
Auto history GC doesn't seem to work.

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2148]
I have noticed that history seemed to take longer and longer time before starting up. It would take several minutes before history from previous sessions became available. My configuration is:

```
snail@sea ~ $ $XONSH_HISTORY_SIZE
(8128, 'commands')
```

But when I looked for the session files I had more than 8700 session files. 
```
snail@sea ~ $ histfiles= g`~/.local/share/xonsh/xonsh-*`
snail@sea ~ $ len(histfiles)
8735
```
I don't know if that many files would be a problem on Linux, but it is on win. 

Running `history gc` manually to limit the files simply stalls xonsh: 
```
snail@sea ~\.local\share\xonsh $ history gc --size 100 files
```
I tried to ctrl-z/ctrl-d, and after 10 sec it gave me this tb, but it didn't give me control back. So I ended up closing the terminal manually. 

``` 
Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\base_shell.py", line 322, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "C:\Users\mel\Documents\xonsh\xonsh\codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Users\mel\Documents\xonsh\xonsh\built_ins.py", line 859, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "C:\Users\mel\Documents\xonsh\xonsh\built_ins.py", line 827, in run_subproc
    command.end()
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 1908, in end
    for _ in self.tee_stdout():
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 1833, in tee_stdout
    for line in self.iterraw():
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 1796, in iterraw
    time.sleep(timeout * cnt)
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 749, in _signal_int
    self.send_signal(signum)
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 882, in send_signal
    time.sleep(1e-7)
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 749, in _signal_int
    self.send_signal(signum)
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 882, in send_signal
    time.sleep(1e-7)
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
AttributeError: module 'signal' has no attribute 'pthread_kill'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mel\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mel\Documents\xonsh\xonsh\__main__.py", line 2, in <module>
    main()
  File "C:\Users\mel\Documents\xonsh\xonsh\main.py", line 296, in main
    _failback_to_other_shells(args, err)
  File "C:\Users\mel\Documents\xonsh\xonsh\main.py", line 265, in _failback_to_other_shells
    raise err
  File "C:\Users\mel\Documents\xonsh\xonsh\main.py", line 294, in main
    return main_xonsh(args)
  File "C:\Users\mel\Documents\xonsh\xonsh\main.py", line 317, in main_xonsh
    shell.shell.cmdloop()
  File "C:\Users\mel\Documents\xonsh\xonsh\ptk\shell.py", line 149, in cmdloop
    self.default(line)
  File "C:\Users\mel\Documents\xonsh\xonsh\base_shell.py", line 322, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
AttributeError: module 'signal' has no attribute 'pthread_kill'

```

I think I will try the Sqlite backend now.

**Comment by mitnk** [comment]
> It would take several minutes before history from previous sessions became available ...
> ... I had more than 8700 session files.

Yeah, this was the exact reason motivated me to write the SQlite version. For JSON backend, I'd admit I haven't spent time dig into it, there are a few places we could improve, like fix (remove) the very old but "locked" files, or the "locked or not" but empty (no cmds values) files. Thousands of json files *are* a lot in any platform, loading them all would beyond a few seconds.

> AttributeError: module 'signal' has no attribute 'pthread_kill'

I think you found a bug here..

**Comment by scopatz** [comment]
Hi @melund thanks for reporting. I had no idea that this was causing problems like this.  I think one of the issues is that certain history files may not be unlocked, depending on how you exited xonsh. The atexit() hook should take care of unlocking files, but if you close the terminal window, Python may not get a chance to unlock the file. I don't know exactly what the conditions are for a clean shutdown of the interpreter, but you can always unplug the computer. So this was always a latent issue.

I have put in #2152 to address this.  Basically it will unlock files during GC if it noticed that they were created before the last boot.  This is how it should always have worked, but getting the last boot time is pretty annoying. 

The manual GC freezing seems like a separate, unrelated issue to the one I just described.

**Comment by scopatz** [comment]
@melund do you think it is OK to close this now?

**Comment by melund** [comment]
Sure
