### ISSUE TITLE
proc signal RecursionError

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#2176]
```
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
From 192.168.1.100 icmp_seq=1 Destination Host Unreachable
From 192.168.1.100 icmp_seq=2 Destination Host Unreachable
From 192.168.1.100 icmp_seq=3 Destination Host Unreachable
From 192.168.1.100 icmp_seq=4 Destination Host Unreachable
^C^C^C
^C^C
^C^C^Cxonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/laerus/src/xonsh/xonsh/base_shell.py", line 322, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/laerus/src/xonsh/xonsh/codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/laerus/src/xonsh/xonsh/built_ins.py", line 861, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/laerus/src/xonsh/xonsh/built_ins.py", line 829, in run_subproc
    command.end()
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 1908, in end
    for _ in self.tee_stdout():
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 1833, in tee_stdout
    for line in self.iterraw():
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 1796, in iterraw
    time.sleep(timeout * cnt)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 751, in _signal_int
    self._restore_sigint(frame=frame)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 764, in _restore_sigint
    old(signal.SIGINT, frame)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 749, in _signal_int
    self.send_signal(signum)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 882, in send_signal
    time.sleep(1e-7)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 749, in _signal_int
    self.send_signal(signum)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 882, in send_signal
    time.sleep(1e-7)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
 [...]
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 753, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 749, in _signal_int
    self.send_signal(signum)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 881, in send_signal
    while self.proc is None and dt < self.timeout:
RecursionError: maximum recursion depth exceeded in comparison
```

it's not that i can reproduce this reliably but it happened again before with different command, cannot recall which.

current master.

**Comment by scopatz** [comment]
Hi @laerus what command where you running? What does your setup look like?

**Comment by laerus** [comment]
oops missed the first line there, 
i was running `ping` on a lan machine,

this was on debian-testing under python3.5 and ptk.

i will try to get some info, just wanted to pin this cause it happened again when i was trying to Ctrl-C another command.

**Comment by laerus** [comment]
haven't seen that in the last days, closing for now
