### ISSUE TITLE
Provide __file__

### ISSUE THREAD

**Issue by flavius** [xonsh/xonsh#2178]
There should be a way to determine the location of the current script, no matter how it's executed:

1. as a stand-alone script with a xonsh shabang header
2. as a parameter to xonsh on the command line
3. via `source`

There is `$XONSH_SOURCE` (related #1169), but that one is not defined in case 3.

**Comment by scopatz** [comment]
Hi @flavius, thanks for reporting. It is unclear to me which one of these cases is failing. Can you please give a more detailed example. Thanks!

**Comment by flavius** [comment]
@scopatz Complete transcript of my terminal session, showcasing the source and the three cases.

```
⋊> /tmp cat -n test.xsh                                                                                                                                                                        22:12:51
     1	#!/usr/bin/xonsh
     2	
     3	print(__file__)
⋊> /tmp /tmp/test.xsh                                                                                                                                                                          22:12:57
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18676, in main
    _failback_to_other_shells(args, err)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18640, in _failback_to_other_shells
    raise err
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18674, in main
    return main_xonsh(args)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18711, in main_xonsh
    loc=None, mode='exec')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2165, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2085, in run_compiled_code
    func(code, glb, loc)
  File "./test.xsh", line 3, in <module>
    print(__file__)
NameError: name '__file__' is not defined
⋊> /tmp xonsh /tmp/test.xsh                                                                                                                                                                    22:13:13
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18676, in main
    _failback_to_other_shells(args, err)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18640, in _failback_to_other_shells
    raise err
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18674, in main
    return main_xonsh(args)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18711, in main_xonsh
    loc=None, mode='exec')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2165, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2085, in run_compiled_code
    func(code, glb, loc)
  File "./test.xsh", line 3, in <module>
    print(__file__)
NameError: name '__file__' is not defined
⋊> /tmp xonsh                                                                                                                                                                                  22:13:26
flav@localhost /tmp $ source /tmp/test.xsh 
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
NameError: name '__file__' is not defined
```

**Comment by scopatz** [comment]
Thanks @flavius. There is an initial implementation in #2181

**Comment by scopatz** [comment]
Closing this since #2181 has been merged. Please feel free to reopen if you continue to have issues.
