### ISSUE TITLE
cd stderr redirection IO error

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#2195]
```
laerus@hive$ cd wrongname
cd: no such file or directory: wrongname
laerus@hive$ cd wrongname err> /dev/null
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/laerus/src/xonsh/xonsh/base_shell.py", line 322, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/laerus/src/xonsh/xonsh/codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/laerus/src/xonsh/xonsh/built_ins.py", line 856, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/laerus/src/xonsh/xonsh/built_ins.py", line 824, in run_subproc
    command.end()
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 1940, in end
    self._end(tee_output=tee_output)
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 1948, in _end
    for _ in self.tee_stdout():
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 1864, in tee_stdout
    for line in self.iterraw():
  File "/home/laerus/src/xonsh/xonsh/proc.py", line 1776, in iterraw
    stderr = NonBlockingFDReader(stderr.fileno(), timeout=timeout)
ValueError: I/O operation on closed file
laerus@hive$ cd wrongname out> /dev/null
cd: no such file or directory: wrongname
```

latest master
```
$ xonfig
+------------------+---------------------------------------------------+
| xonsh            | 0.5.4                                             |
| Git SHA          | 77d30597                                          |
| Commit Date      | Feb 15 09:15:53 2017                              |
| Python           | 3.5.3                                             |
| PLY              | 3.9                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.13                                            |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.2.0                                             |
| on posix         | True                                              |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7f49b7b93588> |
| distro           | debian                                            |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
| xonsh encoding   | utf-8                                             |
| encoding errors  | surrogateescape                                   |
+------------------+---------------------------------------------------+
```

**Comment by scopatz** [comment]
I think the problem here is the that `print_exception()` does not know about any redirections that the user has specified.

**Comment by scopatz** [comment]
Thanks for reporting @laerus!

**Comment by scopatz** [comment]
The fix is probably to allow `print_exception()` to accept a `file=` kwarg, like print(). PRs welcome!

**Comment by astronouth7303** [comment]
I think the fix is to tweak the `cd` command to return an stdout/err instead of directly printing the exception.

**Comment by scopatz** [comment]
That would work too!

**Comment by mitnk** [comment]
Is it a `cd` specific thing? it seems a generic issue?
```
$ ls nonono out> /dev/null
ls: nonono: No such file or directory
```

**Comment by laerus** [comment]
it seems `cd` specific

**Comment by astronouth7303** [comment]
Nope, nevermind. This is not a bug.

```
$ cd wrongname out> /dev/null
```

Will never redirect anything because `cd` never produces output on standard output.

What the OP was aiming for was likely:

```
$ cd wrongname err> /dev/null
```

Which _does_ seem to work.

`cd` printing errors to standard error is the correct behavior, I believe.

**Comment by astronouth7303** [comment]
Ignore previous conversation. Redirecting standard output of `cd` will do nothing, by design. A quick grok of the source code shows that `cd` is doing the right thing.

For the record, I can't reproduce this on windows with:

```
$ cd wrongname err> NUL
```

**Comment by scopatz** [comment]
Actually, I can't reproduce this on Linux either...
