### ISSUE TITLE
SIGINT-ing a ping command truncates output or crashes

### ISSUE THREAD

**Issue by tgoodlet** [xonsh/xonsh#2203]
I hope this isn't just me but I've been noticing that when I `ping` and then ctrl-C it seems to sometimes not give me the final summary output:
```python
 >>> ping google.com                                                                  
PING google.com (172.217.0.46) 56(84) bytes of data.
64 bytes from lga15s43-in-f14.1e100.net (172.217.0.46): icmp_seq=1 ttl=55 time=34.1 ms
64 bytes from lga15s43-in-f14.1e100.net (172.217.0.46): icmp_seq=2 ttl=55 time=45.1 ms
64 bytes from lga15s43-in-f14.1e100.net (172.217.0.46): icmp_seq=3 ttl=55 time=41.4 ms
^C
```

Versus when I do it with `zsh` (presumably under the same network conditions):
```bash
 >>> ping google.com
PING google.com (172.217.0.46) 56(84) bytes of data.
64 bytes from lga15s43-in-f14.1e100.net (172.217.0.46): icmp_seq=1 ttl=55 time=54.8 ms
64 bytes from lga15s43-in-f14.1e100.net (172.217.0.46): icmp_seq=2 ttl=55 time=33.6 ms
64 bytes from lga15s43-in-f14.1e100.net (172.217.0.46): icmp_seq=3 ttl=55 time=34.3 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 33.686/40.960/54.833/9.813 ms
```

Worse still is if I have a bad network connection sometimes `xonsh` seems to hang for a few seconds and then I'll get something cryptic:
```python
 >>> ping google.com                                                                                        
PING google.com (172.217.0.46) 56(84) bytes of data.
64 bytes from lga15s43-in-f14.1e100.net (172.217.0.46): icmp_seq=1 ttl=55 time=54.1 ms
64 bytes from lga15s43-in-f14.1e100.net (172.217.0.46): icmp_seq=2 ttl=55 time=254 ms
^C



xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18251, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2085, in run_compiled_code
    func(code, glb, loc)
  File "/usr/lib/python3.6/site-packages/xontrib/vox_tabcomplete.xsh", line 1, in <module>
    import os
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 17012, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16980, in run_subproc
    command.end()
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 11563, in end
    for _ in self.tee_stdout():
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 11488, in tee_stdout
    for line in self.iterraw():
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 11450, in iterraw
    time.sleep(timeout * cnt)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10407, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10407, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10407, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  [Previous line repeated 20 more times]
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10405, in _signal_int
    self._restore_sigint(frame=frame)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10418, in _restore_sigint
    old(signal.SIGINT, frame)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10407, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10407, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10407, in _signal_int
    signal.pthread_kill(threading.get_ident(), signal.SIGINT)
  [Previous line repeated 299 more times]
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10406, in _signal_int
    if on_main_thread():
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 6093, in on_main_thread
    return threading.current_thread() is threading.main_thread()
  File "/usr/lib/python3.6/threading.py", line 1234, in current_thread
    return _active[get_ident()]
RecursionError: maximum recursion depth exceeded in comparison
```

Is there something nasty going on with `SIGINT` handling?

**Comment by scopatz** [comment]
Hi @tgoodlet thanks for reporting. I am not seeing this behaviour, personally. Can you please post the ouput of `xonfig`?

**Comment by tgoodlet** [comment]
@scopatz I'm always running lastest master from git but here goes:

```
 >>> xonfig                                
+------------------+----------------------+
| xonsh            | 0.5.4.dev174         |
| Git SHA          | e84cb086             |
| Commit Date      | Feb 13 13:04:36 2017 |
| Python           | 3.6.0                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.13               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by gforsyth** [comment]
Hey @tgoodlet -- we're on `0.5.5.dev4` right now on master -- could you update and see if the issue persists?  Thanks!

**Comment by scopatz** [comment]
@gforsyth are you seeing this on arch?

**Comment by gforsyth** [comment]
No, `ping` is behaving itself on my end

**Comment by laerus** [comment]
maybe related to  #2176

**Comment by tgoodlet** [comment]
@gforsyth yeah weird on `xonsh/0.5.5.dev274` seems to be working now?
Good wifi right now so if you guys don't mind I'll keep this open in case it shows up again.

@laerus yeah looks about the same.

**Comment by tgoodlet** [comment]
Seems like it's working now even with a janky connection.
Thanks for the help yet again!

**Comment by scopatz** [comment]
glad to hear it works!
