### ISSUE TITLE
timeit - OSError Inappropriate ioctl for device

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2210]
A new introduced issue.

```
$ timeit ls
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 12437, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 12266, in proxy_two
    return f(args, stdin)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 13794, in timeit_alias
    time_number = timer.timeit(number)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 13747, in timeit
    timing = self.inner(it, self.timer)
  File "<xonsh-timeit>", line 6, in inner
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 18340, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 18281, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 12859, in __init__
    if update_fg_process_group(pipeline_group, background):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 12795, in update_fg_process_group
    return give_terminal_to(pipeline_group)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 8901, in give_terminal_to
    os.tcsetpgrp(sys.stderr.fileno(), pgid)
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by scopatz** [comment]
The fix is probably to replace `sys.stderr.fileno()` with `2`

**Comment by scopatz** [comment]
Thanks for reporting @mitnk

**Comment by mitnk** [comment]
Yes, `2` do the trick here. So what's the reason? some kind of OS competition? Added PR #2217

**Comment by scopatz** [comment]
It probably has to do with the redirections and piping. But `2` is always going to be stderr
