### ISSUE TITLE
cd complains if directory name has trailing backspace.

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2213]
The trailing backspace on directory names on windows cause `cd` to complain. This one is fairly new, but I haven't dug into what PR caused it. (The trailing backspace are automatically added by the tab-completer by design).

```
snail@sea ~\Documents\xonsh master
$ cd build\
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\execer.py", line 164, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "C:\Users\mel\Documents\xonsh\xonsh\parsers\base.py", line 335, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "C:\Users\mel\Anaconda3\lib\site-packages\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Users\mel\Anaconda3\lib\site-packages\ply\yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Users\mel\Anaconda3\lib\site-packages\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "C:\Users\mel\Documents\xonsh\xonsh\parsers\base.py", line 2694, in p_error
    column=p.lexpos))
  File "C:\Users\mel\Documents\xonsh\xonsh\parsers\base.py", line 466, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:3: ('code: build',)
cd build\
   ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\ptk\shell.py", line 134, in _push
    locs=None)
  File "C:\Users\mel\Documents\xonsh\xonsh\execer.py", line 109, in compile
    transform=transform)
  File "C:\Users\mel\Documents\xonsh\xonsh\execer.py", line 79, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "C:\Users\mel\Documents\xonsh\xonsh\execer.py", line 182, in _parse_ctx_free
    line, nlogical = get_logical_line(lines, idx)
  File "C:\Users\mel\Documents\xonsh\xonsh\tools.py", line 361, in get_logical_line
    line = line[:-1] + lines[idx]
IndexError: list index out of range
```

**Comment by scopatz** [comment]
Thanks for reporting this @melund! I feel that this is related to #983

**Comment by melund** [comment]
I am not sure that it is directly related. This has worked nicely for a long time. #983 was mostly about quoted directory path having to end with double backslash.

This issue is when names are not quoted. 

Git bisect tells me the following: 
```
0cb619468a20a2433191111ff7f544c85fb1b04f is the first bad commit
commit 0cb619468a20a2433191111ff7f544c85fb1b04f
Author: Anthony Scopatz <scopatz@gmail.com>
Date:   Wed Feb 15 00:58:38 2017 -0500

    line continuation fixes
```

Probably not surprising. Maybe we can make a special case for `cd`  and Windows.

**Comment by scopatz** [comment]
Yeah, you are right that is a red herring. Sorry.  Maybe we should just makes it so that on windows the `\` needs to be preceded by a space. Other commands, like ls, dir, etc, will also have this problem. So this is less of a `cd` issue and more of a Windows issue.

**Comment by melund** [comment]
Do mean that the line continuation character `\` should be preceded by a space? That could probably be fine as a general solution.

**Comment by melund** [comment]
Of course, it would be annoying that xonsh code can be platform dependent.

**Comment by scopatz** [comment]
yeah that is what I mean.

**Comment by scopatz** [comment]
well the path stuff in Python is already platform independent. We could also restrict the extra space to interactive mode.  That would force scripts to be platform independent

**Comment by scopatz** [comment]
*Python paths = platform dependent

**Comment by melund** [comment]
I think that makes good sense :) I was afraid this was going to be a hard dilemma.
