### ISSUE TITLE
Potential OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2220]
In current `proc.py:CommandPipeline` implementation, we built and run procs first, then give controlling terminal to them. There are cases that all the processes have finished, then the "give terminal to them" will raise errors.

```
$ ls
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/base_shell.py", line 322, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/built_ins.py", line 858, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/built_ins.py", line 799, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1756, in __init__
    if update_fg_process_group(pipeline_group, background):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1691, in update_fg_process_group
    return give_terminal_to(pipeline_group)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/jobs.py", line 138, in give_terminal_to
    os.tcsetpgrp(FD_STDERR, pgid)
OSError: [Errno 22] Invalid argument
```

**Comment by scopatz** [comment]
I think this just needs a try-except. Thanks for reporting @mitnk

**Comment by mitnk** [comment]
@scopatz yes, PR is coming.
