### ISSUE TITLE
"history play" does not work when not installed "pygments"

### ISSUE THREAD

**Issue by harukaeru** [xonsh/xonsh#2264]
I found it if the library does not installed, `history replay` does not work by diving in source code.
![screenshot 2017-02-26 16 29 06](https://cloud.githubusercontent.com/assets/5797788/23337943/df086af6-fc40-11e6-99b0-a4e769e95278.png)

Since there is no explanation about `pygments` or `style` in the document(http://xon.sh/tutorial_hist.html), I want you to add the sentences about that.

**Comment by gforsyth** [comment]
Thanks for reporting @harukaeru!

I can reproduce this error, here's a full traceback:

```console
history replay -o ~/new.json /home/gil/.local/share/xonsh
............... /xonsh-8e015a67-ae61-48c8-b551-f59e7180df5f.json
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/proc.py", line 1333, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/proc.py", line 1175, in proxy_four
    return f(args, stdin, stdout, stderr)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/history/main.py", line 338, in history_main
    xrp.replay_main_action(hist, ns, stdout=stdout, stderr=stderr)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/replay.py", line 111, in replay_main_action
    hist = replayer.replay(merge_envs=ns.merge_envs, target=ns.target)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/replay.py", line 52, in replay
    new_env = self._merge_envs(merge_envs, re_env)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/replay.py", line 76, in _merge_envs
    new_env = Env(**new_env)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/environ.py", line 789, in __init__
    self[key] = val
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/environ.py", line 945, in __setitem__
    val = ensurer.convert(val)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/tools.py", line 1562, in intensify_colors_on_win_setter
    delattr(builtins.__xonsh_shell__.shell.styler, 'style_name')
AttributeError: 'NoneType' object has no attribute 'style_name'
```

It's curious that I'm hitting a windows-specific ensurer.
