### ISSUE TITLE
could not launch xonsh on suse leap..

### ISSUE THREAD

**Issue by jgmtzmd** [xonsh/xonsh#2282]
hi.
i use xonsh as my default shell. after updating could not launch it and this error comes up:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 18345, in main
    args = premain(argv)
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 18297, in premain
    builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 17479, in __init__
    kwargs.get('cacheall', False))
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 17533, in _init_environ
    debug_level=debug)
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 17080, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16916, in load_builtins
    builtins.__xonsh_env__ = Env(default_env(config=config, login=login))
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 14970, in default_env
    issue_warning=False)
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 9139, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/usr/lib64/python3.4/functools.py", line 452, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 8834, in foreign_shell_data
    shkey = CANON_SHELL_NAMES[shell]
  File "/usr/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 331, in __getitem__
    return obj[item]
KeyError: 'Bash'
Xonsh encountered an issue during launch
Failback to /bin/bash
```

i already fixed it. i had to go to /usr/lib/python3.4/site-packages/xonsh/__amalgam__.py
and change line 8675.. change key 'bash' to 'Bash'

this had happenned in a previous update. and now after updating to version 0.5.3-5.5 happened again.

**Comment by melund** [comment]
Can you list the content of your static [configuration file](http://xon.sh/xonshconfig.html)?
`~/.config/xonsh/config.json`

I suspect that you wrote the shell name with a capital B in that file. 

@scopatz. Maybe we should consider converting the shell name to lowercase here: 
https://github.com/xonsh/xonsh/blob/master/xonsh/foreign_shells.py#L493

**Comment by scopatz** [comment]
Yeah I think we should @melund. In fact, I thought we were already doing that!

**Comment by melund** [comment]
@jgmtzmd  Can you try #2285 and see if this fixes the issue you see?

**Comment by jgmtzmd** [comment]
$cat ~/.config/xonsh/config.json
{
 "foreign_shells": [
  {
   "shell": "Bash"
  }
 ]
}

tried #2285.
working ok now. thanks.
