### ISSUE TITLE
Various pudb malfunctions

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#2293]
These issues are sort of related so I'm submitting as a single issue.

## Setup
```python
import pudb
def myFunc():
    pudb.set_trace()
aliases['myAlias'] = my
```
## First issue

If I run `pudb.set_trace()` or `myFunc()`, not aliased it runs fine the first time. All subsequent runs I get this traceback:
```
Traceback (most recent call last):
  File "/lunz/usr/xonsh/xonsh/base_shell.py", line 328, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/lunz/usr/xonsh/xonsh/codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/lunz/usr/xonsh/xonsh/main.py", line 194, in _pprint_displayhook
    def _pprint_displayhook(value):
  File "/lunz/anaconda/envs/py35/lib/python3.5/bdb.py", line 50, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "/lunz/anaconda/envs/py35/lib/python3.5/bdb.py", line 82, in dispatch_call
    self.user_call(frame, arg)
  File "/lunz/anaconda/envs/py35/lib/python3.5/site-packages/pudb/debugger.py", line 350, in user_call
    self.interaction(frame)
  File "/lunz/anaconda/envs/py35/lib/python3.5/site-packages/pudb/debugger.py", line 339, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/lunz/anaconda/envs/py35/lib/python3.5/site-packages/pudb/debugger.py", line 2077, in call_with_ui
    self.show()
  File "/lunz/anaconda/envs/py35/lib/python3.5/site-packages/pudb/debugger.py", line 2068, in show
    self.screen.start()
  File "/lunz/anaconda/envs/py35/lib/python3.5/site-packages/urwid/display_common.py", line 741, in start
    self._start(*args, **kwargs)
  File "/lunz/anaconda/envs/py35/lib/python3.5/site-packages/urwid/raw_display.py", line 203, in _start
    self.write(escape.SWITCH_TO_ALTERNATE_BUFFER)
  File "/lunz/anaconda/envs/py35/lib/python3.5/site-packages/urwid/raw_display.py", line 268, in write
    self._term_output_file.write(data)
  File "/lunz/usr/xonsh/xonsh/base_shell.py", line 163, in write
    self.mem.write(s)
ValueError: I/O operation on closed file.
```

Interestingly if I run `myAlias` first then I can run `pudb.set_trace()` or `myFunc()` indefinitely without error.

## Second issue

If I run my function with just `myFunc()` `pudb` will display correctly, but if i run `myAlias` the `pudb` window width is squashed down to about 15 characters on the left side of the screen.

Also interesting. If I run `myAlias` repeatedly sometimes there will be nothing on screen, just a straight blank console but I know pudb is still running because if I press `q` I will exit back to console.

## `xonfig`
```
+------------------+---------------------------------------------------+
| xonsh            | 0.5.7                                             |
| Git SHA          | 6cf6a39                                           |
| Commit Date      | Mar 4 14:14:10 2017                               |
| Python           | 3.5.2                                             |
| PLY              | 3.7                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.8                                             |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.2.0                                             |
| on posix         | True                                              |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7fe89bc9cda0> |
| distro           | CentOS                                            |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
| xonsh encoding   | utf-8                                             |
| encoding errors  | surrogateescape                                   |
+------------------+---------------------------------------------------+
```

**Comment by gforsyth** [comment]
Hi @JohnLunzer -- can I ask you to put the two issues in as separate issues? I have a feeling that the display stuff isn't strictly related to the first problem (although who knows?)

**Comment by JohnLunzer** [comment]
I'll split this as soon as I get a chance.

**Comment by scopatz** [comment]
Thanks for reporting @JohnLunzer. Have you tried decorating this alias as uncapturable. IIRC pudb uses curses.

**Comment by gforsyth** [comment]
I think it's `urwid`, actually, but that probably would also benefit from the uncapturable decorator

**Comment by gforsyth** [comment]
Is there a "womp womp" emoji?

**Comment by scopatz** [comment]
Haha

**Comment by JohnLunzer** [comment]
`@uncapturable` fixes the second issue (squashed display) but not the first. Makes sense to me since pudb is a terminal UI application.

Should I still close this issue and open a new one for just the first issue? Alternatively I could just rename this issue to better reflect the first problem and edit the OP making a note that a solution to the second problem was found.

**Comment by anki-code** [comment]
I can reproduce on xonsh 0.9.26.
