### ISSUE TITLE
termios, error"(5, 'input/output error') 

### ISSUE THREAD

**Issue by stokhos** [xonsh/xonsh#2309]
I'm using xonsh on arch. When I try to start gdm.service with sudo systemctl start gdm.service
This error will show up. Sometime when I type sudo reboot now. It will show up too. 
I believe this is the log. Though I dont know how did I get this.

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/base_shell.py", line 328, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.6/site-packages/xonsh/codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'LOG' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 137, in _push
    locs=None)
  File "/usr/lib/python3.6/site-packages/xonsh/execer.py", line 110, in compile
    transform=transform)
  File "/usr/lib/python3.6/site-packages/xonsh/execer.py", line 79, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/lib/python3.6/site-packages/xonsh/execer.py", line 179, in _parse_ctx_free
    raise original_error from None
  File "/usr/lib/python3.6/site-packages/xonsh/execer.py", line 166, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/usr/lib/python3.6/site-packages/xonsh/parsers/base.py", line 348, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.6/site-packages/xonsh/ply/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.6/site-packages/xonsh/parsers/base.py", line 2726, in p_error
    column=p.lexpos))
  File "/usr/lib/python3.6/site-packages/xonsh/parsers/base.py", line 479, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:27: ('code: <',)
$XONSH_TRACEBACK_LOGFILE = <LOG.txt>

**Comment by astronouth7303** [comment]
What is the output of `xonfig` and what is your `.xonshrc`?

**Comment by stokhos** [comment]
------------------+---------------------------------------------------+
| xonsh            | 0.5.8                                             |
| Git SHA          | e7a9bcf                                           |
| Commit Date      | Mar 6 23:45:51 2017                               |
| Python           | 3.6.0                                             |
| PLY              | 3.9                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.13                                            |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.2.0                                             |
| on posix         | True                                              |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7fa06866b7b8> |
| distro           | arch                                              |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
| xonsh encoding   | utf-8                                             |
| encoding errors  | surrogateescape                                   |
+------------------+---------------------------------------------------+

I have not created a .xonshrc file yet. The only model loaded is powerline. But it is not working somehow.

My config.json:
{
 "xontribs": [
  "powerline"
 ]
}

**Comment by laerus** [comment]
hey @stokhos! how did you install xonsh?

**Comment by stokhos** [comment]
I installed from pip.

**Comment by fmv1992** [comment]
I'm having the same problem when issuing:
`mv luksencrypted_usb.img backup/archusb/`
It throws an infinite loop on the screen of:
```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 411, in run
    with self.input.raw_mode():
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 470, in __enter__
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)
termios.error: (4, 'Interrupted system call')
```

**Comment by gforsyth** [comment]
I'm closing this as it was an upstream error with prompt toolkit and I'm pretty sure it has been fixed there.
