### ISSUE TITLE
`cmd /c echo %PATH%` fails on Windows

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2322]
$ cmd /c echo %PATH%
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 15470, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 3634, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 5282, in expand_path
    s = expandvars(s)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 6936, in expandvars
    path = WINDOWS_ENVVAR_REGEX.sub(value, path, count=1)
  File "C:\Users\mel\Anaconda3\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\mel\Anaconda3\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\mel\Anaconda3\lib\sre_parse.py", line 944, in parse_template
    addgroup(int(this[1:]), len(this) - 1)
  File "C:\Users\mel\Anaconda3\lib\sre_parse.py", line 888, in addgroup
    raise s.error("invalid group reference %d" % index, pos)
sre_constants.error: invalid group reference 8 at position 842

**Comment by melund** [comment]
It seems like environment substitution with `%var%` is broken. 

Should we consider dropping the support for substituting `%PATH%` variables like this in xonsh. I didn't even know we attempted to support this.

**Comment by laerus** [comment]
hey @melund, i've added a new test about this [here](https://github.com/xonsh/xonsh/blob/expandvars/tests/test_tools.py#L1195) in the expandvars branch that seems to pass on appveyor.

**Comment by laerus** [comment]
can you try while in xonsh
```
from xonsh.tools import expandvars

expandvars('cmd /c echo %PATH%')
```
and see what it returns?

**Comment by laerus** [comment]
i can't get my hands on a windows machine atm :(

**Comment by melund** [comment]
```
$ expandvars('cmd /c echo %PATH%')
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 15470, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 3634, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 6936, in expandvars
    path = WINDOWS_ENVVAR_REGEX.sub(value, path, count=1)
  File "C:\Users\mel\Anaconda3\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\mel\Anaconda3\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\mel\Anaconda3\lib\sre_parse.py", line 944, in parse_template
    addgroup(int(this[1:]), len(this) - 1)
  File "C:\Users\mel\Anaconda3\lib\sre_parse.py", line 888, in addgroup
    raise s.error("invalid group reference %d" % index, pos)
sre_constants.error: invalid group reference 8 at position 842
```

**Comment by melund** [comment]
The question is if we want this at all. We already have one way of replacing environment variables (with the $foo). This functionality just means that we have use macro escapes when running commands like. 

```
$(cmd /c ! %PATH%)
```

Could confuse a lot of people. 

I think stuff like this could go into a xontrib. Like we have 'bashisms' we could also have 'cmdisms'. I think @astronouth7303  suggested that at some point.

**Comment by astronouth7303** [comment]
I did suggest cmdisms at one point to support some cmd-ish functionality. My gut on percent-style envvars is don't do it, or begrudgingly make it a xontrib.

Same way as we only really give a passing nod to bourne shells, I don't think we need to try to emulate cmd or powershell too much.

**Comment by laerus** [comment]
+1

**Comment by melund** [comment]
I have added a PR to remove it.
