### ISSUE TITLE
Endless loop of an input/output error

### ISSUE THREAD

**Issue by refi64** [xonsh/xonsh#2327]
Still trying to accurately reproduce this, but here's the gist of it:

![xonsh_gem](https://cloud.githubusercontent.com/assets/1690697/23972507/14e78db6-09a0-11e7-8c35-dc89c3a3199a.jpg)

Was trying to install a `gem` package. So innocent, yet so much pain in return...

:O

**Comment by gforsyth** [comment]
I've seen this on my machine before -- happened at shutdown and I had to power cycle the machine. Haven't been able to reproduce it, though, and haven't seen it in a while.

Thanks for reporting, @kirbyfan64 !

**Comment by tekacs** [comment]
This happens to me frequently - on OSX and Linux of a variety of descriptions, all under `prompt_toolkit`.

**Comment by astronouth7303** [comment]
Do we need a master tracker bug? We've got a pile of issues of similar symptoms.

**Comment by scopatz** [comment]
Hello All, do we have a full traceback for this?  I have never seen it :(

**Comment by tekacs** [comment]
@scopatz I'll run with `$XONSH_SHOW_TRACEBACK = True` for a few days and see if I can get you one.

**Comment by scopatz** [comment]
Thanks!

**Comment by tekacs** [comment]
@scopatz Here we go!

```
amar@<snip> ~/repos/<snip> master $ kubectl logs -f <some-kubernetes-pod> -p
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                       
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14797, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2322, in run_compiled_code
    func(code, glb, loc)                          
  File "<xonsh-code>", line 1, in <module>                                             
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19353, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')                                                   
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19316, in run_subproc
    command.end()                       
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12622, in end                                                                                                                                                                                                                                                                       
    self._end(tee_output=tee_output)                                             
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12630, in _end
    for _ in self.tee_stdout():                                                      
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12546, in tee_stdout
    for line in self.iterraw():                                                        
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12511, in iterraw
    self.stream_stderr(safe_readlines(stderr))                                                          
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12580, in stream_stderr
    sys.stderr.buffer.write(b)          
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14563, in write                                                                                                                                                                                                                                                                     
    errors=self.errors))                                                         
TypeError: decode() argument 1 must be str, not None
amar@<snip> ~/repos/<snip> master $                                                                                                                                                                                                                                                                                       
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):                                                     
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)                                                      
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 411, in run
    with self.input.raw_mode():         
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 470, in __enter__                                                                                                                                                                                                                                                 
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)                     
termios.error: (5, 'Input/output error')
amar@<snip> ~/repos/<snip> master $                                                                                                                                                                                                                                                                                       
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):                                                     
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)                                                      
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 411, in run
    with self.input.raw_mode():         
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 470, in __enter__                                                                                                                                                                                                                                                 
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)                     
termios.error: (5, 'Input/output error')
amar@<snip> ~/repos/<snip> master $                                                                                                                                                                                                                                                                                       
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):                                                     
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)                                                      
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 411, in run
    with self.input.raw_mode():         
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 470, in __enter__                                                                                                                                                                                                                                                 
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)                     
termios.error: (5, 'Input/output error')
```

xonfig:

```
+------------------+----------------------+
| xonsh            | 0.5.12.dev85         |
| Git SHA          | 5cb3e8dd             |
| Commit Date      | Jul 25 23:44:20 2017 |
| Python           | 3.6.3                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

Interestingly, when I switched to a /separate/, but /already open/ xonsh shell in another tmux window to get the above `xonfig`, I found that it threw a similar error to the above (no Input/Output Error spam, though):

```
amar@<snip> ~/repos/<snip> master $ xonfig
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14797, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2322, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19353, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19316, in run_subproc
    command.end()
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12622, in end
    self._end(tee_output=tee_output)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12630, in _end
    for _ in self.tee_stdout():
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12550, in tee_stdout
    sys.stdout.buffer.write(line)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14563, in write
    errors=self.errors))
TypeError: decode() argument 1 must be str, not None
```

This was not affected by me navigating around (so it wasn't the directory) in that shell and this was completely repeatable.

**Comment by astronouth7303** [comment]
#2366, maybe #2309?

**Comment by scopatz** [comment]
Potential fix in #2557.  Sorry this took so long.

**Comment by scopatz** [comment]
Please feel free to reopen if needed!

**Comment by ediphy-dwild** [comment]
i am aware that this issue is now closed, however it may help to add some color in how i am able to switch this issue on and off as it seems the underlying cause is still somewhat of a mystery. for my use case (running a gem command), with $XONSH_SHOW_TRACEBACK=True, i get the same issue as kirbyfan64. when i set $XONSH_SHOW_TRACEBACK=False, the issue no longer occurs. this is running with :
```
+------------------+----------------------+
| xonsh            | 0.5.9                |
| Git SHA          | 2ae5218              |
| Commit Date      | Mar 15 12:06:26 2017 |
| Python           | 3.6.3                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.14               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by scopatz** [comment]
Hi @ediphy-dwild - thanks for letting us know. I am going to reopen this for now.  Can you please post the full traceback that you are seeing? Does this only happen with gem commands?

**Comment by anki-code** [comment]
No new reports. Closed.
