### ISSUE TITLE
@$ crashes when no output was sent out

### ISSUE THREAD

**Issue by refi64** [xonsh/xonsh#2329]
```
ryan@DevPC-LX ~/stuff/cpython distutils-readme $ @$(echo)
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
IndexError: list index out of range
ryan@DevPC-LX ~/stuff/cpython distutils-readme $ 
```

**Comment by astronouth7303** [comment]
can you set `$XONSH_SHOW_TRACEBACK` and `$XONSH_DEBUG` and post the results?

As well, can you post the output of `xonfig`?

**Comment by kirbyfan64** [comment]
```
ryan@DevPC-LX ~ $ @$(echo)
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/ryan/stuff/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15470, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/ryan/stuff/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 3634, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/ryan/stuff/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19195, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/ryan/stuff/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19128, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured)
  File "/home/ryan/stuff/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19085, in cmds_to_specs
    if cmd[-1] == '&':
IndexError: list index out of range
ryan@DevPC-LX ~ $ xonfig
+------------------+----------------------+
| xonsh            | 0.5.8.dev11          |
| Git SHA          | 8d78f359             |
| Commit Date      | Mar 12 06:04:50 2017 |
| Python           | 3.6.0                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.9                |
| shell type       | prompt_toolkit       |
| pygments         | 2.1.3                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | debian               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
ryan@DevPC-LX ~ $ 
```

**Comment by laerus** [comment]
@gforsyth there may have been a regression with #2360

**Comment by gforsyth** [comment]
@laerus entirely possible -- what are you seeing?
