### ISSUE TITLE
xoreutils: echo fails with KeyError: 'help'

### ISSUE THREAD

**Issue by moigagoo** [xonsh/xonsh#2331]
Any `echo` invocation fails:

```shell
$ $XONSH_SHOW_TRACEBACK = True
$ echo
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13061, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12896, in proxy_four
    return f(args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xoreutils/echo.py", line 9, in echo
    if opts['help']:
KeyError: 'help'
$ echo foo
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13061, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12896, in proxy_four
    return f(args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xoreutils/echo.py", line 9, in echo
    if opts['help']:
KeyError: 'help'
$ echo "foo"
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13061, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12896, in proxy_four
    return f(args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.6/site-packages/xonsh/xoreutils/echo.py", line 9, in echo
    if opts['help']:
KeyError: 'help'
```

Obviously, the problem is that `help` is looked up but missing: http://xon.sh/_modules/xonsh/xoreutils/echo.html#echo

**Comment by moigagoo** [comment]
This is a serious issue since echo is one of the essential commands.

**Comment by astronouth7303** [comment]
The work around is `del aliases['echo']` which will cause xonsh  to revert to your system's echo instead of its own built-in implementation.

**Comment by moigagoo** [comment]
@astronouth7303 Thanks for the tip!

Should I PR the following simple fix, or is the issue more complex than it seems:

```diff
- if opts['help']:
+ if opts.get('help'):
```

**Comment by gforsyth** [comment]
Hey @moigagoo -- that seems like a good fix to me.

**Comment by astronouth7303** [comment]
Either that or set a default 'help' in `_echo_parse_args()`.

**Comment by moigagoo** [comment]
I've decided to set the default value for 'help'. This way it looks more consistent with the existing code. https://github.com/xonsh/xonsh/pull/2332
