### ISSUE TITLE
source an xsh script inside xsh scripts

### ISSUE THREAD

**Issue by mitnk** [xonsh/xonsh#2345]
It seems xonsh is closing some FD too early, may related to running code in threads.

The readline version:

```
$ cat hi.xsh
print("hi")
source foo.xsh
$ cat foo.xsh
print("foo")
$ source hi.xsh
$ source hi.xsh
.... # do this 100 times, you will get:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1349, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1171, in proxy_two
    return f(args, stdin)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/aliases.py", line 293, in source_alias
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/aliases.py", line 289, in source_alias
    with open(fpath, 'r', encoding=encoding, errors=errors) as fp:
OSError: [Errno 9] Bad file descriptor
```

the PTK version:

```
$ source hi.xsh
$ source hi.xsh
.... # do this 100 times, you will get:
^[[23;1RTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 93, in run
    self.add_reader(self._schedule_pipe[0], None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 280, in add_reader
    self.selector.register(fd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/prompt_toolkit/eventloop/select.py", line 75, in register
    sel.register(fd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/prompt_toolkit/eventloop/select.py", line 130, in register
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 541, in register
    self._kqueue.control([kev], 0, 0)
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/main.py", line 337, in main
    return main_xonsh(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/main.py", line 364, in main_xonsh
    shell.shell.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 153, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 119, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/ptk/shortcuts.py", line 118, in prompt
    eventloop.close()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 270, in close
    os.close(schedule_pipe[0])
OSError: [Errno 9] Bad file descriptor
Xonsh encountered an issue during launch
Failback to /bin/bash
```

We can prevent the crash by adding a `try-catch` on `OSError` in shells' `cmdloop()` method. But better to know the root causes.

**Comment by fmv1992** [comment]
Indeed.

I'm getting those very often.

And I think one of the strenghts of xonsh is that it allows one to build a robust/cross platform library of functions and run them everywhere. Thus having your code split up on a bunch of .xsh files seem natural.

If a file sources another file which also sources another file the xonsh main program generally stops (at least in versions around 0.4).

**Comment by scopatz** [comment]
Thanks for reporting @mitnk and @fmv1992!

**Comment by scopatz** [comment]
I can reproduce this.

**Comment by anki-code** [comment]
Can't reproduce this on 0.9.22 version with ptk or readline. Looks solved.

**Comment by scopatz** [comment]
Yeah, likely. Please let us know if we need to reopen
