### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by ofek** [xonsh/xonsh#2349]
On Windows:

```cmd
Ofek@Ofek-PC ~ $ python -c "g=b'\xff'"                       
  File "<string>", line 1                                    
SyntaxError: bytes can only contain ASCII literal characters.
Ofek@Ofek-PC ~ $                                             
```

```cmd
Ofek@Ofek-PC ~ $ python -c "g=b'\x00'"                                                                                          
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>                                               
Traceback (most recent call last):                                                                                              
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 14826, in default                      
    run_compiled_code(code, self.ctx, None, 'single')                                                                           
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 2085, in run_compiled_code             
    func(code, glb, loc)                                                                                                        
  File "<xonsh-code>", line 1, in <module>                                                                                      
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 18503, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')                                                                           
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 18439, in run_subproc                  
    command = HiddenCommandPipeline(specs)                                                                                      
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 12941, in __init__                     
    proc = spec.run(pipeline_group=pipeline_group)                                                                              
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 18141, in run                          
    p = self._run_binary(kwargs)                                                                                                
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 18151, in _run_binary                  
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)                                                                           
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 11749, in __init__                     
    **kwargs)                                                                                                                   
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\subprocess.py", line 707, in __init__                                            
    restore_signals, start_new_session)                                                                                         
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\subprocess.py", line 990, in _execute_child                                      
    startupinfo)                                                                                                                
ValueError: embedded null character                                                                                             
Ofek@Ofek-PC ~ $                                                                                                                
```

**Comment by gforsyth** [comment]
Hey @ofek -- thanks for reporting this. 
I'm guessing that the first run is in a non-xonsh shell?

**Comment by gforsyth** [comment]
Or both are? A few more details would be great, as would the expected behavior.  And could you also please post the output of `xonfig`?  Thanks.

**Comment by ofek** [comment]
@gforsyth Here you go:

```
Ofek@Ofek-PC ~\Desktop $ $XONSH_SHOW_TRACEBACK = True        
Ofek@Ofek-PC ~\Desktop $ python -c "g=b'\xff'"               
  File "<string>", line 1                                    
SyntaxError: bytes can only contain ASCII literal characters.
Ofek@Ofek-PC ~\Desktop $ xonfig                              
+------------------+----------------------+                  
| xonsh            | 0.5.6                |                  
| Git SHA          | fba07c5              |                  
| Commit Date      | Feb 21 15:50:42 2017 |                  
| Python           | 3.6.0                |                  
| PLY              | 3.9                  |                  
| have readline    | False                |                  
| prompt toolkit   | 1.0.13               |                  
| shell type       | prompt_toolkit       |                  
| pygments         | 2.2.0                |                  
| on posix         | False                |                  
| on linux         | False                |                  
| on darwin        | False                |                  
| on windows       | True                 |                  
| on cygwin        | False                |                  
| is superuser     | False                |                  
| default encoding | utf-8                |                  
| xonsh encoding   | utf-8                |                  
| encoding errors  | surrogateescape      |                  
+------------------+----------------------+                  
Ofek@Ofek-PC ~\Desktop $                                     
```

**Comment by astronouth7303** [comment]
I think you need `"\\x00"` or `"\\xFF"`, because xonsh's string interpolation does backslashes.

**Comment by ofek** [comment]
@astronouth7303 Wow yup thanks! Any way to disable that?

**Comment by astronouth7303** [comment]
raw strings (`r""`) work in subprocess.

**Comment by ofek** [comment]
@astronouth7303 `python -c "g=r'\x00'"` still fails

**Comment by gforsyth** [comment]
@ofek how about `python -c r"g=b'\x00'"`?

**Comment by ofek** [comment]
Well done! Please add this to docs :)
