### ISSUE TITLE
PTK termios.error

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#2366]
command:

``` $ sudo systemctl status apache2```

error:

```
Traceback (most recent call last):
  File "/home/kon/.local/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/home/kon/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 411, in run
    with self.input.raw_mode():
  File "/home/kon/.local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 470, in __enter__
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)
termios.error: (4, 'Interrupted system call')

... (repeats forever)
```

this seems like an upstream bug, but when this happened it looked like
xonsh put the command on the background.

**Comment by astronouth7303** [comment]
I can regularly trigger this in 0.5.8 with a failed command right now.

**Comment by fmv1992** [comment]
I'm also having this issue regardless of the shell type:
```
amnesia@amnesia ~ 🐚 xonfig
+------------------+-----------------+
| xonsh            | 0.5.12          |
| Python           | 3.5.3           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.9           |
| shell type       | readline        |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | debian          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
amnesia@amnesia ~ 🐚 git status
fatal: Not a git repository (or any of the parent directories): .git
subprocess.CalledProcessError: Command '['/bin/sh', '/usr/local/bin/git', 'status']' returned non-zero exit status 128
amnesia@amnesia ~ 🐚 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 20486, in main
    return main_xonsh(args)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 20513, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 17569, in cmdloop
    self._cmdloop(intro=intro)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 17551, in _cmdloop
    self._load_remaining_input_into_queue()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 17454, in _load_remaining_input_into_queue
    buf += os.read(self.stdin.fileno(), 1024)
OSError: [Errno 5] Input/output error
Xonsh encountered an issue during launch
Failback to /bin/sh
```
Then it goes into that endless loop.

**Comment by astronouth7303** [comment]
I'm still getting this on my home laptop with v0.5.12.

**Comment by fmv1992** [comment]
Me too...
```
+------------------+---------------------+
| xonsh            | 0.5.12              |
| Git SHA          | 8941dfdd            |
| Commit Date      | Jun 7 16:04:39 2017 |
| Python           | 3.6.1               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.14              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | arch                |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

I will be glad to help.

**Comment by scopatz** [comment]
We probably should add the Python interpreter / version to xonfig info
