### ISSUE TITLE
Foreign shell set to empty string crashes xonsh

### ISSUE THREAD

**Issue by jkw** [xonsh/xonsh#2371]
sh-4.4$ sudo pip install -U xonsh
Requirement already up-to-date: xonsh in /usr/lib/python3.6/site-packages
sh-4.4$ xonsh 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20476, in main
    args = premain(argv)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20429, in premain
    env = start_services(shell_kwargs)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20380, in start_services
    xonshrc_context(rcfiles=rc, execer=execer, ctx=ctx, env=env, login=login)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16772, in xonshrc_context
    login=login)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16810, in static_config_run_control
    issue_warning=False)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9204, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 8888, in foreign_shell_data
    shkey = CANON_SHELL_NAMES[shell]
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 332, in __getitem__
    return obj[item]
KeyError: ''
Xonsh encountered an issue during launch
Failback to /bin/sh
sh-4.4$ which xonsh
/usr/bin/xonsh
sh-4.4$

**Comment by laerus** [comment]
hey @jkw thanks for the report!

this doesn't seem like an amalgam issue, amalgam is just a big file with the whole xonsh codebase.
you can see what is actually going on if you start xonsh with ```XONSH_DEBUG=1``` envvar.

**Comment by jkw** [comment]
Then I get this:
sh-4.4$ XONSH_DEBUG=1 xonsh
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/main.py", line 336, in main
    args = premain(argv)
  File "/usr/lib/python3.6/site-packages/xonsh/main.py", line 289, in premain
    env = start_services(shell_kwargs)
  File "/usr/lib/python3.6/site-packages/xonsh/main.py", line 240, in start_services
    xonshrc_context(rcfiles=rc, execer=execer, ctx=ctx, env=env, login=login)
  File "/usr/lib/python3.6/site-packages/xonsh/environ.py", line 1101, in xonshrc_context
    login=login)
  File "/usr/lib/python3.6/site-packages/xonsh/environ.py", line 1139, in static_config_run_control
    issue_warning=False)
  File "/usr/lib/python3.6/site-packages/xonsh/foreign_shells.py", line 576, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/usr/lib/python3.6/site-packages/xonsh/foreign_shells.py", line 260, in foreign_shell_data
    shkey = CANON_SHELL_NAMES[shell]
  File "/usr/lib/python3.6/site-packages/xonsh/lazyasd.py", line 73, in __getitem__
    return obj[item]
KeyError: ''
Xonsh encountered an issue during launch
Failback to /bin/sh

**Comment by laerus** [comment]
i can reproduce it if i set and empty string as a foreign shell in the `~/.config/xonsh/config.json` file:

```
Traceback (most recent call last):
  File "/home/laerus/sourcecode/py/xonsh/xonsh/main.py", line 298, in main
    return main_xonsh(argv)
  File "/home/laerus/sourcecode/py/xonsh/xonsh/main.py", line 305, in main_xonsh
    args = premain(argv)
  File "/home/laerus/sourcecode/py/xonsh/xonsh/main.py", line 245, in premain
    builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/home/laerus/sourcecode/py/xonsh/xonsh/shell.py", line 92, in __init__
    kwargs.get('cacheall', False))
  File "/home/laerus/sourcecode/py/xonsh/xonsh/shell.py", line 146, in _init_environ
    debug_level=debug)
  File "/home/laerus/sourcecode/py/xonsh/xonsh/execer.py", line 42, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/home/laerus/sourcecode/py/xonsh/xonsh/built_ins.py", line 1117, in load_builtins
    builtins.__xonsh_env__ = Env(default_env(config=config, login=login))
  File "/home/laerus/sourcecode/py/xonsh/xonsh/environ.py", line 1101, in default_env
    issue_warning=False)
  File "/home/laerus/sourcecode/py/xonsh/xonsh/foreign_shells.py", line 551, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/home/laerus/sourcecode/py/xonsh/xonsh/foreign_shells.py", line 246, in foreign_shell_data
    shkey = CANON_SHELL_NAMES[shell]
  File "/home/laerus/sourcecode/py/xonsh/xonsh/lazyasd.py", line 73, in __getitem__
    return obj[item]
KeyError: ''
Xonsh encountered an issue during launch
Failback to /home/laerus/.local/bin/xon.sh
```

[this](https://github.com/xonsh/xonsh/blob/master/xonsh/foreign_shells.py#L260) is the offending line

**Comment by laerus** [comment]
can you post your `~/.config/xonsh/config.json` too for completeness? thanks for catching this up!

PRs are welcomed :smiley:

**Comment by jkw** [comment]
sh-4.4$ cat .config/xonsh/config.json 
{
 "foreign_shells": [
  {
   "shell": ""
  }
 ]
}

What do I need to fill in?

**Comment by laerus** [comment]
@jkw oh yea oops, sorry about that.

one workaround would be to remove the foreign shells entry on the `config.json` all together.
if you want to load an rc file though, something like `"bash"` would do it.

**Comment by laerus** [comment]
Note: this can fixed in the wizard too. (or maybe both)

**Comment by jkw** [comment]
Adding bash to "shell": "" worked indeed. Might be good to set it defaulting to sh or even code check to see if its empty?

**Comment by laerus** [comment]
yup! tbh it used to default to 'bash', a `git bisect` may give some insight.

**Comment by melund** [comment]
Unless you have a developed `bash` setup, with functions etc, then just skip foreign shell stuff. The foreign shell stuff is mostly to make it easier for power users to migrate to xonsh. 

I think there is a bug here. It should, of course, handle that foreign shell is set to an empty string. As @laerus  said PRs are welcome.

**Comment by anki-code** [comment]
I'm going to close this too old issue without new reports and repeatable examples.
