### ISSUE TITLE
Xonsh failing after upgrading to 0.5.10. 

### ISSUE THREAD

**Issue by chewrocca** [xonsh/xonsh#2395]
Tried to upgrade to xonsh 0.5.10 and now I'm getting the following.  

Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20485, in main
    args = premain(argv)
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20438, in premain
    env = start_services(shell_kwargs)
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20387, in start_services
    xonshrc_context(rcfiles=rc, execer=execer, ctx=ctx, env=env, login=login)
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16779, in xonshrc_context
    login=login)
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16835, in static_config_run_control
    update_context(name, ctx=ctx)
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10289, in update_context
    modctx = xontrib_context(name)
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10256, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xontrib/bashisms.py", line 2, in <module>
    from prompt_toolkit.keys import Keys
ModuleNotFoundError: No module named 'prompt_toolkit'
Xonsh encountered an issue during launch
Failback to /bin/bash

What can I do to fix this issue?

**Comment by gforsyth** [comment]
You should install `prompt_toolkit` or disable the `bashisms` xontrib

**Comment by chewrocca** [comment]
Thanks, this got me closer, though I'm still a bit confused.  I have prompt_toolkit installed prompt-toolkit (1.0.14), however, xonfig lists it and pygments as "None".  I have shell type set to 'best' $SHELL_TYPE='best' in xonshrc.  If I change that to "prompt_toolkit" I get the following "/usr/local/Cellar/xonsh/0.5.10/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py:14195: UserWarning: prompt_toolkit is not available, using readline instead.
  warnings.warn('prompt_toolkit is not available, using '
"

Any ideas on how to fix this?

**Comment by astronouth7303** [comment]
How did you install xonsh and prompt_toolkit?

**Comment by chewrocca** [comment]
I used 'brew install xonsh' and pip3 install prompt_toolkit.

**Comment by astronouth7303** [comment]
Open xonsh and use `xip install prompt_toolkit`. Xonsh under homebrew doesn't use the system python environment.

**Comment by chewrocca** [comment]
This worked.  Thank you!
