### ISSUE TITLE
Config file JSON --Invalid JSON Works. Valid JSON Doesn't

### ISSUE THREAD

**Issue by madranet** [xonsh/xonsh#2405]
I've just installed `xonsh` on OSX using homebrew and run through the initial config.  Here is the content of my config file:

```
{
 "foreign_shells": [
  {
   "shell": "zsh"
  }
 ],
 "xontribs": [
  "bashisms",
  "coreutils",
  "z",
  "powerline",
 ]
}
```

When I launch a terminal window, `xonsh` complains my config file is not valid JSON [but `xonsh` does at least launch!]:

```
Last login: Mon Jun 12 21:19:59 on ttys000
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
json.decoder.JSONDecodeError: Expecting value: line 12 column 2 (char 120)
Xonsh config file is not valid JSON.
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
json.decoder.JSONDecodeError: Expecting value: line 12 column 2 (char 120)
Xonsh config file is not valid JSON.
```
[There is an extraneous `,` after `"powerline"`]

If I remove that `,`, so that the config file is now valid JSON, `xonsh` crashes on launch with an error about `prompt_toolkit` not being found and falls back to `bash` [my default shell is `zsh`]:

```
Last login: Mon Jun 12 21:20:23 on ttys000
/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py:8990: RuntimeWarning: could not parse alias "battery": ValueError('No escaped character',)
  RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20485, in main
    args = premain(argv)
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20438, in premain
    env = start_services(shell_kwargs)
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20387, in start_services
    xonshrc_context(rcfiles=rc, execer=execer, ctx=ctx, env=env, login=login)
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16779, in xonshrc_context
    login=login)
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16835, in static_config_run_control
    update_context(name, ctx=ctx)
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10289, in update_context
    modctx = xontrib_context(name)
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 10256, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/Cellar/xonsh/0.5.12/libexec/lib/python3.6/site-packages/xontrib/bashisms.py", line 2, in <module>
    from prompt_toolkit.keys import Keys
ModuleNotFoundError: No module named 'prompt_toolkit'
Xonsh encountered an issue during launch
Failback to /bin/bash
bash-3.2$
```

`prompt_toolkit` is installed. I installed it with `pip`

So, anyone any idea how I get out of this one?

[And, are there any other options for the config file format, other than JSON? I loathe that bloody thing with a passion.]

**Comment by astronouth7303** [comment]
How did you you install `prompt_toolkit`? Some installation methods create an isolated environment for xonsh, so standard system `pip` will not work.

**Comment by madranet** [comment]
I installed it with `pip install prompt_toolkit` from within `xonsh` while [or just after] running the initial setup.

**Comment by gforsyth** [comment]
Hey @madranet -- thanks for reporting.  
The foreign shell stuff does need to be in `config.json` but the `xontribs` can be loaded in your `xonshrc` file. Just do a `xontrib load bashisms` or whichever you want and they'll be loaded when you start up `xonsh`. 

As for `prompt_toolkit` try installing it using the `xip` alias, instead (`xip install prompt_toolkit`).  Homebrew creates an isolated environment, as @astronouth7303 mentioned and so even calling `pip` from within `xonsh` will often not install things to the "correct" location.  `xip` will always install things into the python environment that `xonsh` is living in.

**Comment by madranet** [comment]
Thanks! That seems to have fixed it.
