### ISSUE TITLE
Permission Error when using cd (Windows 10)

### ISSUE THREAD

**Issue by pyeguy** [xonsh/xonsh#2409]
love xonsh but getting some odd behavior on windows 10. I get a `PermissionError` when cd'ing to any directory. 

```
camer@DESKTOP-0IGRTG4                                                                                         [~]  [1] 
$cd repos\
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\camer\\AppData\\Local\\Temp\\tmpjneokbz2'
Exception raised in event handler; ignored.
camer@DESKTOP-0IGRTG4                                                                                      [~\repos]
$
```

It does change directories but throws the error...

**Comment by pyeguy** [comment]
Here's the output with ` $XONSH_SHOW_TRACEBACK = True`

```
camer@DESKTOP-0IGRTG4                                                                                      [~\repos]
$cd ../
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\camer\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 7981, in fire
    rv = handler(*pargs, **kwargs)
  File "C:\Users\camer\Anaconda3\lib\site-packages\xontrib\z.py", line 211, in cd_handler
    self.add(self.getpwd())
  File "C:\Users\camer\Anaconda3\lib\site-packages\xontrib\z.py", line 192, in add
    self.save_data(data)
  File "C:\Users\camer\Anaconda3\lib\site-packages\xontrib\z.py", line 119, in save_data
    shutil.copy(f.name, self.Z_DATA)
  File "C:\Users\camer\Anaconda3\lib\shutil.py", line 235, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\camer\Anaconda3\lib\shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\camer\\AppData\\Local\\Temp\\tmpqqcsca9a'
Exception raised in event handler; ignored.
camer@DESKTOP-0IGRTG4                                                                                            [~]
$
```

and my `xonfig` output:

```
camer@DESKTOP-0IGRTG4                                                                                            [~]
$xonfig
+------------------+-----------------+
| xonsh            | 0.5.2           |
| Python           | 3.5.2           |
| PLY              | 3.9             |
| have readline    | False           |
| prompt toolkit   | 1.0.3           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by scopatz** [comment]
Hi @pyeguy, thanks for reporting! This seems to be an issue with the `z` xontrib.  I think a better place to report this would be https://github.com/astronouth7303/xontrib-z, but @astronouth7303 will know more.

**Comment by astronouth7303** [comment]
Reported as [xontrib-z#3](https://github.com/astronouth7303/xontrib-z/issues/3). Closing this.

**Comment by astronouth7303** [comment]
(The work around is to not load the `z` xontrib.)

**Comment by pyeguy** [comment]
cool thanks, i'll keep an eye on the xontrib-z issue
