### ISSUE TITLE
sre_constants.error: invalid group reference

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#2427]
```
>>> $PATHX="C:\ProgramFiles (x86)\Windows Kits\8.1\Windows Performance Toolkit"
>>> echo "$PATHX"
Traceback (most recent call last):
  File "c:\python35-32\lib\sre_parse.py", line 938, in expand_template
    literals[index] = g(group) or empty
IndexError: no such group

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35-32\lib\site-packages\xonsh\base_shell.py", line 328, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "c:\python35-32\lib\site-packages\xonsh\codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "c:\python35-32\lib\site-packages\xonsh\tools.py", line 91, in expand_path
    s = expandvars(s)
  File "c:\python35-32\lib\site-packages\xonsh\tools.py", line 1752, in expandvars
    path = POSIX_ENVVAR_REGEX.sub(value, path, count=1)
  File "c:\python35-32\lib\re.py", line 330, in filter
    return sre_parse.expand_template(template, match)
  File "c:\python35-32\lib\sre_parse.py", line 940, in expand_template
    raise error("invalid group reference")
sre_constants.error: invalid group reference
```
```
>>> $X="\8"
>>> echo "$X"
Traceback (most recent call last):
  File "c:\python35-32\lib\sre_parse.py", line 938, in expand_template
    literals[index] = g(group) or empty
IndexError: no such group

During handling of the above exception, another exception occurred:

...
```

Is what intended to be?

**Comment by astronouth7303** [comment]
What's the output of `xonfig`?

**Comment by andry81** [comment]
Have had to retest it on different pc:
```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "H:\Python36\lib\site-packages\xonsh\base_shell.py", line 328, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "H:\Python36\lib\site-packages\xonsh\codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "H:\Python36\lib\site-packages\xonsh\tools.py", line 91, in expand_path
    s = expandvars(s)
  File "H:\Python36\lib\site-packages\xonsh\tools.py", line 1752, in expandvars
    path = POSIX_ENVVAR_REGEX.sub(value, path, count=1)
  File "H:\Python36\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "H:\Python36\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "H:\Python36\lib\sre_parse.py", line 944, in parse_template
    addgroup(int(this[1:]), len(this) - 1)
  File "H:\Python36\lib\sre_parse.py", line 888, in addgroup
    raise s.error("invalid group reference %d" % index, pos)
sre_constants.error: invalid group reference 8 at position 1
```
```
+------------------+-----------------------------------------------+
| xonsh            | 0.5.12                                        |
| Git SHA          | 8941dfdd                                      |
| Commit Date      | Jun 7 16:04:39 2017                           |
| Python           | 3.6.1                                         |
| PLY              | 3.9                                           |
| have readline    | False                                         |
| prompt toolkit   | 1.0.14                                        |
| shell type       | prompt_toolkit                                |
| pygments         | None                                          |
| on posix         | False                                         |
| on linux         | False                                         |
| on darwin        | False                                         |
| on windows       | True                                          |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x028256F0> |
| is superuser     | False                                         |
| default encoding | utf-8                                         |
| xonsh encoding   | utf-8                                         |
| encoding errors  | surrogateescape                               |
+------------------+-----------------------------------------------+
```

**Comment by astronouth7303** [comment]
Oh, I see. We either need to run `path` through `re.escape()` or pass `.sub()` a callable in that argument.

**Comment by anki-code** [comment]
Hello! I can't repeat this:
```python
$X="\8"
echo "$X"
#\8
```
This issue looks not actual and should be closed.

**Comment by andry81** [comment]
Now it prints (`0.9.24`):

```
C:\Python\x86\38\Scripts $ $PATHX="C:\ProgramFiles (x86)\Windows Kits\8.1\Windows Performance Toolkit"<unknown>:1: DeprecationWarning: invalid
escape sequence \P
C:\Python\x86\38\Scripts $ $PATHX="C:\ProgramFiles (x86)\Windows Kits\8.1\Windows Performance Toolkit"
C:\Python\x86\38\Scripts $ echo "$PATHX"
"C:\ProgramFiles (x86)\Windows Kits\8.1\Windows Performance Toolkit"
C:\Python\x86\38\Scripts $ $X="\8"<unknown>:1: DeprecationWarning: invalid escape sequence \8
C:\Python\x86\38\Scripts $ $X="\8"
C:\Python\x86\38\Scripts $ echo "$X"
\8
```

**Comment by anki-code** [comment]
@andry81 thanks for the new test! The output looks right. Or it's wrong?

**Comment by andry81** [comment]
I am not sure, but the second output w/o the quotes for some reason and the warning is on the same line with the expression.

**Comment by anki-code** [comment]
AFAIK it's another issue. In this issue we are talking about `invalid group reference` exception and it is solved.
