### ISSUE TITLE
source throwing syntax error [Ubuntu 16]

### ISSUE THREAD

**Issue by pyeguy** [xonsh/xonsh#2448]
another source related error when trying to `source vars` using easy-rsa in Ubuntu Server 16.04

First it pukes on a syntax error in loading the environment vars, then when you attempt to enter another command it fully crashes back down to bash

```
cpye@megatron                                                                                [/etc/openvpn/easy-rsa]
$source vars
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: vars:15:7: ('code: EASY_RSA',)
export EASY_RSA="`pwd`"
       ^
cpye@megatron                                                                             [/etc/openvpn/easy-rsa]  [1]
$source vars$Xon
Traceback (most recent call last):
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20486, in main
    return main_xonsh(args)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20513, in main_xonsh
    shell.shell.cmdloop()
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 153, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 119, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py", line 118, in prompt
    eventloop.close()
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 270, in close
    os.close(schedule_pipe[0])
OSError: [Errno 9] Bad file descriptor
Xonsh encountered an issue during launch
Failback to /bin/sh
$
```

xonfig same as in #2447

**Comment by gforsyth** [comment]
`source` is for sourcing xsh files. You can use `source-bash` for bash
files and it should work better.

On Jul 22, 2017 1:59 PM, "Cameron Pye" <notifications@github.com> wrote:

another source related error when trying to source vars using easy-rsa in
Ubuntu Server 16.04

First it pukes on a syntax error in loading the environment vars, then when
you attempt to enter another command it fully crashes back down to bash

cpye@megatron
                      [/etc/openvpn/easy-rsa]
$source vars
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: vars:15:7: ('code: EASY_RSA',)
export EASY_RSA="`pwd`"
       ^
cpye@megatron
                   [/etc/openvpn/easy-rsa]  [1]
$source vars$Xon
Traceback (most recent call last):
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py",
line 20486, in main
    return main_xonsh(args)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py",
line 20513, in main_xonsh
    shell.shell.cmdloop()
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/ptk/shell.py",
line 153, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/ptk/shell.py",
line 119, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py",
line 118, in prompt
    eventloop.close()
  File "/home/cpye/anaconda3/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py",
line 270, in close
    os.close(schedule_pipe[0])
OSError: [Errno 9] Bad file descriptor
Xonsh encountered an issue during launch
Failback to /bin/sh
$

xonfig same as in #2447 <https://github.com/xonsh/xonsh/issues/2447>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xonsh/xonsh/issues/2448>, or mute the thread

**Comment by pyeguy** [comment]
right you are! good to know, I must have missed that distinction somehow. 

closing.

**Comment by scopatz** [comment]
Perhaps we should add some sort of error message to `source`  that indicates this error. Thanks for reporting @pyeguy!

**Comment by scopatz** [comment]
Please see #2450
