### ISSUE TITLE
'None is not a callable object' in tab completion

### ISSUE THREAD

**Issue by tekacs** [xonsh/xonsh#2454]
Trying to tab-complete after the expression: `(sys.` at my console fails (traceback below). Trying to tab-complete `sys.` works fine.

This gist contains my xonfig, the session JSON (including env) in which the error occurred and the traceback of the error (as below):

https://gist.github.com/tekacs/5061d265a2f1b378b72068c203e0f3d0

Happy to provide anything more that would be useful in tracking this down. Thanks! :)

```pytb
~ $ (sys.<TAB>Exception in thread Thread-153:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 860, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/completer.py", line 49, in get_completions
    self.ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 1431, in complete_base
    python_comps = complete_python(prefix, line, start, end, ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 1254, in complete_python
    rtn = _complete_python(prefix, line, start, end, ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 1278, in _complete_python
    args = python_signature_complete(prefix, line, end, ctx, filt)
  File "/usr/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 1376, in python_signature_complete
    sig = inspect.signature(val)
  File "/usr/lib/python3.6/inspect.py", line 3001, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.6/inspect.py", line 2751, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/lib/python3.6/inspect.py", line 2156, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: None is not a callable object
```

**Comment by laerus** [comment]
hey @tekacs, thanks for reporting this!
can you please post the output of `xonfig` ?

**Comment by laerus** [comment]
hey @tekacs, thanks for reporting!

can you please upgrade to xonsh 0.5.12 and see if this is still an issue?

**Comment by tekacs** [comment]
Nope, I still see this in 0.5.12.dev85 (I installed `xonsh-git` on Arch to get the latest possible and got a dev version, let me know if I should downgrade to the 0.5.12 release version).

Here's an asciinema of the behaviour:

https://asciinema.org/a/3qWOd8KOmbeNiqQfcfmBrHBBO

**Comment by melund** [comment]
I can reproduce this on Windows. Pressing tab anywhere to the right of open parentheses "(" always crashes, unless we starting a real function. 

i.e. the following works:
```
sys.displayhook(
```

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.5.12.dev64         |
| Git SHA          | ab477051             |
| Commit Date      | Jul 22 23:08:26 2017 |
| Python           | 3.6.1                |
| PLY              | 3.9                  |
| have readline    | False                |
| prompt toolkit   | 1.0.14               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | False                |
| on linux         | False                |
| on darwin        | False                |
| on windows       | True                 |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```
