### ISSUE TITLE
Syntax errors in subprocess commands containing []

### ISSUE THREAD

**Issue by blarghmatey** [xonsh/xonsh#2464]
I am trying to run a command which should be getting passed to a subprocess (in this case rake). The command itself includes square brackets (`[]`) which results in a traceback.

The command: `rake so_thing[some,parameters]`
The error:

<details>

```
Traceback (most recent call last):
  File "/home/tmacey/.local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 137, in _push
    locs=None)
  File "/home/tmacey/.local/lib/python3.6/site-packages/xonsh/execer.py", line 110, in compile
    transform=transform)
  File "/home/tmacey/.local/lib/python3.6/site-packages/xonsh/execer.py", line 79, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/tmacey/.local/lib/python3.6/site-packages/xonsh/execer.py", line 179, in _parse_ctx_free
    raise original_error from None
  File "/home/tmacey/.local/lib/python3.6/site-packages/xonsh/execer.py", line 166, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/tmacey/.local/lib/python3.6/site-packages/xonsh/parsers/base.py", line 348, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.6/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.6/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/tmacey/.local/lib/python3.6/site-packages/xonsh/parsers/base.py", line 2726, in p_error
    column=p.lexpos))
  File "/home/tmacey/.local/lib/python3.6/site-packages/xonsh/parsers/base.py", line 479, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: /home/tmacey/.local/lib/python3.6/site-packages/xontrib/jedi.xsh:1:21: ('code: [',)
rake generate_stack[01,dev2-useast1]
                   ^
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by astronouth7303** [comment]
This also happens with pip+extras.

**Comment by blarghmatey** [comment]
I assumed that would be the case. I tried wrapping it in a subprocess call (`$[rake do_stuff[foo,bar]]`) but got the same traceback.

**Comment by blarghmatey** [comment]
I was trying to figure out the workaround and was slowly converging to that. Thanks for saving me the effort!

**Comment by anki-code** [comment]
I've found that zsh also raise an error and requires quotes when using brackets:
```python
zsh
pip install hello[world]                                                                                                                                                           # zsh: no matches found: hello[world]
```
But bash and fish works with this kind of arguments. So this looks like a feature.
