### ISSUE TITLE
Non exisitng command wrapped in parentheses crashes xonsh

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#2467]
If I try to execute a non-existing command xonsh reports the error nicely:

```
snail@sea ~
$ not_a_command
xonsh: subprocess mode: command not found: not_a_command
```

If I do the same with parentheses xonsh comes with a weird traceback.
```
snail@sea ~\Documents\Projects\LLJ
$ (not_a_command)
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 512, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\proc.py", line 559, in __init__
    **kwargs)
  File "C:\Users\mel\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\mel\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\Scripts\xonsh-script.py", line 5, in <module>
    sys.exit(xonsh.main.main())
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\main.py", line 341, in main
    _failback_to_other_shells(args, err)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\main.py", line 305, in _failback_to_other_shells
    raise err
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\main.py", line 339, in main
    return main_xonsh(args)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\main.py", line 371, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\codecache.py", line 209, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "8104809f2f92cd6602961aead5bbcdfe", line 1, in <module>
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 877, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 813, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\proc.py", line 1767, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 502, in run
    p = self._run_binary(kwargs)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 523, in _run_binary
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: not_a_command
```

```
$ xonfig
+------------------+-------------------------------------------------------+
| xonsh            | 0.5.12.dev64                                          |
| Git SHA          | ab477051                                              |
| Commit Date      | Jul 22 23:08:26 2017                                  |
| Python           | 3.6.1                                                 |
| PLY              | 3.9                                                   |
| have readline    | False                                                 |
| prompt toolkit   | 1.0.14                                                |
| shell type       | prompt_toolkit                                        |
| pygments         | 2.2.0                                                 |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000027E4BEC4EB8> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

**Comment by gforsyth** [comment]
Hey @melund -- is this still an issue on windows with 0.6.2?

**Comment by melund** [comment]
I completely forgot about this one. But yes. This is still a problem.

**Comment by melund** [comment]
Maybe the real question here is why `$XONSH_SHOW_TRACEBACK` has no effect on the case with parentheses...

**Comment by scopatz** [comment]
It might be because `FileNotFoundError` is not a XonshError or SyntaxError or something silly like that.

**Comment by scopatz** [comment]
This is weird.  It is also happening with running files that don't have execute permission

**Comment by scopatz** [comment]
The inverse problem is also True.  If you are showing the traceback and don't use parens, the traceback will *not* be displayed:

```console
scopatz@artemis ~ $ $XONSH_SHOW_TRACEBACK = True
scopatz@artemis ~ $ not_command
xonsh: subprocess mode: command not found: not_command
not_command: command not found

```
