### ISSUE TITLE
Syntax error when trying to use python rendering after =

### ISSUE THREAD

**Issue by blarghmatey** [xonsh/xonsh#2481]
If I try to run a subprocess command and pass a Python variable to an argument that contains an `=` I get a syntax error from the parser. For example:
```
Traceback (most recent call last):
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 137, in _push
    locs=None)
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19709, in compile
    transform=transform)
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19678, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19778, in _parse_ctx_free
    raise original_error from None
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19765, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 348, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/ply/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/ply/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2726, in p_error
    column=p.lexpos))
  File "/home/tmacey/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 479, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: /home/tmacey/.local/lib/python3.5/site-packages/xontrib/jedi.xsh:1:49: ('code: [',)
$[sudo salt @(minion) state.sls edx.prod pillar=@[pillar_data]]
```

```
+------------------+---------------------+
| xonsh            | 0.5.12              |
| Git SHA          | 8941dfdd            |
| Commit Date      | Jun 7 16:04:39 2017 |
| Python           | 3.5.3               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.9               |
| shell type       | prompt_toolkit      |
| pygments         | 2.1.3               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by astronouth7303** [comment]
You need `@(pillar_data)`. `@[]` isn't a thing.

(Shameless plug: I wrote `xontrib-salt`, although it's made for salt-api. You can bother me on freenode or gitter about it.)

**Comment by blarghmatey** [comment]
I'll definitely take a look at xontrib-salt.

I did try it with `@()` first. The `@[]` was just me flailing at trying to get something to run.

**Comment by blarghmatey** [comment]
The other thing that I've tried in this kind of situation is to just build the string using `.format` and then executing the string but it always throws `command not found` and then the cmd string.

**Comment by astronouth7303** [comment]
`$[sudo salt @(minion) state.sls edx.prod @("pillar="+str(pillar_data))] ` parses for me.

(`@()` only works on whole words. `echo foo=@(bar)` also produces a syntax error. I thought it would just dump before, though?)

`@()` when given a string, treats the whole string as a single argument, so no additional escaping is needed for eg surprise spaces.

**Comment by blarghmatey** [comment]
:+1: 
Thanks for the breakdown. I've been trying to wrap my head around how to hang all of the nesting together.

**Comment by astronouth7303** [comment]
(And if you'd like, I would love to have a conversation about using xonsh as a better salt environment.)

**Comment by blarghmatey** [comment]
Yeah, that would be great. I've got some ideas that I've started toying with. You can get in touch with me directly on Keybase or via email (listed on my github profile).
