### ISSUE TITLE
first redirection on windows fail to create the file

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#2491]
the first redirection of commands on windows seems to fail to create the files before running, which lead to the message below. After the command is done the file exist and is left open by xonsh until you exit the shell. Aparently any other redirections after the first one work fine. This happens on the released xonsh and on master.

```
$ ls > d.txt
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "c:\dev\xonsh\xonsh\base_shell.py", line 328, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "c:\dev\xonsh\xonsh\codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "c:\dev\xonsh\xonsh\built_ins.py", line 877, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "c:\dev\xonsh\xonsh\built_ins.py", line 813, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "c:\dev\xonsh\xonsh\proc.py", line 1767, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "c:\dev\xonsh\xonsh\built_ins.py", line 502, in run
    p = self._run_binary(kwargs)
  File "c:\dev\xonsh\xonsh\built_ins.py", line 512, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "c:\dev\xonsh\xonsh\proc.py", line 552, in __init__
    os.set_handle_inheritable(stdout.fileno(), False)
OSError: [WinError 6] The handle is invalid
```

**Comment by melund** [comment]
Duplicates: #2469

**Comment by anki-code** [comment]
This issue looks fixed duplicate and should be closed.
