### ISSUE TITLE
Wizard:  Static vs RC | Breaking xontribs ?

### ISSUE THREAD

**Issue by melMass** [xonsh/xonsh#2510]
Hi,

Great initiative and execution!

While running the wizard I was expecting some of the answers to go to the **Run Control config file (~/.xonshrc)** and some in the **Static one (~/.config/xonsh/config.json)**

They all ended up in the latest causing me some errors.

### The steps to reproduce

1. After running the wizard I ended up with some foreign_shells badly escaped aliases errors.
This was easy to fix manually (usually replacing *double quotes* by *single* ones and escaping the rest (`\`) )

2. Then after installing the xontribs dependencies xonsh was trowing me back to bash with the following traceback:

    <details>
      <summary>Traceback Error (Click to expand)</summary>

    ```
    Traceback (most recent call last):
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20486, in main
        return main_xonsh(args)
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20513, in main_xonsh
        shell.shell.cmdloop()
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 153, in cmdloop
        line = self.singleline(auto_suggest=auto_suggest)
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 114, in singleline
        prompt_args['lexer'] = PygmentsLexer(pyghooks.XonshLexer)
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/prompt_toolkit/layout/lexers.py", line 195, in __init__
        ensurenl=False)
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/pygments/lexer.py", line 582, in __call__
        return type.__call__(cls, *args, **kwds)
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/pyghooks.py", line 94, in __init__
        _ = builtins.__xonsh_commands_cache__.all_commands  # NOQA
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 7733, in all_commands
        for cmd in executables_in(path):
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 5894, in executables_in
        yield from func(path)
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 5862, in _executables_in_posix
        yield from _yield_accessible_unix_file_names(path)
    File "/Users/saymyname/anaconda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 5842, in _yield_accessible_unix_file_names
        for file_ in scandir(path):
    NotADirectoryError: [Errno 20] Not a directory: '/usr/local/bin/npm'
    Xonsh encountered an issue during launch
    Failback to /bin/bash
    ```

    </details>

### The solution

3. I decided to check the **static config file**.
**Enabling xontribs one by one** revealed the culprit: **powerline**.
I removed it from the static and added `xontrib load powerline` to the RC file as stated in powerline's readme.

Now everything runs smoothly.
So I don't get the reason of the error but it might be useful informations.

**Comment by astronouth7303** [comment]
@santagada

**Comment by santagada** [comment]
did the way we load xontribs changed? I'm still plagued by the bugs on prompt-toolkit colors on windows (IIRC there's a new version coming out that will fix it) and I'm not using powerline myself for that.

**Comment by scopatz** [comment]
Hi All, I think it is probably long past time we just got rid of the static config file.  Many people don't like it, it was just the easiest thing to implement.

**Comment by gforsyth** [comment]
I'm closing this out as the static config file is dead.  Long live run control!
