### ISSUE TITLE
Application launch error xonsh

### ISSUE THREAD

**Issue by duytrung** [xonsh/xonsh#2538]
Hello,

I have the following error executing xonsh:

```

C:\MyPrograms\Anaconda\lib\site-packages\win_unicode_console\__init__.py:31: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == 'cp1252', readline hook consumer may assume they are the same
readline_hook.enable(use_pyreadline=use_pyreadline)
Traceback (most recent call last):
File "C:\MyPrograms\Anaconda\Scripts\xonsh-script.py", line 5, in 
sys.exit(xonsh.main.main())
File "C:\MyPrograms\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 20488, in main
_failback_to_other_shells(args, err)
File "C:\MyPrograms\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 20457, in _failback_to_other_shells
raise err
File "C:\MyPrograms\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 20486, in main
return main_xonsh(args)
File "C:\MyPrograms\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 20510, in main_xonsh
print_welcome_screen()
File "C:\MyPrograms\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 15144, in print_welcome_screen
termwidth = os.get_terminal_size().columns
OSError: [WinError 6] The handle is invalid

```

![image](https://user-images.githubusercontent.com/2046672/33071949-81240706-cf0d-11e7-94e1-cd057c89c83e.png)

**Comment by duytrung** [comment]
My anaconda:
```

Fetching package metadata ...............
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::blinker-1.4-py36_0
  - conda-forge::blinker-1.4-py_0

# All requested packages already installed.
# packages in environment at C:\MyPrograms\Anaconda:
#
_license                  1.1                      py36_1
alabaster                 0.7.10                   py36_1    conda-forge
anaconda                  custom           py36h363777c_0
anaconda-client           1.6.5                      py_0    conda-forge
anaconda-navigator        1.6.9            py36hc720852_0
anaconda-project          0.8.2                    py36_0    conda-forge
anyqt                     0.0.8                    py36_1    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
astroid                   1.4.8                    py36_0    conda-forge
astropy                   2.0.2               np113py36_1    conda-forge
babel                     2.5.1                    py36_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.4                      py36_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
bitarray                  0.8.1                    py36_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blaze                     0.11.3                   py36_0    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
blinker                   1.4                      py36_0    conda-forge
bokeh                     0.12.10                  py36_0    conda-forge
boto                      2.48.0           py36h1a776d2_1
boto3                     1.4.7                    py36_0    conda-forge
botocore                  1.5.92                   py36_0    conda-forge
bottleneck                1.2.1                    py36_1    conda-forge
bz2file                   0.98                     py36_0
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2017.11.5                     0    conda-forge
certifi                   2017.11.5                py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
cloudpickle               0.4.0                    py36_0    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
commonmark                0.7.3                    py36_0    conda-forge
comtypes                  1.1.3                    py36_0    conda-forge
conda                     4.3.29                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py36_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
curl                      7.55.1                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.27.3                   py36_0    conda-forge
cytoolz                   0.8.2                    py36_0    conda-forge
dask                      0.16.0                     py_0    conda-forge
dask-core                 0.16.0                     py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
dill                      0.2.6                    py36_0    conda-forge
distributed               1.20.0                   py36_0    conda-forge
django                    1.11.7                     py_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
et_xmlfile                1.0.1                    py36_0    conda-forge
fastcache                 1.0.2                    py36_0    conda-forge
flask                     0.12.2                   py36_0    conda-forge
flask-cors                3.0.3                    py36_0    conda-forge
freetype                  2.7                      vc14_2  [vc14]  conda-forge
future                    0.16.0                   py36_0    conda-forge
gensim                    3.1.0               py36_vc14_0  [vc14]  conda-forge
geojson                   2.3.0                      py_0    conda-forge
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2                    py36_0    conda-forge
greenlet                  0.4.12                   py36_0    conda-forge
h5py                      2.7.1                    py36_2    conda-forge
hdf5                      1.10.1                   vc14_1  [vc14]  conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.6                      py36_1    conda-forge
imageio                   2.2.0                    py36_0    conda-forge
imagesize                 0.7.1                    py36_0    conda-forge
intel-openmp              2018.0.0             hcd89f80_7
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.0.5                    py36_0    conda-forge
isort                     4.2.15                   py36_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jdcal                     1.3                      py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jmespath                  0.9.3                    py36_0    conda-forge
joblib                    0.11                     py36_0    conda-forge
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keras                     2.0.9                    py36_0    conda-forge
keyring                   9.0                      py36_0    conda-forge
keyrings.alt              1.2                      py36_0    conda-forge
krb5                      1.14.2                   vc14_0  [vc14]  conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libgpuarray               0.7.5                    vc14_0  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libpng                    1.6.28                   vc14_2  [vc14]  conda-forge
libpython                 2.0                      py36_0
libssh2                   1.8.0                    vc14_2  [vc14]  conda-forge
libtiff                   4.0.7                    vc14_1  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
libxslt                   1.1.29                   vc14_5  [vc14]  conda-forge
llvmlite                  0.20.0                   py36_0
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.1.1                    py36_0    conda-forge
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
mako                      1.0.7                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.0                    py36_1    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
menuinst                  1.4.10           py36h42196fb_0
mistune                   0.8                      py36_0    conda-forge
mkl                       2018.0.0             h36b65af_4
mkl-service               1.1.2            py36h57e144c_4
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.4.8                    py36_0    conda-forge
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9                    py36_0    conda-forge
navigator-updater         0.1.0            py36h8a7b86b_0
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
neovim                    0.2.0                    py36_0    conda-forge
networkx                  2.0                      py36_0    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.2.1                    py36_2    conda-forge
numba                     0.35.0             np113py36_10
numexpr                   2.6.4                    py36_0    conda-forge
numpy                     1.13.3           py36ha320f96_0
numpydoc                  0.7.0                    py36_0    conda-forge
oauthlib                  2.0.6                      py_0    conda-forge
odo                       0.5.1                    py36_0    conda-forge
olefile                   0.44                     py36_0    conda-forge
openpyxl                  2.5.0b1                  py36_0    conda-forge
openssl                   1.0.2l                   vc14_0  [vc14]  conda-forge
orange3                   3.7.1                    py36_0    conda-forge
packaging                 16.8                     py36_0    conda-forge
pandas                    0.21.0                   py36_0    conda-forge
pandoc                    2.0.0.1                       1    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
path.py                   10.3.1                   py36_0    conda-forge
pathlib2                  2.3.0                    py36_0    conda-forge
patsy                     0.4.1                    py36_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    4.3.0                    py36_1    conda-forge
pip                       9.0.1                    py36_0    conda-forge
ply                       3.10                     py36_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.0                    py36_0    conda-forge
py                        1.5.2                      py_0    conda-forge
pyasn1                    0.3.7                      py_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pycurl                    7.43.0           py36h086bf4c_3
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pygpu                     0.7.5                    py36_0    conda-forge
pyjwt                     1.5.3                      py_0    conda-forge
pylint                    1.6.5                    py36_0    conda-forge
pymc3                     3.2                      py36_0    conda-forge
pyodbc                    4.0.17                   py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pyqtgraph                 0.10.0                   py36_2    conda-forge
pyreadline                2.1              py36h094d952_1
pysocks                   1.6.7                    py36_0    conda-forge
pytables                  3.4.2                    py36_7    conda-forge
pytest                    3.2.5                    py36_0    conda-forge
python                    3.6.3                         1    conda-forge
python-crfsuite           0.9.2               py36_vc14_0  [vc14]  conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
pywavelets                0.5.2                    py36_1    conda-forge
pywin32                   220                      py36_1    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.3.1                    py36_0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
requests-oauthlib         0.8.0                    py36_1    conda-forge
rope                      0.10.7                   py36_0    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
s3fs                      0.1.2                    py36_0    conda-forge
s3transfer                0.1.11                   py36_0    conda-forge
scikit-image              0.13.0                   py36_1    conda-forge
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.0.0            py36h1260518_0
seaborn                   0.8.1                    py36_0    conda-forge
serverfiles               0.2.1                      py_0    conda-forge
setuptools                36.7.2                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
singledispatch            3.4.0.3                  py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
smart_open                1.5.3                    py36_0    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sockjs-tornado            1.0.3                    py36_0
sortedcollections         0.5.3                    py36_0    conda-forge
sortedcontainers          1.5.7                    py36_0    conda-forge
sphinx                    1.6.5                    py36_0    conda-forge
sphinxcontrib             1.0              py36hbbac3d2_1
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.4                    py36_0    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.19.3                   vc14_1  [vc14]  conda-forge
statsmodels               0.8.0                    py36_0    conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
theano                    0.9.0                    py36_1    conda-forge
tk                        8.6.6                    vc14_5  [vc14]  conda-forge
toolz                     0.8.2                      py_2    conda-forge
tornado                   4.5.2                    py36_0    conda-forge
tqdm                      4.19.4                     py_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
traits                    4.6.0                    py36_1    conda-forge
twython                   3.6.0                    py36_0    conda-forge
typing                    3.6.2                    py36_0    conda-forge
unicodecsv                0.14.1                   py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.12.2                     py_1    conda-forge
wheel                     0.30.0                     py_1    conda-forge
widgetsnbextension        3.0.8                    py36_0    conda-forge
win_inet_pton             1.0.1                    py36_1    conda-forge
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2                      py36_0    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xlrd                      1.0.0                    py36_1    conda-forge
xlsxwriter                1.0.2                      py_0    conda-forge
xlwings                   0.11.4                   py36_0    conda-forge
xlwt                      1.3.0                    py36_0    conda-forge
yaml                      0.1.6                    vc14_0  [vc14]  conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
```

**Comment by astronouth7303** [comment]
How are you executing xonsh?

**Comment by scopatz** [comment]
Yes, xonsh is meant to be executed from a terminal.

**Comment by melund** [comment]
Ahh. I think this used to work at some point. @duytrung I guess you are starting xonsh from the Anaconda Navigator. That has worked, but maybe the navigator has changed. The whole Navigator laucher idea has always been buggy. See https://github.com/ContinuumIO/anaconda-issues/issues/937

I suggest we just remove the `app:` entry from the conda recipe: 
https://github.com/conda-forge/xonsh-feedstock/blob/master/recipe/meta.yaml#L41

**Comment by melund** [comment]
I have put in a PR for this here: 
https://github.com/conda-forge/xonsh-feedstock/pull/52

**Comment by gforsyth** [comment]
I just merged the conda-forge PR.  I'll leave this open for now until a windows user can confirm that xonsh no longer appears in the anaconda navigator.

**Comment by melund** [comment]
Funny. It is still in the launcher... 

I have installed the newly build version from conda-forge: 
```
C:\Users\mel>conda install -f xonsh
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment C:\Users\mel\Anaconda3:

The following packages will be UPDATED:

    xonsh: 0.6.0-py36_0 conda-forge --> 0.6.0-py36_1 conda-forge

Proceed ([y]/n)? y

C:\Users\mel>
```

But in the navigator, the entry is still there.

![image](https://user-images.githubusercontent.com/1038978/33820288-f7d018cc-de4e-11e7-8f59-32fe164178ca.png)


 Maybe it is cached somehow. I will have to check on new install:

**Comment by melund** [comment]
The xonsh launcher no longer shows up in the newest versions of Navigator. So this is good to close... Thanks @gforsyth
