### ISSUE TITLE
Wrong error with foo(*)

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#2547]
With the input:

```
def spam(*): pass
```

I get the confusing:

```
TypeError: 'NoneType' object is not iterable
```

Instead of 

```
SyntaxError: named arguments must follow bare *
```

Backtrace:

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/jbliss/.conda/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 137, in _push
    locs=None)
  File "/home/jbliss/.conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19877, in compile
    transform=transform)
  File "/home/jbliss/.conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19846, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/jbliss/.conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19933, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/jbliss/.conda/lib/python3.6/site-packages/xonsh/parsers/base.py", line 349, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/jbliss/.conda/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/jbliss/.conda/lib/python3.6/site-packages/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/home/jbliss/.conda/lib/python3.6/site-packages/xonsh/parsers/base.py", line 653, in p_typedargslist_times4
    self._set_var_args(p0, p[2], None)
  File "/home/jbliss/.conda/lib/python3.6/site-packages/xonsh/parsers/base.py", line 762, in _set_var_args
    self._set_args_def(p0, kwargs, kwargs=True)
  File "/home/jbliss/.conda/lib/python3.6/site-packages/xonsh/parsers/base.py", line 736, in _set_args_def
    for v in vals:
TypeError: 'NoneType' object is not iterable
```

**Comment by scopatz** [comment]
Thanks for reporting @astronouth7303 - potential fix in #2556
