### ISSUE TITLE
Jedi auto completion issue

### ISSUE THREAD

**Issue by AndreaCrotti** [xonsh/xonsh#2552]
I noticed that sometimes auto completion breaks with this error below.
I finally noticed that it seems to be related with Jedi and in fact disabling it makes everything work again.

(running
```
$ xonsh --version
xonsh/0.6.0
```

Thanks a lot!

```
$ sudo systemctl start xbException in thread Thread-103:
Traceback (most recent call last):                                                                    
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                               
    self.run()                                                                                        
  File "/usr/lib/python3.6/threading.py", line 864, in run                                            
    self._target(*self._args, **self._kwargs)                                                         
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run               
    completions = list(buffer.completer.get_completions(document, complete_event))                    
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/completer.py", line 49, in get_completions         
    self.ctx)                                                                                         
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 831, in complete_skipper
    ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/usr/lib/python3.6/site-packages/xontrib/jedi.xsh", line 32, in complete_jedi
    script = jedi.api.Interpreter(src, [ctx], column=end)
  File "/home/andrea/.local/lib/python3.6/site-packages/jedi/api/__init__.py", line 386, in __init__
    super(Interpreter, self).__init__(source, **kwds)
  File "/home/andrea/.local/lib/python3.6/site-packages/jedi/api/__init__.py", line 102, in __init__    
    raise ValueError('`column` parameter is not in a valid range.')
ValueError: `column` parameter is not in a valid range.
```

**Comment by scopatz** [comment]
Thanks for reporting @AndreaCrotti! Can you please provide some example strings where this is arises?

**Comment by anki-code** [comment]
> sudo systemctl start xbException

Can't repeat this:

![Screenshot_20201014_212831](https://user-images.githubusercontent.com/1708680/96030091-401b9500-0e64-11eb-8a99-795fb3a12eae.png)

Looks like solved and should be closed.

**Comment by scopatz** [comment]
Yeah this seems pretty out of date. Please let us know if we should reopen!
