### ISSUE TITLE
xonsh don't close pipes on pypy3.5

### ISSUE THREAD

**Issue by lexleogryfon** [xonsh/xonsh#2583]
Hello, 
I'm using recursive function in xonsh script, to iterate a directory with large number of files, on each file i call `captured_output.append( !(ls -lat @(child) 2>&1 | grep r))`

If number of files exceed ulimit (1024 on my system), then python easily spits an 'OSerror way too many open files'.

Possible way to debug it is to add 'try' block ,  with sleep(100) in 'except' block, go to /proc/pidofxonshscript/fd and see that xonsh opened way too many pipes and didn't closed them even after subprocess execution finished.

I suggest to close pipes upon reception of exit code.

```
+------------------+----------------------+
| xonsh            | 0.6.0                |
| Git SHA          | c29819c5             |
| Commit Date      | Nov 22 17:51:52 2017 |
| Python           | 3.5.3                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

gist to reproduce https://gist.github.com/lexleogryfon/703901866bf75e378ca7717973b63e6d

```
Traceback (most recent call last):
  File "de-generate.py", line 28, in scan
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/built_ins.py", line 870, in subproc_captured_object
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/built_ins.py", line 815, in run_subproc
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/proc.py", line 1767, in __init__
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/built_ins.py", line 502, in run
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/built_ins.py", line 512, in _run_binary
  File "/home/lex/Desktop/mystuff/pc/work/work/Projects/runtime_collection/pypy3.5/lib-python/3/subprocess.py", line 691, in __init__
  File "/home/lex/Desktop/mystuff/pc/work/work/Projects/runtime_collection/pypy3.5/lib-python/3/subprocess.py", line 1213, in _execute_child
```

I tried to debug under ipdb and saw builtins.__xonsh_all_jobs__ grows infinitely, jobs do not change their status to 'stopped'. jobs that already done still have status 'running' 

Regarding Pypy GC http://doc.pypy.org/en/latest/cpython_differences.html#differences-related-to-garbage-collection-strategies

> To the best of our knowledge this problem has no better solution than fixing the programs. If it occurs in 3rd-party code, this means going to the authors and explaining the problem to them: they need to close their open files in order to run on any non-CPython-based implementation of Python

**Comment by gforsyth** [comment]
Hey @lexleogryfon -- thanks for reporting.  This is outside of my wheelhouse but I'll try to dig in a little later this week.

**Comment by scopatz** [comment]
Hi @lexleogryfon - does this happen on CPython too or just in PyPy?  If we have a file handle leak, then it would be good to figure that out!  I know that macOS sometimes has a very low file handle limit

**Comment by whitelynx** [comment]
Could this be related to what's mentioned in https://github.com/xonsh/xonsh/pull/2550#issuecomment-349043595 ? (differences in GC behavior, and not explicitly closing files)

**Comment by con-f-use** [comment]
I have a similar problem since very recently:
```
┌─20-22:00 [confus@confusion6 ~]                                              😱  😱
└$ ls                                                                                                                                                          
OSError: [Errno 24] Too many open files
```

```
┌─20-22:00 [confus@confusion6 ~]                                              😱  😱
└$ xonfig                                                                                                                                                      
+------------------+-----------------+
| xonsh            | 0.9.10          |
| Python           | 3.6.8           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

┌─20-22:01 [confus@confusion6 ~]                                              😱  😱
└$ lsof 2>/dev/null | ./lsof_parse.py                                                                                                                          
count -- command -- filename
9628 -- Xorg  --  pipe
8022 -- pulseaudi  --  (deleted)
5805 -- Xorg  --  UNIX
3224 -- gdm-x-ses  --  [eventfd]
2858 -- franz  --  type=SEQPACKET
2741 -- Xorg  --  /SYSV00000000
2176 -- systemd  --  denied)
1887 -- gnome-she  --  (ESTABLISHED)
1821 -- sh  --  directory)
1717 -- systemd  --  [eventpoll]
12583 -- systemd  --  type=STREAM
0988 -- firefox  --  /home/confus/.mozilla/firefox/hsm8zf1g.default/extensions/adnauseam@rednoise.org.xpi
0985 -- firefox  --  /home/confus/.mozilla/firefox/hsm8zf1g.default/extensions/uBlock0@raymondhill.net.xpi
0985 -- firefox  --  /home/confus/.mozilla/firefox/hsm8zf1g.default/extensions/LDSMGweb_plashcor@gmail.com.xpi
0942 -- systemd  --  /dev/null
0848 -- systemd  --  /lib/x86_64-linux-gnu/libc-2.27.so
0848 -- systemd  --  /lib/x86_64-linux-gnu/ld-2.27.so
0846 -- systemd  --  /lib/x86_64-linux-gnu/libdl-2.27.so
0845 -- systemd  --  /lib/x86_64-linux-gnu/libpthread-2.27.so
0837 -- gdm-x-ses  --  /lib/x86_64-linux-gnu/libz.so.1.2.11
```

```
Traceback (most recent call last):
  File "/home/jan/devel/unix/xonsh/xonsh/proc.py", line 1411, in run
  File "/home/jan/devel/unix/xonsh/xonsh/aliases.py", line 189, in __call__
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 190, in exec
    return exec(code, glbs, locs)
  File "<exec-alias:ls>", line 1, in <module>
  File "/home/jan/devel/unix/xonsh/xonsh/built_ins.py", line 1003, in subproc_captured_hiddenobject
  File "/home/jan/devel/unix/xonsh/xonsh/built_ins.py", line 928, in run_subproc
  File "/home/jan/devel/unix/xonsh/xonsh/built_ins.py", line 901, in cmds_to_specs
  File "/home/jan/devel/unix/xonsh/xonsh/built_ins.py", line 835, in _update_last_spec
OSError: [Errno 24] Too many open files
```

**Comment by con-f-use** [comment]
Oh wait, it's something in the `logical_op_aliases` branch because I was testing that!

https://github.com/xonsh/xonsh/issues/3270
