### ISSUE TITLE
Error `Bad file descriptor` in `prompt_toolkit/eventloop/posix`

### ISSUE THREAD

**Issue by lexleogryfon** [xonsh/xonsh#2585]
Currently I face this issue everyday, it happens occasionally.

```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/bin/xonsh", line 3, in <module>
    main()
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/main.py", line 344, in main
    _failback_to_other_shells(args, err)
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/main.py", line 313, in _failback_to_other_shells
    raise err
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/main.py", line 342, in main
    return main_xonsh(args)
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/main.py", line 369, in main_xonsh
    shell.shell.cmdloop()
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/ptk/shell.py", line 153, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/ptk/shell.py", line 119, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/xonsh/ptk/shortcuts.py", line 118, in prompt
    eventloop.close()
  File "/home/lex/Desktop/mystuff/nixexperiments/nixos_pypy35_venv/site-packages/prompt_toolkit/eventloop/posix.py", line 266, in close
    os.close(schedule_pipe[1])
OSError: [Errno 9] Bad file descriptor

```

```
+------------------+----------------------+
| xonsh            | 0.6.0                |
| Git SHA          | c29819c5             |
| Commit Date      | Nov 22 17:51:52 2017 |
| Python           | 3.5.3                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | prompt_toolkit       |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

```
Environment description:
I use NixOS 17.09 distribution, launch inside nix's function `pkgs.buildFHSUserEnv` that establish FHS like container\environment. Inside I `source to /statically_linked_PyPy35_venv/bin/activate` , then open xonsh (which installed from pip), then involve git commands and see this occasional crash from time to time (but at few times per day).

Another issue: xonsh doesn't perform man based --arguments auto-completion in this environment. However, I tested outside nix buildFHSUserEnv container, with standart cpython venv, and it did worked, but requires <TAB>-<TAB> unlike FISH autosuggestion.

Feature request: implement friendly_interactive_shell-like man-based autosuggestion, that doesn't require double press <TAB>-<TAB>, but instead suggest\autocompletes argument with grey font as you type, like regular history-based autosuggestion in xonsh.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for reporting @lexleogryfon - and sorry for the delayed response. It is unclear what is going on here, but it seems like the error is coming from within prompt-toolkit.  You may want to report this there.

> Another issue: xonsh doesn't perform man based --arguments auto-completion in this environment. 

That might be because the man pages are in some weird location. Have you tried setting MANPATH to your venvs `share/man` dir? Or to the root MAN location?

> but instead suggest\autocompletes argument with grey font as you type, like regular history-based autosuggestion in xonsh.

We'd be very open to this!  Pull requests welcome!

**Comment by anki-code** [comment]
Please repeat this in xonsh 0.11
