### ISSUE TITLE
Windows WSL: Tab completion stop working if enable WSL but doesn't install Ubuntu

### ISSUE THREAD

**Issue by LexSong** [xonsh/xonsh#2597]
Error messages:
```
Traceback (most recent call last):
  File "c:\Miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\Miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Miniconda3\lib\subprocess.py", line 1063, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'cp950' codec can't decode byte 0xae in position 8: illegal multibyte sequence

Exception in thread Thread-30:
Traceback (most recent call last):
  File "c:\Miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\Miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Miniconda3\lib\site-packages\prompt_toolkit\interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "c:\Miniconda3\lib\site-packages\xonsh\ptk\completer.py", line 49, in get_completions
    self.ctx)
  File "c:\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "c:\Miniconda3\lib\site-packages\xonsh\completers\__amalgam__.py", line 1455, in complete_from_bash
    command = xp.bash_command()
  File "c:\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 1302, in bash_command
    bc = windows_bash_command()
  File "c:\Miniconda3\lib\site-packages\xonsh\__amalgam__.py", line 1210, in windows_bash_command
    universal_newlines=True)
  File "c:\Miniconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\Miniconda3\lib\subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "c:\Miniconda3\lib\subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "c:\Miniconda3\lib\subprocess.py", line 1113, in _communicate
    stdout = stdout[0]
IndexError: list index out of range
```
Looks like that Xonsh try to get completions from `bash.exe` but failed.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by melund** [comment]
This reminds me of #2224 and #2305. It fails when it tries to detect if it WSL bash that it has on the path. It can't be be used for completion and xonsh should handle this.

The way it fails is a little weird I think. It seems to be inside the subprocess module. So maybe it is picking a bash.exe which Python can't handle. 

Can you try to run `which bash` and see what it is picking up. If it finds a bash.exe try running it manually and see what happens. 

Lastly, you can probably fix this by installing GitForWindows and it's MSys bash to path. But we better figure out what is causing this.

**Comment by LexSong** [comment]
I'm using traditional Chinese version of Windows. `chcp` won't change the prompt messages.

```
$ which bash
C:\windows\system32\bash.exe

$ bash
-- 搶鮮版 (Beta) 功能 --
這會在 Windows 上安裝 Ubuntu，它是由 Canonical
散佈，而且根據其下列條款授權使用:
https://aka.ms/uowterms

輸入 "Y" 以繼續:
n
需要接受才能繼續。正在結束...
請按任意鍵繼續...
```

The messages are translation of [these](https://docs.microsoft.com/en-us/windows/wsl/media/bashshellinstall.png), from [https://docs.microsoft.com/en-us/windows/wsl/install-win10](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by melund** [comment]
I see. Bash.exe is a kind of stub for an installer and causes `subprocess.check_output()` to fail. I guess
 all we can do is to catch the IndexError here.

https://github.com/xonsh/xonsh/blob/master/xonsh/platform.py#L343

A PR is very welcome if you have time.

**Comment by rophin** [comment]
I'm experiencing a similar problem. Running `python-m xonsh` with administrator authority seems to be working fine.
![image](https://user-images.githubusercontent.com/55056558/135009744-163f586a-55eb-46c9-8edb-458c5fbe481c.png)
This is the general authority.
![image](https://user-images.githubusercontent.com/55056558/135009997-d792dce3-281d-454b-a8dd-09ab3451640c.png)
This is the administrator's authority.

**Comment by anki-code** [comment]
I can't reproduce this on Windows 11 without WSL and xonsh installed using Python or Miniconda.
