### ISSUE TITLE
No module named 'prompt_toolkit'

### ISSUE THREAD

**Issue by fenhl** [xonsh/xonsh#2655]
I am having trouble getting the prompt_toolkit shell to work on macOS Sierra. I installed xonsh using Homebrew and prompt_toolkit using pip3.

```
$ py
>>> import prompt_toolkit
>>> prompt_toolkit.__file__
'/usr/local/lib/python3.6/site-packages/prompt_toolkit/__init__.py'
>>> ^D
$ xonsh
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
ModuleNotFoundError: No module named 'prompt_toolkit'
/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py:13132: UserWarning: prompt_toolkit is not available, using readline instead.
  warnings.warn('prompt_toolkit is not available, using '
fenhl@equinox ~ $ ^D
$ XONSH_SHOW_TRACEBACK=True xonsh
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12263, in wait
    r = self.f(self.args, stdin, stdout, stderr, spec)
  File "/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 11803, in proxy_two
    return f(args, stdin)
  File "/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9203, in xontribs_main
    return _MAIN_XONTRIB_ACTIONS[ns.action](ns)
  File "/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9120, in _load
    update_context(name, ctx=ctx)
  File "/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9099, in update_context
    modctx = xontrib_context(name)
  File "/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9066, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xontrib/whole_word_jumping.py", line 5, in <module>
    from prompt_toolkit.keys import Keys
ModuleNotFoundError: No module named 'prompt_toolkit'
/usr/local/Cellar/xonsh/0.6.4/libexec/lib/python3.6/site-packages/xonsh/__amalgam__.py:13132: UserWarning: prompt_toolkit is not available, using readline instead.
  warnings.warn('prompt_toolkit is not available, using '
```

Any ideas on how to fix?

**Comment by scopatz** [comment]
Thanks for reporting @fenhl - can you post the output of `xonfig`?

**Comment by TeamSpen210** [comment]
If you look at your paths carefully, it seems you have 2 different Pythons there (or at least `site-packages`). That's likely your problem.

**Comment by gforsyth** [comment]
Hey @fenhl, thanks for reporting!  `brew` really likes to install things in sandboxes, so `xonsh` lives in its own python environment when you install it with `brew`.  You have installed `prompt_toolkit` into your "main" python install, but not where `xonsh` can see it.  You can use the `xpip` alias to ensure that you are installing packages into the same environment where `xonsh` resides, e.g.

```console
xpip install prompt_toolkit
```

**Comment by fenhl** [comment]
That did the trick, thanks!
