### ISSUE TITLE
xonsh crashes on startup due prompt-toolkit 2.0 refactoring

### ISSUE THREAD

**Issue by apkraft** [xonsh/xonsh#2662]
prompt-toolkit version 2.0 includes a big refactoring of the internal architecture: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG

and xonsh can't work with it:

Last login: Tue Jun  5 10:55:59 on ttys000
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20731, in main
    args = premain(argv)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20684, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20636, in start_services
    builtins.__xonsh_shell__ = Shell(execer=execer, **shell_kwargs)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13145, in __init__
    from xonsh.ptk.shell import PromptToolkitShell as shell_class
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 6, in <module>
    from prompt_toolkit.key_binding.manager import KeyBindingManager
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.manager'
Xonsh encountered an issue during launch
Failback to /bin/bash
bash-3.2$

**Comment by scopatz** [comment]
Thanks for mentioning. There is a PR open to address this at #2570

**Comment by scopatz** [comment]
For now, please install ptk v1.x

**Comment by komuw** [comment]
> For now, please install ptk v1.x
for anyone else who comes to this issue and doesn't know what ptk is, it is `prompt-toolkit` 
and downgrading it to version 1.0.15 fixed it for me; https://pypi.org/project/prompt_toolkit/1.0.15/

**Comment by gforsyth** [comment]
Resolved in #2716
