### ISSUE TITLE
Exception on startup after updating to 0.6.7 (pygments_cache)

### ISSUE THREAD

**Issue by nilehmann** [xonsh/xonsh#2692]
After updating to 0.6.7 (form AUR) I get the following exception on startup.

```python
pygments cache not found, building...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20794, in main
    return main_xonsh(args)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20820, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 153, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 82, in singleline
    self.styler.style_name = env.get('XONSH_COLOR_STYLE')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14930, in styler
    self._styler = XonshStyle(env.get('XONSH_COLOR_STYLE'))
  File "/usr/lib/python3.6/site-packages/xonsh/pyghooks.py", line 410, in __init__
    self.style_name = style_name
  File "/usr/lib/python3.6/site-packages/xonsh/pyghooks.py", line 434, in style_name
    self._smap = get_style_by_name(value)().styles.copy()
  File "/usr/lib/python3.6/site-packages/xonsh/pygments_cache.py", line 377, in get_style_by_name
    load_or_build()
  File "/usr/lib/python3.6/site-packages/xonsh/pygments_cache.py", line 279, in load_or_build
    CACHE = build_cache()
  File "/usr/lib/python3.6/site-packages/xonsh/pygments_cache.py", line 227, in build_cache
    cache['lexers'] = _discover_lexers()
  File "/usr/lib/python3.6/site-packages/xonsh/pygments_cache.py", line 103, in _discover_lexers
    for longname, aliases, filenames, mimetypes in get_all_lexers():
  File "/usr/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/usr/lib/python3.6/site-packages/pygments/plugin.py", line 52, in find_plugin_lexers
    for entrypoint in iter_entry_points(LEXER_ENTRY_POINT):
  File "/usr/lib/python3.6/site-packages/pygments/plugin.py", line 49, in iter_entry_points
    return pkg_resources.iter_entry_points(group_name)
TypeError: 'NoneType' object is not callable
Xonsh encountered an issue during launch
```

**Comment by gforsyth** [comment]
Thanks for reporting, @nilehmann!  
I'm on pygments 2.2.0 on current master and can't seem to reproduce the error.

**Comment by scopatz** [comment]
Thanks for reporting @nilehmann! I have seen this on one of my machines once. It seems to happens if the pygments cache file does not exist on xonsh startup.  That is interesting that downgrading to pygments 2.1.3 fixes it.

**Comment by nilehmann** [comment]
I upgraded Pygments back to 2.2.0 and everything appears to be working correctly, so probably as  @scopatz commented, after successfully creating the cache file with 2.1.3 I can use 2.2.0 without problems.

**Comment by scopatz** [comment]
haha well that is annoying!

**Comment by dugres** [comment]
I have the issue on Fedora 29 with Xonsh 0.8.3
I don't have the problem on Manjaro nor on Ubuntu.

**Comment by scopatz** [comment]
@dugres - are you still experiencing this issue?

**Comment by dugres** [comment]
@scopatz I reopened the issue in #2944.
The fix proposed by @matheus2740 woks.
But I don't get it. I though #2695 would have fixed this issue ... and why does the issue only appears on Fedora (among the distros I've tested) ?

**Comment by scopatz** [comment]
What does  `xonfig` say on Fedora?

**Comment by scopatz** [comment]
A recent version of pygments just came out (v2.3.1). Does this still happen with that version?

**Comment by dugres** [comment]
Yes
```
+------------------+---------------------+
| xonsh            | 0.8.3               |
| Git SHA          | 07eb341c            |
| Commit Date      | Nov 6 07:39:16 2018 |
| Python           | 3.7.1               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 2.0.7               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.3.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | fedora              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```
this works, cool.
but,
as does this
```
+------------------+---------------------+
| xonsh            | 0.8.3               |
| Git SHA          | 07eb341c            |
| Commit Date      | Nov 6 07:39:16 2018 |
| Python           | 3.7.1               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.7               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | manjaro             |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```
and this (ubuntu)
```
+------------------+----------------------+
| xonsh            | 0.8.6                |
| Git SHA          | e0d3552e             |
| Commit Date      | Dec 21 05:15:39 2018 |
| Python           | 3.6.7                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.7                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```
weird ...

**Comment by scopatz** [comment]
Hmm that is very weird

**Comment by RomuloPBenedetti** [comment]
It don't worked for me even with Pygments 2.1.3, so it occurred to me it could be the theme. I tried changing it to `solarizeddark` and it worked with Pygment 2.3.1.

```Python
$XONSH_COLOR_STYLE = 'solarizeddark'
```

Having no `$XONSH_COLOR_STYLE` set in `.xonshrc` is not working for me, is there a default?
