### ISSUE TITLE
Piping cat to grep no longer works (in WSL, unsure if others)

### ISSUE THREAD

**Issue by battaglia01** [xonsh/xonsh#2698]
I'm using xonsh 0.6.8 in WSL (Ubuntu on Windows), and the following causes an error. Unsure if this is only on WSL as I won't have the chance to test on my KDE Neon install for a bit.

I set $XONSH_SHOW_TRACEBACK = True on before doing this, but this env variable has nothing to do with the error.

```
~ $ echo "abc\ndef\nghi" > test
~ $ cat test | grep def
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 12458, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19135, in run
    p = self._run_binary(kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19145, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 11250, in __init__
    **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1552, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn
```

**Comment by gforsyth** [comment]
Thanks for reporting @battaglia01 !  This isn't effecting me on arch on current master so it may be a WSL-specific thing.  Can you please post the output of `xonfig`?

And if you start xonsh in debug mode and trigger the error again we'll get a more useful traceback (since debug mode disables amalgamation).  To start debug mode, from bash or from a previous xonsh session you can run 

```
env XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=True xonsh
```

(not sure if WSL has `env` -- if not you can just set those env-vars in the parent shell session and then run `xonsh`)

**Comment by battaglia01** [comment]
OK, tried doing the above. I actually got an error this time just when typing the first echo command:

```
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
prompt: error: on field 'branch_color'
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1098, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['hg', 'identify', '--id']' timed out after 0.1 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/prompt/base.py", line 82, in _get_field_value
    value = field_value() if callable(field_value) else field_value
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/prompt/vc.py", line 228, in branch_color
    dwd = dirty_working_directory()
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/prompt/vc.py", line 219, in dirty_working_directory
    dwd = hg_dirty_working_directory()
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/prompt/vc.py", line 202, in hg_dirty_working_directory
    env=denv)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 697, in run
    process.kill()
  File "/usr/lib/python3.5/subprocess.py", line 1787, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.5/subprocess.py", line 1777, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
mike@MIKESURFACE ~(ERROR:branch_color) $
```

Upon running the echo command a second time, it worked. But then after running it a few more times, I would randomly get errors (different from the above):

```
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 330, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 881, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 817, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1776, in __init__
    if update_fg_process_group(pipeline_group, background):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1710, in update_fg_process_group
    return give_terminal_to(pipeline_group)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/jobs.py", line 147, in give_terminal_to
    os.tcsetpgrp(FD_STDERR, pgid)
PermissionError: [Errno 1] Operation not permitted
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 330, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 881, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 817, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1776, in __init__
    if update_fg_process_group(pipeline_group, background):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1710, in update_fg_process_group
    return give_terminal_to(pipeline_group)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/jobs.py", line 147, in give_terminal_to
    os.tcsetpgrp(FD_STDERR, pgid)
PermissionError: [Errno 1] Operation not permitted
mike@MIKESURFACE ~ $
```

Upon doing the original test, I got this error:

```
mike@MIKESURFACE ~ $ echo "abc\ndef\nghi" > test
mike@MIKESURFACE ~ $ cat test | grep def
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1767, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 502, in run
    p = self._run_binary(kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 512, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 559, in __init__
    **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1552, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
```

And this happens every time I pipe `cat` to `grep` -- or pipe it to anything. See below:

```
mike@MIKESURFACE ~ $ cat test | asdfasdfasdf
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1767, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 502, in run
    p = self._run_binary(kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 512, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 559, in __init__
    **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1552, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
```

In fact, now I'm getting an error every time I use the pipe at all:

```
mike@MIKESURFACE ~ $ ls | sadf
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1767, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 502, in run
    p = self._run_binary(kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 512, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 559, in __init__
    **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1552, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
mike@MIKESURFACE ~ $ echo "lol" | asdjkflalsjkdflaksdfhjlka
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1767, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 502, in run
    p = self._run_binary(kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 512, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 559, in __init__
    **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1552, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
```

Sometimes I get a slightly different error, randomly, just while running `cat`:

```
mike@MIKESURFACE ~ $ cat test
abc
def
ghi
mike@MIKESURFACE ~ $ cat test
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 330, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 881, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 817, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1776, in __init__
    if update_fg_process_group(pipeline_group, background):
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/proc.py", line 1710, in update_fg_process_group
    return give_terminal_to(pipeline_group)
  File "/home/mike/.local/lib/python3.5/site-packages/xonsh/jobs.py", line 147, in give_terminal_to
    os.tcsetpgrp(FD_STDERR, pgid)
PermissionError: [Errno 1] Operation not permitted

mike@MIKESURFACE ~ $ cat test
abc
def
ghi
mike@MIKESURFACE ~ $
```

Anyway, hopefully that's useful.

**Comment by Droggelbecher** [comment]
Same problem here with 0.7.0 (just installed via pip) on WSL, eg with "convert|less" (to see the help).
xonfig:

```
$ convert|less
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 12477, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 19174, in run
    p = self._run_binary(kwargs)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 19184, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1345, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
 $ xonfig
+------------------+----------------------+
| xonsh            | 0.7.0                |
| Git SHA          | 3779e8b5             |
| Commit Date      | Jul 14 14:40:04 2018 |
| Python           | 3.6.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | readline             |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by scopatz** [comment]
Thanks for letting us know! This defintiely seems to a WSL issue.  I cannot reproduce it on my ubuntu box. I am not sure I have a great way to debug this, but maybe I can help you.  Or perhaps @melund has some thoughts?

**Comment by tamuhey** [comment]
I also use WSL and same problem occurred.
However I changed the [line](https://github.com/xonsh/xonsh/blob/1855e60e4b2f2d779a6e17b73af183e507bbfca9/xonsh/built_ins.py#L582)  as follows, the problem didn't occur.
```
 if pipeline_group is None:
            xonsh_preexec_fn = no_pg_xonsh_preexec_fn
        else:

            def xonsh_preexec_fn():
                """Preexec function bound to a pipeline group."""
                os.setpgid(0, pipeline_group)
                signal.signal(signal.SIGTSTP, default_signal_pauser)
```
↓
```
xonsh_preexec_fn = no_pg_xonsh_preexec_fn
```

Is this a proper solution?

**Comment by scopatz** [comment]
Hi @tamuhey - thanks for looking into this and sorry for the slow response! Would you please put in a PR for that code?

**Comment by tamuhey** [comment]
Hi @scopatz - thanks for reply!
I put a PR #2969

**Comment by scopatz** [comment]
excellent thanks!

**Comment by scopatz** [comment]
Is this closable now?

**Comment by Droggelbecher** [comment]
Sorry didnt notice the progress :-) will check w/ wsl today or tomorrow

**Comment by Droggelbecher** [comment]
Problem still exists with latest master on WSL:



```
~/repos/xonsh$ env XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=True build/scripts-3.6/xonsh                               ~/repos/xonsh master $ echo "abc\ndef\nghi" > test                                                                                   
~/repos/xonsh master $ cat test \| grep def 
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE =                                                    Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/xonsh/base_shell.py", line 328, in default
run_compiled_code(code, self.ctx, None, 'single')
File "/usr/lib/python3/dist-packages/xonsh/codecache.py", line 68, in run_compiled_code                                                      func(code, glb, loc)
File "", line 1, in
File "/usr/lib/python3/dist-packages/xonsh/built_ins.py", line 877, in subproc_captured_hiddenobject                                                                          return run_subproc(cmds, captured='hiddenobject')
File "/usr/lib/python3/dist-packages/xonsh/built_ins.py", line 813, in run_subproc                                                                           command = HiddenCommandPipeline(specs)
File "/usr/lib/python3/dist-packages/xonsh/proc.py", line 1767, in __init__                                                                                                                                             proc = spec.run(pipeline_group=pipeline_group)
File "/usr/lib/python3/dist-packages/xonsh/built_ins.py", line 502, in run 
p = self._run_binary(kwargs)
File "/usr/lib/python3/dist-packages/xonsh/built_ins.py", line 512, in _run_binary
p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
File "/usr/lib/python3/dist-packages/xonsh/proc.py", line 559, in __init__                                            **kwargs) 
File "/usr/lib/python3.6/subprocess.py", line 709, in __init__                                                             restore_signals, start_new_session)
File "/usr/lib/python3.6/subprocess.py", line 1345, in _execute_child
raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
```
And then it seems to hang forever, with one cpu core being at 100%.
```

$ xonfig
+------------------+-----------------+  
\| xonsh            \| 0.6.0           \|
\| Python           \| 3.6.7           \|
\| PLY              \| 3.11            \|
\| have readline    \| True            \|  
\| prompt toolkit   \| 2.0.7           \| 
\| shell type       \| readline        \|   
\| pygments         \| 2.2.0           \|         
\| on posix         \| True            \| 
\| on linux         \| True            \|                                                                                                                                                                                \| distro           \| Ubuntu          \| 
\| on darwin        \| False           \|                                                                                                                                                                                \| on windows       \| False           \|
\| on cygwin        \| False           \|                                                                                                                                                                                \| is superuser     \| False           \|
\| default encoding \| utf-8           \|  
\| xonsh encoding   \| utf-8           \|
\| encoding errors  \| surrogateescape \| 
+------------------+-----------------+

```
PS: Sorry for any potential copy/paste messups my WSL terminal seems to to copy-pasting a bit weirdly so i had to manually separate the lines

**Comment by tamuhey** [comment]
@Droggelbecher Please hit the below commands, and show me the stdout.

```bash
$ python
>>> import platform
>>> platform.release()
```

**Comment by ExileInParadise** [comment]
<DarylMode>
Some folks would see this "bug" as a feature since cat <file> | grep <foo> is a wasteful and unnecessarily redundant way to do things in the shell when compared to simply using  grep <foo> <file>

I could see a snarkier version of xonsh saying "hey they catgrepper, did you know you could just grep by itself and save some cats?" as a helpful note from the AST parser...
</DarylMode>

**Comment by ExileInParadise** [comment]
DarylMode:
Some folks would see this "bug" as a feature since cat file | grep foo is a wasteful and unnecessarily redundant way to do things in the shell when compared to simply using grep foo file

I could see a snarkier version of xonsh saying "hey they catgrepper, did you know you could just grep foo file by itself and save some cats? Just a helpful note from your friendly AST parser..."
End DarylMode

**Comment by Droggelbecher** [comment]
@tamuhey Sorry for the huge delay, here you go

```
$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.release()
'4.4.0-17134-Microsoft'
>>>
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.release()
'4.4.0-17134-Microsoft'
>>>
```
@ExileInParadise to avoid a potential confusion here: This problem is not at all limited to cat & grep. These just easiest to use to test/illustrate the problem

**Comment by ExileInParadise** [comment]
@Droggelbecher no worries, I was just being silly anyway - really loving xonsh and happy to see people really digging into it - and that catgrep caught my eye along the way. Also watching because I've been telling people at work about WSL and we're a Python shop so xonsh on WSL is a keen interest to me.

**Comment by scopatz** [comment]
Is this still a problem on more recent versions of xonsh?

**Comment by anki-code** [comment]
Closed because no new reports with examples.
