### ISSUE TITLE
python 3.6 f'{blah}' works?

### ISSUE THREAD

**Issue by nbecker** [xonsh/xonsh#2707]
Is there a problem with f'{}' syntax?

$[./plot_results_vs_esno2.py @(f'{dir}.pickle') --out @(f'{dir}.pdf')] 

SyntaxError: ./read_and_plot:13:32: ("code: '{dir}.pickle'",)
$[./plot_results_vs_esno2.py @(f'{dir}.pickle') --out @(f'{dir}.pdf')] # --excel ${@:2}]
                                ^

**Comment by gforsyth** [comment]
Hey @nbecker, we do support f-strings.  Can you post the output of `xonfig`?  Are you running xonsh on Python 3.6+?

**Comment by nbecker** [comment]
like this?
 python3 /home/nbecker/.local/lib/python3.6/site-packages/xonsh/xonfig.py
Traceback (most recent call last):
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/xonfig.py",
line 4, in <module>
    import ast
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/ast.py",
line 6, in <module>
    from ast import (
ImportError: cannot import name 'Module'

**Comment by gforsyth** [comment]
Sorry, I was unclear about that.  You can run `xonfig` from the xonsh prompt and it will print out some info about your install and system.  And can you wrap code outputs in triple backticks? (`) it helps with formatting and makes it easier to read.  Thanks!

**Comment by nbecker** [comment]
Here's a simple test:
```
#!/usr/bin/env xonsh
# -*- mode: python; coding: utf-8 -*-

$[ls @(f'-l')]
```
output:
```
./test_xonsh 
Traceback (most recent call last):
  File "/home/nbecker/.local/bin/xonsh", line 3, in <module>
    main()
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/main.py", line 341, in main
    _failback_to_other_shells(args, err)
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/main.py", line 305, in _failback_to_other_shells
    raise err
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/main.py", line 339, in main
    return main_xonsh(args)
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/main.py", line 381, in main_xonsh
    loc=None, mode='exec')
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/codecache.py", line 160, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/codecache.py", line 119, in compile_code
    filename=filename)
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/execer.py", line 110, in compile
    transform=transform)
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/execer.py", line 79, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/execer.py", line 179, in _parse_ctx_free
    raise original_error from None
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/execer.py", line 166, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/parsers/base.py", line 348, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/nbecker/.local/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/nbecker/.local/lib/python3.6/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/nbecker/.local/lib/python3.6/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/parsers/base.py", line 2726, in p_error
    column=p.lexpos))
  File "/home/nbecker/.local/lib/python3.6/site-packages/xonsh/parsers/base.py", line 479, in _parse_error
    raise err
SyntaxError: ./test_xonsh:4:8: ("code: '-l'",)
$[ls @(f'-l')]
        ^
```

**Comment by nbecker** [comment]
```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.5.12              |
| Git SHA          | 8941dfdd            |
| Commit Date      | Jun 7 16:04:39 2017 |
| Python           | 3.6.5               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.15              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | Fedora              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by gforsyth** [comment]
Ahh, ok, current release is `0.6.9` -- if you upgrade xonsh to the latest release you should have f-strings without issue.
