### ISSUE TITLE
find - missing argument to exec unless explicitly put in subprocess mode

### ISSUE THREAD

**Issue by battaglia01** [xonsh/xonsh#2709]
In bash:

```
$ find . -exec echo lol \;
lol
lol
lol
```

In xonsh:
```
$ find . -exec echo lol \;
/usr/bin/find: missing argument to `-exec'
$ find . -exec "echo lol \;"
/usr/bin/find: missing argument to `-exec'
$ find . -exec "echo lol ;"
/usr/bin/find: missing argument to `-exec'
$ find . -exec "echo lol" \;
/usr/bin/find: missing argument to `-exec'
$ find . -exec "echo lol" ;
/usr/bin/find: missing argument to `-exec'
```

But strangely enough, this works

```
$ $[find . -exec echo lol ;]
lol
lol
lol
```

However, things get quite glitchy. This variant causes an error and doesn't even work in explicit subprocess mode:
```
$ find . -exec echo {} ;
........................................................................................ 
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ptk/shell.py", line 137, in _push
    locs=None)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 20015, in compile
    transform=transform)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 19984, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 20084, in _parse_ctx_free
    raise original_error from None
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 20071, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 349, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ply/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ply/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 2760, in p_error
    column=p.lexpos))
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 482, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:7: ('code: -',)
find . -exec echo {} ;
       ^
```

In subprocess mode we get an error at the `{}`, rather than the `-exec`

```
$[find . -exec echo {} ;]
........................................................................................ 
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ptk/shell.py", line 137, in _push
    locs=None)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 20015, in compile
    transform=transform)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 19984, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 20084, in _parse_ctx_free
    raise original_error from None
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 20071, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 349, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ply/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/ply/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 2760, in p_error
    column=p.lexpos))
  File "/usr/local/lib/python3.5/dist-packages/xonsh/parsers/base.py", line 482, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:20: ('code: {',)
$[find . -exec echo {} ;]
                    ^
```

I get similar results trying to use `{}` with awk.

**Comment by battaglia01** [comment]
For the record, these also fail:

```
$ find . -exec "echo lol \;"
/usr/bin/find: missing argument to `-exec'
$ find . -exec "echo lol ;"
/usr/bin/find: missing argument to `-exec'
$ find . -exec "echo lol" \;
/usr/bin/find: missing argument to `-exec'
$ find . -exec "echo lol" ;
/usr/bin/find: missing argument to `-exec'
```

**Comment by gforsyth** [comment]
Hey @battaglia01 -- so in Bash they escape the `;` using a `\`, but in xonsh you want to escape it using quotes, so you can do

```console
find . -exec echo lol ';'
```

**Comment by anki-code** [comment]
The complete answer could be [found on stackoverflow](https://stackoverflow.com/questions/59579274/xonsh-and-rsync-command/64414157#64414157).

@gforsyth please close this issue.
