### ISSUE TITLE
UnboundLocalError: local variable 'complete_style' referenced before assignment

### ISSUE THREAD

**Issue by nasyxx** [xonsh/xonsh#2764]
## xonfig

```
λ xonfig                                                                                                                                                                 
+------------------+---------------------+
| xonsh            | 0.7.3               |
| Git SHA          | 9bbbf07b            |
| Commit Date      | Aug 2 18:08:44 2018 |
| Python           | 3.6.6               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 2.0.4               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | Gentoo Base System  |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | True                |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

## Current Behavior

I have set `$COMPLETIONS_DISPLAY = "single"` and get error. 
Now I change it to `multi` depended on line 73 in `xonsh/ptk2/shell.py`, it works.

I am on GENTOO. xonsh/0.7.3

```
Traceback (most recent call last):
  File "/root/.local/lib64/python3.6/site-packages/xonsh/main.py", line 342, in main
    return main_xonsh(args)
  File "/root/.local/lib64/python3.6/site-packages/xonsh/main.py", line 368, in main_xonsh
    shell.shell.cmdloop()
  File "/root/.local/lib64/python3.6/site-packages/xonsh/ptk2/shell.py", line 158, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/root/.local/lib64/python3.6/site-packages/xonsh/ptk2/shell.py", line 110, in singleline
    'complete_style': complete_style,
UnboundLocalError: local variable 'complete_style' referenced before assignment
Xonsh encountered an issue during launch
Failback to /bin/bash
```

**Comment by scopatz** [comment]
Thanks for reporting @nasyxx!

**Comment by scopatz** [comment]
A potential fix is in #2765, if you would like to try it out!
