### ISSUE TITLE
Error `Bad file descriptor` in `prompt_toolkit/eventloop`

### ISSUE THREAD

**Issue by ghost** [xonsh/xonsh#2790]
If I source a particular file in `rc.xsh` with some function definitions, the characters aren't echoed in the prompt when I type them, but they appear when I press enter and the shell exits with this error:

```bash
saga@arch ~ $ ls
Traceback (most recent call last):
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/main.py", line 343, in main
    return main_xonsh(args)
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/main.py", line 369, in main_xonsh
    shell.shell.cmdloop()
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/ptk/shell.py", line 168, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/ptk/shell.py", line 134, in singleline                                                                                               
    line = self.prompter.prompt(**prompt_args)
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/ptk/shortcuts.py", line 118, in prompt                                                                                               
    eventloop.close()
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 265, in close
    os.close(schedule_pipe[0])
OSError: [Errno 9] Bad file descriptor
Xonsh encountered an issue during launch
Failback to /bin/sh
sh-4.4$ 
```

This is my `rc.xsh` file:

```python

import os, time, sys, re, io
from pathlib import Path

#$XONSH_DEBUG = True
$XONSH_SHOW_TRACEBACK = True
$XONSH_STORE_STDOUT = True

$AUTO_CD = True
$AUTO_PUSHD = 1

$SHELL_TYPE = 'prompt_toolkit'

$XONSH_COLOR_STYLE='paraiso-dark'

$COMPLETIONS_CONFIRM=True

xontrib autojump

$PATH.append("$HOME/.local/bin")
$BASEPATH=$PATH
$HOME='/home/saga'
source-bash $HOME/.env
source-bash $SRC/dotfiles/zsh_custom/aliases.zsh --overwrite-alias
$XONSH=$XDG_CONFIG_HOME+'/xonsh'

for f in g`$XONSH/autoload/*`:
    source @(f)
```

and this is the offending file in autoload directory:

```python

def getChar():
    import tty, sys, termios
    fd = sys.stdin.fileno()
    oldSettings = termios.tcgetattr(fd)
    try:
        tty.setcbreak(fd)
        answer = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, oldSettings)
    return answer

def mke(d):
    mkdir -p @(d)
    cd @(d)

def pql(args):
    pacman -Ql @(args)|awk '{print $2}'|pp_paths -c|less

def d():
    lns = $(dirs|head -10).strip().split()
    for l in range(len(lns)):
        print(l, '---\t---', lns[l])
    i = int(getChar())
    if i in range(len(lns)):
        cd @(lns[i])

```

## xonfig

    +------------------+----------------------+
    | xonsh            | 0.7.6.dev5           |
    | Git SHA          | 837c714a             |
    | Commit Date      | Aug 25 18:35:16 2018 |
    | Python           | 3.7.0                |
    | PLY              | 3.9                  |
    | have readline    | True                 |
    | prompt toolkit   | 1.0.15               |
    | shell type       | prompt_toolkit1      |
    | pygments         | 2.2.0                |
    | on posix         | True                 |
    | on linux         | True                 |
    | distro           | arch                 |
    | on darwin        | False                |
    | on windows       | False                |
    | on cygwin        | False                |
    | on msys2         | False                |
    | is superuser     | False                |
    | default encoding | utf-8                |
    | xonsh encoding   | utf-8                |
    | encoding errors  | surrogateescape      |
    +------------------+----------------------+
    

## Expected Behavior
There shouldn't be any OSError

## Steps to Reproduce
Place the above files at appropriate places, open xonsh and try to run any command.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Hey @gsaga -- thanks for reporting!  Can you try to narrow down which function in the offending file is causing the error to raise?

**Comment by gsaga** [comment]
This is the smallest I could make the file. Removing any definition stops
the error.

**Comment by scopatz** [comment]
Looking at the code, I am pretty sure it is the `getChar()` function that is causing the issues.

**Comment by gsaga** [comment]
Sourcing a file with just the above `getChar` function doesn't cause any trouble. I've tried trimming down the file and the problem disappears if I remove any of the four definitions.

**Comment by scopatz** [comment]
Yeah, actually, now that I am trying it out, I think that the problem might be 

```
source-bash $SRC/dotfiles/zsh_custom/aliases.zsh --overwrite-alias
```

What is the content of `aliases.zsh`?  And is there are reason that you are using `source-bash` and not using `source-zsh`?

**Comment by gsaga** [comment]
This is the file being sourced:
https://github.com/gsaga/dotfiles/blob/master/zsh_custom/aliases.zsh

Though it doesn't seem to cause any problems. Everything runs fine if I remove the four function definitions.

**Comment by scopatz** [comment]
I think that there is definitively some weird alias override issue going on give what is in https://github.com/gsaga/dotfiles/blob/master/xonsh/autoload/functions.xsh

**Comment by scopatz** [comment]
In your xonshrc can you `print(aliases)` so we can see what is going on?  Also, can you try just not registering one or two of the functions in that file as aliases so we can narrow down which one is causing the problem?

**Comment by scopatz** [comment]
@gsaga  - that could be one probkem. 

None of this looks wrong, @gsaga. Do you know yet whether it is `mke`, `pql` or `d` that is causing problems.

**Comment by gsaga** [comment]
@scopatz I've tried it again and the shell fails with this traceback:

$                                                                                               
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt                                                                                               
    document = cli.run(reset_current_buffer=False)
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 91, in run
    self.add_reader(stdin, read_from_stdin)
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 275, in add_reader                                                                                             
    self.selector.register(fd)
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/eventloop/select.py", line 75, in register                                                                                               
    sel.register(fd)
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/eventloop/select.py", line 130, in register                                                                                              
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/usr/lib/python3.7/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 21068, in main
    return main_xonsh(args)
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 21094, in main_xonsh                                                                                           
    shell.shell.cmdloop()
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/ptk/shell.py", line 168, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/ptk/shell.py", line 134, in singleline                                                                                               
    line = self.prompter.prompt(**prompt_args)
  File "/home/saga/.local/lib/python3.7/site-packages/xonsh/ptk/shortcuts.py", line 118, in prompt                                                                                               
    eventloop.close()
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 266, in close
    os.close(schedule_pipe[1])
OSError: [Errno 9] Bad file descriptor
Xonsh encountered an issue during launch
Failback to /bin/sh
sh-4.4$ R

If these two files are being sourced in `rc.xsh`:

https://github.com/gsaga/dotfiles/blob/master/xonsh/autoload/functions.xsh

https://github.com/gsaga/dotfiles/blob/master/xonsh/autoload/err.xsh

They have some of the same function definitions but that shouldn't cause the shell to crash.

@scopatz Are you able to reproduce this error? 
Let me know if you need more info...

**Comment by scopatz** [comment]
Hmm So when I try to load from your rc file, I don't get the error that you are seeing, but I do have some kind of crazy run-away CPU / memory leak that eat up 100% and can crash my computer.  Not sure which command it is yet.

**Comment by scopatz** [comment]
Ok, I had to change the `source-bash $HOME/.env` line of the rc.xsh file to say the following to get it to run normally

```sh
source-bash $HOME/.env -p "set -ex" -s True
```
