### ISSUE TITLE
cross-reference an issue that seems to maybe be a xonsh issue

### ISSUE THREAD

**Issue by sbillinge** [xonsh/xonsh#2799]
This xonsh error occurs when trying to validate a regolith database:

https://github.com/Billingegroup/rg-db-public/issues/110

**Comment by CJ-Wright** [comment]
I think the main part that is important is:
```python
Traceback (most recent call last):
  File "C:/Users/simon/Anaconda3/envs/bg/Scripts/regolith", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "C:\Users\simon\dev\regolith\scripts\regolith", line 3, in <module>
    main()
  File "c:\users\simon\dev\regolith\regolith\main.py", line 254, in main
    CONNECTED_COMMANDS[rc.cmd](rc)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 186, in connect
    dump_database(db, client, rc)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 139, in dump_database
    dump_git_database(db, client, rc)
  File "c:\users\simon\dev\regolith\regolith\database.xsh", line 98, in dump_git_database
    subprocess.check_call(cmd, cwd=dbdir)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\lib\subprocess.xsh", line 20, in check_call
    p = run(cmd, cwd=cwd, check=True)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\lib\subprocess.xsh", line 14, in run
    p = ![@(cmd)]
  File "C:\Users\simon\Anaconda3\envs\bg\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 16338, in swap
    if exception is not None:
UnboundLocalError: local variable 'exception' referenced before assignment
```

**Comment by sbillinge** [comment]
@CJ-Wright found some freakiness.  It seems that exception is defined on line 927 in ``environ.py`` which is before the if if ``exception is not None:`` crash on line 939.

**Comment by gforsyth** [comment]
What's the output of your `xonfig` @sbillinge ?  This may have been fixed already by #2797

**Comment by anki-code** [comment]
Hi @sbillinge! Does this issue still actual? If no please close then.

**Comment by sbillinge** [comment]
sorry, yes, this issue was closed.  Closing this cross-reference.
