### ISSUE TITLE
Environment variables inside f-strings

### ISSUE THREAD

**Issue by MrQubo** [xonsh/xonsh#2822]
It's hard to describe what the exact bug is. See the _Additional info_ section below.

## xonfig
```
+------------------+-----------------+
| xonsh            | 0.7.8           |
| Python           | 3.7.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | prompt_toolkit1 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior
It's a correct code, so it shouldn't cause the SyntaxError.

## Current Behavior
It causes the following SyntaxError (with `XONSH_DEBUG=1`):
```
  File "<string>", line None
SyntaxError: /home/arch/.local/lib/python3.7/site-packages/xontrib/prompt_vi_mode.xsh:1:21: ('code: ]',)
[f'{$HOME}', $PWD, '']
                     ^
```

## Steps to Reproduce
Just type `[f'{$HOME}', $PWD, '']` in the prompt.

### General problem with environment variables inside f-strings
Typing `f'{$HOME}'` inside the prompt doesn't trigger the SyntaxError, but the result isn't printed under the prompt as usual. `print(f'{$HOME}')` doesn't output anything as well.
e.g.
```
   f'{$HOME}s'                       
   print(f'{$HOME}s')      
                               
```

If I try to save the result inside the variable it seems to have no effect at all.
e.g.
```
   y = f'{$HOME}'                    
   y                                                
xonsh: subprocess mode: command not found: y
Did you mean one of the following?
    z:  Alias
    X:  Command (/usr/bin/X)
    w:  Command (/usr/bin/w)
    [:  Command (/usr/bin/[)
    R:  Command (/usr/bin/R)
   print(y)                                    
NameError: name 'y' is not defined
```
```
   y = 42                 
   y = f'{$HOME}'        
   print(y)            
42     
```

Instead of `f'{$HOME}'` one of the following can be used and the behavior will be the same. They don't trigger the SyntaxError as well.
```
[f'{$HOME}', '']

[f'{$HOME}', $PWD]
```

### Examples of working code
Following are the examples of code that __does__ work as expected:
```
x=2; [f'{x}', $PWD, '']

['{$HOME}', $PWD, '']
```

The first one uses f-string and evaluates normal python code inside it.
The second one doesn't involve f-strings at all.

### Another issue with f-strings
It seems there are problems with f-strings in general too. While using them I've run into the following error several times. I've found out it is triggered every time by typing `f""`, without pressing <kbd>Enter</kbd>.
```
   f""Exception in thread Thread-2566:    
Traceback (most recent call last):                                                                                                                                    
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner                                                                                               
    self.run()                                                                                                                                                        
  File "/usr/lib/python3.7/threading.py", line 865, in run                                                                                                             
    self._target(*self._args, **self._kwargs)                                                                                                                         
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/interface.py", line 865, in run                                                                                
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.7/site-packages/xonsh/ptk/completer.py", line 45, in get_completions
    prefix, line_ex, begidx + expand_offset, endidx + expand_offset, self.ctx
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 125, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/usr/lib/python3.7/site-packages/xonsh/completers/__amalgam__.py", line 1274, in complete_path
    p = _path_from_partial_string(line, end)
  File "/usr/lib/python3.7/site-packages/xonsh/completers/__amalgam__.py", line 1064, in _path_from_partial_string
    val = ast.literal_eval(_string)
  File "/usr/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.JoinedStr object at 0x7f82d1549d68>
```

**Comment by MrQubo** [comment]
## My thoughts
The f-strings are currently handled [here](https://github.com/xonsh/xonsh/blob/fd448e515a36cf23a4f03f4e6b16c9dd227196b7/xonsh/parsers/base.py#L2332-L2335). It seems like the f-string is parsed with regular python parser.

The `val = ast.literal_eval(_string)` in the second bug seems like another place where the string is evaluated with normal python parser instead of our xonshy one.

**Comment by scopatz** [comment]
Hi @MrQubo thanks for reporting - that is weird about the `f""` issue.  Can you please open a separate issue for that.  I can't reproduce it, but I am on Python v3.6 and using readline and PTK v2.  I suspect this is either an issue with Python v3.7 or PTK v1.

It seems like what is needed here is to extend the f-string execution context to include the environment and also extend the string minilanguage to include parsing the `$` to know to look up the variable name in the environment.  I think I see a relatively easy fix, though.

**Comment by laloch** [comment]
@scopatz I can confirm the completer exception with PTK1. It doesn't trigger with readline.

**Comment by scopatz** [comment]
Ahh thanks @laloch! If it is really a PTK v1 bug, I think xore is unlikely to fix it because PTK v1 is deprecated. But we'd happily take a PR that fixes it :wink:

**Comment by scopatz** [comment]
Potential implementation in #2829

**Comment by laloch** [comment]
The completer exception seems to be caused by the fact that `ast.literal_eval(...)` does not support f-strings (`_ast.JoinedStr`) at all. It was always like that ever since the f-strings were introduced regardless of the Python version.

**Comment by scopatz** [comment]
Something funny is going on, though,. Because this doesn't happen on python 3.6 and ptk v2

**Comment by laloch** [comment]
@scopatz C'mon... ;)
```
liveuser@localhost-live ~ $ xonfig                                                                                       
+------------------+----------------------+
| xonsh            | 0.7.9                |
| Git SHA          | 78cc725f             |
| Commit Date      | Sep 18 14:34:16 2018 |
| Python           | 3.6.5                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 2.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Fedora               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

Unhandled exception in event loop:
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1637, in new_coroutine
    yield From(coroutine(*a, **kw))
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1495, in async_completer
    cancel=lambda: not proceed()))
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/async_generator.py", line 114, in consume_async_generator
    item = iterator.send(send)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 166, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk2/completer.py", line 45, in get_completions
    prefix, line_ex, begidx + expand_offset, endidx + expand_offset, self.ctx
  File "/usr/local/lib/python3.6/site-packages/xonsh/completer.py", line 36, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/usr/local/lib/python3.6/site-packages/xonsh/completers/path.py", line 269, in complete_path
    p = _path_from_partial_string(line, end)
  File "/usr/local/lib/python3.6/site-packages/xonsh/completers/path.py", line 59, in _path_from_partial_string
    val = ast.literal_eval(_string)
  File "/usr/lib64/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib64/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))

Exception malformed node or string: <_ast.JoinedStr object at 0x7fad1afb6320>
Press ENTER to continue...                                                                                               
liveuser@localhost-live ~ $ f""
```

**Comment by scopatz** [comment]
Very weird.  Here is mine, which executes successfully:

```
scopatz@artemis ~/temp $ xonfig                                                                                                                  
+------------------+----------------------+
| xonsh            | 0.7.9.dev4           |
| Git SHA          | e92cb2ee             |
| Commit Date      | Sep 21 09:15:25 2018 |
| Python           | 3.6.6                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | debian               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
scopatz@artemis ~/temp $ f""                                                                                                                     
''
```

**Comment by laloch** [comment]
You just need to hit <tab> instead of <return> at the end of the line in order to trigger the completer.

**Comment by laloch** [comment]
grrr, hit TAB instead of RETURN...

**Comment by laloch** [comment]
And, btw, `$UPDATE_COMPLETIONS_ON_KEYPRESS=True` also does the trick.

**Comment by scopatz** [comment]
Oh yeah! I see this now.

**Comment by scopatz** [comment]
@laloch @MrQubo  - OK I have a potential bugfix for the TAB issue in #2832
