### ISSUE TITLE
AttributeError str has no attribute value

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#2844]
Running the latest master (fe2a1c320) of xonsh, I see this error when attempting to invoke any command or even change directory:

```
~ $ /usr/bin/zsh                                                                                  
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 164, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/execer.py", line 132, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/execer.py", line 93, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/execer.py", line 214, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/parsers/base.py", line 520, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/parsers/base.py", line 3232, in p_subproc_arg_part
    p[0] = ast.Str(s=p1.value, lineno=p1.lineno, col_offset=p1.lexpos)
AttributeError: 'str' object has no attribute 'value'
```

Rolling back to latest 0.7.9 release corrects the issue.

## xonfig

(crashes with the same error), but after rolling back:

```table
+------------------+----------------------+
| xonsh            | 0.7.9                |
| Git SHA          | 78cc725f             |
| Commit Date      | Sep 18 14:34:16 2018 |
| Python           | 3.7.0                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 2.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

## Expected Behavior

Shouldn't crash.

## Current Behavior

Adding DEBUG mode did change the traceback noticeably.

**Comment by jaraco** [comment]
On further investigation, I found the issue wasn't with a particular revision of xonsh, but with the local working copy I had. After running `git clean -fdx`, which removed several artifacts:

```
$ git clean -fdx
Removing xonsh.egg-info/
Removing xonsh/__pycache__/
Removing xonsh/dev.githash
Removing xonsh/parser.out
Removing xonsh/parser_table.py
Removing xonsh/parsers/__pycache__/
Removing xonsh/ply/ply/__pycache__/
```

Now installing from source works fine (at 0.7.9 and master). I suspect there's something about running the tests or development that created those parser* files, and their presence when installing impacts the installed version.

Probably nothing to be done here, but wanted to share the error message and workaround.

_Maybe_ xonsh should avoid installing those files when installing from source, but for now I'll just be more careful.

**Comment by scopatz** [comment]
> Maybe xonsh should avoid installing those files when installing from source, but for now I'll just be more careful.

Yeah, this is largely a problem seen by devs who are installing multiple xonsh branches simaltaneously.  The benefit to users is huge, though, because it can shave ~1 sec off of startup time.  So I think it would still be a mistake to not install those files.
