### ISSUE TITLE
Bash completion is badly broken on master

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#2856]
Changes to py-bash-completion are having some unexpected side-effects that we need to fix before a release

## xonfig

```
+------------------+---------------------+
| xonsh            | 0.7.10.dev63        |
| Git SHA          | 2286a598            |
| Commit Date      | Oct 2 08:54:29 2018 |
| Python           | 3.6.5               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.5               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

## Expected Behavior

In a directory with one file `test.xsh`, pressing tab at `vim te` should expand to `vim test.xsh`

## Current Behavior

```
tmp/cleandir 88e2064 $ ls
test.xsh

tmp/cleandir 88e2064 $ vim te<TAB>

Unhandled exception in event loop:
  File "/home/gil/miniconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1637, in new_coroutine
    yield From(coroutine(*a, **kw))
  File "/home/gil/miniconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1495, in async_completer
    cancel=lambda: not proceed()))
  File "/home/gil/miniconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/async_generator.py", line 114, in consume_async_generator
    item = iterator.send(send)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 166, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/ptk2/completer.py", line 45, in get_completions
    prefix, line_ex, begidx + expand_offset, endidx + expand_offset, self.ctx
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/completer.py", line 36, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/completers/bash.py", line 22, in complete_from_bash
    quote_paths=_quote_paths,
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/completers/bash_completion.py", line 377, in bash_completions
    if commprefix[strip_len] == strip_prefix[strip_len]:

Exception string index out of range
Press ENTER to continue...
```

## Steps to Reproduce

```
mkdir empty_dir 
cd empty_dir
touch test.xsh
vim te<TAB>
```

**Comment by gforsyth** [comment]
Temporary workaround for those on the bleeding edge is to `completer remove bash`

**Comment by gforsyth** [comment]
Fix incoming

**Comment by gforsyth** [comment]
ugh -- still hitting errors on this one, I'll try to figure out a few reproducible examples

**Comment by scopatz** [comment]
Ok, I found one example.  Namely, if I try to TAB complete `which`, but have mistyped the command as `whic` and then tab complete the argument.

```console
scopatz@artemis ~/xonsh master $ whih you<TAB>                                                                                                                                          
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20846, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12311, in __init__
    *args, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs
  File "/home/scopatz/miniconda/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/scopatz/miniconda/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'whih': 'whih'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13572, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20836, in run
    p = self._run_binary(kwargs)
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20857, in _run_binary
    raise XonshError(e)
xonsh.__amalgam__.XonshError: xonsh: subprocess mode: command not found: whih
Did you mean one of the following?
    wish:   Command (/home/scopatz/miniconda/bin/wish)
    who:    Command (/usr/bin/who)
    which:  Alias
    chsh:   Command (/usr/bin/chsh)

Command 'whih' not found, did you mean:

  command 'which' from deb debianutils

Try: sudo apt install <deb name>

Unhandled exception in event loop:
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1637, in new_coroutine
    yield From(coroutine(*a, **kw))
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1495, in async_completer
    cancel=lambda: not proceed()))
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/prompt_toolkit/eventloop/async_generator.py", line 114, in consume_async_generator
    item = iterator.send(send)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 166, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/ptk2/completer.py", line 45, in get_completions
    prefix, line_ex, begidx + expand_offset, endidx + expand_offset, self.ctx
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 125, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 1674, in complete_from_bash
    quote_paths=_quote_paths,
  File "/home/scopatz/.local/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 441, in bash_completions
    if commprefix[strip_len] == strip_prefix[strip_len]:

Exception string index out of range
```

**Comment by anki-code** [comment]
I can't repeat this. Looks not actual and should be closed.
