### ISSUE TITLE
and semms to be interpreted inside a path

### ISSUE THREAD

**Issue by jb-leger** [xonsh/xonsh#2900]
Example:

```
jbleger@gertrude ~ $ mkdir -p a/path/and/another/one                                                                           
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: /another/one
```

## xonfig

```
jbleger@gertrude ~ [1] $ xonfig                                                                                                
+------------------+---------------------+
| xonsh            | 0.8.0               |
| Git SHA          | aca294b8            |
| Commit Date      | Oct 7 09:53:16 2018 |
| Python           | 3.6.7               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 2.0.6               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

## Current Behavior
```
jbleger@gertrude:~$ XONSH_DEBUG=1 xonsh
jbleger@gertrude ~ $ cd /tmp/                                                                                                           
jbleger@gertrude /tmp $ mkdir -p a/path/and/another/one                                                                                 
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: /another/one
jbleger@gertrude /tmp [1] $ $XONSH_SHOW_TRACEBACK=True                                                                                  
jbleger@gertrude /tmp $ mkdir -p a/path/and/another/one                                                                                 
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/jbleger/.local/lib/python3.6/site-packages/xonsh/built_ins.py", line 550, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/jbleger/.local/lib/python3.6/site-packages/xonsh/proc.py", line 582, in __init__
    *args, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/another/one': '/another/one'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbleger/.local/lib/python3.6/site-packages/xonsh/proc.py", line 1843, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/jbleger/.local/lib/python3.6/site-packages/xonsh/built_ins.py", line 540, in run
    p = self._run_binary(kwargs)
  File "/home/jbleger/.local/lib/python3.6/site-packages/xonsh/built_ins.py", line 561, in _run_binary
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: /another/one
```

It is a very quick filled bug report, sorry.

**Comment by scopatz** [comment]
Thanks for reporting this @jb-leger! I believe that #2930 should fix this.
