### ISSUE TITLE
Evaluating an expression in $PROMPT seems to mess up the prefab variables

### ISSUE THREAD

**Issue by tankorsmash** [xonsh/xonsh#2971]
New to xonsh, I was trying to add the current time to the `$PROMPT`, so after importing `time`, I tried to append `time.ctime()` to the PROMPT variable. If I do, it throws the following errors, but removing the `time.ctime()` but works fine:

```
>>> $PROMPT = ">{prompt_end}"
>$$PROMPT = '{cwd}\n' + @(time.ctime()) + '{prompt_end}'
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: >{prompt_end}

>$$PROMPT = '{cwd}\n' + '{prompt_end}'
~\Documents\cocos_projects\magnolia_cocos
```

Using colors is the same way, where including the `time.ctime()` call breaks, but removing it from the PROMPT works fine:

```
>$$PROMPT = '{cwd}\n' + '{prompt_end}'
~\Documents\cocos_projects\magnolia_cocos
$$PROMPT = '{BOLD_INTENSE_CYAN}{cwd}{NO_COLOR}\n' + '{prompt_end} ' + @(time.ctime())
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: {cwd}
{prompt_end}

~\Documents\cocos_projects\magnolia_cocos
$$PROMPT = '{BOLD_INTENSE_CYAN}{cwd}{NO_COLOR}\n' + '{prompt_end} '
~\Documents\cocos_projects\magnolia_cocos
$
```

## xonfig

```$ xonfig
+------------------+-----------------------------------------------+
| xonsh            | 0.8.6                                         |
| Git SHA          | e0d3552e                                      |
| Commit Date      | Dec 21 05:15:39 2018                          |
| Python           | 3.6.0                                         |
| PLY              | 3.7                                           |
| have readline    | True                                          |
| prompt toolkit   | 1.0.14                                        |
| shell type       | prompt_toolkit1                               |
| pygments         | 2.2.0                                         |
| on posix         | False                                         |
| on linux         | False                                         |
| on darwin        | False                                         |
| on windows       | True                                          |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x03227530> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x03227750> |
| is superuser     | False                                         |
| default encoding | utf-8                                         |
| xonsh encoding   | utf-8                                         |
| encoding errors  | surrogateescape                               |
+------------------+-----------------------------------------------+
```

## Expected Behavior
I expected to be able to call an external Python expression in the PROMPT, whether it was within a string, or a `@()` expression (although I'm too new to know which one -should- work)

## Current Behavior
Errors seeming as though its executing the entire prompt as a Python string. Here's an example of a XONSH_DEBUG=1 full traceback:

```
$ $PROMPT = '{BOLD_INTENSE_CYAN}{cwd}{NO_COLOR}\n' + '{prompt_end} ' + @(time.ctime())
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\JimothyDaniels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xonsh\built_ins.py", line 553, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "C:\Users\JimothyDaniels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xonsh\proc.py", line 582, in __init__
    *args, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs
  File "C:\Users\JimothyDaniels\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\JimothyDaniels\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JimothyDaniels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xonsh\proc.py", line 1849, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "C:\Users\JimothyDaniels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xonsh\built_ins.py", line 543, in run
    p = self._run_binary(kwargs)
  File "C:\Users\JimothyDaniels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xonsh\built_ins.py", line 564, in _run_binary
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: {BOLD_INTENSE_CYAN}{cwd}{NO_COLOR}
{prompt_end}
```

## Steps to Reproduce
On a fresh `python3 -m pip install xonsh`, then entering with `python3 -m xonsh`, then doing a setup using bash.exe as a parent shell,

```
> import time
> $PROMPT = ... #included above

**Comment by gforsyth** [comment]
Hey @tankorsmash -- welcome to xonsh!  

You can create custom fields  for the prompt by adding them to the `$PROMPT_FIELDS` env-var / dictionary, so for your example, something like:

```
gil@bad_cat ~ $ import time
gil@bad_cat ~ $ $PROMPT_FIELDS['time'] = lambda: time.ctime()                                                           
gil@bad_cat ~ $ $PROMPT += '{time}'                                      
gil@bad_cat ~ $ Mon Dec 24 13:38:52 2018
```

**Comment by tankorsmash** [comment]
Hey @gforsyth, thanks I'll use that!

Going forward, is `$PROMPT` a special case in xonsh where you shouldn't otherwise use expressions like that, or was my syntax off?

**Comment by tankorsmash** [comment]
Thanks for helping me out so thoroughly, I'll read more of [the docs](https://xon.sh/tutorial.html#customizing-the-prompt) to see what it says about the PROMPT as I go.
