### ISSUE TITLE
wait_for_active_job recursion error

### ISSUE THREAD

**Issue by dwjbosman** [xonsh/xonsh#2980]
Hi,
I have a xonsh script. If I run it sometimes (!) I am getting this error:
```
Traceback (most recent call last):
  File "/opt/conda/envs/gdb_ipykernel/lib/python3.6/site-packages/xonsh/jobs.py", line 198, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
ChildProcessError: [Errno 10] No child processes
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/envs/gdb_ipykernel/lib/python3.6/site-packages/xonsh/jobs.py", line 198, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
ChildProcessError: [Errno 10] No child processes
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
```
This recurses until 
"RecursionError: maximum recursion depth exceeded while calling a Python object"

If I look in the code at line 198 of jobs.py, I indeed see a recursion which could result in this behavior. 

```
    def wait_for_active_job(last_task=None, backgrounded=False):
        ....
        try:
            _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
        except ChildProcessError:  # No child processes
            return wait_for_active_job(last_task=active_task, backgrounded=backgrounded)
```
Could this be a bug in xonsh?

**Comment by gforsyth** [comment]
Ahh, Heisenbugs.  My favorite :grimacing: .

Thanks for reporting @dwjbosman -- is it possible for you to share the script (or similar) that causes the issue?  And can you give me a sense of the frequency with which it errors?  50% of the time? 10%?

**Comment by dwjbosman** [comment]
What's the idea behind checking for the exception "ChildProcessError" and then recursively calling "wait_for_active_job"?

Wouldn't it be better to do something like this?

```
    def wait_for_active_job(last_task=None, backgrounded=False):
        """
        Wait for the active job to finish, to be killed by SIGINT, or to be
        suspended by ctrl-z.
        """
        done = False   
        while not done:
            done = True

            _clear_dead_jobs()
            active_task = get_next_task()
            # Return when there are no foreground active task
            if active_task is None:
                return last_task   
            obj = active_task["obj"]
            backgrounded = False
            try: 
                _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
            except ChildProcessError:  # No child processes
                done = False
                last_task = active_task
                time.sleep(0.1)
          .....
```

**Comment by deeuu** [comment]
Hey,

I too am O a similar issue.

Essentially I'm subprocessing in a loop, which eventually leads to a bunch of
```
Traceback (most recent call last):
  File "/home/dominic/dotfiles/venvs/xonsh/.venv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9263, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
ChildProcessError: [Errno 10] No child processes
```

**Comment by scopatz** [comment]
Could you please try v0.8.9 (or later) and report if the current issues are still persisting?  #3000 made some changes that I think might have helped here.

**Comment by deeuu** [comment]
@scopatz Okay started my script and finally run into the same errors:

```
pipenv run xonsh --version
xonsh/0.8.9
```
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9457, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
ChildProcessError: [Errno 10] No child processes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9457, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
ChildProcessError: [Errno 10] No child processes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23269, in _failback_to_other_shells
    raise err
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23303, in main
    return main_xonsh(args)
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23347, in main_xonsh
    args.file, shell.execer, glb=shell.ctx, loc=None, mode="exec"
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2557, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 2462, in run_compiled_code
    func(code, glb, loc)
  File "./scripts/remote_to_remote.xsh", line 145, in <module>
    $(rclone ls @(dest_folder) @(rclone_flags)).splitlines()
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 21586, in subproc_captured_stdout
    return run_subproc(cmds, captured="stdout")
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 21570, in run_subproc
    command.end()
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14096, in end
    self._end(tee_output=tee_output)
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14104, in _end
    for _ in self.tee_stdout():
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14017, in tee_stdout
    for line in self.iterraw():
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13903, in iterraw
    task = wait_for_active_job()
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9459, in wait_for_active_job
    return wait_for_active_job(last_task=active_task, backgrounded=backgrounded)
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9459, in wait_for_active_job
    return wait_for_active_job(last_task=active_task, backgrounded=backgrounded)
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9459, in wait_for_active_job
    return wait_for_active_job(last_task=active_task, backgrounded=backgrounded)
  [Previous line repeated 982 more times]
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9449, in wait_for_active_job
    _clear_dead_jobs()
  File "/home/dominic/.local/share/virtualenvs/ost-rclone-client-transfer-hdWlVtaT/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 9494, in _clear_dead_jobs
    to_remove = set()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Note a pure Python implementation (via subprocess) works fine.

Cheers

**Comment by scopatz** [comment]
I think I have a potential fix in #3004. Can you try it out please? Thanks!

**Comment by deeuu** [comment]
@scopatz I found that 
```
[$(echo @(print(_)) >> bleh.txt) for _ in bleh]
```
where `bleh.txt` is some huge txt file, was enough to reproduce the errors.

But yeah, I've checked out master and it seems good now.

**Comment by scopatz** [comment]
Awesome!

**Comment by scopatz** [comment]
Closing this. Please feel free to reopen if needed
