### ISSUE TITLE
xonsh 0.8.11 fails to sart up with "ValueError: Could not translate ANSI color code"

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3039]
After installing xonsh 0.8.11 freshly into its own venv I got on start-up teh following trace back:

```
Traceback (most recent call last):
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/main.py", line 401, in main
    args = premain(argv)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/main.py", line 352, in premain
    env = start_services(shell_kwargs, args)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/main.py", line 287, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/execer.py", line 62, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/built_ins.py", line 1272, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/built_ins.py", line 1348, in load
    self.env = Env(default_env())
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 1337, in __init__
    self[key] = val
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 1499, in __setitem__
    val = ensurer.convert(val)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 445, in convert
    return cls.fromstring(x)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 408, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/ansi_colors.py", line 268, in ansi_color_escape_code_to_name
    msg.format(escape_code=escape_code, names=names, name=name, n=n)
ValueError: Could not translate ANSI color code '01;05;37;41' into a known color in the palette. Specifically, the 'BOLD_SLOWBLINK_WHITE' portion of 'WHITE' in ['BOLD_', 'SLOWBLINK_', 'WHITE', 'BACKGROUND_RED'] seems to missing.
Xonsh encountered an issue during launch
```

This happens under Python3.6.4 on Centos 6 in a proper XTerm (`TERM=xterm`). Obviously I cannot provide a `xonfig` output... %-\

**Comment by scopatz** [comment]
Thanks for reporting @halloleo - I am working on a fix now

**Comment by scopatz** [comment]
There is a potential fix in #3045, if you'd like to check that out

**Comment by halloleo** [comment]
Thanks heaps @scopatz . I will test it after Monday when I have access to the Centos machine again.

**Comment by halloleo** [comment]
Can confirm, 0.8.12 works fine in my CentOS environment. @scopatz Thanks heaps for fixing this. :-)

**Comment by scopatz** [comment]
No problem!

**Comment by ocelotl** [comment]
Hello, I'm finding a very similar issue in `xonsh-0.8.12`:

```
Traceback (most recent call last):
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 24001, in main
    args = premain(argv)
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23952, in premain
    env = start_services(shell_kwargs, args)
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23887, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23018, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22589, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22665, in load
    self.env = Env(default_env())
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19107, in __init__
    self[key] = val
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19269, in __setitem__
    val = ensurer.convert(val)
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18215, in convert
    return cls.fromstring(x)
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18178, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/home/ocelotl/xonvenv/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 7124, in ansi_color_escape_code_to_name
    msg.format(escape_code=escape_code, names=names, name=name, n=n)
ValueError: Could not translate ANSI color code '3;28' into a known color in the palette. Specifically, the 'ITALIC_28' portion of '28' in ['ITALIC_', '28'] seems to missing.
Xonsh encountered an issue during launch
Failback to /bin/sh
/bin/sh: 1: byobu_prompt_status: not found
/bin/sh: 1: byobu_prompt_symbol: not found
(xonvenv) \[\e[38;5;202m\]\[\e[38;5;245m\]\u\[\e[00m\]@\[\e[38;5;172m\]\h\[\e[00m\]:\[\e[38;5;5m\]\w\[\e[00m\] 
```
I'm running this in a fresh virtual environment that runs Python 3.6.7 in Ubuntu 18.04.2 LTS.

Please let me know if I can provide better information or if I should open a new issue.
