### ISSUE TITLE
Line ending in backslash brings chaos in 0.8.12, was working in 0.8.4

### ISSUE THREAD

**Issue by ndemou** [xonsh/xonsh#3044]
This 3 line script works in 0.8.4:
```
# xonsh --version
xonsh/0.8.4

# cat /tmp/test.bak
echo "test" | \
   cat 
print(1)

# xonsh /tmp/test.bak
test
1
```
but fails with syntax error in 0.8.10,11 & 12 (removing the backslash makes xonsh happy)
```
# xonsh /tmp/test.bak                                                      
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23445, in main
    _failback_to_other_shells(args, err)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23409, in _failback_to_other_shells
    raise err
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23443, in main
    return main_xonsh(args)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23487, in main_xonsh
    args.file, shell.execer, glb=shell.ctx, loc=None, mode="exec"
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 2555, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 2514, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 22532, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 22493, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 22632, in _parse_ctx_free
    raise original_error from None
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 22617, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/usr/local/lib/python3.6/dist-packages/xonsh/parsers/base.py", line 546, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/parsers/base.py", line 3295, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/usr/local/lib/python3.6/dist-packages/xonsh/parsers/base.py", line 679, in _parse_error
    raise err
SyntaxError: /tmp/test.bak:1:5: ('code: "test"',)
echo "test" | \
     ^

```
<details>

## xonfig
```
+------------------+---------------------+
| xonsh            | 0.8.10              |
| Git SHA          | 2cb42bdb            |
| Commit Date      | Feb 6 16:49:16 2019 |
| Python           | 3.6.7               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.8               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | unknown             |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | True                |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+

```

</details>

**Comment by scopatz** [comment]
Thanks for reporting! I believe that this was fixed in 0.8.11

**Comment by ndemou** [comment]
Nope, same backtrace in 0.8.11  

(note to self: _"when you grow up become a bug reporter that doesn't forget to upgrade before filling the reports"_)

Backtrace:
<details>

```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 24007, in main
    _failback_to_other_shells(args, err)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23971, in _failback_to_other_shells
    raise err
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 24005, in main
    return main_xonsh(args)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 24049, in main_xonsh
    args.file, shell.execer, glb=shell.ctx, loc=None, mode="exec"
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 2975, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 2934, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23094, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23055, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23194, in _parse_ctx_free
    raise original_error from None
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 23179, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/usr/local/lib/python3.6/dist-packages/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/parsers/base.py", line 3292, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/usr/local/lib/python3.6/dist-packages/xonsh/parsers/base.py", line 676, in _parse_error
    raise err
SyntaxError: /tmp/test.bak:1:5: ('code: "test"',)
echo "test" | \
     ^
```

</details>

**Comment by ndemou** [comment]
Just a not that this bug is still present in 0.8.12

**Comment by scopatz** [comment]
I am still seeing this error in v0.9.5

**Comment by anki-code** [comment]
I can't repeat this in xonsh 0.9.27.
```python
echo @("""
echo "test" | \
   cat 
print(1)
""") > /tmp/tst
xonsh /tmp/tst
# test
# 1
```
