### ISSUE TITLE
Recently installed xonsh 0.8.11 fails back to sh with KeyError: '9'

### ISSUE THREAD

**Issue by bertolinocastro** [xonsh/xonsh#3046]
I have just installed xonsh from source (0.8.11) in a fresh Deepin 15.9 installation, because the OS's apt repository is pointing to xonsh 0.6.3 yet.

I have tried to install through pip, using python 3.6 and 3.7 `-m pip install .` as well as directly calling the `setup.py` executable for these two python versions.

I also tried to install it through `virtualenv` and I still get the same error.

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24004, in main
    args = premain(argv)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23955, in premain
    env = start_services(shell_kwargs, args)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23890, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23021, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 22592, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 22668, in load
    self.env = Env(default_env())
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 19110, in __init__
    self[key] = val
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 19272, in __setitem__
    val = ensurer.convert(val)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 18218, in convert
    return cls.fromstring(x)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 18181, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 7022, in ansi_color_escape_code_to_name
    short_to_ints(short), background=(fore_back == "BACK"), prefix=pre
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 1268, in short_to_ints
    return rgb_to_ints(short2rgb(short))
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 1199, in short2rgb
    return SHORT_TO_RGB[short]
KeyError: '9'
Xonsh encountered an issue during launch
Failback to /bin/sh
(venv) \[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ 
```

</details>

## Steps to Reproduce
```sh
# inside xonsh source relase 0.8.11
# I also tried these commands below with `sudo`
# as well as inside `virtualenv` pointing to both python versions without `sudo`
python3.6 -m pip install .
python3.7 -m pip install .
pip3 install .
```
```sh
# finally, I tried installing directly from pypi repository and still not working
python3.6 -m pip install xonsh
python3.7 -m pip install xonsh
pip3 install xonsh
```
And then, just trying to execute:
```sh
xonsh
```

**Comment by scopatz** [comment]
Thanks for reporting @bertolinocastro! #3045 should fix this problem

**Comment by bertolinocastro** [comment]
Hi. I just tested the latest commit `19b683f00020c5cb1e147508987499e8fc604273` and that problem went out. However, some new appeared. I think that they can be ridded by just updating the package  versions in `install_requires` at `setup.py`.

The errors:
```
/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
/usr/lib/python3/dist-packages/pygments/lexers/lisp.py:142: DeprecationWarning: invalid escape sequence \(
  ("(?<=\()(%s)" % '|'.join(re.escape(entry) + ' ' for entry in builtins),
/usr/lib/python3/dist-packages/pygments/lexers/lisp.py:324: DeprecationWarning: invalid escape sequence \s
  (r'#+nil' + terminated + '\s*\(', Comment.Preproc, 'commented-form'),
/usr/lib/python3/dist-packages/pygments/lexers/lisp.py:336: DeprecationWarning: invalid escape sequence \*
  (r'\*' + symbol + '\*', Name.Variable.Global),
/usr/lib/python3/dist-packages/pygments/lexers/python.py:183: DeprecationWarning: invalid escape sequence \w
  ('[a-zA-Z_]\w*', Name),
/usr/lib/python3/dist-packages/pygments/lexers/python.py:269: DeprecationWarning: invalid escape sequence \!
  '(\![sra])?'                       # conversion
/usr/lib/python3/dist-packages/pygments/lexers/python.py:270: DeprecationWarning: invalid escape sequence \:
  '(\:(.?[<>=\^])?[-+ ]?#?0?(\d+)?,?(\.\d+)?[E-GXb-gnosx%]?)?'
/usr/lib/python3/dist-packages/pygments/lexers/python.py:271: DeprecationWarning: invalid escape sequence \}
  '\}', String.Interpol),
/usr/lib/python3/dist-packages/pygments/lexers/jvm.py:260: DeprecationWarning: invalid escape sequence \d
  letter_letter_digit = u'%s(?:%s|\d)*' % (letter, letter)
/usr/lib/python3/dist-packages/pygments/lexers/ruby.py:407: DeprecationWarning: invalid escape sequence \?
  '|>> |\?> ')
```

After that, I did `sudo python3.7 -m pip install --upgrade pygments` and almost all went out but the first one. I'll try to update other packages and write here if I couldn't clean these errors.

```
/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
```

Many thanks for you quickly response!

**Comment by scopatz** [comment]
Hi @bertolinocastro - what is the output of the `xonfig` command?

**Comment by bertolinocastro** [comment]
Now is this one:

```
+------------------+-----------------+
| xonsh            | 0.8.12          |
| Python           | 3.7.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

But I have to mention that I just updated `prompt_toolkit` as well and that last error is gone.

**Comment by scopatz** [comment]
Ok great! That is where I thought  the deprecation warning was coming from!
