### ISSUE TITLE
nvm installation error due to `ForeignShellFunctionAlias`

### ISSUE THREAD

**Issue by knowsuchagency** [xonsh/xonsh#3053]
## xonfig

<details>

```
# nvm
$NVM_DIR = "~/.nvm"
source-bash "/usr/local/opt/nvm/nvm.sh"
```

</details>

## Expected Behavior

`nvm` shell alias should just work

## Current Behavior

`nvm` raises an error after installation

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/Users/sfitzpatrick/.local/pipx/venvs/xonsh[ptk,mac]/lib/python3.7/site-packages/xonsh/proc.py", line 1856, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/Users/sfitzpatrick/.local/pipx/venvs/xonsh[ptk,mac]/lib/python3.7/site-packages/xonsh/built_ins.py", line 538, in run
    event_name = self._cmd_event_name()
  File "/Users/sfitzpatrick/.local/pipx/venvs/xonsh[ptk,mac]/lib/python3.7/site-packages/xonsh/built_ins.py", line 612, in _cmd_event_name
    return self.alias.__name__
AttributeError: 'ForeignShellFunctionAlias' object has no attribute '__name__'
```

</details>

## Steps to Reproduce

```
brew install nvm
You should create NVM's working directory if it doesn't exist:

  mkdir ~/.nvm

Add the following to ~/.bash_profile or your desired shell
configuration file:

  export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
 
# in .xonshrc
$NVM_DIR = "~/.nvm"
source-bash "/usr/local/opt/nvm/nvm.sh"

nvm # raises error

**Comment by crombach** [comment]
I am having a similar issue, but it is not exactly the same. I am running xonsh 0.8.12.

I have this in my `.xonshrc`:

```
import os
$NVM_DIR = $HOME+'/.nvm'
if (os.path.isfile($NVM_DIR+'/nvm.sh')):
    source-bash $("$NVM_DIR/nvm.sh")
```

The file I am trying to source exists, and the permissions have been properly set. Unfortunately, I get this message when I start up a xonsh terminal:

```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
TypeError: source_foreign() got an unexpected keyword argument 'spec'
```

Here's the traceback from running `source-bash $("$NVM_DIR/nvm.sh")` directly in the xonsh shell:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 13392, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/__amalgam__.py", line 20033, in _alias
    stack=stack,
TypeError: source_foreign() got an unexpected keyword argument 'spec'
```

Note that I tried adding the exact code from OP's example (with the correct path) and I still got the same error described above. I could not replicate the error they are seeing.

**Comment by scopatz** [comment]
Thanks @knowsuchagency - what are the contents of `/usr/local/opt/nvm/nvm.sh`? Namely what does the nvm alias look like?

**Comment by AngellusMortis** [comment]
https://github.com/nvm-sh/nvm/blob/master/nvm.sh

**Comment by scopatz** [comment]
I think this might have been fixed in 0.9.8.  Could someone try it out please and see if it is still an issue?

**Comment by bobhy** [comment]
Working OK as of xonsh 0.9.14 (ubuntu 19.10)

**Comment by scopatz** [comment]
ok great 👍
