### ISSUE TITLE
Can't execute command that contains a space as environment variable

### ISSUE THREAD

**Issue by carmenbianca** [xonsh/xonsh#3073]
## xonfig

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.8.12          |
| Python           | 3.7.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | prompt_toolkit1 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | fedora          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

When I set a command that contains a space as environment variable, I expect to be able to execute that command using the environment variable. i.e.:

```
carmen@carmen-thinkpad ~ $ $LSL = 'ls -l'
carmen@carmen-thinkpad ~ $ $LSL
<output here>
```

The current behaviour is problematic twofold: Executing the command without argument just prints the command as string, and if the command contains a space, it throws an error.

## Current Behavior

See the following output:

```
carmen@carmen-thinkpad ~ $ $LS = 'ls'
carmen@carmen-thinkpad ~ $ $LSL = 'ls -l'
carmen@carmen-thinkpad ~ $ # Just the environment variable prints its value.
carmen@carmen-thinkpad ~ $ $LS
'ls'
carmen@carmen-thinkpad ~ $ # Adding a path executes the command
carmen@carmen-thinkpad ~ $ $LS .
Bildoj  Dokumentoj  Elŝutoj  Games  Labortablo  Muziko  Nextcloud  Projektoj  Publike  Videoj  dotfiles  rpmbuild  texmf  tmp  Ŝablonoj
carmen@carmen-thinkpad ~ $ # The command that contains a space fails.
carmen@carmen-thinkpad ~ $ $LSL .
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: ls -l
```

### Traceback (if applicable)

```
carmen@carmen-thinkpad ~ $ $LSL .
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/xonsh/built_ins.py", line 560, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.7/site-packages/xonsh/proc.py", line 583, in __init__
    *args, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ls -l': 'ls -l'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/xonsh/proc.py", line 1856, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3.7/site-packages/xonsh/built_ins.py", line 549, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3.7/site-packages/xonsh/built_ins.py", line 571, in _run_binary
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: ls -l

```

## Steps to Reproduce

See above :)

**Comment by carmenbianca** [comment]
Maybe I forgot. Why this is important in a real-world scenario: I set `$EDITOR = 'emacsclient -t' `, and it doesn't work. Currently I get around it by doing:

```
aliases['edit'] = ['emacsclient', '-t']
$EDITOR = 'edit'
```

But this isn't great because any non-xonsh subprocess won't recognise `edit` as command.

**Comment by laloch** [comment]
I don't know whether this is a bug or not, but in general xonsh is not sh-lang compatible shell, so you can't really expect that everything that works in sh and/or bash will work the same way in xonsh.

Your example can be written in xonsh like:
```
laloch@uriel ~ $ $LSL = "ls -l"
laloch@uriel ~ $ $[@($LSL.split()) /]
total 25
lrwxrwxrwx   1 root root    7 Dec  6 15:19 bin -> usr/bin
drwxr-xr-x   4 root root 1024 Jan  1  1970 boot
drwxr-xr-x  23 root root 3980 Apr 10 12:22 dev
...
```
That is, however, not optimal, since it does not work for arguments with spaces. The best way I know would be:
```
laloch@uriel ~ $ $LSL = ["ls", "-l"]
laloch@uriel ~ $ $[@($LSL) /]
total 25
lrwxrwxrwx   1 root root    7 Dec  6 15:19 bin -> usr/bin
...
```

**Comment by gforsyth** [comment]
Is there a particular reason to use environment variables to store these aliases?

You might have an easier time sticking definitions like this in the `aliases` dict:

```console
 ~/tmp/test $ aliases["lsl"] = "ls -l"
 ~/tmp/test $ lsl
total 8
-rw-r--r--  1 user  group  86 Jan 31  2018 README.md
-rw-r--r--  1 user  group   0 Feb  8  2018 anothernewfile_0
-rw-r--r--  1 user  group   0 Feb  8  2018 anothernewfile_1
-rw-r--r--  1 user  group   0 Feb  8  2018 anothernewfile_2
-rw-r--r--  1 user  group   0 Feb  8  2018 anothernewfile_3
-rw-r--r--  1 user  group   0 Feb  8  2018 anothernewfile_4
drwxr-xr-x  3 user  group  96 Apr 10 10:52 test2
 ~/tmp/test $ lsl test2
total 0
-rw-r--r--  1 user  group  0 Apr 10 10:52 anotherfile
```

**Comment by gforsyth** [comment]
Ahh, sorry, just saw your second comment.

**Comment by gforsyth** [comment]
> Maybe I forgot. Why this is important in a real-world scenario: I set `$EDITOR = 'emacsclient -t' `, and it doesn't work.

Can you clarify how this doesn't work?  I think there's a bug in versions of prompt_toolkit that always opens `nano`

**Comment by laloch** [comment]
@gforsyth: Try for yourself...
```
~ $ $EDITOR = "mcedit -u"  # replace with your favorite editor plus some argument
~ $ @($EDITOR) test.txt
Traceback
...
FileNotFoundError: [Errno 2] No such file or directory: 'mcedit -u': 'mcedit -u'
...
~ $ $EDITOR = ["mcedit", "-u"]
~ $ @($EDITOR) test.txt
# That worked - opens test.txt in editor
# Now the important thing:
~ $ sh
sh-5.0$ $EDITOR test.txt
sh: ['mcedit',: command not found
# Did not work, because:
sh-5.0$ echo $EDITOR
['mcedit', '-u']
```
Subprocesses do not know what `"['mcedit', '-u']"` means.

**Comment by carmenbianca** [comment]
You might be right that this is not necessarily a bug. I set `$EDITOR = 'emacsclient -t'` for subprocesses, and just use an alias to invoke that command within xonsh.

**Comment by scopatz** [comment]
Yeah, sh-langs automatically tokenize with the `$IFS` environment variable, which most of us xonsh users consider to be deeply strange behavior. `aliases` is the proper interface for this in xonsh, which will tokenize based on whitespace.  So you can do something like the following if you need:

```
$EDITOR = 'emacsclient -t'
aliases["edit"] = $EDITOR
```

> But this isn't great because any non-xonsh subprocess won't recognise edit as command.

Do you have a specific example in mind?

**Comment by carmenbianca** [comment]
> > But this isn't great because any non-xonsh subprocess won't recognise edit as command.
> 
> Do you have a specific example in mind?

```
carmenbianca@thinkpad-a285 ~ $ $EDITOR = "emacsclient -t"                                                                                                                                                                           
carmenbianca@thinkpad-a285 ~ $ aliases["edit"] = $EDITOR                                                                                                                                                                                                                                                                                                                                                                                             
carmenbianca@thinkpad-a285 ~ $ cat hello.py                                                                                                                                                                                                   
import subprocess

subprocess.run(["edit"])                                                                                                                                                                                       
carmenbianca@thinkpad-a285 ~ $ python3 hello.py                                                                                                                                                                                               
Traceback (most recent call last):
  File "hello.py", line 3, in <module>
    subprocess.run(["edit"])
  File "/usr/lib64/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'edit': 'edit'
```

**Comment by scopatz** [comment]
Ahh yeah - that is something that just cannot work, because you are making a direct system call with `subprocess.run()`.  This is true for all shells.  For example, if you were to define a Bash alias, `subprocess.run()` would not know about that alias unless you first sourced the file where that definition lives (e.g. `~/.bashrc`).

That said, xonsh does have a standard library drop-in replacement that *is* alias aware.  All you have to do is `from xonsh.lib import subporcess`. https://xon.sh/api/lib/subprocess.html This provides the normal subprocess API, but using the xonsh interface, so you get all of the normal bells and whistles.

**Comment by carmenbianca** [comment]
Ah, just ignorance on my part then :) Whatever the case, I am no longer personally affected by this issue. I have altered my workflow with the available tools. If you want, this issue can be closed. If you think there is still an issue to be solved, then that is also good—I'm just no longer affected.

**Comment by scopatz** [comment]
Thanks so much for bringing it up!
