### ISSUE TITLE
xonsh badly handles LS_COLORS

### ISSUE THREAD

**Issue by auscompgeek** [xonsh/xonsh#3091]
```console
% xonsh --version
xonsh/0.8.12
```

## Expected Behavior
xonsh should start.

## Current Behavior
xonsh fails to start with a KeyError whilst processing LS_COLORS.

### Traceback (if applicable)

<details>

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/xonsh/main.py", line 401, in main
    args = premain(argv)
  File "/usr/lib/python3.7/site-packages/xonsh/main.py", line 352, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/lib/python3.7/site-packages/xonsh/main.py", line 287, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/usr/lib/python3.7/site-packages/xonsh/execer.py", line 62, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/usr/lib/python3.7/site-packages/xonsh/built_ins.py", line 1272, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/usr/lib/python3.7/site-packages/xonsh/built_ins.py", line 1348, in load
    self.env = Env(default_env())
  File "/usr/lib/python3.7/site-packages/xonsh/environ.py", line 1342, in __init__
    self[key] = val
  File "/usr/lib/python3.7/site-packages/xonsh/environ.py", line 1504, in __setitem__
    val = ensurer.convert(val)
  File "/usr/lib/python3.7/site-packages/xonsh/environ.py", line 450, in convert
    return cls.fromstring(x)
  File "/usr/lib/python3.7/site-packages/xonsh/environ.py", line 413, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/usr/lib/python3.7/site-packages/xonsh/ansi_colors.py", line 297, in ansi_color_escape_code_to_name
    short_to_ints(short), background=(fore_back == "BACK"), prefix=pre
  File "/usr/lib/python3.7/site-packages/xonsh/color_tools.py", line 430, in short_to_ints
    return rgb_to_ints(short2rgb(short))
  File "/usr/lib/python3.7/site-packages/xonsh/color_tools.py", line 360, in short2rgb
    return SHORT_TO_RGB[short]
KeyError: '074'
```
</details>

## Steps to Reproduce
1. Install https://github.com/trapd00r/LS_COLORS
2. Attempt to start xonsh.

**Comment by laloch** [comment]
Could you please post (via Gist or `cat ~/.xonshrc | curl -F 'f:1=<-' ix.io`) the exact contents of your `.xonshrc` file?

**Comment by auscompgeek** [comment]
I don't have a `.xonshrc`.

**Comment by laloch** [comment]
OK, I can see the problem. PR incoming...
