### ISSUE TITLE
Spaces taken away for aliased function

### ISSUE THREAD

**Issue by shadow-light** [xonsh/xonsh#3140]
## xonfig

<details>

```

+------------------+----------------------+
| xonsh            | 0.8.12               |
| Git SHA          | 986bf28d             |
| Commit Date      | Mar 11 14:37:52 2019 |
| Python           | 3.6.8                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.3.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

```

</details>

## Expected Behavior
An aliased function should be able to accept a single period as its first argument.

## Current Behavior
xonsh interprets `printme . hi` as `printme.hi` (removing the spaces)

### Traceback (if applicable)

<details>

```shell

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xonsh/base_shell.py", line 360, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/local/lib/python3.6/dist-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
AttributeError: 'function' object has no attribute 'hi'

```

</details>

## Steps to Reproduce

```shell
~ def printme(args): 
.     print(args) 
.                                                                                                                                           
~ aliases['printme'] = printme        
~ printme hi hi                                                                                                                             
['hi', 'hi']                                                                                                      
~ printme . hi                                                                                                                              
AttributeError: 'function' object has no attribute 'hi'
```

**Comment by jb-leger** [comment]
For me this is not a bug.

The expression `printme . hi` is valid in python (but the `hi` attr is missing), the `printme` name exist in `python` therefore, python syntax have precedence.

To prevent this behavior, these function should be prefixed by a `_`. For your example.

```
jben@garance ~ $ def _printme(args): 
................     print(args) 
................ aliases['printme'] = _printme                                                                   
jben@garance ~ $ printme hi hi                                                                                    
['hi', 'hi']
jben@garance ~ $ printme . hi                                                                                   
['.', 'hi']
```

This is explained in a note in [this section of the tutorial](https://xon.sh/tutorial.html#adding-modifying-and-removing-aliases). It is not the first thing a user read, I understand that.

**Comment by shadow-light** [comment]
Wow... all these years and I never knew you could have spaces around periods in Python. In that case, agreed, it works as it should, and thanks for the fix too.
