### ISSUE TITLE
cannot install xonsh into debian python3.4

### ISSUE THREAD

**Issue by svejcik** [xonsh/xonsh#3148]
## xonfig

<details>
```
$ xonfig
```
</details>

## Expected Behavior

I've tried and failed to install xonsh with the following 2 methods:
python3.4 -m pip install xonsh
or
pip3 install xonsh

## Current Behavior

(omitting the (non)-ascii art)

package init file 'xontrib/__init__.py' not found (or not a regular file)
    warning: no previously-included files found matching 'tests/test_news.py'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Installing collected packages: xonsh
  Running setup.py install for xonsh
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mv4hdrls/xonsh/setup.py", line 411, in <module>
        main()
      File "/tmp/pip-build-mv4hdrls/xonsh/setup.py", line 407, in main
        setup(**skw)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-mv4hdrls/xonsh/setup.py", line 214, in run
        build_tables()
      File "/tmp/pip-build-mv4hdrls/xonsh/setup.py", line 94, in build_tables
        yacc_debug=True,
      File "/tmp/pip-build-mv4hdrls/xonsh/xonsh/lazyasd.py", line 78, in __call__
        obj = self._lazy_obj()
      File "/tmp/pip-build-mv4hdrls/xonsh/xonsh/lazyasd.py", line 46, in _lazy_obj
        obj = d["load"]()
      File "/tmp/pip-build-mv4hdrls/xonsh/xonsh/parser.py", line 13, in Parser
        return p
    UnboundLocalError: local variable 'p' referenced before assignment

### Traceback (if applicable)

<details>
```
traceback
```
</details>

**Comment by svejcik** [comment]
Resolved - I thought 3.4 was still an option. Looking at code and moving to 3.5 resolved issue.
