### ISSUE TITLE
Multiple calls to logging.info/debug/error etc. will result in a exception

### ISSUE THREAD

**Issue by CherryWorm** [xonsh/xonsh#3157]
If one imports logging and more than once calls any logging function (or imports some module that does exactly that, like pwntools), then that will fail and print an exception.

## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.4           |
| Python           | 3.7.3           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior
Executing
```python
import logging
logging.error('test')
logging.error('test')
```
should print
```
ERROR:root:test
ERROR:root:test
```
## Current Behavior
Instead, it prints
```
$ import logging
$ logging.error('test')
ERROR:root:test
$ logging.error('test')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 17432, in write
    self.mem.write(s)
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/bin/xonsh", line 4, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24025, in main
    return main_xonsh(args)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24054, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 194, in cmdloop
    self.default(line)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 17611, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 2943, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
Message: 'test'
Arguments: ()
```
### Traceback (if applicable)

<details>

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 17432, in write
    self.mem.write(s)
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/bin/xonsh", line 4, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24025, in main
    return main_xonsh(args)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24054, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 194, in cmdloop
    self.default(line)
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 17611, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 2943, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
Message: 'test'
Arguments: ()
```

</details>

## Steps to Reproduce
```python
import logging
logging.error('test')
logging.error('test')
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Weird. Thanks for reporting @nicosio2! Does this happen only at the interactive terminal or also in scripts?

**Comment by nicosio2** [comment]
This only seems to happen in the interactive terminal.

Another issue I stumbled across that is very likely related occurs if one calls `logging.basicConfig()` (this gets called in all the logging functions) and then exits the shell, there is an exception:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 2038, in shutdown
    h.flush()
  File "/usr/lib/python3.7/logging/__init__.py", line 1018, in flush
    self.stream.flush()
  File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 17444, in flush
    self.std.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

**Comment by scopatz** [comment]
I can confirm that this happens. It is odd

**Comment by dclong** [comment]
There is an issue with the loguru module too. 

https://github.com/xonsh/xonsh/issues/3359

**Comment by yarikoptic** [comment]
just discovered xonsh an decided to try in "python" mode to use our datalad, immediately stumbling into this issue I believe:

<details>
<summary>although first thought to blame colorama. Click for more details</summary> 

```shell
(dev3) yoh@lena ~/proj/misc/xonsh master $ import datalad.api as dl
/usr/lib/python3/dist-packages/duecredit/entries.py:69: DeprecationWarning: invalid escape sequence \s
  reg = re.match("\s*@(?P<type>\S*)\s*\{\s*(?P<key>\S*)\s*,.*",
/usr/lib/python3/dist-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/lib/python3/dist-packages/boto/__init__.py:1105: DeprecationWarning: invalid escape sequence \c
  """
/usr/lib/python3/dist-packages/boto/pyami/config.py:98: DeprecationWarning: invalid escape sequence \s
  match = re.match("^#import[\s\t]*([^\s^\t]*)[\s\t]*$", line)
/usr/lib/python3/dist-packages/boto/connection.py:672: DeprecationWarning: invalid escape sequence \w
  '(?:(?P<user>[\w\-\.]+):(?P<pass>.*)@)?'
/usr/lib/python3/dist-packages/boto/connection.py:674: DeprecationWarning: invalid escape sequence \d
  '(?::(?P<port>\d+))?'
/usr/lib/python3/dist-packages/boto/https_connection.py:80: DeprecationWarning: invalid escape sequence \.
  host_re = host.replace('.', '\.').replace('*', '[^.]*')

(dev3) yoh@lena ~/proj/misc/xonsh master $ d = dl.install(source='///', path='/tmp/datasets')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 17078, in write
    self.mem.write(s)
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/bin/xonsh", line 33, in <module>
    sys.exit(load_entry_point('xonsh==0.9.24', 'console_scripts', 'xonsh')())
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 24932, in main
    sys.exit(main_xonsh(args))
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 24970, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/lib/python3/dist-packages/xonsh/ptk_shell/shell.py", line 259, in cmdloop
    self.default(line)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 17257, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 2375, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 495, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 483, in return_func
    results = list(results)
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 402, in generator_func
    for r in _process_results(
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 570, in _process_results
    for res in results:
  File "/usr/lib/python3/dist-packages/datalad/distribution/install.py", line 369, in __call__
    for r in res:
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 402, in generator_func
    for r in _process_results(
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 570, in _process_results
    for res in results:
  File "/usr/lib/python3/dist-packages/datalad/core/distributed/clone.py", line 288, in __call__
    yield from clone_dataset(
  File "/usr/lib/python3/dist-packages/datalad/core/distributed/clone.py", line 416, in clone_dataset
    log_progress(
  File "/usr/lib/python3/dist-packages/datalad/log.py", line 308, in log_progress
    lgrcall(*args, extra=d)
Message: 'Cloning dataset to %s'
Arguments: (Dataset('/tmp/datasets'),)
...
```
</details>
