### ISSUE TITLE
echo $? fails

### ISSUE THREAD

**Issue by d33tah** [xonsh/xonsh#316]
```
d@d-laptop ~/transmission $ echo $?
........................... 
Traceback (most recent call last):
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/execer.py", line 151, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/parser.py", line 258, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/parser.py", line 2353, in p_error
    column=p.lexpos))
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/parser.py", line 329, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:7: expected NAME, (, [, or { after $, but got TokenInfo(type=53 (ERRORTOKEN), string='?', start=(1, 8), end=(1, 9), line='$[echo $?]\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/base_shell.py", line 63, in push
    locs=self.ctx)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/execer.py", line 95, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/execer.py", line 70, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/execer.py", line 164, in _parse_ctx_free
    raise original_error
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/execer.py", line 151, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/parser.py", line 258, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/parser.py", line 2353, in p_error
    column=p.lexpos))
  File "/home/d/virtualenv-3.4/lib/python3.4/site-packages/xonsh/parser.py", line 329, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: expected NAME, (, [, or { after $, but got TokenInfo(type=53 (ERRORTOKEN), string='?', start=(1, 6), end=(1, 7), line='echo $?\n')
```

**Comment by scopatz** [comment]
Hi @d33tah - we don't support this yet.  It is on the roadmap, but we need to finish our integrated history management. PR #213 is a start to this, but needs to be finished.

**Comment by scopatz** [comment]
This information can now be accessed vis `__xonsh_history__.rtns[-1]`

**Comment by kergoth** [comment]
Just a note for anyone else who didn't know, `rtns[-1]` is only useful in a git build for this, not 0.2.3. master works great though.

**Comment by scopatz** [comment]
Yeah, we need to do another release :).  Before the end of the year, for sure.

**Comment by laerus** [comment]
This issue is solved!
