### ISSUE TITLE
.xonshrc runs before setting $XONSH_LOGIN and $XONSH_INTERACTIVE

### ISSUE THREAD

**Issue by NorthIsUp** [xonsh/xonsh#3176]
Most shells give you immediate access to interactive/login information so you can source files appropriately, in xonsh it seems that the rc files are executed before the interactive/login args are parsed

## xonfig

<details>
```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.5           |
| Python           | 3.7.3           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.7           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
```
</details>

## Expected Behavior
`$XONSH_LOGIN` and `$XONSH_INTERACTIVE should be available in `.xonshrc`

Or have a .xonshenv -> .xonshlogin -> .xonshprofile -> .xonshrc like zsh or something

## Current Behavior
I don't have access to this information

### Traceback (if applicable)

<details>
```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.9.5/libexec/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 19429, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/usr/local/Cellar/xonsh/0.9.5/libexec/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 3038, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/Cellar/xonsh/0.9.5/libexec/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 2943, in run_compiled_code
    func(code, glb, loc)
  File "/Users/adam/.xonshrc", line 24, in <module>
    if $XONSH_INTERACTIVE:
  File "/usr/local/Cellar/xonsh/0.9.5/libexec/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 19277, in __getitem__
    raise KeyError(e.format(key))
KeyError: 'Unknown environment variable: $XONSH_INTERACTIVE'
error running xonsh run control file '/Users/adam/.xonshrc': 'Unknown environment variable: $XONSH_INTERACTIVE'
```
</details>

## Steps to Reproduce
```
$ cat <<-EOF > ~/.xonshrc
print($XONSH_INTERACTIVE)
print($XONSH_LOGIN)
EOF
$ xonsh
```

**Comment by scopatz** [comment]
Thanks for opening this @NorthIsUp.  You are right that interactive and login are somewhat different than other environment variables.  This is probably a matter of moving some code around in `main.py`

**Comment by cafehaine** [comment]
I'm currently looking at this since I also want to use xonsh as my login shell, and it looks like the problem is quite complex.

The .xonshrc is loaded in `premain` by the `start_services` call.
https://github.com/xonsh/xonsh/blob/8b933da995c3ee5c72981744c191a9f816ec59b2/xonsh/main.py#L357
However the environment variables for interactive/login are defined afterwards.
https://github.com/xonsh/xonsh/blob/8b933da995c3ee5c72981744c191a9f816ec59b2/xonsh/main.py#L358-L363

One way to fix this would be to define the interactive/login environment variables *inside* `start_services`, before loading the .xonshrc
Another solution would be to not load the .xonshrc inside of `start_services` but instead at the end of `premain`

I don't really know which way is better/would break less code.

**Comment by scopatz** [comment]
Yeah, this might be one of those catch-22s with configuration
