### ISSUE TITLE
multiline python evaluation `@(...)` under try block fails with IndexError

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3191]
## config
`Windows x64 7`, `Python 3.7.3`, `xonsh/0.9.6`

## details
```
def pcall(args):
  args.pop(0)(*args)

try:
    @(pcall, print, \
    123)
except:
    pass
```

**Output:**
```
Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 220, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "C:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "C:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "C:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 3299, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "C:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 676, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:6:0: ('code: ',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\ptk2\shell.py", line 173, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "C:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "C:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 96, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "C:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 242, in _parse_ctx_free
    line, nlogical, idx = get_logical_line(lines, idx)
  File "C:\Python\x64\37\lib\site-packages\xonsh\tools.py", line 545, in get_logical_line
    line = lines[idx]
IndexError: list index out of range
```

## Expected Behavior
Print `123`.

## Current Behavior
Double exception.

**Comment by laloch** [comment]
This is the same as #3192.
