### ISSUE TITLE
multiline python evaluation `@(...)` breaks the parser

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3192]
## config
`Windows x64 7`, `Python 3.7.3`, `xonsh/0.9.6`

## details
1. Create the `.xsh` script file (**Example 1**):
```
def pcall(args):
  args.pop(0)(*args)

@(pcall, print, \
"'")

def dummy():
  pass
```

2. Run the script externally from the python executable:
```
python.exe -m xonsh 1.xsh
```

**Output**:
```
Traceback (most recent call last):
  File "c:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 220, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "c:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "c:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "c:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "c:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "c:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 3299, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "c:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 676, in _parse_error
    raise err
SyntaxError: 1.xsh:9:0: ('code: ',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python\x64\37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python\x64\37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python\x64\37\lib\site-packages\xonsh\__main__.py", line 3, in <module>
    main()
  File "c:\Python\x64\37\lib\site-packages\xonsh\main.py", line 404, in main
    _failback_to_other_shells(args, err)
  File "c:\Python\x64\37\lib\site-packages\xonsh\main.py", line 368, in _failback_to_other_shells
    raise err
  File "c:\Python\x64\37\lib\site-packages\xonsh\main.py", line 402, in main
    return main_xonsh(args)
  File "c:\Python\x64\37\lib\site-packages\xonsh\main.py", line 446, in main_xonsh
    args.file, shell.execer, glb=shell.ctx, loc=None, mode="exec"
  File "c:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 160, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "c:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 119, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "c:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "c:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 96, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "c:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 242, in _parse_ctx_free
    line, nlogical, idx = get_logical_line(lines, idx)
  File "c:\Python\x64\37\lib\site-packages\xonsh\tools.py", line 545, in get_logical_line
    line = lines[idx]
IndexError: list index out of range
```

If try to remove the dummy code section (**Example 2**):
```
def pcall(args):
  args.pop(0)(*args)

@(pcall, print, \
"'")
```

Then the exception flow would change:
```
Traceback (most recent call last):
  File "c:\Python\x64\37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python\x64\37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python\x64\37\lib\site-packages\xonsh\__main__.py", line 3, in <module>
    main()
  File "c:\Python\x64\37\lib\site-packages\xonsh\main.py", line 404, in main
    _failback_to_other_shells(args, err)
  File "c:\Python\x64\37\lib\site-packages\xonsh\main.py", line 368, in _failback_to_other_shells
    raise err
  File "c:\Python\x64\37\lib\site-packages\xonsh\main.py", line 402, in main
    return main_xonsh(args)
  File "c:\Python\x64\37\lib\site-packages\xonsh\main.py", line 446, in main_xonsh
    args.file, shell.execer, glb=shell.ctx, loc=None, mode="exec"
  File "c:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 160, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "c:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 119, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "c:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "c:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 96, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "c:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 235, in _parse_ctx_free
    raise original_error from None
  File "c:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 220, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "c:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "c:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "c:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "c:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "c:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 3299, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "c:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 676, in _parse_error
    raise err
SyntaxError: 1.xsh:4:0: ('code: @(',)
@(pcall, print, \
^
```

May be different bug places in the parser code.

**Update:**
Seems it is related specifically to the multiline, not to the single quote itself as long as the empty string print fails too.

**Update 2:**
Another example of broken multiline:
```
@(pcall, print, "111") | \
  cmd.exe /c echo 222
```

## Expected Behavior
Print `'`.

## Current Behavior
Different exceptions for different examples.

**Comment by laloch** [comment]
I can confirm the issue. The same code works just fine from the command line.

**Comment by scopatz** [comment]
Thanks for reporting @andry81!

**Comment by anki-code** [comment]
I can't repeat this on xonsh 0.9.27.

```python
echo @("""
def pcall(args):
  args.pop(0)(*args)

@(pcall, print, \
"'")

def dummy():
  pass
""") > /tmp/3192-1.xsh
xonsh /tmp/3192-1.xsh
# '

echo @("""
def pcall(args):
  args.pop(0)(*args)

@(pcall, print, \
"'")
""") > /tmp/3192-2.xsh
xonsh /tmp/3192-2.xsh
# '

echo @("""
def pcall(args):
  args.pop(0)(*args)

@(pcall, print, "111") | \
  echo 222
""") > /tmp/3192-3.xsh
xonsh /tmp/3192-3.xsh
# 222

# Prepared by xontrib-hist-format
```
