### ISSUE TITLE
raw strings still expands

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3197]
## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.7                                                 |
| Git SHA          | 626b94db                                              |
| Commit Date      | Jun 28 17:20:28 2019                                  |
| Python           | 3.7.3                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | None                                                  |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000000002A7B4E0> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x0000000002A7B3C8> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```
</details>

## Expected Behavior
echo the string.

## Current Behavior
https://xon.sh/changelog.html#v0-9-4
`Xonsh now does not attempt to expand raw strings`
But seems still does:
`bad escape \w at position 2`

### Traceback (if applicable)
<details>

```
Traceback (most recent call last):
  File "C:\Python\x64\37\lib\sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\w'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\base_shell.py", line 360, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "C:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Python\x64\37\lib\site-packages\xonsh\tools.py", line 105, in expand_path
    s = expandvars(s)
  File "C:\Python\x64\37\lib\site-packages\xonsh\tools.py", line 2154, in expandvars
    path = POSIX_ENVVAR_REGEX.sub(value, path, count=1)
  File "C:\Python\x64\37\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Python\x64\37\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Python\x64\37\lib\sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \w at position 2
```

</details>

## Steps to Reproduce
```
$p = r'c:\windows'
print($p) # ok
echo $p   # not ok
```

**Comment by scopatz** [comment]
Thanks for reporting. This is because it is being shoved into the environment. The error I am seeing with `echo` is coming from expanding a variable.  If you expand this out literally, it seems to work.

```
 $ echo r"C:\Windows"
C:\Windows
$ echo @($p)
C:\Windows
```

This seems like it should be an easy fix.

**Comment by AstraLuma** [comment]
To be clear: variables not tracking what kind of string they were originally is the programming model, not a bug.

It might be a bug that environment variables in a command are re-interpreted, though? I'm not sure what the desired behavior here should be.

**Comment by scopatz** [comment]
I mean only that there is a bug that expandvars() throws an error, rather than returning the original string.

**Comment by andry81** [comment]
@astronouth7303 But this is how the bash works:
```
p='c:\windows'
echo $p
```
That prints in the bash the `c:\windows` string as expected.
So the way you propose it to workaround is some kind of messy or confused way.

**Comment by AstraLuma** [comment]
xonsh is not bash, never was, never will be, never wanted to be.

Xonsh is python with additional shell features. `$p` is a python variable that's tied to the process environment.

However, you're right. I would not expect `echo $p` to re-interpret the contents again. To be honest, I figured it would follow similar rules as `@()`?

**Comment by andry81** [comment]
> xonsh is not bash, never was, never will be, never wanted to be.
>> never wanted to be.

Then what this does mean: www.youtube.com/watch?v=uaje5I22kgE&t=2m56s (`Anthony Scopatz - xonsh - PyCon 2016`)
Does it means a joke?

**Comment by AstraLuma** [comment]
"best of bash" would be things like easy execution of subprocess with being able to customize the commands with variables and stuff.

But xonsh has never tried to be a bourne shell nor compatible with it.

**Comment by andry81** [comment]
> But xonsh has never tried to be a bourne shell nor compatible with it.

The Bourne shell just the most popular among all shells, so this is just the same to say it never tried to be a shell, that is not true of cause:

https://xon.sh/index.html
>Xonsh is a Python-powered, cross-platform, **Unix-gazing shell** language and command prompt.

**Comment by cjrh** [comment]
It isn't only `echo` obviously, I think I'm seeing the same issue with expanding `PWD` for `docker run` invocations. The workaround works, but it's annoying to have to remember to wrap in `@()` because there is already a lot of the complexity in the line. 
```
~/temp/aiorun-42   (venv)
$ docker run --rm -it -v $PWD:/src python:3.8.1-slim-buster /bin/bash
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
re.error: bad escape \U at position 2

~/temp/aiorun-42   (venv)
$ docker run --rm -it -v @($PWD):/src python:3.8.1-slim-buster /bin/bash
root@fb86c7a69085:/# exit
exit
```

A drawback of the current state is that I can't share (or use in discussions) some of these smaller scripts with my bash-using colleagues.  Is there a use-case that would break if it were changed to avoid expanding environment variables specifically?

If someone can point me (roughly) to the section of code in xonsh that deals with this "variable expansion" I'm happy to try out a few experiments to see if I can change the behaviour?

**Comment by andry81** [comment]
> The workaround works, but it's annoying to have to remember to wrap in @() because there is already a lot of complexity in the line.

This is the exact reason why I did replace Xonsh by the Plumbum. Plumbum much more stable than this, a bit longer to write with but at least has less problems on the straight line.

**Comment by anki-code** [comment]
I can't reproduce this all. Everything is working on Windows 11, Windows Terminal, xonsh 0.23.0, Python 3.13

```xsh
$p = r'c:\windows'
print($p)
# c:\windows
echo $p
# c:\windows
```
```xsh
showcmd docker $PWD:/src container
# ['docker', 'C:\\Users\\pc:/src', 'container']
```
