### ISSUE TITLE
`source` statement does not respect the `os.sep`

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3201]
## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.7                                                 |
| Git SHA          | 626b94db                                              |
| Commit Date      | Jun 28 17:20:28 2019                                  |
| Python           | 3.7.3                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | None                                                  |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000000002ACB518> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x0000000002ACB400> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## Expected Behavior
Include the script from the current script directory.

## Current Behavior
The xonsh `source` statement can not process Windows style paths when the python can.

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "c:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 1411, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "c:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 1204, in proxy_two
    return f(args, stdin)
  File "c:\Python\x64\37\lib\site-packages\xonsh\aliases.py", line 556, in source_alias
    "must source at least one file, " + fname + "does not exist."
RuntimeError: must source at least one file, c:/Python/x64/37☻.xshdoes not exist.
>configure: 123
```

</details>

## Steps to Reproduce
**1.xsh**
```
import sys, os, inspect

SOURCE_FILE = os.path.abspath(inspect.getsourcefile(lambda:0)).replace('\\','/')
SOURCE_DIR = os.path.dirname(SOURCE_FILE).replace('\\','/')

evalx("source '{0}'".format(os.path.join(SOURCE_DIR, '2.xsh')))                     # source does not support os.sep
#evalx("source '{0}'".format(os.path.join(SOURCE_DIR, '2.xsh').replace('\\','/')))  # work

CONFIGURE_DIR = sys.argv[1].replace('\\', '/')

def configure(configure_dir):
  print(">configure:", configure_dir)

configure(CONFIGURE_DIR)
```

**2.xsh**
```
print(222)
```

**main**
```
python -m xonsh 1.xsh 123
```

**Comment by astronouth7303** [comment]
Probably because backslash is an escape.

You would have the same problem if you broke out everything into a command and not an `evalx()`

**Comment by andry81** [comment]
> Probably because backslash is an escape.
You are right! This one works:
`evalx("source r'{0}'".format(os.path.join(SOURCE_DIR, '2.xsh')))`
