### ISSUE TITLE
AssertionError: Ctrl+C after tab-completing a filename on Windows

### ISSUE THREAD

**Issue by TehVulpes** [xonsh/xonsh#3231]
On Windows, hitting Ctrl+C after writing a command but before executing it sometimes causes Xonsh to raise an AssertionError. I'm able to reliably reproduce this issue every time at least one of the arguments is a filename that I've tab-completed rather than typed out.

## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.3                                                 |
| Git SHA          | 679d4e06                                              |
| Commit Date      | May 14 17:45:24 2019                                  |
| Python           | 3.7.1                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | 2.4.0                                                 |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000015FACF31B70> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x0000015FACF31A58> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## Expected Behavior
Xonsh should cancel the current line of input and start the next one

## Current Behavior
Xonsh raises an AssertionError and crashes

### Traceback

<details>

In this traceback, I've typed "source secr", hit tab, then Ctrl+C

```
user@host ~\src\<--snip--> [master] $ source secrets.xsh Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xonsh\__main__.py", line 3, in <module>
    main()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xonsh\main.py", line 404, in main
    _failback_to_other_shells(args, err)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xonsh\main.py", line 373, in _failback_to_other_shells
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xonsh\main.py", line 402, in main
    return main_xonsh(args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xonsh\main.py", line 431, in main_xonsh
    shell.shell.cmdloop()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xonsh\ptk2\shell.py", line 189, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xonsh\ptk2\shell.py", line 158, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 738, in prompt
    return run_sync()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 727, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\prompt_toolkit\application\application.py", line 709, in run
    return run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\prompt_toolkit\application\application.py", line 681, in run
    f = self.run_async(pre_run=pre_run)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\prompt_toolkit\application\application.py", line 527, in run_async
    assert not self._is_running, 'Application is already running.'
AssertionError: Application is already running.
```

</details>

## Steps to Reproduce
1. On Windows, write a command name and part of a filename
2. Tab complete the filename
3. Press Ctrl+C to cancel the line

xonsh should then raise the exception I've pasted above.

**Comment by scopatz** [comment]
Thanks for reporting this.  This seems like it might be a prompt-toolkit error, rather than a xonsh on.  Any thoughts @jonathanslenders?

**Comment by melund** [comment]
It is related to the second error I reported some time ago on prompt toolkit: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/690

**Comment by scopatz** [comment]
Ahh thanks @melund!

**Comment by lypanov** [comment]
I have can reproduce this stacktrace on Ubuntu on WSL, and Termux on Android. It happens randomly on CTRL-C key press but mostly during an active tab completion. It makes the shell entirely unusable when ptk is enabled to get custom keybindings.

**Comment by anki-code** [comment]
I can't reproduce this on Windows 11 with xonsh 0.23.0.
