### ISSUE TITLE
pipe from python function to an external executable does hang (Windows)

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3236]
## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.7                                                 |
| Git SHA          | 626b94db                                              |
| Commit Date      | Jun 28 17:20:28 2019                                  |
| Python           | 3.7.3                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | None                                                  |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000000002AC78D0> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x0000000002AC77B8> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## Expected Behavior
I closed the old issue (https://github.com/xonsh/xonsh/issues/3187) because the only issue left is a hang problem. It still does hang for no reason.

## Current Behavior
Still hangs.

## Steps to Reproduce
```
def pp(args):
  print(*args)
```
Example #1. Nothing prints and hangs:
```
@(pp, 123) | cmd.exe /c more
```

Example #2. Prints `123` and hangs:
```
@(pp, 123) | ./wtee.exe .log123
```

Example #3. Prints *Command `MORE.EXE` not found.* and hangs:
```
@(pp, 123) | more
```

Extactly the same results for the suggested solution:
```
def pp(args, stdin=None, stdout=None):
  print(*args, file=stdout)
```

Ideas?

**Comment by scopatz** [comment]
Hmm Do you have a traceback or any other info? Can you try running xonsh in level 1 or 2 debug mode by setting `$XONSH_DEBUG = 1` before you run the command?

**Comment by andry81** [comment]
The only traceback i have got is after the ctrl+c:

```
@(pp, 123) | cmd.exe /c more
```
```
<xonsh-code>:1:0 - @(pp, 123) | cmd.exe /c more
<xonsh-code>:1:0 + ![@(pp, 123) | cmd.exe /c more]
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\base_shell.py", line 360, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "C:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Python\x64\37\lib\site-packages\xonsh\built_ins.py", line 998, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "C:\Python\x64\37\lib\site-packages\xonsh\built_ins.py", line 961, in run_subproc
    command.end()
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2117, in end
    self._end(tee_output=tee_output)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2125, in _end
    for _ in self.tee_stdout():
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2038, in tee_stdout
    for line in self.iterraw():
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2001, in iterraw
    yield from safe_readlines(stdout)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 1763, in safe_readlines
    lines = handle.readlines(hint)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 180, in readlines
    return self._read_all_lines()
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 171, in _read_all_lines
    chunk = self.read_queue()
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 134, in read_queue
    return self.queue.get(block=True, timeout=self.timeout)
  File "C:\Python\x64\37\lib\queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "C:\Python\x64\37\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 787, in _signal_int
    self.send_signal(signum)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 941, in send_signal
    rtn = self.proc.send_signal(signal)
  File "C:\Python\x64\37\lib\subprocess.py", line 1306, in send_signal
    raise ValueError("Unsupported signal: {}".format(sig))
ValueError: Unsupported signal: 2
```

**Comment by andry81** [comment]
Seems the first example is fixed in `0.9.10`. But the others still hangs.

**Comment by andry81** [comment]
Seems the examples has been fixed in `0.9.10`. But there is another set of examples which isn't fixed:

Example # 4:
```
def pcall(args):
  args.pop(0)(*args)

@(pcall, print, 123) | cmd.exe /c more
```

Prints `123`, but hangs until interruption (`ctrl+c`) with the trace message:
```
<details>
^Cxonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\base_shell.py", line 360, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "C:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Python\x64\37\lib\site-packages\xonsh\built_ins.py", line 1003, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "C:\Python\x64\37\lib\site-packages\xonsh\built_ins.py", line 966, in run_subproc
    command.end()
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2117, in end
    self._end(tee_output=tee_output)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2125, in _end
    for _ in self.tee_stdout():
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2038, in tee_stdout
    for line in self.iterraw():
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2001, in iterraw
    yield from safe_readlines(stdout)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 1763, in safe_readlines
    lines = handle.readlines(hint)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 180, in readlines
    return self._read_all_lines()
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 171, in _read_all_lines
    chunk = self.read_queue()
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 134, in read_queue
    return self.queue.get(block=True, timeout=self.timeout)
  File "C:\Python\x64\37\lib\queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "C:\Python\x64\37\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 787, in _signal_int
    self.send_signal(signum)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 941, in send_signal
    rtn = self.proc.send_signal(signal)
  File "C:\Python\x64\37\lib\subprocess.py", line 1306, in send_signal
    raise ValueError("Unsupported signal: {}".format(sig))
ValueError: Unsupported signal: 2
</details>
```

Example # 5:
```
@(pcall, print, 123) | ./wtee.exe .log123
```

Prints `123` and hangs. The same trace message as in the Example # 4.

Example # 6:
```
@(pcall, print, 123) | more
```

Prints `123` and hangs. Different trace message after the interruption (`ctrl+c`):
```
The first string is about `Error: can not find process "1234".` or something like that.
<details>
Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\jobs.py", line 95, in wait_for_active_job
    obj.wait(0.01)
  File "C:\Python\x64\37\lib\subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "C:\Python\x64\37\lib\subprocess.py", line 1230, in _wait
    timeout_millis)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 1489, in _signal_int
    self._restore_sigint(frame=frame)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 1501, in _restore_sigint
    old(signal.SIGINT, frame)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\base_shell.py", line 360, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "C:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Python\x64\37\lib\site-packages\xonsh\built_ins.py", line 1003, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "C:\Python\x64\37\lib\site-packages\xonsh\built_ins.py", line 966, in run_subproc
    command.end()
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2117, in end
    self._end(tee_output=tee_output)
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2125, in _end
    for _ in self.tee_stdout():
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 2038, in tee_stdout
    for line in self.iterraw():
  File "C:\Python\x64\37\lib\site-packages\xonsh\proc.py", line 1924, in iterraw
    task = wait_for_active_job()
  File "C:\Python\x64\37\lib\site-packages\xonsh\jobs.py", line 99, in wait_for_active_job
    _kill(active_task)
  File "C:\Python\x64\37\lib\site-packages\xonsh\jobs.py", line 74, in _kill
    subprocess.check_output(["taskkill", "/F", "/T", "/PID", str(job["obj"].pid)])
  File "C:\Python\x64\37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Python\x64\37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['taskkill', '/F', '/T', '/PID', '5584']' returned non-zero exit status 128.
</details>
```

**Comment by andry81** [comment]
still having instable hangs in `0.9.13.dev1`

**Comment by anki-code** [comment]
I can't reproduce this on Windows 11

```xsh
@aliases.register
def _a():
    for i in range(100):
        print('stdout', i)

a | cmd /c more
# more is working
a | more
# more is working
```

I found that this is not working properly on master:
```xsh
@aliases.register
def _a():
    for i in range(100):
        echo @(i)

a | cmd /c more
# current master: more not capturing the output
# 6159: more capturing the output
```
But #6159 fixed it.
