### ISSUE TITLE
'TypeError: required field "posonlyargs" missing from arguments' when defining function in xonsh on python 3.8

### ISSUE THREAD

**Issue by jhdulaney** [xonsh/xonsh#3271]
## xonfig
```
+------------------+---------------------+
| xonsh            | 0.9.10              |
| Git SHA          | c6e168ff            |
| Commit Date      | Aug 9 15:03:58 2019 |
| Python           | 3.8.0               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.9               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.4.2               |
| on posix         | True                |
| on linux         | True                |
| distro           | fedora              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

## Expected Behavior
When defining a function, eg:
```
def some_func(some_arg):
    print(some_arg)
```
Should just define the function with no errors and I should be able to call said function at will

## Current Behavior
Crashes on noted error

### Traceback (if applicable)

```
..........

def some_func(some_arg):
    print(some_arg)
    
..........

<_ast.Interactive object at 0x7fa0d29a5790>
<class '_ast.Interactive'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_attributes', '_fields', 'body']
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILDROOT/xonsh-0.9.10-1.fc31.x86_64/usr/lib/python3.8/site-packages/xonsh/ptk2/shell.py", line 178, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/home/mock/rpmbuild/BUILDROOT/xonsh-0.9.10-1.fc31.x86_64/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 23101, in compile
    code = compile(tree, filename, mode)
TypeError: required field "posonlyargs" missing from arguments
```

## Steps to Reproduce
Run xonsh with python 3.8
define a function
failure

**Comment by gforsyth** [comment]
Hey @jhdulaney -- thanks for reporting!

I can't reproduce this on OSX.  Which Python 3.8 are you using?  I'm on 3.8.0a3 in this environment:

```
(py38) gil ~/githu/xonsh/xonsh master $ xonfig
+------------------+---------------------+
| xonsh            | 0.9.10              |
| Git SHA          | aae977c4            |
| Commit Date      | Aug 6 12:40:51 2019 |
| Python           | 3.8.0               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.9               |
| shell type       | prompt_toolkit2     |
| pygments         | None                |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
(py38) gil ~/githu/xonsh/xonsh master $ def func(some_arg):
.......................................     print(some_arg)
.......................................
(py38) gil ~/githu/xonsh/xonsh master $ func('hi')
hi
(py38) gil ~/githu/xonsh/xonsh master $ python --version
Python 3.8.0a3
```

**Comment by jhdulaney** [comment]
3.8.0b3 on Linux

**Comment by jhdulaney** [comment]
I got it figured out, will try and have a pull request shortly.

**Comment by scopatz** [comment]
Excellent! I look forward to the PR @jhdulaney!

**Comment by carmenbianca** [comment]
I have the same error while running the tests during the building of the RPM for Fedora 32:

```
/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/bin/xonsh run-tests.xsh
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/bin/xonsh", line 4, in <module>
    main()
  File "/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 24011, in main
    _failback_to_other_shells(args, err)
  File "/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 23975, in _failback_to_other_shells
    raise err
  File "/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 24009, in main
    return main_xonsh(args)
  File "/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 24052, in main_xonsh
    run_script_with_cache(
  File "/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 3036, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 2995, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "/builddir/build/BUILDROOT/xonsh-0.9.10-3.fc32.x86_64/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 23095, in compile
    code = compile(tree, filename, mode)
TypeError: required field "posonlyargs" missing from arguments
error: Bad exit status from /var/tmp/rpm-tmp.TyaM7t (%check)
    Bad exit status from /var/tmp/rpm-tmp.TyaM7t (%check)
```
