### ISSUE TITLE
lambda with an environment variable `${...}` gives NameError

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3296]
## xonfig

<details>

```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.11                                                |
| Git SHA          | dd16d59d                                              |
| Commit Date      | Aug 25 13:21:16 2019                                  |
| Python           | 3.7.4                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | None                                                  |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x0000000002ACA788> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x0000000002ACAD88> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## Expected Behavior
The same way as for the usual python variable.

## Current Behavior
`NameError: name 'x' is not defined`
or
`SyntaxError: <xonsh-code>:1:16: ('code: del',)`

## Steps to Reproduce
```
foo = lambda x: del ${x}
```
<details>

```
Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\base_shell.py", line 360, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "C:\Python\x64\37\lib\site-packages\xonsh\codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'x' is not defined
```

</details>

```
foo = lambda x: del ${...}[x]
```
<details>

```
Traceback (most recent call last):
  File "C:\Python\x64\37\lib\site-packages\xonsh\ptk2\shell.py", line 178, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "C:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "C:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "C:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 235, in _parse_ctx_free
    raise original_error from None
  File "C:\Python\x64\37\lib\site-packages\xonsh\execer.py", line 220, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "C:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "C:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Python\x64\37\lib\site-packages\xonsh\ply\ply\yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "C:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 3299, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "C:\Python\x64\37\lib\site-packages\xonsh\parsers\base.py", line 676, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:16: ('code: del',)
foo = lambda x: del ${...}[x]
```

</details>

**Comment by astronouth7303** [comment]
`del` is a statement in python and not valid in a lambda.

**Comment by andry81** [comment]
I've made a workaround:
```
def delvar(x):
  del ${x}
foo = lambda x: delvar(x)
```

**Comment by astronouth7303** [comment]
Per the `MutableMapping` spec, there is also the `.pop()` method.

See `help(${...})`.

**Comment by andry81** [comment]
> Per the `MutableMapping` spec, there is also the `.pop()` method.

Is that more effective than `del`?

**Comment by astronouth7303** [comment]
Define "effective"? They will both delete the item. They both raise a KeyError if it doesn't exist.

**Comment by andry81** [comment]
> Define "effective"?

If it does the same, then the function call like `pop()` would be slower than a direct delete by an reference I think.

**Comment by TeamSpen210** [comment]
They run about the same code. Pop might be slightly slower because of the overhead of method calls, but it's on the order of microseconds.
