### ISSUE TITLE
ValueError: Wrong color format 'ansibrightblack'

### ISSUE THREAD

**Issue by chatumao** [xonsh/xonsh#3303]
I installed xonsh via apt on Xubuntu 18, and I also used the setup.py method from a recent pull, a couple of days ago. What I get when I  start xonsh is a traceback.

Version 0.9.11.

## Expected Behavior
I expect to enter the xonsh shell and start experiencing the awesomeness.

## Current Behavior
$ env XONSH_DEBUG=1 xonsh
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xonsh/main.py", line 402, in main
    return main_xonsh(args)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/main.py", line 428, in main_xonsh
    print_welcome_screen()
  File "/usr/local/lib/python3.6/dist-packages/xonsh/xonfig.py", line 759, in print_welcome_screen
    print_color(line)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/tools.py", line 1744, in print_color
    builtins.__xonsh__.shell.shell.print_color(string, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/ptk/shell.py", line 296, in print_color
    proxy_style = PygmentsStyle(pyghooks.xonsh_style_proxy(self.styler))
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_pygments.py", line 64, in __new__
    return style_from_dict(pygments_style_cls.styles)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py", line 124, in style_from_dict
    attrs = attrs._replace(color=_colorformat(part))
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py", line 39, in _colorformat
    raise ValueError('Wrong color format %r' % text)
ValueError: Wrong color format 'ansibrightblack'
Xonsh encountered an issue during launch
Failback to /bin/sh

I know an issue of this kind was filed last year, but I don't believe that it is the same issue. My pygments version is 2.4.2.

Any help appreciated.

**Comment by gforsyth** [comment]
Thanks for reporting @chatumao -- @melund, do you have any ideas on this?  I remember you fixing a bunch of similar issues not too long ago (or maybe it was years ago? )

**Comment by melund** [comment]
It was probably a few years ago. Time flies.... I don't know what is causing this. 

@chatumao could  you try to update prompt toolkit. Preferably even switch to prompt toolkit 2.

**Comment by chatumao** [comment]
@melund Thank you kind sir :)

**Comment by salotz** [comment]
Had the same thing. I uninstalled the system 'python3-prompt-toolkit' and it fixed the issue.

**Comment by anki-code** [comment]
I've tested `apt install xonsh` on Xubuntu 20 and it works perfect:

![Screenshot_20201007_132339](https://user-images.githubusercontent.com/1708680/95319304-6360a600-08a0-11eb-8eab-fbc6b63ec41b.png)

One thing is old xonsh version.

I suggest to close this issue.
