### ISSUE TITLE
WSL1: ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3367]
Hi! Thank you for the great solution!

I've catch `ValueError: I/O operation on closed file` in WSL1 when try to customize prompt. But simple case to repeat is:
```
$ cat 1.xsh
#!/usr/bin/env xonsh

for i in range(0, 10):
  a=$(echo @(i))
  print("a=%s" % a)
```

Every run 1.xsh in WSL1 can return different result:

1. No error and no result:
```
a=0
a=1
a=2

^Z
a=
a=4
a=5
a=6
a=7
a=8
a=9
```

2. Error on line 14199:
```
a=4

^Z
a=
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14199, in run
    procerr = NonBlockingFDReader(caperr.fileno(), timeout=self.timeout)
ValueError: I/O operation on closed file

a=6
```

3. Error on line 14266:
```
a=2

^Z
a=
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14201, in run
    self._read_write(procout, stdout, sys.__stdout__)
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14266, in _read_write
    writer.flush()
ValueError: I/O operation on closed file.

a=4
```

4. And without error (rare case):
```
# ./1.xsh
a=0
a=1
a=2
a=3
a=4
a=5
a=6
a=7
a=8
a=9
```

```
# xonfig
+------------------+-----------------+
| xonsh            | 0.9.13          |
| Python           | 3.7.3           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | True            |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

It looks like I can repeat it only in WSL1. Please help to fix it. Thanks!

**Comment by anki-code** [comment]
I've got this error when I just copy:
```
$(date)
$(date)
$(date)
$(date)
$(date)
$(date)
```
and paste:
```
(base) root@abc ~ # $(date)
'Mon 21 Oct 2019 09:48:48 PM MSK\n'
(base) root@abc ~ # $(date)
'Mon 21 Oct 2019 09:48:48 PM MSK\n'
(base) root@abc ~ # $(date)
^Z
Exception in thread Thread-631:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14201, in run
    self._read_write(procout, stdout, sys.__stdout__)
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14266, in _read_write
    writer.flush()
ValueError: I/O operation on closed file.
''
```

**Comment by anki-code** [comment]
I've tried to repeat this on Linux but it was not repeated. Could you please try to repeat in WSL1 and Linux too?

**Comment by anki-code** [comment]
This bug made WSL unusable and unstable for xonsh.
```
$ cat 1.xsh
#!/usr/bin/env xonsh

for i in range(0, 10):
        a=$(echo 123)
        print("a=%s" % a)
```
```
$ ./1.xsh
a=123
a=123
a=123
a=123

^Z
a=
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14199, in run
    procerr = NonBlockingFDReader(caperr.fileno(), timeout=self.timeout)
ValueError: I/O operation on closed file

a=123
a=123
a=123
a=123
a=123
```

**Comment by anki-code** [comment]
Every run 1.xsh can return different result:

1. No error and no result:
```
a=0
a=1
a=2

^Z
a=
a=4
a=5
a=6
a=7
a=8
a=9
```

2. Error on line 14199:
```
a=4

^Z
a=
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14199, in run
    procerr = NonBlockingFDReader(caperr.fileno(), timeout=self.timeout)
ValueError: I/O operation on closed file

a=6
```

3. Error on line 14266:
```
a=2

^Z
a=
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14201, in run
    self._read_write(procout, stdout, sys.__stdout__)
  File "/root/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 14266, in _read_write
    writer.flush()
ValueError: I/O operation on closed file.

a=4
```

4. And without error (rare case):
```
# ./1.xsh
a=0
a=1
a=2
a=3
a=4
a=5
a=6
a=7
a=8
a=9
```

**Comment by anki-code** [comment]
Closed because WSL2 is on the way.
