### ISSUE TITLE
xonfig wizard throws runtime-error

### ISSUE THREAD

**Issue by gragundier** [xonsh/xonsh#3405]
## xonfig

<details>

```
$ xonfig
```

</details>

## Expected Behavior

xonfig wizard should proceed as normal
## Current Behavior

xonfig wizard throws error

### Traceback (if applicable)

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 17049, in _wizard
    pv.visit()
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 635, in visit
    rtn = super().visit(node)
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 457, in visit
    rtn = meth(node)
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 720, in visit_wizard
    self.visit(child)
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 635, in visit
    rtn = super().visit(node)
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 457, in visit
    rtn = meth(node)
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 779, in visit_while
    while node.cond(visitor=self, node=node):
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 425, in truefalse_cond
    rtn = visitor.visit(tf)
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 635, in visit
    rtn = super().visit(node)
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 457, in visit
    rtn = meth(node)
  File "/usr/lib/python3.8/site-packages/xonsh/wizard.py", line 740, in visit_input
    raw = self.shell.singleline(**self.shell_kwargs)
  File "/usr/lib/python3.8/site-packages/xonsh/ptk2/shell.py", line 165, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 986, in prompt
    return self.app.run()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 788, in run
    return get_event_loop().run_until_complete(self.run_async(pre_run=pre_run))
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-12'.
```

</details>

## Steps to Reproduce

```
                   -`                    gragundier@gragundier-pc-desktop 
                  .o+`                   -------------------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Z97X-Gaming 3 
               `+oooooo:                 Kernel: 5.4.3-arch1-1 
               -+oooooo+:                Uptime: 7 hours, 38 mins 
             `/:-:++oooo+:               Packages: 1069 (pacman) 
            `/++++/+++++++:              Shell: xonsh 0.9.13 
           `/++++++++++++++:             DE: Plasma 
          `/+++ooooooooooooo/`           WM: KWin 
         ./ooosssso++osssssso+`          WM Theme: QuasiDeepinDarkII 
        .oossssso-````/ossssss+`         Theme: Breeze-Dark [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: Deepin Dark [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       Terminal Font: Hack 10 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-4790K (8) @ 4.400GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel HD Graphics 
 `++:.                           `-/+/   GPU: NVIDIA GeForce RTX 2080 Rev. A 
 .`                                 `/   Memory: 2389MiB / 15865MiB 

```
+------------------+-----------------+
| xonsh            | 0.9.13          |
| Python           | 3.8.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.2           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.5.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

**Comment by gforsyth** [comment]
Hey @gragundier -- thanks for reporting!  I'm pretty sure this is because we haven't added support for `prompt_toolkit>2` yet -- if you downgrade prompt_toolkit to a v2 release everything should work.  Alternatively, you can force the `readline` backend (which is slightly less featureful) using `--shell-type readline`

**Comment by gragundier** [comment]
@gforsyth Thanks, I'll wait for the update.  Closing issue.

**Comment by duncreg** [comment]
I tried installing all of the prompt-toolkit 2.0.x line and none of them fixed the problem. The readline workaround did though.
