### ISSUE TITLE
Exception 'Window' object has no attribute 'children'

### ISSUE THREAD

**Issue by swedneck** [xonsh/xonsh#3424]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.13.dev1          |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.7.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.2                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | fedora               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior

Running `ls` quickly after typing out the command should not result in an error message.

## Current Behavior

Running `ls` quickly after typing out the command results in an error message.

### Traceback (if applicable)

<details>

```
Unhandled exception in event loop:
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/prompt_toolkit/eventloop/async_generator.py", line 43, in runner
    for item in get_iterable():
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/ptk2/completer.py", line 63, in get_completions
    self.reserve_space()
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/ptk2/completer.py", line 95, in reserve_space
    window = app.layout.container.children[0].content.children[1].content

Exception 'Window' object has no attribute 'children'
```

</details>

## Steps to Reproduce

Type out `ls` and immediately hit enter.

**Comment by scopatz** [comment]
I think you are prompt-toolkit v3, which we don't support yet.

**Comment by laloch** [comment]
PTK3 user here. No issues whatsoever. Can't reproduce this one either.

**Comment by scopatz** [comment]
We should have proper ptk3 support though ;)

**Comment by laloch** [comment]
For us "proper ptk3 support" is mostly declarative - there are no changes in ptk3 relevant to Xonsh.

**Comment by scopatz** [comment]
Yeah, that is probably true.  I haven't looked into it at all, but we should have that declaration

**Comment by swedneck** [comment]
maybe the installation instructions need to be fixed then? i just ran `pip3 install xonsh`..

**Comment by gforsyth** [comment]
@swedneck -- can you try upgrading `xonsh` please?  We do need to add a proper ptk3 declaration but I'm able to run using ptk3 without issue.

**Comment by swedneck** [comment]
do i just run `pip3 install --user --upgrade xonsh`?

**Comment by gforsyth** [comment]
That will work.  I would recommend running that command as `python -m pip install --user --upgrade xonsh` -- that will ensure that when you are using environments of any kind (virtualenv, conda, etc) that you are using the `pip` that you _think_ you are using.

**Comment by swedneck** [comment]
hmm, well now i can't even run xonsh..
```
Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24142, in main
    return main_xonsh(args)
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24171, in main_xonsh
    shell.shell.cmdloop()
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 197, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 101, in singleline
    self.styler.style_name = env.get("XONSH_COLOR_STYLE")
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 17713, in styler
    self._styler = XonshStyle(env.get("XONSH_COLOR_STYLE"))
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/pyghooks.py", line 346, in __init__
    self.style_name = style_name
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/pyghooks.py", line 385, in style_name
    color_token = color_token_by_name(xonsh_color, self.styles)
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/pyghooks.py", line 224, in color_token_by_name
    pc = color_name_to_pygments_code(xc[0], styles)
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/pyghooks.py", line 144, in color_name_to_pygments_code
    if token in styles:
  File "/usr/lib64/python3.7/collections/__init__.py", line 931, in __contains__
    return any(key in m for m in self.maps)
  File "/usr/lib64/python3.7/collections/__init__.py", line 931, in <genexpr>
    return any(key in m for m in self.maps)
  File "/usr/lib64/python3.7/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/pyghooks.py", line 313, in __getitem__
    value = code_by_name(name, self.styles)
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/pyghooks.py", line 206, in code_by_name
    code = color_name_to_pygments_code(fg, styles)
  File "/home/tim/.local/lib/python3.7/site-packages/xonsh/pyghooks.py", line 148, in color_name_to_pygments_code
    raise ValueError("{!r} is not a color!".format(name))
ValueError: 'TARGET' is not a color!
Xonsh encountered an issue during launch
Failback to /bin/sh
```

should i open a new issue for this?

**Comment by gforsyth** [comment]
That sounds like a regression -- can you delete the `$LS_COLORS` env-var and try relaunching `xonsh`?  (I'm assuming you are launching `xonsh` from `bash` or `zsh` or similar)

**Comment by swedneck** [comment]
ah yes, that fixed it.
Okay so it definitely seems better now than with the previous version, but i'm still getting the error when i consciously spam `ls` while suggestions are enabled.

**Comment by swedneck** [comment]
Just noticed something, it only seems to happen when there are multiple lines of output.  
Also, after running `ls` multiple times with UPDATE_COMPLETIONS_ON_KEYPRESS enabled the shell seems to get stuck when i try to `exit` it.

**Comment by gforsyth** [comment]
Ah, ok.  I think `UPDATE_COMPLETIONS_ON_KEYPRESS` can cause a lot of problems.  Can you confirm that the window error only occurs when that is enabled?

**Comment by gforsyth** [comment]
this sounds like an ugly race condition where the `update` call is hit while ptk is still redrawing the prompt

**Comment by swedneck** [comment]
i can confirm it only happens with UPDATE_COMPLETIONS_ON_KEYPRESS enabled

**Comment by gforsyth** [comment]
Thanks for checking!  Ok, the workaround, then, is to disable `UPDATE_COMPLETIONS_ON_KEYPRESS` until we can figure out how to harden that.

**Comment by swedneck** [comment]
alright, thanks!

**Comment by swedneck** [comment]
Should i go ahead and close this issue?

**Comment by scopatz** [comment]
I think it is OK to keep open as long as it exists

**Comment by gforsyth** [comment]
> I think it is OK to keep open as long as it exists

Agreed.  @swedneck -- could you update the issue title and description to reflect that the issue is related to the update keypress variable?  It'll make it easier for us to triage in the future.

Thanks for being so responsive and helping us narrow this down!

**Comment by swedneck** [comment]
of course! I really want to be able to use xonsh as my daily driver so i'm more than glad to help troubleshoot issues i run into :D
