### ISSUE TITLE
xonsh not running after installation : No module named 'prompt_toolkit.key_binding.manager'

### ISSUE THREAD

**Issue by malijani** [xonsh/xonsh#3439]
Thanks for creating xonsh shell !

after running xonsh this happend : 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 20657, in main
    args = premain(argv)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 20610, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 20562, in start_services
    builtins.__xonsh_shell__ = Shell(execer=execer, **shell_kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 13132, in __init__
    from xonsh.ptk.shell import PromptToolkitShell as shell_class
  File "/usr/lib/python3/dist-packages/xonsh/ptk/shell.py", line 6, in <module>
    from prompt_toolkit.key_binding.manager import KeyBindingManager
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.manager'
Xonsh encountered an issue during launch
Failback to /bin/sh
$ 

I'm running **Linux Mint 19.2 Tina x86_64** 

python --version
Python 3.6.9

installed by **apt** : `apt install xonsh`

**Comment by gforsyth** [comment]
Hi @malijani ! Can you check which version of prompt toolkit you have installed? And how did you install xonsh?

We currently support prompt_toolkit versions 1 and 2 -- we haven't added support for version 3 yet

**Comment by malijani** [comment]
Thanks for the fast response @gforsyth :rose: 
I installed xonsh using **apt** package manager : `apt install xonsh`

And  `python3-prompt-toolkit` version *1.0.15-1* is installed but error remains.

But there's no problem with installing xonsh by pip3 and it runs great.

After installing `prompt_toolkit==1.0` and using xonsh installed by *apt* error gets bigger: 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 20657, in main
    args = premain(argv)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 20610, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 20562, in start_services
    builtins.__xonsh_shell__ = Shell(execer=execer, **shell_kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 13122, in __init__
    elif not ptk_version_is_supported():
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 1014, in ptk_version_is_supported
    return ptk_version_info()[:2] >= minimum_required_ptk_version
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 1006, in ptk_version_info
    return tuple(int(x) for x in ptk_version().strip('<>+-=.').split('.'))
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 996, in ptk_version
    import prompt_toolkit
  File "/home/emperor/.local/lib/python3.6/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/emperor/.local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 18, in <module>
    from .application import Application, AbortAction
  File "/home/emperor/.local/lib/python3.6/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/emperor/.local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 36, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/home/emperor/.local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "/home/emperor/.local/lib/python3.6/site-packages/prompt_toolkit/completion/__init__.py", line 1, in <module>
    from .base import (
  File "/home/emperor/.local/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 7, in <module>
    from prompt_toolkit.eventloop import generator_to_async_generator
ImportError: cannot import name 'generator_to_async_generator'
Xonsh encountered an issue during launch
Failback to /bin/sh
$ 

I think DEB package need some fixing. idk

**Comment by gforsyth** [comment]
Glad you got it working! So Debian lags pretty far behind our dev cycle -- we added prompt toolkit 2 support 18 months ago, so I would suggest you also install xonsh using pip or conda if you want to take advantage of newer features.

**Comment by malijani** [comment]
Yeah I'll do that; thanks for suggestion :rose: the new features are also cool and helpful particularly the command colour formatting , I think it's better to close the issue cause my problem is solved by your help.
