### ISSUE TITLE
from selenium import webdriver; AttributeError with pkgutil

### ISSUE THREAD

**Issue by wereii** [xonsh/xonsh#3458]
Importing webdriver from selenium fails in xonsh with `AttributeError: 'NoneType' object has no attribute 'decode'` as `pkgutil.get_data` returns `None`. (see traceback)

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.13.dev1          |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.7.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.10               |
| shell type       | prompt_toolkit2      |
| pygments         | 2.5.2                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior

`webdriver` should get imported without error.

## Current Behavior

Fails with exception. If I hop into xonsh then `python3` and then try it again it works without problem. 

### Traceback

<details>

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/tomas/.local/lib/python3.7/site-packages/xonsh/base_shell.py", line 360, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/home/tomas/.local/lib/python3.7/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/tomas/.local/lib/python3.7/site-packages/xonsh/imphooks.py", line 291, in exec_module
    rtn = self.loader.exec_module(module)
  File "/home/tomas/.local/lib/python3.7/site-packages/selenium/webdriver/__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/tomas/.local/lib/python3.7/site-packages/xonsh/imphooks.py", line 291, in exec_module
    rtn = self.loader.exec_module(module)
  File "/home/tomas/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 29, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/tomas/.local/lib/python3.7/site-packages/xonsh/imphooks.py", line 291, in exec_module
    rtn = self.loader.exec_module(module)
  File "/home/tomas/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 26, in <module>
    from .webelement import WebElement
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/tomas/.local/lib/python3.7/site-packages/xonsh/imphooks.py", line 291, in exec_module
    rtn = self.loader.exec_module(module)
  File "/home/tomas/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 43, in <module>
    getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

</details>

#### Readable Traceback

<details>

```python

Traceback (Most recent call last):
360 /home/tomas/.local/lib/python3.7/site-packages/xonsh/base_shell.py default --> run_compiled_code(code, self.ctx, None, "single")
67 /home/tomas/.local/lib/python3.7/site-packages/xonsh/codecache.py run_compiled_code --> func(code, glb, loc)
1 <xonsh-code> <module> --> 
983 <frozen importlib._bootstrap> _find_and_load --> 
967 <frozen importlib._bootstrap> _find_and_load_unlocked --> 
677 <frozen importlib._bootstrap> _load_unlocked --> 
291 /home/tomas/.local/lib/python3.7/site-packages/xonsh/imphooks.py exec_module --> rtn = self.loader.exec_module(module)
18 /home/tomas/.local/lib/python3.7/site-packages/selenium/webdriver/__init__.py <module> --> from .firefox.webdriver import WebDriver as Firefox  # noqa
983 <frozen importlib._bootstrap> _find_and_load --> 
967 <frozen importlib._bootstrap> _find_and_load_unlocked --> 
677 <frozen importlib._bootstrap> _load_unlocked --> 
291 /home/tomas/.local/lib/python3.7/site-packages/xonsh/imphooks.py exec_module --> rtn = self.loader.exec_module(module)
29 /home/tomas/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py <module> --> from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
983 <frozen importlib._bootstrap> _find_and_load --> 
967 <frozen importlib._bootstrap> _find_and_load_unlocked --> 
677 <frozen importlib._bootstrap> _load_unlocked --> 
291 /home/tomas/.local/lib/python3.7/site-packages/xonsh/imphooks.py exec_module --> rtn = self.loader.exec_module(module)
26 /home/tomas/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py <module> --> from .webelement import WebElement
983 <frozen importlib._bootstrap> _find_and_load --> 
967 <frozen importlib._bootstrap> _find_and_load_unlocked --> 
677 <frozen importlib._bootstrap> _load_unlocked --> 
291 /home/tomas/.local/lib/python3.7/site-packages/xonsh/imphooks.py exec_module --> rtn = self.loader.exec_module(module)
44 /home/tomas/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py <module> --> getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'

```
</details>

## Steps to Reproduce
- Install latest from pip[3]:
  - `xonsh`
  - `selenium`
- In xonsh, run `from selenium import webdriver`.

**Comment by wereii** [comment]
### My debuggings

- the `_pkg` variable in call `pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')` equals to `"selenium.webdriver.remote"` 
- the `getAttribute.js` is a file in same directory as the file which fails (`webelement.py`) eg. `.../site-packages/selenium/webdriver/remote/`
- `dir()` on selenium module [`import selenium; dir(selenium)`]:
  - in **Xonsh**:
      <details>

    ```
    ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'common']
    ```

    </details>
  - in **Python**:
    <details>

    ```
    ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'common', 'webdriver']
    ```

    </details>
   - `selenium.webdriver` **is missing in Xonsh's dir()**
- The selenium module is the same in both Xonsh and native Python (tested by issuing `>>> selenium` or `print(selenium)`, path matches)

**Comment by scopatz** [comment]
Hi there @wereii - I can't reproduce this with conda. Everything seems to import fine.  Here is my environment:

```bash
$ conda list -n seltest                                                                         
# packages in environment at /home/scopatz/miniconda/envs/seltest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
cffi                      1.13.2           py38h8022711_0    conda-forge
cryptography              2.8              py38h72c5cf5_1    conda-forge
idna                      2.9                        py_1    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pycparser                 2.19                       py_2    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1                    py38_0    conda-forge
python                    3.8.2           h9d8adfe_1_cpython    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
selenium                  3.141.0         py38h516909a_1000    conda-forge
setproctitle              1.1.10          py38h516909a_1001    conda-forge
setuptools                45.2.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
urllib3                   1.25.7                   py38_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xonsh                     0.9.14                   py38_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by wereii** [comment]
Well conda is completly different environment, so at least we know it doesn't happen there:)

**Comment by anki-code** [comment]
I can't reproduce this.

```python
docker run --rm -it python:3.9-slim /bin/bash -c @("""
pip install 'xonsh[full]' selenium
xonsh
""")

from selenium import webdriver
webdriver
# <module 'selenium.webdriver' from '/usr/local/lib/python3.9/site-packages/selenium/webdriver/__init__.py'>
```
