### ISSUE TITLE
Cannot back cursor after capturing standard output stream

### ISSUE THREAD

**Issue by wotsushi** [xonsh/xonsh#3491]
I cannot back cursor of my terminal after capturing standard output stream by using `$()`.

## xonfig

- I have confirmed that there is **no** problem when I use xonsh 0.9.13.dev1.
- I have confirmed that this problem **occurs** when I use xonsh 0.9.14 or 0.9.15.

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.15               |
| Git SHA          | feeb6315             |
| Commit Date      | Mar 19 10:50:33 2020 |
| Python           | 3.8.2                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior

The cursor of input buffer backs.

## Current Behavior

- The cursor of input buffer does not back.
- `^[[D` is inserted into input buffer of your terminal

## Steps to Reproduce

1.  Run `source set_keybind.xsh`. Here, `set_keybind.xsh` is the following script.

```xonsh
from prompt_toolkit.keys import Keys

@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    handler = bindings.add

    @handler(Keys.ControlQ)
    def capture_stdout(event):
    	_ = $(echo 1).strip()
```

2. Press `A`. Then input buffer of your terminal is `a`.

```
$ a
```

3. Press `C-q` (hold Ctrl and press `Q`) to call `capture_stdout` that captures standard output stream.
4. Press left arrow key. Then `^[[D` is inserted into input buffer of your terminal.

```
$ a^[[D
```

**Comment by laloch** [comment]
Hi @wotsushi, thanks for reporting! I can't reproduce the issue.
Does issuing `reset` on the command line recover the cursor keys functionality?
If it does, I suspect [this commit](https://github.com/xonsh/xonsh/commit/6082b61fc3cc6db05351fd4c35e54cbb58633cef) to be the culprit. @bobhy, do you think it's possible?
I would suggest to try to revert the suspected commit, but the commit itself is such a mess that I don't really think it can be easily reverted :-(

**Comment by wotsushi** [comment]
Hi @laloch , thank you for the fast answer.

> Does issuing reset on the command line recover the cursor keys functionality?

Yes.
It seems that the cursor keys recover after the input buffer flush.

BTW, press `C-c` (hold `Ctrl` and press `C`) after step 4 in steps to reproduce, then my input does not cancel but the following traceback is printed.

```
$ 1^[[D^CTraceback (most recent call last):
  File "/Users/wotsushi/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 24189, in main
    return main_xonsh(args)
  File "/Users/wotsushi/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 24218, in main_xonsh
    shell.shell.cmdloop()
  File "/Users/wotsushi/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/xonsh/ptk2/shell.py", line 197, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/Users/wotsushi/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/xonsh/ptk2/shell.py", line 166, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/Users/wotsushi/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 994, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/Users/wotsushi/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 811, in run
    return loop.run_until_complete(
  File "/Users/wotsushi/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/wotsushi/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 614, in run_async
    assert not self._is_running, "Application is already running."
AssertionError: Application is already running.
Xonsh encountered an issue during launch
Failback to /bin/bash
bash-3.2$
```

I hope the stacktrace will help.

**Comment by bobhy** [comment]
Hi @wotsushi,
Sorry, I cannot repro the failure either.  When I press ^Q, nothing appears on the input line, but I can then press either left arrow or ^C and have them behave as expected.  Is your test case intended to display the captured text ( '1') on the input line?  
Here is a modification of your test that does (stolen directly from the xonsh doc, I have not messed with keybindings before).  When I press ^Q with this one, it does add 11 to the input and I can again press left arrow and have it move the cursor.  Please give it a try and LMK what happens.
```python
from prompt_toolkit.keys import Keys

@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    handler = bindings.add

    @handler(Keys.ControlQ)
    def capture_stdout(event):
	event.current_buffer.insert_text($(echo 11).strip())
```
Another experiment I'd suggest is to rebind your function to ^W instead of ^Q (the latter having a historical default function,a let me know if it matters which control char you bind.
 
Lots of layers process keystrokes before prompt_toolkit,  it's difficult to get  the configuration information that's important for creating the repro.  But if you could mention the version of Linux, graphical shell and terminal or console program you're using along with the value of $TERM, that would be a start.

**Comment by bobhy** [comment]
I've got a repro which succeeds or fails for the same text being inserted into the command buffer, depending only(?) on whether the captured subcommand generated the output via `cat` or `ls`.  And I think the incremental lexing is involved because I'm seeing secondary dot prompts for multi-line input, lexer has not got a complete expression yet. But I've simplified the failure down to the python mode, subcommand parsing is not involved. So if the old hands ( @laloch , @scopatz ) would take a look too, we'll make faster progress.

Here's the scenario:
Define ^Q and ^W as shortcuts that insert the same multiline input into command buffer, one via `ls` and the other by `cat`.  (Switching ^Q to be the one that works, to satisfy some lingering superstitions of my own...)

```python
ls -l --color=never > out.txt
ls -l --color=never > out.txt  # so size of out.txt appears in the list...

from prompt_toolkit.keys import Keys

@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    handler = bindings.add

    @handler(Keys.ControlQ)
    def capture_stdout(event):
	event.current_buffer.insert_text($(cat out.txt))

    @handler(Keys.ControlW)
    def capture_stdout(event):
	event.current_buffer.insert_text($(ls -l --color=never))
```
Now invoke these bindings in the context of a python expression which accepts multiline input: triple double quote string:

```bash
$ print("""[- ^Q -]total 24       <=== ^Q replaced by cat'ed string: this will be editable!
. -rw-r--r-- 1 bob bob 257 Mar 29 19:56 1kb.xsh 
. -rw-r--r-- 1 bob bob   0 Mar 29 21:23 out.txt 
. drwx------ 2 bob bob   7 Mar 24 17:46 phonelist 
. -rw-r--r-- 1 bob bob 463 Mar 29 21:23 set_keybind.xsh 
. [- left arrow -][- up arrow -][- down arrow -][- right arrow -]""")       <== arrows work as expected
. [- enter -]                                                                                                                      
total 24
-rw-r--r-- 1 bob bob 257 Mar 29 19:56 1kb.xsh
-rw-r--r-- 1 bob bob   0 Mar 29 21:23 out.txt
drwx------ 2 bob bob   7 Mar 24 17:46 phonelist
-rw-r--r-- 1 bob bob 463 Mar 29 21:23 set_keybind.xsh

~~~~~~~~~~~~ (current) bob@bob-desktop ~/work  ~~~~~~~~~~~~                                                             
$ print("""[- ^W -]total 24                    <=== ^W replaced by ls output (same strings as above)
. -rw-r--r-- 1 bob bob 257 Mar 29 19:56 1kb.xsh 
. -rw-r--r-- 1 bob bob 203 Mar 29 21:23 out.txt 
. drwx------ 2 bob bob   7 Mar 24 17:46 phonelist 
. -rw-r--r-- 1 bob bob 463 Mar 29 21:23 set_keybind.xsh 
. [- right arrow -]^[[C[- up arrow -]^[[A[- down arrow -]^[[B""")       <=== editing does *not* work.                                                                                                   
. """) 
.  ```

**Comment by bobhy** [comment]
... and now I know that xonsh provides a callable alias for `cat` but not for `ls`.  And there's a lot of code in xonsh/built_ins.py that invokes those cases differently, which probably explains the different behavior above.  There's mucking about with ioctl in there, too; always a bad sign for proper preservation of terminal modes set by caller.  But no smoking gun yet...

**Comment by scopatz** [comment]
Does this only happen on prompt-toolkit?

**Comment by bobhy** [comment]
Happens with $SHELL_TYPE prompt_toolkit2, custom key bindings not supported in readline.  Having problems running prompt_toolkit1.  It is supported with package prompt-toolkit 3.0.4?

**Comment by laloch** [comment]
prompt_toolkit 3.x is not officially supported yet. There are, however, currently no known issues related to PTK3.

**Comment by scopatz** [comment]
Yeah, we should work on getting PTK3 up and running officially

**Comment by bobhy** [comment]
I would take a crack at that if it meant I could drop ptk1 at the same time.

Are there any ptk3 specific features you'd like to see added?

**Comment by melund** [comment]
I am all for dropping PTK1 support. That would be great.

**Comment by laloch** [comment]
> Are there any ptk3 specific features you'd like to see added?

There's already an open issue for ptk3 support: #3391.
What's needed basically is `--shell-type` and `$SHELL_TYPE` option for ptk3 and documentation updates where appropriate. Internally, I would prefer not to distinguish between ptk2 and ptk3 for the time being since, as far as I can tell, there were no changes affecting us so far.

**Comment by scopatz** [comment]
Yeah, we can definitely drop PTK1 support at this time

**Comment by deeuu** [comment]
Hey,

Is anyone having success now that the ptk3 is supported? I'm running into issues but can't reproduce reliably (seems to depend on the terminal emulator).
Using the macos `Terminal`:
```
$ xonsh --shell-type 'ptk3' --no-rc
$ xonfig                                                                                                                           
+------------------+-----------------+
| xonsh            | 0.9.18          |
| Python           | 3.8.3           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit  |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

$ cat temp.xsh                                                                                                                     
from prompt_toolkit.keys import Keys

@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    handler = bindings.add

    @handler(Keys.ControlW)
    def capture_stdout(event):
	event.current_buffer.insert_text($(echo "Hello").strip())

$ source temp.xsh
$ Hello # pressed C and w
```
(can't back cursor)

Strangely, it works as expected (can back cursor) in `Alacritty`, but then subsequent processes get sent to the background. This also means that adding key bindings to programs like `fzf` simply do not work.

**Comment by deeuu** [comment]
oopps I should add, this only reproducible when not using `echo` from `xoreutils` (needs a subprocess).

**Comment by anki-code** [comment]
I can reproduce this using steps from the first message on xonsh 0.9.26 with ptk3.
