### ISSUE TITLE
comment ending in colon (:) sometimes leads to a syntax error on the next line

### ISSUE THREAD

**Issue by das-g** [xonsh/xonsh#3502]
## xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.14          |
| Python           | 3.7.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.5.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior
Punctuation in comments should be ignored

## Current Behavior

In some situations, a comment ending in a colon (`:`) leads to a syntax error on the next line, that doesn't occur without that comment.

### Traceback (if applicable)

<details>

From
```
$XONSH_SHOW_TRACEBACK = True
# This comment ends in a colon:
echo "hello world"
```

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/ptk2/shell.py", line 181, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/execer.py", line 271, in _parse_ctx_free
    raise original_error
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/execer.py", line 220, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/parsers/base.py", line 3299, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/nix/store/065c22xxxd3v2a84vnhki5dgvlbnf7b3-xonsh-0.9.14/lib/python3.7/site-packages/xonsh/parsers/base.py", line 676, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:2:5: ('code: "hello world"',)
echo "hello world"
     ^
```

</details>

### quoted argument
Running
```xonsh
# This comment ends in a colon:
echo "hello world"
```
leads to
```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: <xonsh-code>:2:5: ('code: "hello world"',)
echo "hello world"
     ^
```

But
```xonsh
# This comment does not end in a colon.
echo "hello world"
```
works fine.

### unquoted argument
Running
```xonsh
# This comment ends in a colon:
echo hello world
```
leads to
```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: <xonsh-code>:2:5: ('code: hello',)
echo hello world
     ^
```

But
```xonsh
# This comment does not end in a colon.
echo hello world
```
works fine.

### sourcing quoted path
Running
```xonsh
# This comment ends in a colon:
source "/etc/xonshrc"
```
leads to
```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: <xonsh-code>:2:7: ('code: "/etc/xonshrc"',)
source "/etc/xonshrc"
       ^
```

But
```xonsh
# This comment ends in a colon:
source /etc/xonshrc
```
and
```xonsh
# This comment does not end in a colon.
source "/etc/xonshrc"
```
work fine.

### `.` pseudo dir
Running
```xonsh
# This comment ends in a colon:
ls .
```
leads to
```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: <xonsh-code>:2:4: ('code: \n',)
ls .
    ^

```

But
```xonsh
# This comment does not end in a colon.
ls .
```
and
```xonsh
# This comment ends in a colon:
ls /etc/xonshrc
```
work fine.

**Comment by das-g** [comment]
Same behavior on current `master` (b7265fcd971510ec5969518084075b2a21e27f12)

(Tested with `python xonsh-in-docker.py`)

### xonfig

<details>

```
+------------------+---------------------+
| xonsh            | 0.9.15.dev29        |
| Git SHA          | b7265fcd            |
| Commit Date      | Apr 4 13:08:23 2020 |
| Python           | 3.5.9               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.4               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.6.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | True                |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

**Comment by scopatz** [comment]
Thanks for reporting @das-g - this is definitely a bug
