### ISSUE TITLE
Syntax error when using if statement with subprocess mode

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3518]
When trying to run a script, it raises SyntaxError. It seems to be a bug in the handling of subprocess mode and python code.

## xonfig

<details>
```
+------------------+---------------------+
| xonsh            | 0.9.17.dev2         |
| Git SHA          | 97a921c7            |
| Commit Date      | Apr 8 14:48:23 2020 |
| Python           | 3.8.2               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.5               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.6.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | manjaro             |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```
</details>

## Expected Behavior

The following script should be valid. 
```python ❯ for d in ["poetry", "click"]: 
..     pkg = d.split()[0] 
..     reqs = $(pip show @(pkg) | grep "Required-by") 
..     print(reqs) 
..     if reqs: 
..         has_req = all([s.strip() for s in reqs.split(":")] 
..     else: 
..         print(pkg) 
```

### Traceback (if applicable)

<details>

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/ptk2/shell.py", line 181, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 23263, in compile
    if filename is None:
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 23223, in parse
    # in Python mode "ls -l", "ls-l", and "ls - l" all parse to the
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 23366, in _parse_ctx_free
    raise original_error
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 23347, in _parse_ctx_free
    greedy = False
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/parsers/base.py", line 3299, in p_error
    "empty : "
  File "/home/noor/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/parsers/base.py", line 676, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:7:4: ('code: else',)
    else:
    ^
```
</details>

## Steps to Reproduce

running the above code inside a `xonsh` shell

# Suggesion
It is error prone trying to parse a code as Python or shell code automatically. Something like a comment keyword to mark start and end of a python code block would help in such situation.

**Comment by gforsyth** [comment]
> ..         has_req = all([s.strip() for s in reqs.split(":")] 

you are missing a trailing parenthesis on this line
