### ISSUE TITLE
xonsh in docker: OSError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3553]
Catched when running from docker.
```
$ xonsh
Traceback (most recent call last):
  File "/root/opt/python3.8/lib/python3.8/site-packages/xonsh/main.py", line 405, in main
    return main_xonsh(args)
  File "/root/opt/python3.8/lib/python3.8/site-packages/xonsh/main.py", line 431, in main_xonsh
    print_welcome_screen()
  File "/root/opt/python3.8/lib/python3.8/site-packages/xonsh/xonfig.py", line 774, in print_welcome_screen
    termwidth = os.get_terminal_size().columns
OSError: [Errno 25] Inappropriate ioctl for device
Xonsh encountered an issue during launch
Failback to /bin/sh
```
```
+------------------+-----------------+
| xonsh            | 0.9.17          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit  |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | True            |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```
Next runs were ok.

**Comment by anki-code** [comment]
I'm going to close this issue because the details in #3555

**Comment by anki-code** [comment]
Don't know how to repeat.
