### ISSUE TITLE
AttributeError exception in JSON history backend

### ISSUE THREAD

**Issue by laloch** [xonsh/xonsh#3562]
## xonfig

<details>

```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.9.18              |
| Git SHA          | 292d292d            |
| Commit Date      | May 1 13:35:50 2020 |
| Python           | 3.8.2               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.5               |
| shell type       | prompt_toolkit      |
| pygments         | 2.6.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | arch                |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

## Current Behavior
If `$HISTCONTROL` is set to either `ignoreerr`, `ignoredups` or both, JSON history backend may crash with the backtrace below. Though the backtrace was triggered by Powerline xontrib, it happens whenever something attempts to reach the end of the history (e.g. `__xonsh__.history.rtns[-1]`) of an already flushed history buffer. This is due to the fact that not all history entries are always flushed to the history file, but the change of the history length, caused by skipping some entries, is not reflected by the internal state (it simply thinks that the history is longer than it really is).

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/home/str/code/xonsh/xonsh/prompt/base.py", line 47, in __call__
    prompt = self._format_prompt(template=template)
  File "/home/str/code/xonsh/xonsh/prompt/base.py", line 55, in _format_prompt
    template = template() if callable(template) else template
  File "/usr/lib/python3.8/site-packages/xontrib/powerline.xsh", line 170, in prompt
    r = s()
  File "/usr/lib/python3.8/site-packages/xontrib/powerline.xsh", line 105, in rtns
    if __xonsh__.history.rtns and __xonsh__.history.rtns[-1] != 0:
  File "/home/str/code/xonsh/xonsh/history/json.py", line 273, in __getitem__
    rtn = lj["cmds"][key].get(self.field, self.default)
AttributeError: 'list' object has no attribute 'get'
```

</details>

## Steps to Reproduce

```
$ __xonsh__.history.buffersize = 1
$ $XONSH_SHOW_TRACEBACK=True
$ $XONSH_DEBUG=True
$ foobarfoobar # returns error
$ __xonsh__.history.rtns[-1]
Traceback (most recent call last):
  File "/home/str/code/xonsh/xonsh/base_shell.py", line 362, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/home/str/code/xonsh/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/str/code/xonsh/xonsh/history/json.py", line 274, in __getitem__
    rtn = lj["cmds"][key].get(self.field, self.default)
AttributeError: 'list' object has no attribute 'get'
```

**Comment by laloch** [comment]
There's another issue with the JSON history backend: History buffer flushing happens asynchronously in a background thread, but the buffer gets cleared immediately after it is handed over to the flusher thread constructor, so the history gets most probably truncated.

**Comment by scopatz** [comment]
Is this still an issue on master?

**Comment by laloch** [comment]
Yes, this is still an issue. Crashes the shell reliably if `$HISTCONTROL` is anything else than `{}` and the `HistoryFlusher` kicks in.
