### ISSUE TITLE
cpython 3.9 run fails due end_lineno being None

### ISSUE THREAD

**Issue by gaborbernat** [xonsh/xonsh#3581]
When trying to add python 3.9 to the test target of [virtualenv](https://github.com/pypa/virtualenv/pull/1839) discovered xonsh now throws the following error:

```
E       AssertionError: Traceback (most recent call last):
E           File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
E             return _run_code(code, main_globals, None,
E           File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
E             exec(code, run_globals)
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/__main__.py", line 3, in <module>
E             main()
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/main.py", line 407, in main
E             _failback_to_other_shells(args, err)
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/main.py", line 371, in _failback_to_other_shells
E             raise err
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/main.py", line 405, in main
E             return main_xonsh(args)
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/main.py", line 448, in main_xonsh
E             run_script_with_cache(
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/codecache.py", line 160, in run_script_with_cache
E             ccode = compile_code(filename, code, execer, glb, loc, mode)
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/codecache.py", line 119, in compile_code
E             ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
E             tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/execer.py", line 109, in parse
E             tree = self.ctxtransformer.ctxvisit(
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/ast.py", line 376, in ctxvisit
E             node = self.visit(node)
E           File "/usr/lib/python3.9/ast.py", line 400, in visit
E             return visitor(node)
E           File "/usr/lib/python3.9/ast.py", line 476, in generic_visit
E             value = self.visit(value)
E           File "/usr/lib/python3.9/ast.py", line 400, in visit
E             return visitor(node)
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/ast.py", line 491, in visit_Expr
E             newnode = self.try_subproc_toks(node)
E           File "/home/vsts/work/1/s/.tox/py39/lib/python3.9/site-packages/xonsh/ast.py", line 443, in try_subproc_toks
E             increment_lineno(newnode, n=node.lineno - 1)
E           File "/usr/lib/python3.9/ast.py", line 233, in increment_lineno
E             child.end_lineno = getattr(child, 'end_lineno', 0) + n
E         TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

```

**Comment by pradyunsg** [comment]
Would it make sense to @-mention Pablo here, to flag this to him eagerly?

**Comment by gaborbernat** [comment]
I've already reached out to him directly, we need a proper reproducible first 👍

**Comment by laloch** [comment]
Is the issue specific to `$PYTHONOLDPARSER=0`?

**Comment by laloch** [comment]
It's due to the fact that some AST nodes now default to `end_lineno=None`. For instance `type(ast.Call().end_lineno)` now returns `NoneType` in Python 3.9.0b1. It used to be undefined in Python 3.8.
It's, however, still an upstream bug in my opinion.

**Comment by gaborbernat** [comment]
Yeah:

```
py -3.8 -c 'import ast; type(ast.Call().end_lineno)'                                                                                                                                                                 Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'Call' object has no attribute 'end_lineno'

py -3.9 -c 'import ast; type(ast.Call().end_lineno)'
```

**Comment by gaborbernat** [comment]
Created https://bugs.python.org/issue40726

**Comment by laloch** [comment]
@gaborbernat, could you please edit the issue title to be a bit less generic? I'm afraid that there are more Python 3.9 support issues to come. I've already seen our parser to crash for other reasons with the current Python beta.
Thank you!

**Comment by laloch** [comment]
The Python 3.9 support is currently seriously broken. I have opened #3588 draft to track my progress on fixing it.
