### ISSUE TITLE
Callable alias hung if returning list.

### ISSUE THREAD

**Issue by fengttt** [xonsh/xonsh#3598]
## xonfig

<details>

```
ftian@ftian-desktop:~$ xonsh
ftian@ftian-desktop ~ $ def _foo(args): 
.......................     return [1, 2], [3, 4] 
.......................                                                                         
ftian@ftian-desktop ~ $ aliases['foo'] = _foo                                                   
ftian@ftian-desktop ~ $ foo                                                                     
Exception in thread Thread-138:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/xonsh/__amalgam__.py", line 15040, in run
    self.returncode = parse_proxy_return(r, sp_stdout, sp_stderr)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/__amalgam__.py", line 14785, in parse_proxy_return
    stdout.write(r[0])
TypeError: write() argument must be str, not list



```

</details>

## Expected Behavior

Error.

## Current Behavior

xonsh hung, ^C won't kill it either.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

**Comment by laloch** [comment]
Hi @fengttt, thanks for reporting and sorry for the delay.
I can confirm the issue.
