### ISSUE TITLE
Error while loading pyenv xontrib (+ no effect of XONSH_DEBUG for xontrib?)

### ISSUE THREAD

**Issue by paugier** [xonsh/xonsh#3610]
## xonfig

```
+------------------+-----------------+
| xonsh            | 0.9.13          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

`xontrib load pyenv` should load the pyenv contrib without error.

## Current Behavior

It leads to an error (related to "No such file or directory: 'pyenv\n'"). Moreover, even with `$XONSH_DEBUG = 1`, the traceback involves `xonsh/__amalgam__.py`.

Note that even before loading the pyenv xontrib, the command pyenv is available:

```
(env_xonsh) pierre@kth ~ $ which pyenv -v                                       
aliases['pyenv'] = ForeignShellFunctionAlias(extra_args=(), filename='/home/pierre/.bashrc', funcname='pyenv', shell='bash', sourcer='source')
```
Moreover, the file `pyenv` is in one of the directories in $PATH:

```
(env_xonsh) pierre@kth ~ $ ls /home/pierre/.pyenv/bin                           
pyenv
(env_xonsh) pierre@kth ~ $ "/home/pierre/.pyenv/bin" in $PATH                   
True
```

### Traceback (if applicable)

```
pierre@kth ~ $ source-bash ~/Dev/env_xonsh/bin/activate                         
(env_xonsh) pierre@kth ~ $ $XONSH_DEBUG=1                                       
(env_xonsh) pierre@kth ~ $ $XONSH_SHOW_TRACEBACK = True                         
(env_xonsh) pierre@kth ~ $ xonsh                                                
Hello Pierre!
^Z
(env_xonsh) pierre@kth ~ $ xontrib load pyenv                                   
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22033, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 14147, in __init__
    self.proc = proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyenv\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 15421, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22022, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22046, in _run_binary
    sug = suggest_commands(cmd0, env, builtins.aliases)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 5293, in suggest_commands
    c = command_not_found(cmd)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 5241, in command_not_found
    s = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/usr/lib/command-not-found pyenv
; exit 0' returned non-zero exit status 2.
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22033, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 14147, in __init__
    self.proc = proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyenv\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 15421, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22022, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22046, in _run_binary
    sug = suggest_commands(cmd0, env, builtins.aliases)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 5293, in suggest_commands
    c = command_not_found(cmd)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 5241, in command_not_found
    s = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/usr/lib/command-not-found pyenv
; exit 0' returned non-zero exit status 2.
```

**Comment by laloch** [comment]
Hi @paugier, thanks for reporting.
[xontrib-pyenv](https://github.com/dyuri/xontrib-pyenv) is an external add-on package, so you shoud probably report the issue at its issue tracker. @dyuri, what do you think?

The `XONSH_DEBUG` behavior is, however, very strange. Does the `XONSH_DEBUG` value propagate to the child Xonsh process?

**Comment by dyuri** [comment]
Sure, investigating.

**Comment by paugier** [comment]
I think the first problem is solved (see https://github.com/dyuri/xontrib-pyenv/issues/1).

> Does the XONSH_DEBUG value propagate to the child Xonsh process?

Yes it does.

> Edit: Your Xonsh version is quite dated. Can you reproduce the issue with v0.9.18?

That was why I tried to install a newer version (from the repository) in a virtualenv. But unfortunately it does not work:
```
pierre@gre ~ $ xonfig                                                                                                                                     
+------------------+-----------------+
| xonsh            | 0.9.13          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
pierre@gre ~ $ source-bash ~/Dev/env_xonsh/bin/activate                                                                                                   
(env_xonsh) pierre@gre ~ $ which xonsh                                                                                                                    
/home/pierre/Dev/env_xonsh/bin/xonsh
(env_xonsh) pierre@gre ~ $ xonsh --version                                                                                                                
xonsh/0.9.18

# let's try to try the new xonsh
(env_xonsh) pierre@gre ~ $ xonsh                                                                                                                          
^Z

(env_xonsh) pierre@gre ~ $ xonfig                                                                                                                         
+------------------+-----------------+
| xonsh            | 0.9.13          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by gforsyth** [comment]
> # let's try to try the new xonsh
> (env_xonsh) pierre@gre ~ $ xonsh                                                                                                                          
> ^Z

It looks like `xonsh` is being immediately backgrounded, so you aren't actually in the new shell instance, which would also explain `XONSH_DEBUG` not working as expected.

**Comment by paugier** [comment]
Yes. But how can one get a new shell instance then?

**Comment by paugier** [comment]
Using bash, I get something more explicit:
```
(env_xonsh) pierre@gre:~$ xonsh
[1]+  Stopped                 xonsh
```

And with `--no-rc`, even more info:
```
(env_xonsh) pierre@gre:~$ xonsh --no-rc
Traceback (most recent call last):
  File "/home/pierre/Dev/xonsh/xonsh/main.py", line 404, in main
    args = premain(argv)
  File "/home/pierre/Dev/xonsh/xonsh/main.py", line 357, in premain
    env = start_services(shell_kwargs, args)
  File "/home/pierre/Dev/xonsh/xonsh/main.py", line 306, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/home/pierre/Dev/xonsh/xonsh/shell.py", line 223, in __init__
    raise XonshError("{} is not recognized as a shell type".format(shell_type))
xonsh.tools.XonshError: prompt_toolkit2 is not recognized as a shell type
Xonsh encountered an issue during launch
Failback to /bin/sh
```

I reinstalled xonsh with `pip install -e ".[ptk,linux,pygments,proctitle]"` and `python -c "import prompt_toolkit as m; print(m.__version__)"` gives 3.0.5.

Could it be that a config file of the Ubuntu package interacts badly with the new xonsh? I'm going to investigate.

**Comment by paugier** [comment]
> Could it be that a config file of the Ubuntu package interacts badly with the new xonsh?

Doesn't seem to be the problem...
```
apt-file list xonsh | grep -v "/usr/lib" | grep -v "doc/xonsh"                                                                                      
xonsh: /usr/bin/xonsh
xonsh: /usr/share/jupyter/kernels/xonsh/kernel.json
xonsh: /usr/share/man/man1/xonsh.1.gz
xonsh: /usr/share/xonsh/xon.sh
xonsh: /usr/share/xonsh/xonsh-cat
```

**Comment by paugier** [comment]
At least
```
$SHELL_TYPE='prompt_toolkit'
xonsh --no-rc
```
correctly opens xonsh 0.9.18

**Comment by laloch** [comment]
Yes. You may also leave the `SHELL_TYPE` variable unset and let Xonsh decide the best prompter available: `env -u SHELL_TYPE xonsh`.

**Comment by paugier** [comment]
Yes! This works:
```
pierre@gre ~ $ source-bash ~/Dev/env_xonsh/bin/activate                         
(env_xonsh) pierre@gre ~ $ env -u SHELL_TYPE xonsh                              
(env_xonsh) pierre@gre ~ $ xonfig                                               
+------------------+-----------------+
| xonsh            | 0.9.18          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit  |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

But still it's strange that this does not work:
```
pierre@gre ~ $ source-bash ~/Dev/env_xonsh/bin/activate                         
(env_xonsh) pierre@gre ~ $ $SHELL_TYPE='prompt_toolkit'                         
(env_xonsh) pierre@gre ~ $ xonsh                                                
^Z
```
