### ISSUE TITLE
Change in p_factor_unary causes tracebacks

### ISSUE THREAD

**Issue by con-f-use** [xonsh/xonsh#3615]
A recent change in  [p_factor_unary](https://github.com/xonsh/xonsh/commit/3a6e9de2014adf06fa2bfe6816fd1382dd785cc4#diff-74dc4178cde5747e163ca2a37163c1b7) merged to master by @laloch causes

### Tracebacks

<details>

```
Traceback (most recent call last):
  File "/home/jan/devel/unix/xonsh/xonsh/proc.py", line 1737, in wait
    r = self.f(self.args, stdin, stdout, stderr, spec, spec.stack)
  File "/home/jan/devel/unix/xonsh/xonsh/proc.py", line 1232, in proxy_two
    return f(args, stdin)
  File "/home/jan/devel/unix/xonsh/xonsh/xontribs.py", line 203, in xontribs_main
    return _MAIN_XONTRIB_ACTIONS[ns.action](ns)
  File "/home/jan/devel/unix/xonsh/xonsh/xontribs.py", line 123, in _load
    xontribs_load(ns.names, verbose=ns.verbose)
  File "/home/jan/devel/unix/xonsh/xonsh/xontribs.py", line 115, in xontribs_load
    update_context(name, ctx=ctx)
  File "/home/jan/devel/unix/xonsh/xonsh/xontribs.py", line 64, in update_context
    modctx = xontrib_context(name)
  File "/home/jan/devel/unix/xonsh/xonsh/xontribs.py", line 28, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "/home/jan/devel/unix/xonsh/xonsh/imphooks.py", line 123, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 223, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/home/jan/devel/unix/xonsh/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/jan/devel/unix/xonsh/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/jan/devel/unix/xonsh/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/home/jan/devel/unix/xonsh/xonsh/parsers/base.py", line 2161, in p_factor_unary
    op = self._factor_ops[p1.value]()
AttributeError: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/jan/devel/unix/xonsh/xonsh/environ.py", line 1757, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/home/jan/devel/unix/xonsh/xonsh/codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/jan/devel/unix/xonsh/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "/home/jan/.xonshrc", line 163, in <module>
  File "/home/jan/devel/unix/xonsh/xonsh/aliases.py", line 135, in __setitem__
    elif isexpression(val):
  File "/home/jan/devel/unix/xonsh/xonsh/ast.py", line 315, in isexpression
    node = builtins.__xonsh__.execer.parse(node, ctx, *args, **kwargs)
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/jan/devel/unix/xonsh/xonsh/execer.py", line 223, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/home/jan/devel/unix/xonsh/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/jan/devel/unix/xonsh/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/jan/devel/unix/xonsh/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/home/jan/devel/unix/xonsh/xonsh/parsers/base.py", line 2161, in p_factor_unary
    op = self._factor_ops[p1.value]()
AttributeError: 'str' object has no attribute 'value'
```

</details>

**Comment by laloch** [comment]
Hi @con-f-use, thanks for reporting.
Are you sure you didn't forget to run setup/reinstall after upgrading? Each time there's a change in the grammar, our parser tables need to be regenerated.

**Comment by con-f-use** [comment]
I am pretty sure

![image](https://user-images.githubusercontent.com/11145016/84374060-bde14280-abdd-11ea-9e0b-b613722e03df.png)

**Comment by laloch** [comment]
Could you please help me in reproducing the issue? Looking at source code, I can't figure out how the `p[1]` could possibly be a string other than that the parser doesn't match the grammar.

**Comment by con-f-use** [comment]
I will try to dig a little deeper. It some call in my xonshrc that mostly trigger the tracebacks. I'll find out which and try to make a minimal example.

**Comment by laloch** [comment]
See #3570 - it's the same issue caused by stale parser tables. I'm pretty sure that's the reason, but I don't know how it can be possible.
Are you sure about all the files in your worktree being writable by your user?

**Comment by laloch** [comment]
Also, just out of curiosity, how did you do your editable install? Was it `pip install --no-use-pep517 --user -e .`?

**Comment by anki-code** [comment]
Hi @con-f-use ! Have you any news here or we can close the issue?
