### ISSUE TITLE
Is there a way to pickle for running parallel code?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3626]
Hello! xonsh is something new every day! Thanks!

I try to run parallel code which require pickle. I've found the common way to do it using class. But in xonsh I've got an error.

Run in xonsh:

```python
import sys
from multiprocessing import Pool, cpu_count

class xontribPipelinerParallel(object):
   def __init__(self):
       pass

   def f(self, args):
       code, line, num = args
       return eval(code, globals(), locals())

   def go(self, func_args, stdout):
       with Pool(cpu_count()) as p:
           parallel_tasks = p.imap_unordered(self, func_args)
           for result in parallel_tasks:
               print(result, file=stdout, flush=True)

   def __call__(self, x):
     return self.f(x)

xppl = xontribPipelinerParallel()
xppl.go([['line', 'some line', 0]], sys.stdout)
# this returns one line "some line"
```

xonsh stdout:
```
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 17776, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 2942, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "<xonsh-code>", line 12, in go
  File "/opt/miniconda/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
  File "/opt/miniconda/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/opt/miniconda/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/miniconda/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class '__main__.xontribPipelinerParallel'>: attribute lookup xontribPipelinerParallel on __main__ failed
```
And I have the same error when try to do it in xontrib.

How I can run multiprocess code in xonsh?

Thanks!

**Comment by astronouth7303** [comment]
The simple answer is "put all the requisite classes in importable modules".

Multiprocessing creates a new process with a new `__main__` and new globals, and it needs to be able to find the class to reconstruct any objects you send over. (Pickles are kinda like instructions for how to build an instance of an object.)

xonsh makes no extensions to multiprocessing or pickle. (although maybe we should to make sure that xsh imports are enabled.)

**Comment by anki-code** [comment]
I've put the code to the module and it works. Thanks!
