### ISSUE TITLE
`conda init xonsh` doesn't work on windows

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#3676]
I know this may belong on the conda issue tracker but I thought there may be a better chance that it gets fixed if we report here.

> Note: xonsh on windows still works out of the box with `activate <conda environement`/`deactivate`. This is because it piggyback on cmd.exe. 

However, conda advertises that you can use `conda inti xonsh`. But that has problems on windows. 

The snippet in `.xonshrc` looks like is generated with "linux/cygwin" style paths. (e.g. "/C/Users/.."). 

``` 
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
import sys as _sys
from types import ModuleType as _ModuleType
_mod = _ModuleType("xontrib.conda",
                   "Autogenerated from $(/C/Users/mel/Miniconda3/Scripts/conda.exe shell.xonsh hook)")
__xonsh__.execer.exec($("/C/Users/mel/Miniconda3/Scripts/conda.exe" "shell.xonsh" "hook"),
                      glbs=_mod.__dict__,
                      filename="$(/C/Users/mel/Miniconda3/Scripts/conda.exe shell.xonsh hook)")
_sys.modules["xontrib.conda"] = _mod
del _sys, _mod, _ModuleType
# <<< conda initialize <<<
```

Fixing that manually, ensures that xonsh can launch. But then I get an error when activating 

```
(base) snail@sea ~
🐌 conda activate pytest6

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\mel\Miniconda3\lib\site-packages\conda\cli\main.py", line 138, in main
        return activator_main()
      File "C:\Users\mel\Miniconda3\lib\site-packages\conda\activate.py", line 1094, in main
        print(activator.execute(), end='')
      File "C:\Users\mel\Miniconda3\lib\site-packages\conda\activate.py", line 182, in execute
        return getattr(self, self.command)()
      File "C:\Users\mel\Miniconda3\lib\site-packages\conda\activate.py", line 156, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "C:\Users\mel\Miniconda3\lib\site-packages\conda\activate.py", line 301, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "C:\Users\mel\Miniconda3\lib\site-packages\conda\activate.py", line 380, in _build_activate_stack
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
      File "C:\Users\mel\Miniconda3\lib\site-packages\conda\activate.py", line 706, in _get_deactivate_scripts
        prefix, 'etc', 'conda', 'deactivate.d', '*' + self.script_extension
      File "C:\Users\mel\Miniconda3\lib\ntpath.py", line 76, in join
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ C:\Users\mel\Miniconda3\Scripts\conda-script.py shell.xonsh activate pytest6`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_BAT=C:\Users\mel\Miniconda3\condabin\conda.bat
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:/Users/mel/Miniconda3/Scripts/conda.exe
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:/Users/mel/Miniconda3/python.exe
               CONDA_ROOT=C:\Users\mel\Miniconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\mel
                     PATH=C:\Users\mel\Miniconda3\condabin;C:\Program Files\WindowsApps\Microsof
                          t.WindowsTerminalPreview_1.2.2022.0_x64__8wekyb3d8bbwe;C:\WINDOWS\syst
                          em32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPo
                          werShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\TortoiseGit\bin;C:\Program
                          Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\PowerShell\7\;C:\Program Files\Git\cmd;C:\Program
                          Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\mel\Minico
                          nda3;C:\Users\mel\Miniconda3\Library\mingw-w64\bin;C:\Users\mel\Minico
                          nda3\Library\usr\bin;C:\Users\mel\Miniconda3\Library\bin;C:\Users\mel\
                          Miniconda3\Scripts;C:\Users\mel\AppData\Local\Microsoft\WindowsApps;C:
                          \Users\mel\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program
                          Files\CMake\bin;C:\Program Files (x86)\GitHub CLI\;C:\src\flutter\bin;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 1
       user config file : C:\Users\mel\.condarc
 populated config files : C:\Users\mel\.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\mel\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\mel\Miniconda3\pkgs
                          C:\Users\mel\.conda\pkgs
                          C:\Users\mel\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\mel\Miniconda3\envs
                          C:\Users\mel\.conda\envs
                          C:\Users\mel\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

**Comment by scopatz** [comment]
Thanks @melund! This should probably be on the conda issue tracker.  Let me see if I can track down a fix

**Comment by scopatz** [comment]
Potential fix at https://github.com/conda/conda/pull/10167, if you could try that out @melund that would be great!

**Comment by anki-code** [comment]
I'm going to close this until the fixes in conda will be merged (16064, 16065).
