### ISSUE TITLE
Environment context manager doesn't always clean up the environment

### ISSUE THREAD

**Issue by laloch** [xonsh/xonsh#3686]
Since #3377, the environment `swap()` context manager doesn't always remove temporary variables.
Before:
```
$ with ${...}.swap(TEST_PATH="test"):
.     print($TEST_PATH)
. print($TEST_PATH)
['test']
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'Unknown environment variable: $TEST_PATH'
```
Now, with #3377:
```
$ with ${...}.swap(TEST_PATH="test"):
.     print($TEST_PATH)
. print($TEST_PATH)
['test']
[]
```

**Comment by scopatz** [comment]
I am seeing:

```sh
base scopatz@artemis ~ $ with ${...}.swap(TEST_PATH="test"):
`·.,¸,.·*¯`·.,¸,.·*¯`·.,      print($TEST_PATH)
`·.,¸,.·*¯`·.,¸,.·*¯`·., print($TEST_PATH)
`·.,¸,.·*¯`·.,¸,.·*¯`·.,
['test']
None
base scopatz@artemis ~ $ with ${...}.swap(TEST_PATH="test"):
`·.,¸,.·*¯`·.,¸,.·*¯`·.,      print($TEST_PATH)
`·.,¸,.·*¯`·.,¸,.·*¯`·., $TEST_PATH
`·.,¸,.·*¯`·.,¸,.·*¯`·.,
['test']
EnvPath(
[]
)
```

This might be partially because the `_PATH` is getting matched by the path regex.  When I remove that, I get the previous behavior:

```
base scopatz@artemis ~ $ with ${...}.swap(TEST="test"):
`·.,¸,.·*¯`·.,¸,.·*¯`·.,      print($TEST)
`·.,¸,.·*¯`·.,¸,.·*¯`·., $TEST
`·.,¸,.·*¯`·.,¸,.·*¯`·.,
test
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.7/site-packages/xonsh/base_shell.py", line 362, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/home/scopatz/.local/lib/python3.7/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 3, in <module>
  File "/home/scopatz/.local/lib/python3.7/site-packages/xonsh/environ.py", line 1923, in __getitem__
    raise KeyError(e.format(key))
KeyError: 'Unknown environment variable: $TEST'
```

So I the cleanup might be happening correctly, but a new, empty default PATH envar is being found/created

**Comment by anki-code** [comment]
I can't repeat this on xonsh 0.11:

```python
with ${...}.swap(TEST_PATH="test"):
     print($TEST_PATH)
print($TEST_PATH)

# ['test']
# xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
# KeyError: 'Unknown environment variable: $TEST_PATH'

```
