### ISSUE TITLE
xonsh-virtualenv

### ISSUE THREAD

**Issue by gaborbernat** [xonsh/xonsh#3689]
Hello, I'd like to migrate out the xonsh activator from the virtualenv project into a virtualenv-xonsh project. The reason for this is that xonsh seems is sensitive to new Pythons/package releases, and as such breaks quite often virtualenvs own CI. virtualenv is a crucial core project for the python ecosystem, and this is consuming significant time for me to handle that I'd like to avoid. So I'd like to spin out this feature from core virtualenv into a plugin. Can you setup a repository for this please under this domain so I can make a PR against it and hand over it to the project itself this maintainership? Thanks.

**Comment by scopatz** [comment]
Hey @gaborbernat - It is hard for xonsh to target unreleased versions of Python. Is there any way for virtualenv to just skip the xonsh tests on unrelased versions of python? It would be a big regression for xonshusers to not be able to activate environments

**Comment by gaborbernat** [comment]
It's not just about new versions, but e.g. the ci breaks on windows release, and this hasn't been the first case of this.

**Comment by gaborbernat** [comment]
Note they could still activate environments, just not out of box, they'd have to install the virtualenv plugin.

**Comment by astronouth7303** [comment]
There was a xonsh activator?

**Comment by gaborbernat** [comment]
Here's the latest of these:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\_pytest\main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\_pytest\config\__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\pytest_plugin.py", line 13, in pytest_configure
INTERNALERROR>     setup()
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\main.py", line 548, in setup
INTERNALERROR>     execer = Execer(xonsh_ctx=ctx)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\execer.py", line 63, in __init__
INTERNALERROR>     load_builtins(execer=self, ctx=xonsh_ctx)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\built_ins.py", line 1346, in load_builtins
INTERNALERROR>     builtins.__xonsh__.link_builtins(execer=execer)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\built_ins.py", line 1480, in link_builtins
INTERNALERROR>     resetting_signal_handle(sig, _lastflush)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\built_ins.py", line 87, in resetting_signal_handle
INTERNALERROR>     signal.signal(sig, newh)
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\signal.py", line 47, in signal
INTERNALERROR>     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
INTERNALERROR> ValueError: signal only works in main thread
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\_pytest\main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\_pytest\config\__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\pytest_plugin.py", line 13, in pytest_configure
INTERNALERROR>     setup()
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\main.py", line 548, in setup
INTERNALERROR>     execer = Execer(xonsh_ctx=ctx)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\execer.py", line 63, in __init__
INTERNALERROR>     load_builtins(execer=self, ctx=xonsh_ctx)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\built_ins.py", line 1346, in load_builtins
INTERNALERROR>     builtins.__xonsh__.link_builtins(execer=execer)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\built_ins.py", line 1480, in link_builtins
INTERNALERROR>     resetting_signal_handle(sig, _lastflush)
INTERNALERROR>   File "D:\a\virtualenv\virtualenv\.tox\py38\lib\site-packages\xonsh\built_ins.py", line 87, in resetting_signal_handle
INTERNALERROR>     signal.signal(sig, newh)
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\signal.py", line 47, in signal
INTERNALERROR>     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
INTERNALERROR> ValueError: signal only works in main thread
```

https://github.com/pypa/virtualenv/runs/1584927387?check_suite_focus=true


> Can you setup a repository for this please under this domain so I can make a PR against it and hand over it to the project itself this maintainership?

Due to lack of progress on this, I'm simply removing xonsh from virtualenv. Thanks!

**Comment by Wolfizen** [comment]
I'm not (yet) a xonsh contributor, but as I regularly make use of this feature I am willing to put int the work to update and migrate the activator from the virtualenv project. I won't be able to complete it quickly but seeing as this hasn't been worked on for six months I  would say better than nothing :).

I arrived here after I noticed `activate.xsh` was gone from my new virtualenvs :disappointed: .
