### ISSUE TITLE
KeyError `locked` in latest build of xonsh

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#3699]
I recently updated to the latest version of xonsh and also installed a bespoke branch of ptk2. When I did, I started getting the error on startup:

```
~ $ Exception in thread Thread-10:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 372, in run
    files = self.files(only_unlocked=True)
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 426, in files
    if lj["locked"] and lj["ts"][0] < boot:
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 783, in __getitem__
    rtn = self._getitem_mapping(key)
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 767, in _getitem_mapping
    offset = self.offsets[key]
KeyError: 'locked'
```

I then re-installed the latest stable version of prompt_toolkit, but the error continues.

The prompt works after the error is emitted.

I have not tried troubleshooting further.

Given that others haven't reported this issue, I suspect it's somewhat localized to my environment (and history).

## xonfig

<details>

```
~ $ xonfig
+------------------+---------------------+
| xonsh            | 0.9.19              |
| Git SHA          | 74450cb5            |
| Commit Date      | Aug 9 13:27:55 2020 |
| Python           | 3.8.5               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.6               |
| shell type       | prompt_toolkit      |
| pygments         | None                |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

## Expected Behavior

Prompt should startup without error.

**Comment by scopatz** [comment]
Thanks for reporting @jaraco! I think #3700 should address this
