### ISSUE TITLE
AttributeError: 'Env' object has no attribute '_docs' when running `xonfig wizard`

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#3711]
Running master as of today, attempting to document `xonfig wizard` for Getting Started docs.

## Repro:
``` bash
$ xonfig wizard
```
### Expect
It works.

### Traceback 

<details>

```
Traceback (most recent call last):
  File "c:\users\bobhy\src\xonsh\xonsh\proc.py", line 1439, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "c:\users\bobhy\src\xonsh\xonsh\proc.py", line 1232, in proxy_two
    return f(args, stdin)
  File "c:\users\bobhy\src\xonsh\xonsh\aliases.py", line 703, in xonfig
    return xonfig_main(args)
  File "c:\users\bobhy\src\xonsh\xonsh\xonfig.py", line 689, in xonfig_main
    return _XONFIG_MAIN_ACTIONS[ns.action](ns)
  File "c:\users\bobhy\src\xonsh\xonsh\xonfig.py", line 450, in _wizard
    w = make_xonfig_wizard(
  File "c:\users\bobhy\src\xonsh\xonsh\xonfig.py", line 410, in make_xonfig_wizard
    wiz.YesNo(question=WIZARD_ENV_QUESTION, yes=make_env_wiz(), no=wiz.Pass()),
  File "c:\users\bobhy\src\xonsh\xonsh\xonfig.py", line 343, in make_env_wiz
    w = _make_flat_wiz(make_envvar, sorted(builtins.__xonsh__.env._docs.keys()))
AttributeError: 'Env' object has no attribute '_docs'
```

</details>

## xonfig

<details>

```
$ xonfig
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.19                                                |
| Git SHA          | 528d2f91                                              |
| Commit Date      | Aug 24 04:25:32 2020                                  |
| Python           | 3.8.5                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 3.0.6                                                 |
| shell type       | prompt_toolkit                                        |
| pygments         | 2.6.1                                                 |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x00000224E0688C70> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x00000224E0688DF0> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laloch** [comment]
Hi @bobhy, you are absolutely right. Thanks for reporting!
This relates to #3377.

**Comment by anki-code** [comment]
@bobhy this issue looks closed by PR. If yes please close.
