### ISSUE TITLE
Prompt toolkit failback to /bin/bash afte failed completion

### ISSUE THREAD

**Issue by CharString** [xonsh/xonsh#3716]
## xonfig

<details>

```
chars@trailblazer:~$ XONSH_DEBUG=1 xonsh --no-rc
... Enumerated       3 history files.
                                Welcome to the xonsh shell (0.9.19)                                

                                    ~ The shell, bourne again ~                                    
... Enumerated       4 history files.
---------------------------------------------------------------------------------------------------
xonfig tutorial    ->    Launch the tutorial in the browser
xonfig web         ->    Run the configuration tool in the browser and claim your shell 
(Note: Run the configuration tool or create a ~/.xonshrc file to suppress the welcome screen)

chars@trailblazer ~ $ xonfig
+------------------+---------------------+
| xonsh            | 0.9.19              |
| Git SHA          | 74450cb5            |
| Commit Date      | Aug 9 13:27:55 2020 |
| Python           | 3.7.3               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.6               |
| shell type       | prompt_toolkit      |
| pygments         | None                |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
chars@trailblazer ~ $ xpip freeze
distro==1.5.0
pkg-resources==0.0.0
prompt-toolkit==3.0.6
wcwidth==0.2.5
xonsh==0.9.19
xonsh-vox-tabcomplete==0.4
xontrib-kitty==0.0.2
xontrib-prompt-vi-mode==0.1.3
```

</details>

## Expected Behavior
A `KeyError` like
```
chars@trailblazer ~ $ $TEST
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'Unknown environment variable: $TEST'
```
## Current Behavior
AttributeError and a complete breakdown and failback to bash
### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/main.py", line 424, in main
    sys.exit(main_xonsh(args))
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/main.py", line 455, in main_xonsh
    shell.shell.cmdloop()
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/ptk_shell/shell.py", line 197, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/ptk_shell/shell.py", line 166, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 994, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 816, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 782, in run_async
    return await _run_async2()
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 770, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 871, in cancel_and_wait_for_background_tasks
    await task
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 1684, in async_completer
    document, complete_event
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/completion/base.py", line 270, in get_completions_async
    document, complete_event
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/ptk_shell/completer.py", line 52, in get_completions
    prefix, line_ex, begidx + expand_offset, endidx + expand_offset, self.ctx
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/completer.py", line 36, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/completers/path.py", line 335, in complete_path
    paths.update(filter(filtfunc, _env(prefix)))
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/completers/path.py", line 104, in _env
    "$" + k for k in builtins.__xonsh__.env if get_filter_function()(k, key)
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/completers/path.py", line 104, in <setcomp>
    "$" + k for k in builtins.__xonsh__.env if get_filter_function()(k, key)
  File "/home/chars/.local/pipx/venvs/xonsh/lib/python3.7/site-packages/xonsh/completers/tools.py", line 7, in _filter_normal
    return s.startswith(x)
AttributeError: 're.Pattern' object has no attribute 'startswith'
Xonsh encountered an issue during launch
Failback to /bin/bash
```

</details>

## Steps to Reproduce
1. Start a clean, unconfigured xonsh with prompt-toolkit.
2. Type an unset environment variable like $TEST
3. Press <kbd>tab</kbd>
4. Press <kbd>enter</kbd>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laloch** [comment]
Hi @CharString, thanks for reporting!
Sorry for the inconvenience. I believe the issue has already been fixed in #3679.

**Comment by CharString** [comment]
Cool @laloch 
I'm sorry for not testing against master branch... I did switch from the stable deb package to pipx install the latest pypi xonsh... And I checked the closed issues with the prompt-toolkit label.

It's an interesting project you have going here. :)

**Comment by laloch** [comment]
> I'm sorry for not testing against master branch...

That's just fine. The last release was not the luckiest one. We are still stabilizing towards v1.0, so such things sometimes happen. Sorry for the inconvenience.

> It's an interesting project you have going here. :)

Thanks! I hope the occasional instabilities won't deter you from using Xonsh.
