### ISSUE TITLE
Subprocess command from the xontrib freezes xonsh when load from RC in 0.9.20

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3725]
Hello! xonsh is great! Thanks!

I've updated to 0.9.20 and when run xonsh I've got freeze. It looks like something in xontrib autojump.

How to repeat:
```bash
bash$ xonsh -V                                                                                     
xonsh/0.9.20
bash$ pip list | grep xontrib-autojump
xontrib-autojump       1.2

bash$ xonsh --no-rc
xonsh$ xontrib load autojump
xonsh$ # ok!

bash$ echo "xontrib load autojump" > /tmp/rc
bash$ XONSH_DEBUG=1 xonsh --rc /tmp/rc
### FREEZE ###
^CTraceback (most recent call last):
```
<details>

```

  File "/opt/miniconda/bin/xonsh", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/main.py", line 423, in main
    args = premain(argv)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/main.py", line 359, in premain
    env = start_services(shell_kwargs, args)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/main.py", line 305, in start_services
    xonshrc_context(rcfiles=rc, execer=execer, ctx=ctx, env=env, login=login)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/environ.py", line 2154, in xonshrc_context
    status = xonsh_script_run_control(rcfile, ctx, env, execer=execer, login=login)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/environ.py", line 2191, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "/home/pc/tst/rc", line 1, in <module>
    xontrib load autojump
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/built_ins.py", line 1019, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/built_ins.py", line 978, in run_subproc
    command.end()
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2150, in end
    self._end(tee_output=tee_output)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2158, in _end
    for _ in self.tee_stdout():
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2071, in tee_stdout
    for line in self.iterraw():
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 1959, in iterraw
    proc.wait()
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 1737, in wait
    r = self.f(self.args, stdin, stdout, stderr, spec, spec.stack)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 1232, in proxy_two
    return f(args, stdin)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/xontribs.py", line 217, in xontribs_main
    return _MAIN_XONTRIB_ACTIONS[ns.action](ns)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/xontribs.py", line 137, in _load
    return xontribs_load(ns.names, verbose=ns.verbose)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/xontribs.py", line 124, in xontribs_load
    update_context(name, ctx=ctx)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/xontribs.py", line 69, in update_context
    modctx = xontrib_context(name)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/xontribs.py", line 35, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/opt/miniconda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/miniconda/lib/python3.8/site-packages/xontrib/autojump.xsh", line 122, in <module>
    _autojump_xonsh()
  File "/opt/miniconda/lib/python3.8/site-packages/xontrib/autojump.xsh", line 117, in _autojump_xonsh
    if !(completer list|grep autojump):
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 1914, in __bool__
    return self.returncode == 0
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2354, in returncode
    self.end()
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2150, in end
    self._end(tee_output=tee_output)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2158, in _end
    for _ in self.tee_stdout():
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2071, in tee_stdout
    for line in self.iterraw():
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 1957, in iterraw
    task = wait_for_active_job()
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/jobs.py", line 202, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
KeyboardInterrupt

```

</details>

Any thoughts will be helpful. Thanks!

🏅 Workaround - https://github.com/xonsh/xonsh/issues/3725#issuecomment-682432463

**Comment by laloch** [comment]
Hi @anki-code, thanks for reporting.
Autojump is, or rather was, an external xontrib, that unfortunately seems to be dead. The original author did even remove the repository completely, so we can't fork it and take over the ownership.
Let's wait for some time for someone who has a maintained fork of the original repository and is willing to negotiate and take over the ownership of the xontrib. If no one is interested in maintaining the xontrib, I'll propose it's removal from the list of supported external xontribs.

**Comment by anki-code** [comment]
@laloch thank you for response!

>  The original author did even remove the repository completely

There is the author email on the [PyPi page](https://pypi.org/project/xontrib-autojump/): iaansagar@gmail.com

> we can't fork it and take over the ownership.

Or you can download the source code from PyPi ([xontrib-autojump-1.2.tar.gz](https://pypi.org/project/xontrib-autojump/#files)) and create new repository for this in https://github.com/xonsh. MIT license allows this. Isn't it?

**Comment by anki-code** [comment]
@laloch This looks like something wrong in xonsh jobs when xontrib run `!(completer list|grep autojump)`:
```
...
  File "/opt/miniconda/lib/python3.8/site-packages/xontrib/autojump.xsh", line 117, in _autojump_xonsh
    if !(completer list|grep autojump):
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 1914, in __bool__
    return self.returncode == 0
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2354, in returncode
    self.end()
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2150, in end
    self._end(tee_output=tee_output)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2158, in _end
    for _ in self.tee_stdout():
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 2071, in tee_stdout
    for line in self.iterraw():
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/proc.py", line 1957, in iterraw
    task = wait_for_active_job()
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/jobs.py", line 202, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
KeyboardInterrupt
```
This command works in 0.9.19 and also works in 0.9.20 when `xontrib load autojump` typed manually. But in RC it is no working.

**Comment by laloch** [comment]
Yeah, that's probably due to #3705. You can try to set `$THREAD_SUBPROCS=True` before loading the xontrib.

**Comment by anki-code** [comment]
> Yeah, that's probably due to #3705

fyi @scopatz 

> You can try to set $THREAD_SUBPROCS=True before loading the xontrib.

@laloch thanks! It works:
```bash
$ cat xonshrc
ts_backup = $THREAD_SUBPROCS
$THREAD_SUBPROCS = True
xontrib load autojump
$THREAD_SUBPROCS = ts_backup

$ xonsh --rc xonshrc
xonsh:~$ j tm
xonsh:/tmp$
```

**Comment by willsALMANJ** [comment]
Did one of you try to email Sagar already? If Sagar is unreachable, perhaps @flaper87 would revive https://github.com/flaper87/autojump-xonsh? Otherwise, I could revive https://github.com/willsALMANJ/autojump-xonsh.

**Comment by laloch** [comment]
Thanks for your interest in maintaining the xontrib, @willsALMANJ! Someone needs to contact Sagar and take over the ownership of the PyPI package. We would have to rename the package otherwise.

**Comment by willsALMANJ** [comment]
Okay, I emailed Sagar and unarchived/fixed my repo. If I don't hear back I can make a new PyPI listing.
