### ISSUE TITLE
AttributeError: '_MergedKeyBindings' object has no attribute 'add'

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#3759]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.21               |
| Git SHA          | 95b3872c             |
| Commit Date      | Sep 12 04:57:08 2020 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.7                |
| shell type       | prompt_toolkit       |
| pygments         | 2.6.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

```

</details>

## Current Behavior
this happens on the master branch when xontrib uses `bindings.add `

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/home/noor/.config/xonsh/xonsh/xonsh/events.py", line 248, in _call
    handler(**self._kwargs)
  File "/home/noor/.config/xonsh/.venv/lib/python3.8/site-packages/xontrib/hist_navigator.xsh", line 72, in custom_keybindings
    handler = bindings.add
AttributeError: '_MergedKeyBindings' object has no attribute 'add'
Exception raised in event handler; ignored.
Traceback (most recent call last):
  File "/home/noor/.config/xonsh/xonsh/xonsh/events.py", line 248, in _call
    handler(**self._kwargs)
  File "/home/noor/.config/xonsh/xonsh/xontrib/abbrevs.py", line 80, in custom_keybindings
    handler = bindings.add
AttributeError: '_MergedKeyBindings' object has no attribute 'add'
Exception raised in event handler; ignored.
Traceback (most recent call last):
  File "/home/noor/.config/xonsh/xonsh/xonsh/events.py", line 248, in _call
    handler(**self._kwargs)
  File "/home/noor/.config/xonsh/user_xsh/evnt_hooks/keybindings/bindings.py", line 23, in custom_keybindings
    handler = bindings.add
AttributeError: '_MergedKeyBindings' object has no attribute 'add'
Exception raised in event handler; ignored.
```

</details>

## Steps to Reproduce
- install xonsh from latest master branch
- enable a xontrib
```sh
xontrib load abbrevs
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by dannysepler** [comment]
ah dang! i bet this is fallout from this diff https://github.com/xonsh/xonsh/pull/3697 -- i can fix, thanks!
