### ISSUE TITLE
Crash on ctrl-c during FZF history filtering on Windows

### ISSUE THREAD

**Issue by mwm-twx** [xonsh/xonsh#3769]
Using the fzf-widgets plugin, pressing ctrl-c to exit without changing the command input causes xonsh to crash.

## xonfig

<details>

```
$ xonfig
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.21                                                |
| Python           | 3.8.1                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 3.0.7                                                 |
| shell type       | prompt_toolkit                                        |
| pygments         | 2.6.1                                                 |
| on posix         | False                                                 |
| on linux         | False                                                 |
| on darwin        | False                                                 |
| on windows       | True                                                  |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x000001698D9CD4F0> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x000001698D9CD550> |
| is superuser     | False                                                 |
| default encoding | utf-8                                                 |
| xonsh encoding   | utf-8                                                 |
| encoding errors  | surrogateescape                                       |
+------------------+-------------------------------------------------------+
```

</details>

## Expected Behavior
FZF filtering should terminate and return to the original prompt.

## Current Behavior
Xonsh crashes because prompt_toolkit application is already running.

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "\xonsh\Scripts\xonsh.exe\__main__.py", line 7, in <module>
  File "\xonsh\lib\site-packages\xonsh\main.py", line 426, in main
    _failback_to_other_shells(args, err)
  File "\xonsh\lib\site-packages\xonsh\main.py", line 395, in _failback_to_other_shells
    raise err
  File "\xonsh\lib\site-packages\xonsh\main.py", line 424, in main
    sys.exit(main_xonsh(args))
  File "\xonsh\lib\site-packages\xonsh\main.py", line 455, in main_xonsh
    shell.shell.cmdloop()
  File "\xonsh\lib\site-packages\xonsh\ptk_shell\shell.py", line 224, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "\xonsh\lib\site-packages\xonsh\ptk_shell\shell.py", line 193, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "\xonsh\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "\xonsh\lib\site-packages\prompt_toolkit\application\application.py", line 814, in run
    return loop.run_until_complete(
  File "\python\python38\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "\xonsh\lib\site-packages\prompt_toolkit\application\application.py", line 626, in run_async
    assert not self._is_running, "Application is already running."
AssertionError: Application is already running.
```

</details>

## Steps to Reproduce

1.  Run xonsh with `fzf-widgets` xontrib
2.  Set `$fzf_history_binding = "c-r"`
3.  Trigger completion with ctrl-r
4.  Press ctrl-c

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for reporting! This seems to be because prompt-toolkit is raising an AssertionError instead of an KeyboardInterrupt for some reason. This could either be fixed in prompt-toolkit or captured by xonsh somehow. Thoughts @jonathanslenders?

**Comment by jonathanslenders** [comment]
Would it be possible to share a traceback?

**Comment by laloch** [comment]
The traceback is hidden within the `<details>` element under the "Traceback (if applicable)" heading of the OP.

**Comment by mwm-twx** [comment]
@jonathanslenders As mentioned previously, the traceback is there, but it's click-to-expand.

**Comment by mwm-twx** [comment]
I see the same error if I do completion for git:

1. `git checkout <TAB><TAB>`
2. Ctrl-C (exits completion correctly)
3. Ctrl-C again
4. "Application is already running." exception

**Comment by Awpteamoose** [comment]
same error with any letter, space, tab, Ctrl+

https://user-images.githubusercontent.com/3111840/183436091-e976a34d-9bdb-46bf-9ca8-dbaf58e5606d.mp4

C

**Comment by Awpteamoose** [comment]
I'm not using fzf in my video, just (mostly) stock xonsh. My point was that the error isn't fzf-specific.

**Comment by Awpteamoose** [comment]
@anki-code running `xonsh --no-rc` in latest `wt.exe` (although `cmd.exe` is the same), reproduces across 3 pcs with similar setups, this is from my home PC:

<details>

```
Awpteamoose@DESKTOP-P2E6VK1 D:\projects [1] $ xonfig
+------------------+-----------------+
| xonsh            | 0.13.0          |
| Python           | 3.10.5          |
| PLY              | 3.11            |
| have readline    | False           |
| prompt toolkit   | 3.0.30          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | None            |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib          | []              |
| RC file          | []              |
+------------------+-----------------+
```

</details>

**Comment by anki-code** [comment]
I can't reproduce this on xonsh 0.23.0
