### ISSUE TITLE
Bad documentation or bug: _.rtn does not work

### ISSUE THREAD

**Issue by Anonym-User-426** [xonsh/xonsh#3795]
[In the Documentation](https://xon.sh/bash_to_xsh.html) you write that `_.rtn` is the equivalent of the shell `$?` and that it `Returns the exit code, or status, of the previous command.`. Either I understand the documentation wrong or there is a bug:
```
#!/usr/bin/env xonsh
echo "abc"
print(_.rtn)
```
Outputs
```
abc
Traceback (most recent call last):
  File "/home/volker/.local/bin/xonsh", line 8, in <module>
    sys.exit(main())
  File "/home/volker/.local/lib/python3.8/site-packages/xonsh/main.py", line 426, in main
    _failback_to_other_shells(args, err)
  File "/home/volker/.local/lib/python3.8/site-packages/xonsh/main.py", line 373, in _failback_to_other_shells
    raise err
  File "/home/volker/.local/lib/python3.8/site-packages/xonsh/main.py", line 424, in main
    sys.exit(main_xonsh(args))
  File "/home/volker/.local/lib/python3.8/site-packages/xonsh/main.py", line 471, in main_xonsh
    run_script_with_cache(
  File "/home/volker/.local/lib/python3.8/site-packages/xonsh/codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/volker/.local/lib/python3.8/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "./generateIso.xonsh", line 24, in <module>
    print(_.rtn)
NameError: name '_' is not defined
```

**Comment by anki-code** [comment]
It looks like this working only in the shell prompt:

![Screenshot_20200924_214133](https://user-images.githubusercontent.com/1708680/94185968-bc970580-feae-11ea-8cad-6ae433e51573.png)

I don't know is it a bug or not but for scripts try captured subproc:
```
#!/usr/bin/env xonsh
r = !(echo 123)
print(r.rtn)
```
