### ISSUE TITLE
Run xonsh with RC and xontrib from xonsh from xonsh: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3842]
Hi! Let's deep dive into conch spiral!

```bash
# bash
cd /tmp
echo 'xontrib load whole_word_jumping' > rc
XONSH_DEBUG=1 xonsh --rc rc    # run xonsh from bash
$XONSH_DEBUG=1 xonsh --rc rc   # run xonsh from xonsh from bash
$XONSH_DEBUG=1 xonsh --rc rc   # run xonsh from xonsh from xonsh from bash
```
As result:
```
Traceback (most recent call last):es.
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/main.py", line 426, in main
    sys.exit(main_xonsh(args))
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/main.py", line 464, in main_xonsh
    shell.shell.cmdloop()
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 254, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 222, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/opt/miniconda/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/opt/miniconda/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 814, in run
    return loop.run_until_complete(
  File "/opt/miniconda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/miniconda/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 781, in run_async
    return await _run_async2()
  File "/opt/miniconda/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 763, in _run_async2
    result = await _run_async()
  File "/opt/miniconda/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 694, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "/opt/miniconda/lib/python3.8/site-packages/prompt_toolkit/input/vt100.py", line 244, in __enter__
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)
termios.error: (4, 'Interrupted system call')
Xonsh encountered an issue during launch
Failback to /bin/bash
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

xonfig

<details>

```
$ xonfig
+------------------+--------------------------------------------+
| xonsh            | 0.9.22.dev188                              |
| Git SHA          | f9e0f072                                   |
| Commit Date      | Oct 5 23:59:24 2020                        |
| Python           | 3.8.2                                      |
| PLY              | 3.11                                       |
| have readline    | True                                       |
| prompt toolkit   | 3.0.7                                      |
| shell type       | prompt_toolkit                             |
| pygments         | 2.6.1                                      |
| on posix         | True                                       |
| on linux         | True                                       |
| distro           | ubuntu                                     |
| on darwin        | False                                      |
| on windows       | False                                      |
| on cygwin        | False                                      |
| on msys2         | False                                      |
| is superuser     | False                                      |
| default encoding | utf-8                                      |
| xonsh encoding   | utf-8                                      |
| encoding errors  | surrogateescape                            |
| on jupyter       | True                                       |
| jupyter kernel   | /opt/miniconda/share/jupyter/kernels/xonsh |
+------------------+--------------------------------------------+
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for reporting @anki-code - does this happen if you start your terminal emulator with xonsh?

**Comment by anki-code** [comment]
Yes. I can repeat it in Konsole and without X11 also (Ctrl+Alt+F2) with xonsh as default user shell and from bash as well.

**Comment by anki-code** [comment]
I can't repeat this on xonsh 0.11
