### ISSUE TITLE
f-string with env vars raises syntxc error in 0.9.23 under Python 3.9

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3865]
f-strings with env vars in expressions give an error. When you type into the repl

    f"hallo {$PATH}" 

you get an error:

_SyntaxError: <xonsh-code>:1:0: f-string: invalid syntax_

### xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.23          |
| Python           | 3.9.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+

```

</details>

**Comment by anki-code** [comment]
Hi @halloleo! I can't repeat:
```
f"hallo {$PATH}" 
#"hallo ['/opt/miniconda/bin', '/opt/miniconda/condabin']"

print(f"hallo {$PATH}" )
# hallo ['/opt/miniconda/bin', '/opt/miniconda/condabin']

```

**Comment by halloleo** [comment]
Interesting!

For me, both lines give a Syntax Error...

Any other way to debug this?

**Comment by anki-code** [comment]
I've tested it on ubuntu and on mac and it works for me. Try to run give the result:
```
# bash
XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=1 xonsh
$PATH
f"hallo {$PATH}" 
```

**Comment by scopatz** [comment]
hmmm very strange, this works for me...

**Comment by anki-code** [comment]
I can repeat it. The key is:
> | Python           | 3.9.0           |

```bash
docker run --rm -it python:3.9-slim /bin/bash -c "pip install xonsh && xonsh"
$XONSH_SHOW_TRACEBACK = $XONSH_DEBUG = 1
f"hallo {$PATH}" 
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/xonsh/ptk_shell/shell.py", line 238, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 238, in _parse_ctx_free
    raise original_error from None
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 499, in parse
    self._parse_error(self._error[0], self._error[1])
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 639, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:0: f-string: invalid syntax (<unknown>, line 1)
f"hallo {$PATH}"
^
```

**Comment by scopatz** [comment]
> @scopatz I think you need random choice not only for the shell type but for the python version too ;)

haha :laughing: 

Yeah this might be a 3.9 issue

**Comment by halloleo** [comment]
Yes, I had xonsh running under 3.9.0 on that machine! (Had forgotten to pin the old Python version in Homebrew, so it got silently upgraded...)

**Comment by tirkarthi** [comment]
Python 3.9 enables new parser by default. Can you try setting `PYTHONOLDPARSER=1` as environment variable to see if it helps?

**Comment by halloleo** [comment]
I have downgraded to Python 3.8.

So I installed Python3.9. sepeately and created a new venv with it in which I installed xonsh - but I cannot reproduce the issue anymore!

Now f-strings in xonsh 0.9.23 under Python 3.9 behave correctly - maybe because there _is_ a Python 3.8 still on the system...

**Comment by scopatz** [comment]
What does `xonfig` say in the xonsh session where it works?

**Comment by laloch** [comment]
Confirmed with a fix in #3884.
Thanks for reporting @halloleo.

**Comment by halloleo** [comment]
@scopatz Not sure whether still relevant, but the xonfig with the "overloaded" Python 3.9. xonsh showed:

```
+------------------+-----------------+
| xonsh            | 0.9.23          |
| Python           | 3.9.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

**Comment by scopatz** [comment]
Thanks @halloleo - always good to have more debug info
