### ISSUE TITLE
Crash on Win10 Windows Terminal

### ISSUE THREAD

**Issue by sgraham** [xonsh/xonsh#3880]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.23          |
| Python           | 3.8.5           |
| PLY              | 3.11            |
| have readline    | False           |
| prompt toolkit   | None            |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

### Traceback (if applicable)

<details>

```
 sgraham@layne c:\src> ls
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: ls
Did you mean one of the following?
    cls:  Alias
    CLS:  Command (CLS)
    cd:   Alias
    fg:   Alias
    bg:   Alias

  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\main.py", line 458, in main_xonsh
    shell.shell.cmdloop()
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\ptk_shell\shell.py", line 254, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\ptk_shell\shell.py", line 222, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xontrib\free_cwd.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\shortcuts\prompt.py", line 994, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\application\application.py", line 811, in run
    return loop.run_until_complete(
  File "c:\program files\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\application\application.py", line 778, in run_async
    return await _run_async2()
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\application\application.py", line 760, in _run_async2
    result = await _run_async()
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\application\application.py", line 685, in _run_async
    self._request_absolute_cursor_position()
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\application\application.py", line 939, in _request_absolute_cursor_position
    self.renderer.request_absolute_cursor_position()
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\renderer.py", line 426, in request_absolute_cursor_position
    self._min_available_height = self.output.get_rows_below_cursor_position()
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\output\win32.py", line 367, in get_rows_below_cursor_position
    info = self.get_win32_screen_buffer_info()
  File "C:\Users\sgraham\AppData\Roaming\Python\Python38\site-packages\xonsh\vended_ptk\prompt_toolkit\output\win32.py", line 195, in get_win32_screen_buffer_info
    success = windll.kernel32.GetConsoleScreenBufferInfo(
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP__CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO

[process exited with code 1]
```

</details>

**Comment by melund** [comment]
I can confirm the error. Right now you are using the builtin version that comes with xonsh, which is a few month old. This version of prompt-toolkit seems to have a problem with the newest version of windows terminal.

Can you try to install the newest version of `prompt-toolkit`? `pip install prompt_toolkit`. Xonsh should automatically pick it up and it solved the problem for me.

**Comment by melund** [comment]
@sgraham Thanks for reporting. I will update the builtin version of prompt-toolkit in xonsh

**Comment by sgraham** [comment]
Yes, thanks `pip install prompt_toolkit` fixes it.

**Comment by alannt777** [comment]
I am getting this error:

```
    self.proc = proc = subprocess.Popen(
  File "f:\miniconda\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "f:\miniconda\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\miniconda\lib\site-packages\xonsh\proc.py", line 1889, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "f:\miniconda\lib\site-packages\xonsh\built_ins.py", line 581, in run
    p = self._run_binary(kwargs)
  File "f:\miniconda\lib\site-packages\xonsh\built_ins.py", line 608, in _run_binary
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: ls
Did you mean one of the following?
    cls:  Alias
    CLS:  Command (CLS)
    cd:   Alias
    fg:   Alias
    bg:   Alias
```

**Comment by alannt777** [comment]
when I run `ls`
