### ISSUE TITLE
Exception at start in uptime code on Haiku

### ISSUE THREAD

**Issue by extrowerk** [xonsh/xonsh#3882]
xonsh prints some errors at startup:
```

Welcome to the Haiku shell.

~> uname -a
Haiku shredder 1 hrev54608 Sep 30 2020 06:33:40 x86_64 x86_64 Haiku
~> uptime
 19:33:59  up   1:00,  0 users
~> xonsh
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/packages/python3-3.7.7-2/.self/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/packages/python3-3.7.7-2/.self/lib/python3.7/vendor-packages/xonsh/history/__amalgam__.py", line 379, in run
    files = self.files(only_unlocked=True)
  File "/packages/python3-3.7.7-2/.self/lib/python3.7/vendor-packages/xonsh/history/__amalgam__.py", line 422, in files
    boot = uptime.boottime()
  File "/packages/python3-3.7.7-2/.self/lib/python3.7/vendor-packages/xonsh/xoreutils/uptime.py", line 280, in boottime
    up = uptime()
  File "/packages/python3-3.7.7-2/.self/lib/python3.7/vendor-packages/xonsh/xoreutils/uptime.py", line 265, in uptime
    or _uptime_linux()
  File "/packages/python3-3.7.7-2/.self/lib/python3.7/vendor-packages/xonsh/xoreutils/uptime.py", line 56, in _uptime_linux
    if xp.LIBC.sysinfo(buf) < 0:
AttributeError: 'NoneType' object has no attribute 'sysinfo'


                     Welcome to the xonsh shell (0.9.23)                      

         ~ Piggy glanced nervously into hell and cradled the xonsh ~          

------------------------------------------------------------------------------
xonfig tutorial    ->    Launch the tutorial in the browser
xonfig web         ->    Run the configuration tool in the browser and claim your shell 
(Note: Run the configuration tool or create a ~/.xonshrc file to suppress the welcome screen)

user@shredder ~ #      
```

## xonfig

<details>

```
user@shredder ~ # xonfig                                                      
+------------------+-----------------+
| xonsh            | 0.9.23          |
| Python           | 3.7.7           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | prompt_toolkit  |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | True            |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
user@shredder ~ #     
```

</details>

## Expected Behavior

xonsh should start without any warning, error or exception

## Current Behavior

As it is clearly visible in the provided output xonsh prints an error about linux uptime, which is unexpected, as xonsh have code to get the uptime on BeOS/Haiku too. I don't know too much about python, so i don't know why it tries to use the linux uptime code-path.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

Start xonsh on Haiku. I used a recent 64 bit nightly version.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Hey Thanks for opening this issue! I think this is happening because xonsh will usually default to linux behavior if no other valid OS is found. I don't think we have ever had anyone try to use it on Haiku, so thanks for opening an error message.  

PRs welcome!

Also, @extrowerk - do you know of any BeOS/Haiku CI services that we could use to develop and test on this OS?

**Comment by extrowerk** [comment]
If you check the uptime functions in xonsh you will see there is a codepath already for BeOS/Haiku and as far as i can see it should actually work, but somehow xonsh trying to use the linux way instead. No idea why. Haiku reports itself as "haiku1" in python i think (or maybe as "Haiku1", i am unsure, and no idea how to check it, sorry.)

Sorry, i don't know about any Haiku-enabled CI services yet :(

**Comment by extrowerk** [comment]
Maybe thiscould help:
```
>>> import os
>>> import platform
>>> platform.platform()
'Haiku-1-x86_64-64bit'
>>> platform.system()
'Haiku'
>>> print('Version      :', platform.python_version())
Version      : 3.7.7
>>> print('Version tuple:', platform.python_version_tuple())
Version tuple: ('3', '7', '7')
>>> print('Compiler     :', platform.python_compiler())
Compiler     : GCC 8.3.0
>>> print('Build        :', platform.python_build())
Build        : ('default', 'May 15 2020 14:21:28')
>>> print('uname:', platform.uname())
uname: uname_result(system='Haiku', node='Boxy', release='1', version='hrev54641 Oct 12 2020 08:12:53', machine='x86_64', processor='x86_64')
>>> print('system   :', platform.system())
system   : Haiku
>>> print('node     :', platform.node())
node     : Boxy
>>> print('release  :', platform.release())
release  : 1
>>> print('version  :', platform.version())
version  : hrev54641 Oct 12 2020 08:12:53
>>> print('machine  :', platform.machine())
machine  : x86_64
>>> print('processor:', platform.processor())
processor: x86_64
```
Let me know if you need any other info.

**Comment by Hierosme** [comment]
i can take a look , i think understand the trouble and clearly Haiku must have it work.

as start can It have one source of confusion:
```
sys.platform
'linux'
platform.uname().system
'Linux'
os.uname().sysname
'Linux'
```
and what return ``uname -o`` and ``uname -s`` on Haiku system ?

as exemple for GNU/Linux
```
$ uname -o
GNU/Linux
(venv) tuxa @ organon  ~/PycharmProjects/xonsh
$  uname -s
Linux
```
In our case i suppose we searching for 'Haiku'. like:

```
if str(platform.uname().system).lower() == 'haiku':
    # you a man !
    pass

```
Regards

**Comment by extrowerk** [comment]
Hi,

sadly not every python command works for me, probably i am just stupid :

```
~> python3
Python 3.7.7 (default, May 15 2020, 14:21:28) 
[GCC 8.3.0] on haiku1
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import platform
>>> sys.platform()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'sys' is not defined
>>> platform.uname().system
'Haiku'
>>> os.uname().system
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'posix.uname_result' object has no attribute 'system'
>>> 
~> uname -o
Haiku
~> uname -s
Haiku
~> 
```

Best Regards,
--Z

Hierosme <notifications@github.com>:

**Comment by Hierosme** [comment]
Look like ``platform`` work on Haiku-OS: ``platform.uname().system`` is the way...

I just have make a uname support for xonsh and my bad i have base it on ``os`` module .... i'll rewrite it for Haiku :)

Thank for you assistance i take a look

**Comment by extrowerk** [comment]
Thank you. Let me know if you need any other info.

**Comment by Hierosme** [comment]
extroweek, i back to you because i'll really hard to have a Haiku DEV env for me.

The uptime.py file line 260 use sys.platform.

Could you please return me what is the return on the Hailku please

**Comment by Hierosme** [comment]
in case juste go to ./xonsh/xoreutils/uptime.py line 244 and change "haiku1" by "haiku", that should work if i understand well...

**Comment by scopatz** [comment]
PRs very welcome!

**Comment by Hierosme** [comment]
The uptime.py have to be update, i have found the original script from [Pypi repo](https://pypi.org/project/uptime/) 

https://github.com/Cairnarvon/uptime/tree/master/src last pull request 2014 ;)

haiku1 mean Haiku R1 Alpha 4.1 [from here](https://pythonhosted.org/uptime/index.html#supported-platforms)

I'll integrate the update inside the xonsh-uptime and add changes for Haiku.

**Comment by extrowerk** [comment]
@Hierosme:
```
~> python3
Python 3.7.7 (default, May 15 2020, 14:21:28) 
[GCC 8.3.0] on haiku1
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.platform)
haiku1
>>> 
```

**Comment by Hierosme** [comment]
I have update the uptime.py file for have the last version with more system detection, i hop it will fixe the trouble.

**Comment by extrowerk** [comment]
I can confirm, the changes in the PR #3909 solved the problem and seems to be working ok:

```
Haiku shredder 1 hrev54608 Sep 30 2020 06:33:40 x86_64 x86_64 Haiku
~> xonsh

                     Welcome to the xonsh shell (0.9.24)                      

                          ~ The xonsh is a symbol ~                           

------------------------------------------------------------------------------
xonfig tutorial    ->    Launch the tutorial in the browser
xonfig web         ->    Run the configuration tool in the browser and claim your shell 
(Note: Run the configuration tool or create a ~/.xonshrc file to suppress the welcome screen)

user@shredder ~ #  
```

**Comment by Hierosme** [comment]
Pooooooo congratulation !!!

It was a true honnor to make the port for Haiku-OS.

**Comment by Hierosme** [comment]
After days of research i let here my notes

The fixe consist to edit: ``xonsh/xorutils/uptime.py`` file and relace **def _uptime_beos():** function by that

```
def _uptime_beos():
    """Returns uptime in seconds on None, on BeOS/Haiku."""
    try:
        libroot = ctypes.CDLL("libroot.so")
    except (AttributeError, OSError):
        return None

    if not hasattr(libroot, "system_time"):
        return None

    libroot.system_time.restype = ctypes.c_int64
    return libroot.system_time() / 1000000.0
```
Original uptime from where xonsh uptime module was forcked is a Python 2 module it have never been port to python3.

The update of uptime module + pass the pipeline CI look a impossible task because the actual CI pipieline let totaly no change for a code port by **2to3** (and by the way don't respect docstring specs about formated text 'TAB>'text)

That 100% a pipeline trouble, where python3 understand well any code convert by 2to3. Update to the last uptime version is possible and functional. (@extrowerk have test it version)

If one day the pipeline CI will accept code port by 2to3 then yes it will be possible to make a official port, in that case call me back i'll make the update.

Regards

**Comment by jnoortheen** [comment]
Fixed in #3909

**Comment by Hierosme** [comment]
Enjoy Haiku-OS user Xonsh is here !!!!

**Comment by extrowerk** [comment]
Great news, let me test it!

**Comment by extrowerk** [comment]
Latest git master:
```

Welcome to the Haiku shell.

~> xonsh
Skipping setup. Because no `readline` implementation available.
            Please install a backend (`readline`, `prompt-toolkit`, etc) to use
            `xonsh` interactively.
            See https://github.com/xonsh/xonsh/issues/1170
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/packages/python3-3.7.12-1/.self/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/packages/python3-3.7.12-1/.self/non-packaged/lib/python3.7/site-packages/xonsh/history/__amalgam__.py", line 408, in run
    files = self.files(only_unlocked=True)
  File "/packages/python3-3.7.12-1/.self/non-packaged/lib/python3.7/site-packages/xonsh/history/__amalgam__.py", line 451, in files
    boot = uptime.boottime()
  File "/packages/python3-3.7.12-1/.self/non-packaged/lib/python3.7/site-packages/xonsh/xoreutils/uptime.py", line 262, in boottime
    btime = func()
TypeError: 'NoneType' object is not callable


                    Welcome to the xonsh shell 0.11.0                     

       ~ I wanna thank you for putting me back in my snail shell ~        

--------------------------------------------------------------------------

Create ~/.xonshrc file manually or use xonfig to suppress the welcome message

Start from commands:
  xonfig web         # Run the configuration tool in the browser to create ~/.xonshrc 
  xonfig tutorial    # Open the xonsh tutorial in the browser

You are currently using the readline backend. For interactive tab-completion, on-the-fly syntax highlighting, and more, install prompt_toolkit by running:

  xpip install -U 'xonsh[full]'

--------------------------------------------------------------------------

user@Flatty ~ # uname -a
Haiku Flatty 1 hrev55763 Jan  5 2022 07:25:19 x86_64 x86_64 Haiku
user@Flatty ~ # 
```

**Comment by jnoortheen** [comment]
@extrowerk what is the output of `python -c "import sys;print(sys.platform)" ?

**Comment by extrowerk** [comment]
@jnoortheen :

```
Welcome to the Haiku shell.

~> python -c "import sys;print(sys.platform)"
haiku1
```

**Comment by jnoortheen** [comment]
It is a typo, can you check with this PR #4632

**Comment by extrowerk** [comment]
@jnoortheen : could you please elaborate what you mean with the typo?

**Comment by jnoortheen** [comment]
The typo was on the Xonsh code. The above PR will solve that

**Comment by extrowerk** [comment]
The problem is still there in 0.11.0:

```
/Ports/haikuports> xonsh
Skipping setup. Because no `readline` implementation available.
            Please install a backend (`readline`, `prompt-toolkit`, etc) to use
            `xonsh` interactively.
            See https://github.com/xonsh/xonsh/issues/1170

                      Welcome to the xonsh shell 0.11.0                      

                      ~ Become the Lord of the Files ~                       

-----------------------------------------------------------------------------

Create ~/.xonshrc file manually or use xonfig to suppress the welcome message

Start from commands:
  xonfig web         # Run the configuration tool in the browser to create ~/.xonshrc 
  xonfig tutorial    # Open the xonsh tutorial in the browser
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/packages/python3-3.7.12-1/.self/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/packages/python3-3.7.12-1/.self/non-packaged/lib/python3.7/site-packages/xonsh/history/__amalgam__.py", line 408, in run
    files = self.files(only_unlocked=True)
  File "/packages/python3-3.7.12-1/.self/non-packaged/lib/python3.7/site-packages/xonsh/history/__amalgam__.py", line 451, in files
    boot = uptime.boottime()
  File "/packages/python3-3.7.12-1/.self/non-packaged/lib/python3.7/site-packages/xonsh/xoreutils/uptime.py", line 262, in boottime
    btime = func()
TypeError: 'NoneType' object is not callable

You are currently using the readline backend. For interactive tab-completion, on-the-fly syntax highlighting, and more, install prompt_toolkit by running:

  xpip install -U 'xonsh[full]'

-----------------------------------------------------------------------------


```

**Comment by extrowerk** [comment]
My bad, i had an old version in the non-packaged folder structure, removing the old version solved the problem. Sorry for the noise.

**Comment by hierosme-nova** [comment]
Hi,
About the warning `readline`, `prompt-toolkit` ... That is not the root cause :)

Should be provide by you system, and in you case look strange...
The line with or _uptime_linux(), let me think about a worng OS detection .

Normaly the OS detection lib have been update for the last one.

Then:
if xp.LIBC.sysinfo(buf) < 0: follow by AttributeError: 'NoneType' object has no attribute 'sysinfo'>
Let me think about **buf** is **None** ....

**Comment by extrowerk** [comment]
Could you please reopen this issue? Thank you.

**Comment by extrowerk** [comment]
No need for rreopen, i checked the xonsh master branch, it doesn't have any bug. Sorry  for the noise!
