### ISSUE TITLE
Error following Tutorial: Write Your Own History Backend

### ISSUE THREAD

**Issue by grg121** [xonsh/xonsh#3961]
Hello there, 

I'm trying to follow the document [Tutorial: Write Your Own History Backend](https://xon.sh/tutorial_history_backend.html) but got some error when making the first described test.

I've added the file `~/.xonsh/history_couchdb.py` with:

```
import collections
from xonsh.history.base import History

class CouchDBHistory(History):
    def append(self, cmd):
        pass

    def items(self):
        yield {'inp': 'couchdb in action', 'ts': 1464652800, 'ind': 0}

    def all_items(self):
        return self.items()

    def info(self):
        data = collections.OrderedDict()
        data['backend'] = 'couchdb'
        data['sessionid'] = str(self.sessionid)
        return data
```

## xonfig

And my xonshrc:

```
import os.path
import sys
xonsh_ext_dir = os.path.expanduser('~/.xonsh')
if os.path.isdir(xonsh_ext_dir):
    sys.path.append(xonsh_ext_dir)

from history_couchdb import CouchDBHistory
$XONSH_HISTORY_BACKEND = CouchDBHistory

$PROMPT = '{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{RESET} {BOLD_BLUE}{prompt_end}{RESET} '

xontrib load abbrevs

## Abbrevs
abbrevs['gst'] = 'git status'

```

When I run xonsh:

```
❯ xonsh
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/grg121/.local/share/virtualenvs/xonsh-XYEHH6RD/lib/python3.8/site-packages/prompt_toolkit/history.py", line 70, in load
    for item in self.load_history_strings():
  File "/home/user/WORKSPACE/xonsh/xonsh/ptk_shell/history.py", line 28, in load_history_strings
    for cmd in hist.all_items(newest_first=True):
TypeError: all_items() got an unexpected keyword argument 'newest_first'
```

(Installed from sources in a Pipenv) 

```
xonsh --version
xonsh/0.9.24
```

Any idea what going on?

**Comment by laloch** [comment]
Hi @grg121, thanks for reporting. It's a documentation bug.
The current `xonsh.history.base.History.all_items()` prototype is
https://github.com/xonsh/xonsh/blob/f158a8e5e10468cb81a64bf37eae00c8687dea7c/xonsh/history/base.py#L132-L134

So, you need to implement the method as `all_items(self, newest_first=False)`.
I guess the argument is there to instruct the method to return history in reversed order, but I'm not 100% sure, because, as you can see, it's undocumented.

**Comment by grg121** [comment]
Oh! thanks @laloch I will review this and report here if I find a solution!
