### ISSUE TITLE
TypeError which is causing xonfig wizard to fail

### ISSUE THREAD

**Issue by SolarAquarion** [xonsh/xonsh#3971]
```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/xonsh/procs/__amalgam__.py", line 2287, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/usr/lib/python3.8/site-packages/xonsh/procs/__amalgam__.py", line 2079, in proxy_two
    return f(args, stdin)
  File "/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 19415, in xonfig
    return xonfig_main(args)
  File "/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 15007, in xonfig_main
    return XONFIG_MAIN_ACTIONS[ns.action](ns)
  File "/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 14664, in _wizard
    w = make_xonfig_wizard(
  File "/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 14627, in make_xonfig_wizard
    question=WIZARD_XONTRIB_QUESTION, yes=make_xontribs_wiz(), no=wiz.Pass()
  File "/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 14601, in make_xontribs_wiz
    return _make_flat_wiz(make_xontrib, get_xontribs().items())
  File "/usr/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 14552, in _make_flat_wiz
    for k in kids:
TypeError: make_xontrib() missing 1 required positional argument: 'xontrib'
```

**Comment by scopatz** [comment]
Hi @SolarAquarion - what is the output of `xonfig`?
