### ISSUE TITLE
assert False Error using custom appimage

### ISSUE THREAD

**Issue by grg121** [xonsh/xonsh#4007]
Hello there, I'm having troubles building a custom app image for Xonsh with additional pip dependencies. 

I want to install and load (among others contribs, the [powerline2](https://github.com/vaaaaanquish/xontrib-powerline2) plugin. Which I've tested and worked well in the official appimage for `xonsh/0.9.24`. Nevertheless, if I try to build the app image using the following:

## Dockerfile
```
FROM appimagecrafters/appimage-builder:latest

RUN apt-get install -y git && \
    pip3 install git+https://github.com/niess/python-appimage

ADD build.sh /entrypoint.sh
ADD pre-requirements.txt /pre-requirements.txt

RUN chmod u+x /entrypoint.sh

CMD "/entrypoint.sh"```
```

## build.sh

```
#!/bin/bash

mkdir -p /tmp/build && cd /tmp/build || exit
git clone --depth 1 https://github.com/xonsh/xonsh -b 0.9.24
cd xonsh/appimage || exit
echo 'xonsh' > requirements.txt
cat /pre-requirements.txt >> requirements.txt 
cd ..
python3 -m python_appimage build app ./appimage
mv xonsh-x86_64.AppImage /tmp/build/output
```

## Requirements.txt

```
backtrace==0.2.1
Pygments==2.7.3
colorama==0.3.7
offsh-xxh==1.0.0
packaging==20.7
pexpect==4.8.0
prompt-toolkit==3.0.8
ptyprocess==0.6.0
pyparsing==2.4.7
PyYAML==5.3.1
wcwidth==0.2.5
xonsh==0.9.24
xontrib-powerline2==1.2.1
```

Copy everything to the same directory and run:
```
docker build -t build_example ,
docker run -v $(pwd):/tmp/build/output build_example
```

When I test the generated appimage in a testing centos7  with this `.xonshrc`:
## .xonshrc
```
xontrib load readable-traceback
xontrib load powerline2
```

I got this traceback

### Traceback (if applicable)

```
[vagrant@centos7m ~]$ ./xonsh-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/xontribs.py", line 124, in xontribs_load
    update_context(name, ctx=ctx)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/xontribs.py", line 69, in update_context
    modctx = xontrib_context(name)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/xontribs.py", line 35, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/imphooks.py", line 123, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/tmp/.mount_xonsh-GWit0N/opt/python3.9/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
    assert False
AssertionError
Failed to load xontrib powerline2.
```
I have no idea why it is entering in such `assert False`, nor if the problem is with the way I'm building the image or is a bug in Xonsh.

Any help would be really appreciated.

Best regards,

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by AstraLuma** [comment]
I've always avoided the parser. AppImage actually mounts--xonsh is not running in a container or from zip.

**Comment by gforsyth** [comment]
> I've always avoided the parser.

Whoop, sorry, I should've read the traceback more carefully!

**Comment by gforsyth** [comment]
@grg121 can you try building this on python 3.8 instead and see if it works?

**Comment by grg121** [comment]
EY @gforsyth you're rigjt, I didn't realized that the official image is built with 3.8, I've just tried extracting both appimages and looking for differences and it seems that the only difference is the python version.

```
diff extracted_official_xonsh/AppRun extracted_custom_xonsh/AppRun
18c18
< ${APPDIR}/usr/bin/python3.8 -u "${APPDIR}/opt/python3.8/bin/xonsh" "$@"
---
> ${APPDIR}/usr/bin/python3.9 -u "${APPDIR}/opt/python3.9/bin/xonsh" "$@"
Common subdirectories: extracted_official_xonsh/opt and extracted_custom_xonsh/opt
Common subdirectories: extracted_official_xonsh/usr and extracted_custom_xonsh/usr
diff extracted_official_xonsh/xonsh.desktop extracted_custom_xonsh/xonsh.desktop
5c5
< Comment=Xonsh on Python 3.8.6
---
> Comment=Xonsh on Python 3.9.0
9d8
< X-AppImage-Version=0.9.24
```

I'm going to build it with python 3.8 and return here, thanks!

**Comment by anki-code** [comment]
The xonsh AppImage was built by [regro/rever](https://github.com/regro/rever) using [appimage.xsh](https://github.com/regro/rever/blob/master/rever/activities/appimage.xsh).

**Comment by grg121** [comment]
Hello there! 

Yes, I tried building the app image with python 3.8 and it worked just fine! I imagine that the problem is with pytho3.9 then. 

I'll check that appimage,xsh script @anki-code, thank you very much!

Best regards

**Comment by gforsyth** [comment]
Thanks for helping out @anki-code !  I'm going to close this out @grg121 -- please feel free to ping here if you have further issues.

**Comment by lypanov** [comment]
I'm curious why this issue was closed? I'm having issues with the same asserts in random xsh scripts since updating to 3.9.

**Comment by gforsyth** [comment]
@lypanov -- I don't think that `pacman` system updates respect constraints imposed by AUR packages.  Probably the AUR recipe should be updated to link to a system python 38.

This was closed out because it was an issue w.r.t. appimage usage, not general Python 3.9 support (for which there are other open issues and a PR, as you noted)
