### ISSUE TITLE
Error after comment with colon

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4033]
Hi!

```python
touch example.txt
```
Test 1:
```
chmod +x example.txt
```
Output: ok!

Test 2:
```
#qwe
chmod +x example.xsh
```
Output: ok!

Test 3:
```
#qwe:
chmod +x example.xsh
```
Output:
```
# xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
# Traceback (most recent call last):
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 322, in _push
#     code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/execer.py", line 135, in compile
#     tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/execer.py", line 95, in parse
#     tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/execer.py", line 274, in _parse_ctx_free
#     raise original_error
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
#     tree = self.parser.parse(
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/parsers/base.py", line 497, in parse
#     tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
#     return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
#     tok = call_errorfunc(self.errorfunc, errtoken, self)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
#     r = errorfunc(token)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/parsers/base.py", line 3432, in p_error
#     self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/parsers/base.py", line 639, in _parse_error
#     raise err
#   File "<string>", line None
# SyntaxError: <xonsh-code>:2:9: ('code: example',)
# chmod +x example.xsh
#          ^

```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Yep, that's definitely a parser bug.  Thanks for opening this @anki-code !
