### ISSUE TITLE
xonfig wizard: list index out of range

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4035]
Hi!

```python
XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=1 xonsh --no-rc
xonfig wizard
# Traceback (most recent call last):
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/procs/proxies.py", line 506, in run
#     r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/procs/proxies.py", line 298, in proxy_two
#     return f(args, stdin)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/aliases.py", line 703, in xonfig
#     return xonfig_main(args)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/xonfig.py", line 794, in xonfig_main
#     return XONFIG_MAIN_ACTIONS[ns.action](ns)
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/xonfig.py", line 449, in _wizard
#     fname = env.get("XONSHRC")[-1] if ns.file is None else ns.file
#   File "/opt/miniconda/lib/python3.8/site-packages/xonsh/tools.py", line 206, in __getitem__
#     return _expandpath(self._l[item])
# IndexError: list index out of range
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by AsafFisher** [comment]
Did you fix it? I can do a PR..

**Comment by anki-code** [comment]
Nope, PR is welcome!
