### ISSUE TITLE
@$(cmd) substitution doesn't work properly with $THREAD_SUBPROCS off, but de-sugaring it does

### ISSUE THREAD

**Issue by Qyriad** [xonsh/xonsh#4056]
The [tutorial](https://xon.sh/tutorial.html#command-substitution-with) says that `@$(cmd)` is syntax sugar for `@([i.strip() for i in $(cmd).split()])`, but if `$THREAD_SUBPROCS` is set to `False`, then they behave differently, with only the latter having the correct behavior. `@$(cmd)` fails to capture the output of `cmd`, and `cmd`'s output is written directly to standard out instead of being passed as arguments, which since `$THREAD_SUBPROCS == False` is not particularly surprising, but de-sugaring the input to `@([i.strip() for i in $(cmd).split()])` correctly captures the output of the substituted command just fine, and correctly substitutes it in as arguments.

## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.9.1           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.8           |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+

```

</details>

## Expected Behavior

Where `args` is a simple program that prints the arguments as a list, for clarity's sake.
```python
# args.py
import sys
print(sys.argv)
```
Then:
```python
>>> args @$(echo 1 2 3)
['/home/qyriad/.local/bin/args', '1', '2', '3']
>>> args @([i.strip() for i in $(echo 1 2 3).split()])
['/home/qyriad/.local/bin/args', '1', '2', '3']
```

## Current Behavior

```python
>>> args @$(echo 1 2 3)
1 2 3
['/home/qyriad/.local/bin/args']
>>> args @([i.strip() for i in $(echo 1 2 3).split()])
['/home/qyriad/.local/bin/args', '1', '2', '3']
```

## Steps to Reproduce

An example without that `args` script:
```
$ xonsh --no-rc
>>> $THREAD_SUBPROCS = False
>>> $XONSH_SHOW_TRACEBACK = True
>>> aliases['ls'] = 'ls --color=auto'
>>> @([i.strip() for i in $(which ls).split()])
# -Snip directory listing-

>>> @$(which ls)
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 17275, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 2377, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23342, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23263, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured, envs=envs)
  File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23216, in cmds_to_specs
    spec = SubprocSpec.build(cmd, captured=captured, env=env)
  File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 22978, in build
    spec.resolve_alias()
  File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23009, in resolve_alias
    cmd0 = self.cmd[0]
IndexError: list index out of range
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
I think this has to do with py39. Could you check with lesser Python versions ? xonsh doesn't have py39 compatibility yet

**Comment by Qyriad** [comment]
Same behavior on Python 3.8 and Python 3.7.

**Comment by gforsyth** [comment]
Thanks for reporting this @Qyriad!  

That does look like a bug to me, likely stemming from us handling the different subproc execution classes slightly incorrectly.  This is probably yet another reason we should get rid of `@$`.

This is obviously an annoying bug -- the less-than-helpful workaround right now is to keep `THREAD_SUBPROCS=True` (which precludes using the `bashisms` xontrib atm)

**Comment by anki-code** [comment]
JFYI #4094

**Comment by anki-code** [comment]
Fix is in #6112

> This is probably yet another reason we should get rid of @$

[Decorator aliases](https://xon.sh/tutorial.html#decorator-aliases) and [xontrib-dalias](https://github.com/anki-code/xontrib-dalias) are here for solving this kind of things.
