### ISSUE TITLE
Xonsh cannot parse negative index to a list?

### ISSUE THREAD

**Issue by jonaslb** [xonsh/xonsh#4059]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.21          |
| Python           | 3.9.1           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit  |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | fedora          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior

`[0][-1]==0`

## Current Behavior

Raises an AssertionError

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xonsh/ptk_shell/shell.py", line 208, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/usr/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/lib/python3.9/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/lib/python3.9/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.9/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.9/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
    assert False
AssertionError
```
</details>

## Steps to Reproduce

I was originally trying to find the last return value by `list(__xonsh__.history.rtns)[-1]`, which besides being a very long way of writing it (maybe there's an easier way?), didn't work. However the reason appeared to be some parse error, see the traceback above. I managed to simplify it to using `[-1]` for indexing, like eg `[0][-1]`.

Edit: Found a workaround, although it looks really weird: `__xonsh__.history.rtns[-1:][0]`

**Comment by gforsyth** [comment]
Thanks for reporting @jonaslb -- this is a known issue with Python 3.9 because of changes in the AST that we haven't caught up to yet.  There's an issue tracking this in #4028 so I'm going to close this out here.
