### ISSUE TITLE
xonsh shows error when pickling function using multiprocessing on windows

### ISSUE THREAD

**Issue by james5deutschland** [xonsh/xonsh#4065]
running following code:
```python
if __name__ == '__main__':
    from multiprocessing import Process, Manager
    # cannot open this!
    import multiprocessing as mp
    import time
    # what is going on?
    def longSleep():
        # import time
        time.sleep(50)
    mp.freeze_support() # great now?
    for x in range(5):
        p = Process(target=longSleep,args=())
        p.start()
        time.sleep(3)
        alive = p.is_alive()
        # let's just create a die-away thread. does it work?
        print("check is alive?",alive)
        if alive:
            print("i will kill you.")
            p.terminate()
    import os
    os.abort()
```

will result into following error:
```cmd
Traceback (most recent call last):
  File "d:\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Python\Python38\Scripts\xonsh.exe\__main__.py", line 7, in <module>
  File "d:\programs\python\python38\lib\site-packages\xonsh\main.py", line 422, in main
    _failback_to_other_shells(args, err)
  File "d:\programs\python\python38\lib\site-packages\xonsh\main.py", line 369, in _failback_to_other_shells
    raise err
  File "d:\programs\python\python38\lib\site-packages\xonsh\main.py", line 420, in main
    sys.exit(main_xonsh(args))
  File "d:\programs\python\python38\lib\site-packages\xonsh\main.py", line 474, in main_xonsh
    run_script_with_cache(
  File "d:\programs\python\python38\lib\site-packages\xonsh\codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "d:\programs\python\python38\lib\site-packages\xonsh\codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File ".\check_timeout.xsh", line 13, in <module>
    p.start()
  File "d:\programs\python\python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "d:\programs\python\python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "d:\programs\python\python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "d:\programs\python\python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "d:\programs\python\python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function longSleep at 0x000001D83AB5B670>: attribute lookup longSleep on __main__ failed

E:\AGI\AutoUP\poster\essay_upload>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\programs\python\python38\lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect
```

**Comment by gforsyth** [comment]
Does it run using your Python 3.8 repl?

**Comment by james5deutschland** [comment]
Yes it is

**Comment by james5deutschland** [comment]
By the way, multiple errors when running ```cls``` or ```clear``` on windows, and does not even properly install using python3.6 win_x64
