### ISSUE TITLE
xonfig styles

### ISSUE THREAD

**Issue by andrii482** [xonsh/xonsh#4067]
```
 ~ $ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.8.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.9           |
| shell type       | prompt_toolkit  |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+

```

```
~ $ xonfig styles
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
pkg_resources.VersionConflict: (prompt-toolkit 3.0.9 (/home/user/.local/lib/python3.8/site-packages), Requirement.parse('prompt-toolkit<2.1.0,>=2.0.0'))
pygments cache not found, building...
```

also, it required version installed - I get error:
```
Traceback (most recent call last):
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 419, in main
    args = premain(argv)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 355, in premain
    env = start_services(shell_kwargs, args)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 308, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/shell.py", line 211, in __init__
    from xonsh.ptk_shell.shell import PromptToolkitShell as shell_class
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 26, in <module>
    from prompt_toolkit.key_binding.bindings.emacs import (
ImportError: cannot import name 'load_emacs_shift_selection_bindings' from 'prompt_toolkit.key_binding.bindings.emacs' (/usr/lib/python3/dist-packages/prompt_toolkit/key_binding/bindings/emacs.py)
Xonsh encountered an issue during launch
Failback to /bin/bash
Traceback (most recent call last):
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 419, in main
    args = premain(argv)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 355, in premain
    env = start_services(shell_kwargs, args)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 308, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/shell.py", line 211, in __init__
    from xonsh.ptk_shell.shell import PromptToolkitShell as shell_class
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 26, in <module>
    from prompt_toolkit.key_binding.bindings.emacs import (
ImportError: cannot import name 'load_emacs_shift_selection_bindings' from 'prompt_toolkit.key_binding.bindings.emacs' (/usr/lib/python3/dist-packages/prompt_toolkit/key_binding/bindings/emacs.py)
Xonsh encountered an issue during launch
```

**Comment by gforsyth** [comment]
Hey @andrii482 -- sorry about the bug, that's weird.  I would keep `prompt_toolkit` installed at a version >= 3

Did the message from `pkg_resources` break anything?

**Comment by andrii482** [comment]
@gforsyth  this message just inform that  I cant see/choose/change  styles because I get error when run `xonfig styles`

(also, I already use prompt_toolkit version >= 3, but this version, as you see make unavailable to use `xonfig styles` command)

**Comment by gforsyth** [comment]
Ahh, can you try upgrading `pygments`?  And then if it still doesn't work, maybe try to uninstall and reinstall `prompt_toolkit`.

I have ptk 3.0.9 with pygments 2.7.3 and I can view the styles without the error you're seeing

**Comment by gforsyth** [comment]
(Also possible that this is fixed on current master

**Comment by andrii482** [comment]
@gforsyth 
```
 pip3 install pygments==2.7.3                                                                                                           3  20:03 
Collecting pygments==2.7.3
  Using cached Pygments-2.7.3-py3-none-any.whl (950 kB)
ERROR: gitsome 0.8.4 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 3.0.14 which is incompatible.
Installing collected packages: pygments
Successfully installed pygments-2.7.3
 ~  pip3 install pygments                                                                                                                      4  20:03 
Requirement already satisfied: pygments in ./.local/lib/python3.8/site-packages (2.7.3)
 ~  xonfig styles                                                                                                                              5  20:04 
pygments cache not found, building...
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
pkg_resources.VersionConflict: (prompt-toolkit 3.0.14 (/home/andrii/.local/lib/python3.8/site-packages), Requirement.parse('prompt-toolkit<2.1.0,>=2.0.0'))
 ~  !   
```

**Comment by gforsyth** [comment]
Ahh, I see -- `gitsome` is raising those errors because it hasn't been updated in quite some time and requires an old version of `prompt_toolkit`.  I think you'll have to remove it to get `xonsh` working (or stick it in a separate environment)

**Comment by andrii482** [comment]
@gforsyth  I delete `gitsome`, reinstall `xonsh` and now get this error 
```
xonsh
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 419, in main
    args = premain(argv)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 355, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 308, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/shell.py", line 211, in __init__
    from xonsh.ptk_shell.shell import PromptToolkitShell as shell_class
  File "/usr/local/lib/python3.8/dist-packages/xonsh/ptk_shell/shell.py", line 26, in <module>
    from prompt_toolkit.key_binding.bindings.emacs import (
ImportError: cannot import name 'load_emacs_shift_selection_bindings' from 'prompt_toolkit.key_binding.bindings.emacs' (/home/andrii/.local/lib/python3.8/site-packages/prompt_toolkit/key_binding/bindings/emacs.py)
Xonsh encountered an issue during launch
Failback to /bin/bash
```

```
~$ xonsh --version
xonsh/0.9.24
```

**Comment by andrii482** [comment]
`pip3 install ' prompt-toolkit==3.0.9' --force-reinstall`
little bit fixing problem

**Comment by andrii482** [comment]
in xonsh/0.9.25 bug fixed . thanks
