### ISSUE TITLE
Bad file descriptor [Errno 9] when using executable aliases with pipeing  

### ISSUE THREAD

**Issue by rtomaszewski** [xonsh/xonsh#4081]
## xonfig

When trying to run 2 executable aliases and chain/pipe them together they randomly error out.

The 1st alias 'l' is a wrapper around 'ls'. 
The 2nd alias 'g' is a wrapper around 'grep'. 
See the code below.

The command to trigger the issue is:

```
$ l | g test
```

The errors i see are (see below for more details):

1) 
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xonsh/proc.py", line 1889, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3.9/site-packages/xonsh/built_ins.py", line 581, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3.9/site-packages/xonsh/built_ins.py", line 592, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.9/site-packages/xonsh/proc.py", line 584, in __init__
    self.proc = proc = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 9] Bad file descriptor
```

2) the xonsh hangs because 'grep' is running in 'foreground' and waiting for input.

### mine xonshrc

My .xonshrc:

```
import datetime
from shutil import get_terminal_size
import sys 

time=str(datetime.datetime.now())
print(f"[{time}]config .xonshrc start ...")

$COMPLETIONS_CONFIRM=True
$PROMPT = '\n[{localtime}] {YELLOW}{env_name} {BOLD_BLUE}{user}@{hostname} {BOLD_GREEN}{cwd} {gitstatus}{RESET}\n> '

# xontrib load coreutils

def _l(args, stdin=None, stdout=None, stderr=None):

    cmd=[ "/usr/bin/ls", 
                        "-l", 
                        "--group-directories-first", 
                        "--color=auto",
        ]

    cmd_args = cmd + args 

    p=![@(cmd_args)]
    # p=![/usr/bin/ls -l --group-directories-first --color=auto] # 

aliases['l']=_l
# del _l

def _grep(args, stdin=None, stdout=None, stderr=None):
    """https://xon.sh/tutorial.html
    """
    cmd=[ "/usr/bin/grep", 
                "--colour=always",
                "-i",
                "-E"
        ]

    if stdin == None :
        return

    # import ipdb; ipdb.set_trace()
    input=[ i for i in stdin]

    cmd_args = cmd + args 
    p=![/bin/echo @("".join(input)) | @(cmd_args) ]

    # sleep 1.2s

aliases['g']=_grep
# aliases['grep']=_grep


time=str(datetime.datetime.now())
print(f"[{time}]config .xonshrc end.")

```

<details>
```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.9.1           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.8           |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | manjaro         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```
</details>

The xpip freez generate a lot of packages but if you need please let me know.

## Expected Behavior

The ls alias pipes its std output as stdin to grep alias.

## Current Behavior

When i run 

```
$ l | g test
```

I see 2 types of errors very consistently. 
I see more often the 'bad file descriptor error' then xonsh hanging. 
But overall at least 50% of the time the command fails.  

More info on the second error type: 
It looks like the whole xonsh session is hanging. 
When you run `ps` from another terminal you can see that xonsh has
started a 'grep' process (as a child) and because of the nature of grep command it waits now on some input. 
I assume any stdin text was provided to grep and it waits and hangs and this causes the whole command to appear as hanging.
You can press ctrol+c and it terminates the grep and brings back the prompt from xonsh.

When i enabled the "verbose" and debug flags this is what i see for both errors:

```
~ >>> bash
[rado@manjaro ~]$ cat  /tmp/xonsh-debug-variables
export XONSH_TRACEBACK_LOGFILE=/tmp/xonsh-traceback.log
export XONSH_SHOW_TRACEBACK=True ;
export XONSH_TRACE_SUBPROC=True ;
export XONSH_DEBUG=2

[rado@manjaro ~]$ source /tmp/xonsh-debug-variables
[rado@manjaro ~]$ xonsh
[2021-02-05 22:40:47.973067]config .xonshrc start ...
[2021-02-05 22:40:47.973132]config .xonshrc end.

# example error type 2

[22:40:48]  rado@manjaro ~
> l | g 'test'
<xonsh-code>:1:6 - l | g 'test'
<xonsh-code>:1:6 + ![l | g 'test']
TRACE SUBPROC: (['l'], '|', ['g', 'test'])
TRACE SUBPROC: (['/usr/bin/ls', '-l', '--group-directories-first', '--color=auto'],)
TRACE SUBPROC: (['/bin/echo', 'total 24\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[0m\x1b[34mDesktop\x1b[0m\ndrwxr-xr-x 1 rado rado  616 Jan 26 20:26 \x1b[34mDocuments\x1b[0m\ndrwxr-xr-x 1 rado rado  350 Feb  4 14:53 \x1b[34mDownloads\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mMusic\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Jan 13 19:20 \x1b[34mPictures\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mPublic\x1b[0m\ndrwxr-xr-x 1 rado rado   92 Dec 12 14:11 \x1b[34mTemplates\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mVideos\x1b[0m\nlrwxrwxrwx 1 rado rado   39 Dec 15 20:37 \x1b[96m_manjaro-files\x1b[0m -> \x1b[44;30m/run/media/rado/USB128GB/_manjaro-files\x1b[0m\ndrwxr-xr-x 1 rado rado  298 Jan 31 17:36 \x1b[34mcolors-test\x1b[0m\ndrwxr-xr-x 1 rado rado    6 Jan  3 17:15 \x1b[34mgo\x1b[0m\ndrwxr-xr-x 1 rado rado 1116 Feb  2 19:30 \x1b[34mtmp\x1b[0m\nlrwxrwxrwx 1 rado rado   24 Dec 17 15:20 \x1b[96musb\x1b[0m -> \x1b[44;30m/run/media/rado/USB128GB\x1b[0m\n-rw-r--r-- 1 rado rado   42 Jan  3 21:37 manjaro-log-helper.logs\n-rw------- 1 rado rado 3930 Jan  2 22:40 \x1b[36mnohup.out\x1b[0m\n-rwxr-xr-x 1 rado rado   33 Dec 16 22:11 \x1b[92mstart\x1b[0m\n-rw-r--r-- 1 rado rado    3 Jan 13 20:42 test.txt\n'], '|', ['/usr/bin/grep', '--colour=always', '-i', '-E', 'test'])

^^^ hangs here right now, pressed ctrol+c to return to the xonsh prompt
^C
[22:41:07]  rado@manjaro ~

# example error type 1 

[22:41:07]  rado@manjaro ~
> l | g 'test'
<xonsh-code>:1:6 - l | g 'test'
<xonsh-code>:1:6 + ![l | g 'test']
TRACE SUBPROC: (['l'], '|', ['g', 'test'])
TRACE SUBPROC: (['/usr/bin/ls', '-l', '--group-directories-first', '--color=auto'],)
TRACE SUBPROC: (['/bin/echo', 'total 24\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[0m\x1b[34mDesktop\x1b[0m\ndrwxr-xr-x 1 rado rado  616 Jan 26 20:26 \x1b[34mDocuments\x1b[0m\ndrwxr-xr-x 1 rado rado  350 Feb  4 14:53 \x1b[34mDownloads\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mMusic\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Jan 13 19:20 \x1b[34mPictures\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mPublic\x1b[0m\ndrwxr-xr-x 1 rado rado   92 Dec 12 14:11 \x1b[34mTemplates\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mVideos\x1b[0m\nlrwxrwxrwx 1 rado rado   39 Dec 15 20:37 \x1b[96m_manjaro-files\x1b[0m -> \x1b[44;30m/run/media/rado/USB128GB/_manjaro-files\x1b[0m\ndrwxr-xr-x 1 rado rado  298 Jan 31 17:36 \x1b[34mcolors-test\x1b[0m\ndrwxr-xr-x 1 rado rado    6 Jan  3 17:15 \x1b[34mgo\x1b[0m\ndrwxr-xr-x 1 rado rado 1116 Feb  2 19:30 \x1b[34mtmp\x1b[0m\nlrwxrwxrwx 1 rado rado   24 Dec 17 15:20 \x1b[96musb\x1b[0m -> \x1b[44;30m/run/media/rado/USB128GB\x1b[0m\n-rw-r--r-- 1 rado rado   42 Jan  3 21:37 manjaro-log-helper.logs\n-rw------- 1 rado rado 3930 Jan  2 22:40 \x1b[36mnohup.out\x1b[0m\n-rwxr-xr-x 1 rado rado   33 Dec 16 22:11 \x1b[92mstart\x1b[0m\n-rw-r--r-- 1 rado rado    3 Jan 13 20:42 test.txt\n'], '|', ['/usr/bin/grep', '--colour=always', '-i', '-E', 'test'])
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xonsh/proc.py", line 1889, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3.9/site-packages/xonsh/built_ins.py", line 581, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3.9/site-packages/xonsh/built_ins.py", line 592, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.9/site-packages/xonsh/proc.py", line 584, in __init__
    self.proc = proc = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 9] Bad file descriptor

[22:41:08]  rado@manjaro ~

# example good output 

[22:41:08]  rado@manjaro ~
> l | g 'test'
<xonsh-code>:1:6 - l | g 'test'
<xonsh-code>:1:6 + ![l | g 'test']
TRACE SUBPROC: (['l'], '|', ['g', 'test'])
TRACE SUBPROC: (['/usr/bin/ls', '-l', '--group-directories-first', '--color=auto'],)
TRACE SUBPROC: (['/bin/echo', 'total 24\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[0m\x1b[34mDesktop\x1b[0m\ndrwxr-xr-x 1 rado rado  616 Jan 26 20:26 \x1b[34mDocuments\x1b[0m\ndrwxr-xr-x 1 rado rado  350 Feb  4 14:53 \x1b[34mDownloads\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mMusic\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Jan 13 19:20 \x1b[34mPictures\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mPublic\x1b[0m\ndrwxr-xr-x 1 rado rado   92 Dec 12 14:11 \x1b[34mTemplates\x1b[0m\ndrwxr-xr-x 1 rado rado    0 Dec 12 14:11 \x1b[34mVideos\x1b[0m\nlrwxrwxrwx 1 rado rado   39 Dec 15 20:37 \x1b[96m_manjaro-files\x1b[0m -> \x1b[44;30m/run/media/rado/USB128GB/_manjaro-files\x1b[0m\ndrwxr-xr-x 1 rado rado  298 Jan 31 17:36 \x1b[34mcolors-test\x1b[0m\ndrwxr-xr-x 1 rado rado    6 Jan  3 17:15 \x1b[34mgo\x1b[0m\ndrwxr-xr-x 1 rado rado 1116 Feb  2 19:30 \x1b[34mtmp\x1b[0m\nlrwxrwxrwx 1 rado rado   24 Dec 17 15:20 \x1b[96musb\x1b[0m -> \x1b[44;30m/run/media/rado/USB128GB\x1b[0m\n-rw-r--r-- 1 rado rado   42 Jan  3 21:37 manjaro-log-helper.logs\n-rw------- 1 rado rado 3930 Jan  2 22:40 \x1b[36mnohup.out\x1b[0m\n-rwxr-xr-x 1 rado rado   33 Dec 16 22:11 \x1b[92mstart\x1b[0m\n-rw-r--r-- 1 rado rado    3 Jan 13 20:42 test.txt\n'], '|', ['/usr/bin/grep', '--colour=always', '-i', '-E', 'test'])
drwxr-xr-x 1 rado rado  298 Jan 31 17:36 colors-test
-rw-r--r-- 1 rado rado    3 Jan 13 20:42 test.txt

```

## Steps to Reproduce

run multiple times and observe the errors 

```
$ l | g test
```

**Comment by rtomaszewski** [comment]
Ive found a workaround for my issue.
When i run the command in this form 

```
 l | cat | g test
```

It seems to work perfectly fine 100% of the time. Ive tried to see if i can trigger one of the above described errors but nothing like this. All executions are good and don't produce any errors

```
> for i in range(200):
.    l | cat | g test
```

**Comment by rtomaszewski** [comment]
I can see there is still open https://github.com/xonsh/xonsh/issues/2496
But not sure how relevant it is to my issue with aliases

Is python 3.9 actually supported and recommended at the moment anyway? If not what python version could be considered as most stable? Would prefer to hit as little bugs as possible :).
https://github.com/xonsh/xonsh/pull/3588

**Comment by anki-code** [comment]
> Is python 3.9 actually supported and recommended at the moment anyway? If not what python version could be considered as most stable? 

Python 3.8 is recommended as current stable.
