### ISSUE TITLE
When disk is full the xonsh SQLite history backend raises exception

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4084]
Hi!

When disk is full the xonsh SQLite history backend raises exception and back to bash. Expected behavior is to show warning and stay working.

Exception (xonsh 0.9.26, Ubuntu 20):
<details>

```
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/main.py", line 421, in main
    sys.exit(main_xonsh(args))
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/main.py", line 459, in main_xonsh
    shell.shell.cmdloop()
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 344, in cmdloop
    self.default(line, raw_line)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/base_shell.py", line 389, in default
    self._append_history(
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/base_shell.py", line 429, in _append_history
    hist.append(info)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/history/sqlite.py", line 275, in append
    xh_sqlite_append_history(
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/history/sqlite.py", line 172, in xh_sqlite_append_history
    _xh_sqlite_insert_command(c, cmd, sessionid, store_stdout, remove_duplicates)
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/history/sqlite.py", line 123, in _xh_sqlite_insert_command
    values["frequency"] = _xh_sqlite_erase_dups(cursor, values["inp"]) + 1
  File "/opt/miniconda/lib/python3.8/site-packages/xonsh/history/sqlite.py", line 91, in _xh_sqlite_erase_dups
    cursor.execute(sql, (input,))
sqlite3.OperationalError: database or disk is full
Xonsh encountered an issue during launch
Failback to /bin/bash
(base) pc@pc:~$
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by rijusougata13** [comment]
can you guide me in which file i should look for the problem?

**Comment by jnoortheen** [comment]
@rijusougata13 you could start with this file `xonsh/history/sqlite.py`

**Comment by anki-code** [comment]
PR is here. JFYI The way to test with RAM disk:
```python
bash
sudo mount -t tmpfs -o size=1m tmpfs /mnt/ramdisk  # Create 1 megabyte size RAM disk
cd /mnt/ramdisk
echo '$XONSH_HISTORY_BACKEND = "sqlite"' > rc
echo '$XONSH_DATA_DIR = "/mnt/ramdisk"' >> rc
xonsh --rc rc
cat /dev/random > dump
# SQLite History Backend Error: database or disk is full
```
