### ISSUE TITLE
Parsing error when storing tuples in a dictionary

### ISSUE THREAD

**Issue by RitikShah** [xonsh/xonsh#4110]
If I'm making a dictionary with tuples as the keys, I get an odd error that is not present in normal python:

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.26               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.1                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.16               |
| shell type       | prompt_toolkit       |
| pygments         | 2.8.0                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | autoxsh              |
| xontrib 2        | commands             |
| xontrib 3        | coreutils            |
| xontrib 4        | hist_navigator       |
| xontrib 5        | jedi                 |
| xontrib 6        | mpl                  |
| xontrib 7        | onepath              |
| xontrib 8        | output_search        |
| xontrib 9        | pdb                  |
| xontrib 10       | pipeliner            |
| xontrib 11       | pipeliner_parallel   |
| xontrib 12       | prompt_bar           |
| xontrib 13       | whole_word_jumping   |
| xontrib 14       | xog                  |
| xontrib 15       | z                    |
+------------------+----------------------+
```

</details>

## Expected Behavior
```py
>>> a = {(1, 2): 3}
>>> a[(1,2)]
3
```

## Current Behavior

```py
$ a = {(1, 2): 3}
$ a[(1,2)]
TypeError: {(1, 2): 3} is not a callable object
```

### Traceback (if applicable)

<details>

```
$ a[(1,2)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/xonsh/base_shell.py", line 374, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/local/lib/python3.9/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/xonsh/built_ins.py", line 403, in call_macro
    sig = inspect.signature(f)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 3130, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 2879, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 2254, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: {(1, 2): 3} is not a callable object
```

</details>

## Steps to Reproduce
```py
$ a = {(1, 2): 3}
$ a[(1,2)]
TypeError: {(1, 2): 3} is not a callable object
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
hi! 
The fix for this is in master. Please install xonsh from master:
```python
pip install -U git+https://github.com/xonsh/xonsh.git
```
