### ISSUE TITLE
Prompt toolkit throws AssertionError [xonsh installed using PyPy3.7]

### ISSUE THREAD

**Issue by ashwinvis** [xonsh/xonsh#4117]
I tried xonsh + PyPy3.7. It generally works. However if I write a command, and then if I interrupt it with Ctrl-C before executing it, an unhandled AssertionError is thrown.

## xonfig
<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.7.9           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.16          |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

## Expected Behavior

Handle the AssertionError within xonsh / it could be a prompt-toolkit issue.

### Traceback (if applicable)

<details>

```py
Traceback (most recent call last):
  File "/home/avmo/.local/pipx/venvs/xonsh/site-packages/xonsh/main.py", line 420, in main
    sys.exit(main_xonsh(args))
  File "/home/avmo/.local/pipx/venvs/xonsh/site-packages/xonsh/main.py", line 458, in main_xonsh
    shell.shell.cmdloop()
  File "/home/avmo/.local/pipx/venvs/xonsh/site-packages/xonsh/ptk_shell/shell.py", line 254, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/avmo/.local/pipx/venvs/xonsh/site-packages/xonsh/ptk_shell/shell.py", line 222, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/avmo/.local/pipx/venvs/xonsh/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/avmo/.local/pipx/venvs/xonsh/site-packages/prompt_toolkit/application/application.py", line 849, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/home/avmo/.pyenv/versions/pypy3.7-7.3.3/lib-python/3/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/avmo/.pyenv/versions/pypy3.7-7.3.3/lib-python/3/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/home/avmo/.pyenv/versions/pypy3.7-7.3.3/lib-python/3/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/home/avmo/.local/pipx/venvs/xonsh/site-packages/prompt_toolkit/application/application.py", line 650, in run_async
    assert not self._is_running, "Application is already running."
AssertionError: Application is already running.
Xonsh encountered an issue during launch
Failback to /bin/bash```
```

</details>

## Steps to Reproduce

```sh
# Install
pyenv install pypy3.7-7.3.3
pipx install --python $PYENV_ROOT/versions/pypy3.7-7.3.3/bin/pypy xonsh
xpip install prompt-toolkit
# Launch xonsh
XONSH_DEBUG=1 xonsh --no-rc
# Inside xonsh, interrupt with Ctrl-C to error
cd /something^C
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting @ashwinvis -- I agree this sounds like it's probably on the prompt_toolkit side, but if there's anything we can fix on our end, please let us know.
