### ISSUE TITLE
Cannot echo {}

### ISSUE THREAD

**Issue by kseistrup** [xonsh/xonsh#413]
Initializing a JSON file fails:

```pytb
~ $ echo {} > empty.json
...<ENTER>
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: {',)
~ $
```
(the redirection doesn't contribute to the failure, it just adds context to the example)

**Comment by scopatz** [comment]
This is interesting. Even if I force a subproc mode, it still thinks that there is a parser error.

```console
scopatz@artemis ~ $ $[echo {}]
`·.,¸,.·*¯`·.,¸,.·* 
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 151, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 264, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 2506, in p_error
    column=p.lexpos))
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 335, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:9: ('code: {',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 158, in push
    locs=self.ctx)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 95, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 70, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 164, in _parse_ctx_free
    raise original_error
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 151, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 264, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 2506, in p_error
    column=p.lexpos))
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 335, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:7: ('code: {',)
```

This is probably a relatively easy fix somewhere in the parser or lexer...

**Comment by scopatz** [comment]
Note that forcing the argument to be a string does work, so you can use that for the moment.

```console
scopatz@artemis ~ $ echo "{}"
{}
```

**Comment by kseistrup** [comment]
Thanks, I'm aware of that (and should have mentioned it in the issue), but quotes suck. :wink:

**Comment by scopatz** [comment]
Yeah, they do :).
