### ISSUE TITLE
Can't access the last element of a list via [-1]

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#4135]
## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.26               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.2                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.14               |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.4                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+
```

</details>

## Expected Behavior

Using `[-1]` should print the last element of a list
```
$ some_list = [1, 2, 3]
$ some_list[0]
1
$ some_list[-1]
```
Expect to get `3`

## Current Behavior

I get an `AssertionError` instead (see traceback below)

### Traceback (if applicable)

<details>

```
traceback
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/ptk_shell/shell.py", line 322, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2253, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/0.9.26/libexec/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2247, in apply_trailers
    assert False
AssertionError
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi! I can't reproduce this on xonsh 0.9.27. Please update.

**Comment by eugenesvk** [comment]
Hm, yeah, updating xonsh resolved it
