### ISSUE TITLE
Multiple, seemingly random errors (OSError, AttributeError, ...)

### ISSUE THREAD

**Issue by AdamJamil** [xonsh/xonsh#4224]
Create a new directory, with three files. `touch a b c`. Then define the following alias:

```
def forall_(args, stdin=None, stdout=None):
	input = stdin.read().strip()
	for x in input.split("\n"):
		execx(args[0].replace("$x", x))
	return 0

aliases["forall"] = forall_
```

Then simply call `ls | forall "touch $x"` repeatedly. The expected behavior is that nothing should happen. Instead, after some number of calls, particular errors arise.

The most common one is this:
```
Exception in thread Thread-1856:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/galois/.local/lib/python3.8/site-packages/xonsh/procs/proxies.py", line 497, in run
    io.open(self.errwrite, "wb", -1), encoding=enc, errors=err
OSError: [Errno 9] Bad file descriptor
```

After some more calls, this might happen:
```
Traceback (most recent call last):
  File "/home/galois/.local/lib/python3.8/site-packages/xonsh/procs/pipelines.py", line 160, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/galois/.local/lib/python3.8/site-packages/xonsh/procs/specs.py", line 445, in run
    p = self.cls(self.alias, self.cmd, **kwargs)
  File "/home/galois/.local/lib/python3.8/site-packages/xonsh/procs/proxies.py", line 430, in __init__
    self.stdin = io.open(stdin, "wb", -1)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ProcProxyThread.__del__ at 0x7f5b91c57550>
Traceback (most recent call last):
  File "/home/galois/.local/lib/python3.8/site-packages/xonsh/procs/proxies.py", line 452, in __del__
    self._restore_sigint()
  File "/home/galois/.local/lib/python3.8/site-packages/xonsh/procs/proxies.py", line 591, in _restore_sigint
    old = self.old_int_handler
AttributeError: 'ProcProxyThread' object has no attribute 'old_int_handler'
```

Sometimes, especially with chaining more custom functions, the shell might even crash and exit out. I am running Ubuntu 20.04.1 LTS on WSL. Any knowledge as to why this is happening would be helpful.

**Comment by anki-code** [comment]
Hi @AdamJamil ! 
1. It looks like you want to create something like [xontrib-pipeliner](https://github.com/anki-code/xontrib-pipeliner).
Please take a look on [Pipeliner exec](https://github.com/anki-code/xontrib-pipeliner/blob/master/README.md#pipeliner-exec).

2. I've tested your code on Arch Linux and it works without errors. To make stress test I've ran:
```python
mkdir -p /tmp/t
cd /tmp/t
for i in range(10):
    ls / | forall "touch $x"
```

What is your xonsh version?

**Comment by AdamJamil** [comment]
Ah sorry, here is my xonfig. I am running WSL v2 btw.

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+
```

So, sometimes even 10 executions in a row could work okay. Also, I don't think you added any files to /tmp/t. Try `touch a b c` in the directory first, then maybe 20 iters of my code to be safe. For some reason I find a lesser rate of errors when there are fewer files in the directory.

Also, thank you for the reference! I am new to xonsh (and indeed, linux in general), so I appreciate it.

**Comment by anki-code** [comment]
> Try touch a b c in the directory first, then maybe 20 iters of my code

Ok, after increasing the counter to 100 I can repeat something similar on Arch:

```python
mkdir -p /tmp/t
cd /tmp/t
for i in range(100):
    ls / | forall @(f"touch $x-{i}")
```
```
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/procs/pipelines.py", line 160, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/procs/specs.py", line 449, in run
    p = self._run_binary(kwargs)
  File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/procs/specs.py", line 460, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/procs/posix.py", line 99, in __init__
    self.proc = proc = subprocess.Popen(
  File "/opt/miniconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 9] Bad file descriptor
```

**Comment by AdamJamil** [comment]
Nice! Also, I'm curious - was it necessary to change the arg to an fstring using i, in order to reproduce the result?

I would like to help with this issue, but I'm unsure what to do. Would I basically start debugging the files in the traceback?

**Comment by anki-code** [comment]
> was it necessary to change the arg to an fstring using i, in order to reproduce the result?

I did it to just increase the count of files in the directory.

> Would I basically start debugging the files in the traceback?

When I read the traceback that I got on Arch my thought was that the massive `subprocess.Popen` to do `execx(cmd)` uses the one file descriptor and this raises the collisions. It will be great to understand how it works and do prevent the uncontrolled using the descriptor or change the descriptor for every thread. 

You can start from testing pure Python code that do the same as you found: `for i in range(100): subprocess.Popen(cmd)` and try to catch the error.

**Comment by AdamJamil** [comment]
Yeah, I've got no clue what is going on. Anyone else who could figure this out?

**Comment by anki-code** [comment]
I had time to dive into it a bit. It looks like when we use commands with pipe in the loop then the descriptor to read stdin could be closed while other command already start and try to read from it.

I tried to add `sleep` to check this:
```python
def forall_(args, stdin=None, stdout=None):
	input = stdin.read().strip()
	for x in input.split("\n"):
		execx(args[0].replace("$x", x))
	return 0

aliases["forall"] = forall_

mkdir -p /tmp/t
cd /tmp/t
for i in range(60):
    ls / | forall @(f"echo -n $x-{i}")
    sleep 1
```
But I got the same error after a few iterations of the loop. And this is the good news: the issue is not about speed of creating/destroying the pipe. It looks like logic issue around piping and it could be solved.

**Comment by anki-code** [comment]
@AdamJamil please rename this issue to `OSError: [Errno 9] Bad file descriptor`.

I can repeat this also for the aliases:

```python
aliases['e'] = 'echo -n @(1)'
for i in range(50):
      e

#111111Exception in thread Thread-162:
#Traceback (most recent call last):
#  File "/opt/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
#    self.run()
#  File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/procs/__amalgam__.py", line 2295, in run
#    io.open(self.c2pwrite, "wb", -1), encoding=enc, errors=err
#OSError: [Errno 9] Bad file descriptor
```

**Comment by AdamJamil** [comment]
Nice reduction. Your code also hangs my shell (I cannot do anything to regain it other than close the terminal).

**Comment by anki-code** [comment]
I've tested the [case described above around ExecAlias](https://github.com/xonsh/xonsh/issues/4224#issuecomment-820567660) and it fails on all previous versions of xonsh. This is not a regress issue.

**Comment by cottrell** [comment]
I can repro this too but I land on the self.errwrite bit (I suspect it is OS dependent code path variations here). Breaking into the error I see that self.errwrite is an *integer* (10 to be specific). Why is io.open(10) being run and what should happen if it ends up being an integer at that spot? I think some local knowledge is needed to understand what is intended there.

And notice that the io.open(integer) fails on the SECOND write. See the example immediately below:


```python
In [1]: import io                                                                                                                                                                                                  

In [2]: io.open(10, 'wb', -1).write(b'this')                                                                                                                                                                       
Out[2]: 4

In [3]: io.open(10, 'wb', -1).write(b'this')                                                                                                                                                                       
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-df1ce7a78ce6> in <module>
----> 1 io.open(10, 'wb', -1).write(b'this')

OSError: [Errno 9] Bad file descriptor

In [4]: io.open('j', 'wb', -1).write(b'this')                                                                                                                                                                      
Out[4]: 4

In [5]: io.open('j', 'wb', -1).write(b'this')                                                                                                                                                                      
Out[5]: 4

In [6]: io.open('j', 'wb', -1).write(b'this')                                                                                                                                                                      
Out[6]: 4
```


Repro as above
```
$ aliases['e'] = 'echo -n @(1)'  # ExecAlias 
.......................................... for i in range(100): 
..........................................       e 
..........................................                                                                                                                                                                         
111111Exception in thread Thread-48:
Traceback (most recent call last):
  File "/home/cottrell/anaconda3/envs/38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/cottrell/dev/xonsh/xonsh/procs/proxies.py", line 497, in run
    io.open(self.errwrite, "wb", -1), encoding=enc, errors=err
OSError: [Errno 9] Bad file descriptor
```

**Comment by cottrell** [comment]
We have also noticed this which might be bad? 

![image](https://user-images.githubusercontent.com/223276/117282723-f83e7880-ae5c-11eb-96b4-b96f2cd291d9.png)

**Comment by anki-code** [comment]
> And notice that the io.open(integer) fails on the SECOND write. 

Good catch. We have to understand how to fix the xonsh code.

**Comment by cottrell** [comment]
Not sure but posting as we get ideas, this might be relevant: 

https://stackoverflow.com/questions/9084099/re-opening-stdout-and-stdin-file-descriptors-after-closing-them

Calling dup when passing file descriptors around might be a good idea.

https://stackoverflow.com/questions/9084099/re-opening-stdout-and-stdin-file-descriptors-after-closing-them

**Comment by anki-code** [comment]
hi @AstraLuma! May be you have thoughts around this issue and the links above?

**Comment by cottrell** [comment]
@anki-code @AstraLuma 

Another finding is that the error goes away with gc disabled.

See the test.py below.  In xonsh:

./test.py # fails 
./test.py true # succeeds

```
$ cat test.py                                                                                                                                                             
import sys

aliases['e'] = 'echo -n @(1)'  # ExecAlias

if __name__ == '__main__':
    args = sys.argv
    disable_gc = False
    if len(args) > 1:
        disable_gc = args[1].lower() == 'true'
    print(f'disable_gc = {disable_gc}')
    if disable_gc:
        import gc
        gc.disable()
    for i in range(100):
        e

```

**Comment by anki-code** [comment]
I can confirm that it works. Could you explain the machinery behind this fix?

```python
xonsh --no-rc
import gc
gc.disable()
aliases['e'] = 'echo -n @(1)'  # ExecAlias
for i in range(100):
      e
# it works
```

**Comment by ediphy-dwild** [comment]
hi anki - after patching parts of xonsh to trace fd-related calls and running the repro in a loop...

my guess is non deterministic collection time of some file or wrapper object that is part of a cycle causes close() to be called while a fd is still in use, or perhaps while the extracted int fileno is used rather than the object, *or* the same fd number is reused, after which a wrapper from a previous loop is collected, calling close on a fileno that it no longer owns (eg i see fileno 4, 6 etc being opened and closed regularly - but never (?) duped)

sorry i cant be more definitive here but the ownership/lifecycle of the fds was not very clear to me as i am not familiar at all with the xonsh codebase, but we'd been getting hit by this so decided to have a go at determining the underlying issue.

**Comment by anki-code** [comment]
@ediphy-dwild yeah, I have the same hypothesis after diving into this part of code. I give more probability to "the same fd number is reused". So I'm wondering: is there a way to use different fd number for every new execution of the command pipeline? Why xonsh developers use the same numbers...

I think we would have the new step in this issue if we determine: is it possible to use different FD or we should use one scope of FDs and do deep review the logic behind pipelining.

**Comment by ediphy-dwild** [comment]
the same fd entry number is used in both the working case and the failing case - which is why my guess is that the error is early/late cleanup of objects pointing at the same number.

it gets hairy as the number is extracted from the object, and the raw int is then used for an open. so now you have two things within the process with a close() call. theres some additional hair around a cache of already closed fd numbers in there too :)

**Comment by anki-code** [comment]
Another workaround is to [avoid using `ProcProxyThread`](https://github.com/xonsh/xonsh/blob/4dc08232e615a75a524fbf96f17402a7a5b353a5/xonsh/procs/specs.py#L652-L655) by [marking the alias as unthreadable](https://xon.sh/tutorial.html#unthreadable-aliases):

```python
from xonsh.tools import unthreadable

@unthreadable
def _e():
    execx('echo -n 1')
aliases['e'] = _e

for i in range(100):
      e
# it works
```

**Comment by doronz88** [comment]
@anki-code I also couldn't reproduce from your example on my macOS, but as I reported in #5241 the problem persists, but it seems the cause might be a bit different, or maybe it's racy

**Comment by nedsociety** [comment]
Yup, I've been using xonsh on all Windows, Mac and (recently) Linux yet encountered this error in Linux only.
