### ISSUE TITLE
Error in parser

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#4282]
```
~ 🐚 for l, r in list(links.keys()):
....     links[r, l] = links[l, r]
....
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/bin/xonsh/xonsh/ptk_shell/shell.py", line 238, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/usr/local/bin/xonsh/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/local/bin/xonsh/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/bin/xonsh/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/usr/local/bin/xonsh/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/bin/xonsh/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/bin/xonsh/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/bin/xonsh/xonsh/parsers/base.py", line 2643, in p_subscriptlist
    elts=[p1.value] + [x.value for x in p2],
AttributeError: 'Name' object has no attribute 'value'
```

v0.9.24

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by AstraLuma** [comment]
Possibly related:

```
🐚 for place in liter:
..     print(place, sum(links[(place, b)] for b in bodies))
..
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/bin/xonsh/xonsh/base_shell.py", line 362, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/local/bin/xonsh/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 2, in <module>
  File "<xonsh-code>", line 2, in <genexpr>
  File "/usr/local/bin/xonsh/xonsh/built_ins.py", line 1241, in call_macro
    sig = inspect.signature(f)
  File "/usr/lib/python3.9/inspect.py", line 3130, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.9/inspect.py", line 2879, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.9/inspect.py", line 2254, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: <large object snipped> is not a callable object
```

**Comment by anki-code** [comment]
Hi @AstraLuma ! Thank you for catching this. Please provide the repeatable example of code that could be just copy and pasted.

Try to update xonsh to 0.9.27 to get better support of Python 3.9.

**Comment by AstraLuma** [comment]
You should try the snippets above.

If you get an error about missing variables, it didn't reproduce.

**Comment by anki-code** [comment]
> If you get an error about missing variables, it didn't reproduce.

On the current master:

```python
for l, r in list(links.keys()):
    links[r, l] = links[l, r]
# NameError: name 'links' is not defined

for place in liter:
    print(place, sum(links[(place, b)] for b in bodies))
# NameError: name 'liter' is not defined

# Prepared by xontrib-hist-format
```

Does it mean that we can close this issue?

**Comment by AstraLuma** [comment]
Probably.

**Comment by anki-code** [comment]
Could you please update xonsh to 0.9.27 and try to repeat?

**Comment by anki-code** [comment]
I'm going to close this because I can't repeat this on 0.9.27
