### ISSUE TITLE
XSH singleton doesn't work with amalgamated (==production) xonsh

### ISSUE THREAD

**Issue by daniel-shimon** [xonsh/xonsh#4289]
@jnoortheen 

```sh
# Ensure amalgamate.py is installed
which amalgamate.py
# Install xonsh in production mode (without '-e')
pip install '.[full]'
# Try running xonsh
xonsh
```

I'm getting:
```
AttributeError: 'XonshSession' object has no attribute 'completers'
Failed to load xontrib jedi.
Traceback (most recent call last):
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 22082, in main
    args = premain(argv)
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 22022, in premain
    env = start_services(shell_kwargs, args, pre_env=pre_env)
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 21970, in start_services
    XSH.shell = Shell(execer=execer, **shell_kwargs)
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 16365, in __init__
    XSH.history = hist = xhm.construct_history(
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 1241, in construct_history
    backend = env.get("XONSH_HISTORY_BACKEND")
AttributeError: 'NoneType' object has no attribute 'get'
Xonsh encountered an issue during launch
```

**Comment by jnoortheen** [comment]
`XSH.load()` is not called. I am not sure why this is the case. Does the same run after removing all generated __amalgam__.py modules?

**Comment by daniel-shimon** [comment]
> `XSH.load()` is not called. I am not sure why this is the case. Does the same run after removing all generated **amalgam**.py modules?

No. Installing without amalgamation (`pip install -e`) works fine.
The issue seems to be that code from submodules imports and uses the non-amalgamated XSH, while amalgamated code uses the amalgamated XSH (I printed in a few places and indeed XSH in `xonsh/history/__amalgam__.py` and in `xonsh/__amalgam__.py` are two different objects).
Seems to me we need to disable amalgamating `built_ins.py` altogether
