### ISSUE TITLE
env.get - AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4293]
Hi @jnoortheen! I think it's related to #4280.

Running xonsh on current main branch (38295a1):
```python
bash
XONSH_DEBUG=1 xonsh --no-rc
# ok

xonsh --no-rc
# Traceback (most recent call last):
#   File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 22082, in main
#     args = premain(argv)
#   File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 22022, in premain
#     env = start_services(shell_kwargs, args, pre_env=pre_env)
#   File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 21970, in start_services
#     XSH.shell = Shell(execer=execer, **shell_kwargs)
#   File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 16365, in __init__
#     XSH.history = hist = xhm.construct_history(
#   File "/opt/miniconda3/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 1241, in construct_history
#     backend = env.get("XONSH_HISTORY_BACKEND")
# AttributeError: 'NoneType' object has no attribute 'get'
# Xonsh encountered an issue during launch
# Failback to /bin/bash
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Duplicate #4289
