### ISSUE TITLE
Multi line command gets copied and pasted as several lines, not one line

### ISSUE THREAD

**Issue by jerabaul29** [xonsh/xonsh#4348]
I am on Ubuntu 20.04, Xonsh 0.9.27.

It looks like long lines that get wrapped are treated by Xonsh as two (or more) lines, not one line, when being copy pasted. This is really painful when copy pasting terminal output between terminals. For example:

terminal 1 wrapping:

```
jrmet@L590 ~ $ echo "some looooooooooooooooooooooooooooooooo
ooooog command"
some loooooooooooooooooooooooooooooooooooooog command
```

Copy pasting to terminal 2, which is wider, also running Xonsh: I get two lines, instead of getting 1 long line, and this creates problems down the line:

```
jrmet@L590 ~ $ echo "some looooooooooooooooooooooooooooooooo
.............. ooooog command"
..............
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
SyntaxError: <xonsh-code>:1:5: "
echo "some looooooooooooooooooooooooooooooooo
     ^
```

Any way that copy pasting from Xonsh behaves as in bash and other shells, where even a long wrapped line is still well understood as a single line?

**Comment by anki-code** [comment]
Hi! I can't repeat this in Konsole on Arch.

To create the long line you can use simple example:
```python
echo @('.' * 200)
```

What is your terminal emulator?

**Comment by yaxollum** [comment]
@jerabaul29 Can you try to run Xonsh using the readline backend and see if the line wrapping behavior matches bash? (to test the readline backend, launch xonsh using `xonsh --shell-type=readline`)

If you want to permanently switch to readline, add the line `$SHELL_TYPE='readline'` to your `~/.xonshrc`.

**Comment by jerabaul29** [comment]
@anki-code : the example you suggest works just fine:

```
L590 ~ $ echo @('.' * 200)
........................................................................................................................................................................................................
```

I think this is an issue about input vs output? (?). Your example is with multiline as output, mine as input?

Regarding the terminal emulator, here is what I get:

```
L590 ~ $ echo $SHELL
/bin/bash
```

I.e., the 'usual' bash (I am on Ubuntu 20.04).

@yaxollum I tried with the readline backend, still getting the issue.

Attached the detailed trackeback when I set ```$XONSH_SHOW_TRACEBACK = True``` first:

```
L590 ~ $ echo "some looooooooooooooooooooooooooooooooo
.............. ooooog command"
..............
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 322, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/execer.py", line 238, in _parse_ctx_free
    raise original_error from None
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/parsers/base.py", line 506, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/parsers/base.py", line 3448, in p_error
    self._parse_error(
  File "/home/jrmet/.local/lib/python3.8/site-packages/xonsh/parsers/base.py", line 648, in _parse_error
    raise err
SyntaxError: <xonsh-code>:1:5: "
echo "some looooooooooooooooooooooooooooooooo
     ^
```

**Comment by anki-code** [comment]
@jerabaul29 in Python you should use `\` character if you want to split the string. This should work:
```python
echo "some looooooooooooooooooooooooooooooooo\
ooooog command"
# some loooooooooooooooooooooooooooooooooooooog command
```

**Comment by jerabaul29** [comment]
Ok, you are right, this is the explanation! :) .

However, this is a bit painful when copy pasting stuff between terminals having different widths as explained in the first post. Any idea how there could be worked around? ...

**Comment by anki-code** [comment]
@jerabaul29 I have no problem with this in Konsole. Please check your terminal emulator.

AFAIK when you have the line `123456789` in small window with size 4:
```
1234
5678
9
```
and you want to copy this line some terminal emulators put to the clipboard `1234\n5678\n9` instead of `123456789`.
If I run `echo @('.' * 400)` in Konsole and then copy and paste the multiline result I'll get single line with size 400.

**Comment by yaxollum** [comment]
@anki-code I think jerabaul29 is talking about copying the *prompt line*, not the output of the command. Can you try that? (i.e. actually type a long line like `echo hellooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo` and try to copy the *prompt* to another terminal, not the output)

**Comment by anki-code** [comment]
Yeah, I can reproduce this now. This looks like prompt-toolkit issue because I can't reproduce this on `xonsh --no-rc --shell-type readline`. You can open an issue in https://github.com/prompt-toolkit/python-prompt-toolkit/issues

**Comment by jerabaul29** [comment]
Will do tomorrow :) .

**Comment by jerabaul29** [comment]
Reported there, feel free to add some explanations there: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1475

**Comment by itszn** [comment]
I wanted to share a bit of a hacky workaround:

https://gist.github.com/itszn/5db98e131da33b8154112abf8ae781f8

It reprints the prompt + command over the prompt toolkit one. That way you can copy it like normal!

**Comment by paugier** [comment]
It's indeed a very annoying issue. Copy pasting a string in a line longer that the terminal width is broken in xonsh. This is really a strong limitation.

It gives things like that with several dots (here I only tried to copy paste the date):

```
pierre@gre /data0/Sim_data/aniso/ns3d.strat_toro_Fh2.500e-02_Rb10_160x160x40_V3x3x0.75_N40_2022-03
-03_09-06-57 $ 22-03 
..................................................................................................
.............. -03
```

It doesn't seem easy to fix upstream (https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1475#issuecomment-893248967). Could another solution be found in xonsh?

**Comment by anki-code** [comment]
I'm going to close this because it's upstream prompt-toolkit restriction. But I see some workarounds:

## Workarounds

### Bing shortcut to copy command

You can add a shortcut like `Ctrl+Y` to copy current command without any selection.

Binding in `~/.xonshrc`:
```xsh
# ~/.xonshrc
@events.on_ptk_create
def custom_keybindings(bindings, **kw):
    @bindings.add("c-y")
    def copy_current_command(event):  # Ctrl+Y (crossplatform)
        if (text := event.current_buffer.text):
            event.app.clipboard.set_data(@.imp.prompt_toolkit.clipboard.ClipboardData(text))
            @.imp.prompt_toolkit.shortcuts.print_formatted_text('Copied!')
```
or [bind during session](https://github.com/xonsh/xonsh/discussions/6116):
```xsh
@__xonsh__.shell.shell.key_bindings.add("c-y")  # Ctrl+Y (crossplatform)
def _copy_cmd(event):
    if (text := event.current_buffer.text):
        event.app.clipboard.set_data(@.imp.prompt_toolkit.clipboard.ClipboardData(text))
        @.imp.prompt_toolkit.shortcuts.print_formatted_text('Copied!')
```

### Using editor

Press `Ctrl+X Ctrl+E` [binding](https://xon.sh/keyboard_shortcuts.html) to open editor and copy the command from there.
