### ISSUE TITLE
OSError('out of pty devices') when running many background jobs in Subprocess Mode

### ISSUE THREAD

**Issue by stellarpower** [xonsh/xonsh#4354]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.8.10               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | 2.3.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | linuxmint            |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+

```

</details>

## Current Behavior
Firstly I'm new to Xonsh, so afraid I'm not entirely sure what information would be helpful, please let me know and I can add details. Also I'm limited in my ability to paste code in as this script as-is contains sensitive information for work.

I have a script that is querying a web server, parsing the JSON returned, extracting some URLS, and then downloading these resources in the background before later processing them. Under our testing server, with few resources, the script runs fine; on the production server, with many returned resources in the JSON, I am constantly getting an OSError('out of pty devices') raised. I have increased the PTY limit from the system default of 4096 to over 1,000,000 using sysctl and this error still occurs. Note that whilst we have a large number of resources to download, it's to the order of 1000, far fewer than the 1,000,000 PTY device limit _ I'm definitely not calling out to wget e.g. a million times. Without any more knowledge of Xonsh's internals, this leads me to suspect that some of these may not be closed over time.

I believe the culprit is running commands in the background - in this case, the resources we want to download are several megabytes, it would take hours to run the script and wait for the output sequentially, but only minutes to launch in the background in subprocess mode. However, this then appears to overload the system. The suspected cause is below, although I think I am also seeing this exception raised in other parts of the script, such as in querying the server before we even start downloading:

```
def wgetDefault(url, outputDir, supplementaryArgs = []):
    # Original, just worked with testing server with few resources:
    # wget --quiet --content-disposition -P @( outputDir ) @( supplementaryArgs )  @( url ) &
    
    # sleep 0.5 # Even this line has been the source of the exception
    time.sleep(0.5) # so replaced with internal version
    
    wget --quiet --content-disposition -P @( outputDir ) @( supplementaryArgs )  @( url ) &
```
I would call this function over each in a list of URLs, for example. I have added a sleep before the wget call, in an attempt to stagger the process like a waterfall, rather than have them all start immediately and exhaust the PTY devices. This is an inconvenience and does not always prevent errors but has enabled me to continue working at times. However I have also seen the exception raised form the sleep line - so I am guessing the subprocess mode call is raising the exception even with simple commands. I therefore replaced it with the Python call.

## Expected Behaviour:
Don't want to fill this out too much being new to the language - "it just works as I expected without crashing" isn't particularly helpful for you if I don't know with much certainty what the error is :D

I guess as an end user, if this isn't a setup issue and indicated that I can't launch too many jobs in the background using subprocess mode at once, then that would require a bit of a redesign to my scripts. Other shell scripting languages are poor in support for programming concepts, but are able to handle things like redirection and running background tasks very simply; so without much prior knowledge, if Xonsh is python + shell, I'd sort of expect it to be able to forget about things like this too, unless mentioned otherwise.

### Traceback
- Note that this includes another error - I get a `key error: lue` message for any expresson returned to the terminal output - I have to wrap it explicitly in a print call. Believe this relates to colour handling.

<details>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/xonsh/procs/proxies.py", line 508, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/procs/proxies.py", line 300, in proxy_two
    return f(args, stdin)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/aliases.py", line 752, in showcmd
    sys.displayhook(args)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 264, in _pprint_displayhook
    print_color(tokens, end=end)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/tools.py", line 1884, in print_color
    builtins.__xonsh__.shell.shell.print_color(string, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/base_shell.py", line 584, in print_color
    formatter = pyghooks.XonshTerminal256Formatter(style=style_proxy)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/pyghooks.py", line 1367, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pygments/formatters/terminal256.py", line 134, in __init__
    self._setup_styles()  # convert selected style's colors to term. colors
  File "/usr/lib/python3/dist-packages/pygments/formatters/terminal256.py", line 224, in _setup_styles
    self.style_string[str(ttype)] = (escape.color_string(),
  File "/usr/lib/python3/dist-packages/pygments/formatters/terminal256.py", line 53, in color_string
    esc = codes[self.fg[5:]]
KeyError: 'lue'
{"pageNumber":19,"pageSize":100,"totalRecords":1889,"result":[],"success":true,"message":"","errors":[],"traceId":null}
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
/usr/lib/python3/dist-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Callable
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 423, in main
    _failback_to_other_shells(args, err)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 370, in _failback_to_other_shells
    raise err
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 421, in main
    sys.exit(main_xonsh(args))
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 475, in main_xonsh
    run_script_with_cache(
  File "/usr/local/lib/python3.8/dist-packages/xonsh/codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "./main.xsh", line 65, in <module>
    main()
  File "./main.xsh", line 54, in main
    downloadAll(resourceUrls, DownloadDir)
  File "/mnt/ramdisk/resourceQuery.xsh", line 62, in downloadAll
    wgetDefault(i, outputDir)
  File "/mnt/ramdisk/resourceQuery.xsh", line 25, in wgetDefault
    wget --quiet --content-disposition -P @( outputDir ) @( supplementaryArgs )  @( url ) &
  File "/usr/local/lib/python3.8/dist-packages/xonsh/built_ins.py", line 199, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/procs/specs.py", line 843, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured, envs=envs)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/procs/specs.py", line 813, in cmds_to_specs
    _update_last_spec(specs[-1])
  File "/usr/local/lib/python3.8/dist-packages/xonsh/procs/specs.py", line 768, in _update_last_spec
    r, w = xli.pty.openpty() if use_tty else os.pipe()
  File "/usr/lib/python3.8/pty.py", line 30, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python3.8/pty.py", line 60, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 26, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 36, in <module>
    apt_pkg.init_system()
apt_pkg.Error: E:Error reading the Tuple table

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 423, in main
    _failback_to_other_shells(args, err)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 370, in _failback_to_other_shells
    raise err
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 421, in main
    sys.exit(main_xonsh(args))
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 475, in main_xonsh
    run_script_with_cache(
  File "/usr/local/lib/python3.8/dist-packages/xonsh/codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "./main.xsh", line 65, in <module>
    main()
  File "./main.xsh", line 54, in main
    downloadAll(resourceUrls, DownloadDir)
  File "/mnt/ramdisk/resourceQuery.xsh", line 62, in downloadAll
    wgetDefault(i, outputDir)
  File "/mnt/ramdisk/resourceQuery.xsh", line 25, in wgetDefault
    wget --quiet --content-disposition -P @( outputDir ) @( supplementaryArgs )  @( url ) &
  File "/usr/local/lib/python3.8/dist-packages/xonsh/built_ins.py", line 199, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/procs/specs.py", line 843, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured, envs=envs)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/procs/specs.py", line 813, in cmds_to_specs
    _update_last_spec(specs[-1])
  File "/usr/local/lib/python3.8/dist-packages/xonsh/procs/specs.py", line 768, in _update_last_spec
    r, w = xli.pty.openpty() if use_tty else os.pipe()
  File "/usr/lib/python3.8/pty.py", line 30, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python3.8/pty.py", line 60, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices

```

</details>

## Steps to Reproduce
If someone could help either confirm my suspicions are correct or point me towards a more appropriate source of the error, then I'm happy to submit a minimal reproducible example. As it stands, I can't paste in large sections of this script for sensitivity reasons, and I don't believe that would be helpful without confirming this is a bug and what it effects first.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
Hi!
We changed the default way we capture subprocs, and if I'm not mistaken
they shouldn't allocate a pty by default now.
Could you try running your script with the updated main branch from the
repo?

**Comment by stellarpower** [comment]
Thanks, sorry for the delay! Have tried building from source as I don't think it'll necessarily be reproducible using the docker container provided. I've installed to a scratch directory and alterred the shebangs in my scripts but still looks like it's trying to fallback below to the system version (which I can uninstall temporarily if it's easier) - but any quick way I can install locally and run? I don't want to chroot either as I'll be missing so binaries I need to call out from it:

```
Traceback (most recent call last):
  File "/mnt/ramdisk/install/usr/local/bin/xonsh", line 11, in <module>
    load_entry_point('xonsh==0.9.27', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.8/dist-packages/xonsh/main.py", line 423, in main
    _failback_to_other_shells(args, err)
....
....
OSError: out of pty devices

```

**Comment by daniel-shimon** [comment]
I would recommend creating a virtualenv and running `pip install REPO_DIR` when inside the virtualenv

**Comment by stellarpower** [comment]
Sorry, only had the time to try and reproduce this just now. It builds nicely using the virtualenv but now changes to the setup my script is operating around is preventing it from being reproducible, so I'll have to look at it again in more detail.
