### ISSUE TITLE
[on main] xonsh startup fails if $UPDATE_OS_ENVIRON=1 and $LS_COLORS is set on entry

### ISSUE THREAD

**Issue by egnor** [xonsh/xonsh#4383]
## xonfig

NOTE: This happens in the code I just pulled from main (92ac565e) but does NOT happen in the last release.

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | db99b646             |
| Commit Date      | Jul 17 23:15:15 2021 |
| Python           | 3.9.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.19               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.9.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | apt_tabcomplete      |
| xontrib 2        | direnv               |
| xontrib 3        | kitty                |
| xontrib 4        | prompt_ret_code      |
+------------------+----------------------+
```

</details>

## Expected Behavior
Xonsh should start up normally, importing `$LS_COLORS` if it is set, using defaults otherwise.

## Current Behavior
(Launching from `bash`, for illustration.)

```
egnor@ostrict:~$ xonsh --no-rc  # --no-rc just to simplify
... xonsh startup messages ...
egnor@ostrich ~ $   # clean launch!
```

No problem. But (again starting from bash):

```
egnor@ostrich:~$ export UPDATE_OS_ENVIRON=1
egnor@ostrich:~$ export LS_COLORS="bd=1;33"
egnor@ostrich:~$ xonsh
Traceback (most recent call last):
  File "/home/egnor/source/xonsh/xonsh/main.py", line 440, in main
    args = premain(argv)
  File "/home/egnor/source/xonsh/xonsh/main.py", line 380, in premain
    env = start_services(shell_kwargs, args, pre_env=pre_env)
  File "/home/egnor/source/xonsh/xonsh/main.py", line 288, in start_services
    execer = Execer(
  File "/home/egnor/source/xonsh/xonsh/execer.py", line 64, in __init__
    XSH.load(execer=self, ctx=xonsh_ctx)
  File "/home/egnor/source/xonsh/xonsh/built_ins.py", line 557, in load
    self.env = kwargs.pop("env") if "env" in kwargs else Env(default_env())
  File "/home/egnor/source/xonsh/xonsh/environ.py", line 1772, in __init__
    self[key] = val
  File "/home/egnor/source/xonsh/xonsh/environ.py", line 2006, in __setitem__
    deval = detyper(val)
  File "/home/egnor/source/xonsh/xonsh/tools.py", line 1171, in detype
    return x.detype()
  File "/home/egnor/source/xonsh/xonsh/environ.py", line 404, in detype
    style = self.style
  File "/home/egnor/source/xonsh/xonsh/environ.py", line 436, in style
    style_name = self.style_name
  File "/home/egnor/source/xonsh/xonsh/environ.py", line 427, in style_name
    env_style_name = env.get("XONSH_COLOR_STYLE", "default")
AttributeError: 'NoneType' object has no attribute 'get'
Xonsh encountered an issue during launch
Failback to /bin/zsh
%                                                                              

```

This appears to happen because, if `$UPDATE_OS_ENVIRON=1` at startup, the initial load from `os.environ` also re-updates `os.environ` (a little silly, but whatev?), and that calls detypers, and the detyper for `$LS_COLORS` tries to access the style name, which tries to get it from the environment, but the environment hasn't been initialized yet.

Note that `$UPDATE_OS_ENVIRON=1` is the default, so, this bug will affect any xonsh subshell, if `$LS_COLORS` has been set.

I can think of these fixes?
- Remove/deprecate `$UPDATE_OS_ENVIRON`? I'm not even sure what it's for to be honest, and it seems like it just adds another axis of variable behavior? Maybe just pick something and that way it gets tested.
- When extracting the initial environment from `os.environ`, avoid/override each set re-exporting back to `os.environ`?
- Make individual detypers more robust to missing XSH.env?

## Steps to Reproduce
1. Set $UPDATE_OS_ENVIRON=1
2. Set $LS_COLORS to some value (e.g. "bd=1;33")
3. Launch xonsh

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for opening this @egnor !  I had hit this once or twice but hadn't had time to track down the combination of settings that was triggering it.  I appreciate the thoughtful writeup!

The original intent of `UPDATE_OS_ENVIRON` is a bit of an edge-case, some related issues and PRs:
#661
#775

One current painpoint I still have with `$UPDATE_OS_ENVIRON=False` is on OSX (or at least that's where I've run into it) if I set my `$EDITOR` in my `xonshrc`, this doesn't get propagated to the `os.environ` and so trying to open up an interactive command editor with ctrl-x ctrl-e drops me into `nano` instead of `vim`.

> the initial load from `os.environ` also re-updates `os.environ`

yeah, this we can probably tweak to not cause the problem you're hitting above -- we DO want to load from `os.environ` and then update it but we can probably defer that initial update until we change another environment variable.

**Comment by daniel-shimon** [comment]
Yeah I agree `UPDATE_OS_ENVIRON` is useful sometimes and shouldn't be removed. 

Probably the right resolution would be to change this behavior:

> the initial load from os.environ also re-updates os.environ

**Comment by egnor** [comment]
Naively, I would have proposed that `os.environ` should _always_ be updated!
