### ISSUE TITLE
bash-completer bad-file descriptor

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#4414]
![image](https://user-images.githubusercontent.com/6702219/129148085-6c2319b1-3dcd-4eda-9483-4c2d5c6283cd.png)

## xonfig

<details>

```
$ xonfig
```

</details>

### Traceback (if applicable)

<details>

```
disown xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1999, in _communicate
    data = os.read(key.fd, 32768)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/shell/xsh/xonsh/completer.py", line 135, in generate_completions
    out = func(completion_context)
  File "/src/shell/xsh/xonsh/completers/tools.py", line 156, in _completer
    return func(context.command)
  File "/src/shell/xsh/xonsh/completers/bash.py", line 36, in complete_from_bash
    comps, lprefix = bash_completions(
  File "/src/shell/xsh/xonsh/completers/bash_completion.py", line 387, in bash_completions
    out = subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
  File "/usr/lib/python3.9/subprocess.py", line 1019, in __exit__
    self.stdout.close()
OSError: [Errno 9] Bad file descriptor
```

</details>

## Steps to Reproduce

This happens occasionally when trying to complete a command with tab keypress. 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
I no longer get this. Perhaps the change of OS.
