### ISSUE TITLE
App Execution Aliases no longer return False for `os.path.exists()` in latest python versions (3.8.10 and 3.9.6)

### ISSUE THREAD

**Issue by cmidkiff87** [xonsh/xonsh#4426]
`os.path.exists(fname)` no longer returns `False` when targeting an App Execution Alias, which means [this fix](https://github.com/xonsh/xonsh/blob/0.10.1/xonsh/procs/specs.py#L42) for issue #3752 is no longer effective.

Seems to be related to [this issue](https://bugs.python.org/issue38453) ([python 3.9.5 changelog](https://docs.python.org/release/3.9.6/whatsnew/changelog.html#id7))
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.10.1               |
| Git SHA          | e9b12c8b             |
| Commit Date      | Jul 24 22:47:37 2021 |
| Python           | 3.9.6                |
| PLY              | 3.11                 |
| have readline    | False                |
| prompt toolkit   | 3.0.19               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.10.0               |
| on posix         | False                |
| on linux         | False                |
| on darwin        | False                |
| on windows       | True                 |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | autovox              |
| xontrib 2        | free_cwd             |
| xontrib 3        | vox                  |
| xontrib 4        | voxapi               |
+------------------+----------------------+
```
</details>

## Expected Behavior
Running the command `wt` opens a new Windows Terminal

## Current Behavior
Running the command `wt` fails.

### Traceback
<details>
```
<xonsh-code>:1:0 - wt
<xonsh-code>:1:0 + ![wt]
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\__amalgam__.py", line 16418, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\__amalgam__.py", line 3190, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\built_ins.py", line 202, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\procs\__amalgam__.py", line 3510, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured, envs=envs)
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\procs\__amalgam__.py", line 3463, in cmds_to_specs
    spec = SubprocSpec.build(cmd, captured=captured, env=env)
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\procs\__amalgam__.py", line 3213, in build
    spec.resolve_executable_commands()
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\procs\__amalgam__.py", line 3300, in resolve_executable_commands
    scriptcmd = get_script_subproc_command(self.binary_loc, self.cmd[1:])
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\procs\__amalgam__.py", line 2740, in get_script_subproc_command
    elif _is_binary(fname):
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\procs\__amalgam__.py", line 2702, in _is_binary
    raise e
  File "C:\Users\Cass\AppData\Roaming\Python\Python39\site-packages\xonsh\procs\__amalgam__.py", line 2690, in _is_binary
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Cass\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe'
```
</details>

## Steps to Reproduce
Update python to 3.9.6 or 3.8.10 and try to run a Windows App in xonsh via an app execution alias

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by cmidkiff87** [comment]
It looks like python [has support for detecting AEA's](https://docs.python.org/3/library/stat.html#stat.IO_REPARSE_TAG_APPEXECLINK) since 3.8
