### ISSUE TITLE
Error on Autocomplete using @()

### ISSUE THREAD

**Issue by ErickTucto** [xonsh/xonsh#4455]
Error trying to use autocomplete with undefined variables on @()

![imagen](https://user-images.githubusercontent.com/22831024/131755616-2eb3186e-a4c7-4212-a599-a9b77b833d92.png)

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.10.1               |
| Git SHA          | e9b12c8b             |
| Commit Date      | Jul 24 22:47:37 2021 |
| Python           | 3.8.10               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.20               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.10.0               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | add_variable         |
| xontrib 2        | base16_shell         |
+------------------+----------------------+
```

</details>

## Expected
Do not launch autocomplete and neither do the autocomplete menu because the variable does not exist

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/xonsh/__amalgam__.py", line 9290, in generate_completions
    out = func(completion_context)
  File "/usr/local/lib/python3.8/dist-packages/xonsh/completers/__amalgam__.py", line 1426, in complete_path
    prefix = line.rsplit(" ", 1)[1]
IndexError: list index out of range
Completer complete_path raises exception when gets old_args=('@(noexi', '@(noexi', 0, 7) / completion_context=CompletionContext(command=None, python=PythonContext('noexi', 5, is_sub_expression=True)):
list index out of range
```

</details>

## Steps to Reproduce
1. Launch new terminal
2. Type `@(` followed by the name of an undefined variable
3. Press Tab

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
Thanks for reporting this!
