### ISSUE TITLE
Crash with FileNotFoundError when current working directory is deleted

### ISSUE THREAD

**Issue by blahgeek** [xonsh/xonsh#4467]
## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.10.1               |
| Git SHA          | e9b12c8b             |
| Commit Date      | Jul 24 22:47:37 2021 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.20               |
| shell type       | prompt_toolkit       |
| history backend  | sqlite               |
| pygments         | 2.10.0               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | abbrevs              |
| xontrib 2        | autojump             |
| xontrib 3        | prompt_ret_code      |
+------------------+----------------------+

```

</details>

## Expected Behavior

Should not crash.

## Current Behavior

Xonsh crashed when current working directory is deleted

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/home/yikai/.local/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 21338, in main
    sys.exit(main_xonsh(args))
  File "/home/yikai/.local/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 21376, in main_xonsh
    shell.shell.cmdloop()
  File "/home/yikai/.local/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 390, in cmdloop
    line = self.precmd(line)
  File "/home/yikai/.local/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 16393, in precmd
    self.precwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Xonsh encountered an issue during launch
Failback to /home/yikai/.nix-profile/bin/fish
...
```

</details>

## Steps to Reproduce

```
mkdir /tmp/some_folder
cd /tmp/some_folder
rmdir /tmp/some_folder
cd
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Good catch! PR is very welcome!

Here should be the fix:

https://github.com/xonsh/xonsh/blob/e25ab34e328c09b3098b598346ddda06ab7b40b5/xonsh/base_shell.py#L358-L361

**Comment by spencer-burke** [comment]
I will attempt to patch this when Hacktoberfest starts.

**Comment by lypanov** [comment]
I'm not sure this should silently eat the broken cd. I'd prefer the script in question to exit entirely. "cd directory-doesn't-exist; rm -rf ." is going to end very badly in the current version of the PR.

**Comment by iam-shanmukha** [comment]
Hi @lypanov. From my understanding, after removing current directory Xonsh is crashing and exit. So with my commit, it is not crashing and be in xonsh environment. Am I missing anything here? Sorry, if I didn't get you!
