### ISSUE TITLE
Error executing non-administrator rights in Windows

### ISSUE THREAD

**Issue by concertypin** [xonsh/xonsh#4491]
## xonfig

<details>

```
rophini@DESKTOP-H4PRMDP ~ # xonfig
+------------------+----------------------+
| xonsh            | 0.10.1               |
| Git SHA          | e9b12c8b             |
| Commit Date      | Jul 24 22:47:37 2021 |
| Python           | 3.9.6                |
| PLY              | 3.11                 |
| have readline    | False                |
| prompt toolkit   | 3.0.20               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.10.0               |
| on posix         | False                |
| on linux         | False                |
| on darwin        | False                |
| on windows       | True                 |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | True                 |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+
```

</details>

## Expected Behavior

When I executed `python -m xonsh` command, I expected it to work normally.
## Current Behavior
When I run xonsh with a normal account other than administrator rights in Windows 11(21H2), it stops with an error.
### Traceback (if applicable)

<details>

![image](https://user-images.githubusercontent.com/55056558/135193896-f5a2645f-af1f-466f-aaf1-94407980f526.png)
```

After approval from dircolors.exe UAC

Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\lib\site-packages\xonsh\__main__.py", line 3, in <module>
    main()
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 21340, in main
    _failback_to_other_shells(args, err)
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 21309, in _failback_to_other_shells
    raise err
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 21338, in main
    sys.exit(main_xonsh(args))
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 21373, in main_xonsh
    print_welcome_screen()
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 16051, in print_welcome_screen
    print_color(line)
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 6569, in print_color
    xsh.shell.shell.print_color(string, **kwargs)
  File "C:\Python39\lib\site-packages\xonsh\ptk_shell\shell.py", line 511, in print_color
    tokens = partial_color_tokenize(string)
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 14544, in partial_color_tokenize
    styles = XSH.shell.shell.styler.styles
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 16368, in styler
    self._styler = XonshStyle(env.get("XONSH_COLOR_STYLE"))
  File "C:\Python39\lib\site-packages\xonsh\pyghooks.py", line 377, in __init__
    self.style_name = style_name
  File "C:\Python39\lib\site-packages\xonsh\pyghooks.py", line 418, in style_name
    for file_type, xonsh_color in XSH.env.get("LS_COLORS", {}).items():
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 18610, in get
    return self[key]
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 18559, in __getitem__
    val = self._d[key] = val(self)
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 17203, in default_lscolors
    lsc = LsColors.fromdircolors()
  File "C:\Python39\lib\site-packages\xonsh\__amalgam__.py", line 17068, in fromdircolors
    s = out.splitlines()[0]
IndexError: list index out of range
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by concertypin** [comment]
Sorry. I forgot that I should close this issue.
