### ISSUE TITLE
Starting fzf inside a completion function crashes Xonsh

### ISSUE THREAD

**Issue by ajeetdsouza** [xonsh/xonsh#4536]
## xonfig

<details>

```python
# xonshrc

from xonsh.completers.tools import *

@contextual_completer
def foo_complete(context):
    fzf > /dev/null
    return {"/tmp/foo"}

completer add foo foo_complete
```

</details>

## How to reproduce

After setting the above xonshrc, type `foo <TAB>`. When `fzf` opens, hit `<ESC>` to exit from it. The `/tmp/foo` completion should have been returned successfully. Now, press backspace or the arrow keys. It doesn't actually backspace, instead it enters an ANSI escape sequence. Press Ctrl-C and Xonsh itself crashes.

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.10.1_1/libexec/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 21338, in main
    sys.exit(main_xonsh(args))
  File "/usr/local/Cellar/xonsh/0.10.1_1/libexec/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 21376, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/local/Cellar/xonsh/0.10.1_1/libexec/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 385, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/local/Cellar/xonsh/0.10.1_1/libexec/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 354, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/usr/local/Cellar/xonsh/0.10.1_1/libexec/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "/usr/local/Cellar/xonsh/0.10.1_1/libexec/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/xonsh/0.10.1_1/libexec/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 651, in run_async
    assert not self._is_running, "Application is already running."
AssertionError: Application is already running.
Xonsh encountered an issue during launch
Failback to /bin/zsh
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
completer functions are run in a thread and it is not advisable to start interactive commands inside them. If you want to use fzf for completions, you need to do some digging, start it separately and fill the buffer after selection. Please check the xontrib-fzf widgets for inspiration.
