### ISSUE TITLE
v0.11.0 broke launching xonsh scripts from shell

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#4555]
I can't execute xonsh scripts anymore as I get an `OSError: [WinError 193] %1 is not a valid Win32 application` since version 0.11.0 due to this [PR](https://github.com/xonsh/xonsh/pull/4077)

If I change the [code here](https://github.com/auneri/xonsh/blob/03f1f43a0ecac01f2047e260b2a40a40a6e075ea/xonsh/procs/specs.py#L467) like so, I get the old behavior back

```py
#cmd = [self.binary_loc] + self.cmd[1:]
cmd = self.cmd
```

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.11.0               |
| Git SHA          | 337cf25a             |
| Commit Date      | Nov 17 15:37:41 2021 |
| Python           | 3.9.7                |
| PLY              | 3.11                 |
| have readline    | False                |
| prompt toolkit   | 3.0.22               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.10.0               |
| on posix         | False                |
| on linux         | False                |
| on darwin        | False                |
| on windows       | True                 |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
| RC file          | []                   |
+------------------+----------------------+
```

</details>

## Expected Behavior

Executing a xonsh script from the command line should work

## Current Behavior

Instead, I get an `OSError: [WinError 193] %1 is not a valid Win32 application`

This is likely due to the fact that I don't have `.xsh` as a registered file association, and I don't want to register it, I want to be able to double-click to open a file instead of execute it.
So the new changes that check `[self.binary_loc]` fails and prevents from launching xonsh scripts from the command line

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/path/to/xonsh\lib\site-packages\xonsh\procs\pipelines.py", line 160, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/path/to/xonsh\lib\site-packages\xonsh\procs\specs.py", line 460, in run
    p = self._run_binary(kwargs)
  File "/path/to/xonsh\lib\site-packages\xonsh\procs\specs.py", line 479, in _run_binary
    p = self.cls(cmd, bufsize=bufsize, **kwargs)
  File "/path/to/Python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/path/to/Python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

</details>

## Steps to Reproduce

1. Create a `test.xsh`
```py
#!/usr/bin/env xonsh.exe
print("test")
```

  (for some reason, missing `exe` fails with `ModuleNotFoundError: No module named 'xonsh'`, but I thought the new PR fixing https://github.com/xonsh/xonsh/issues/3763 would fix it)

2. Launch xonsh

3. Add path to `xonsh.exe` to `environ['PATH']` (`$PATH` doesn't seem to work either)

4. cd to where `test.xsh` is and run `./test.xsh` 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting @eugenesvk -- and sorry about the breakages.

cc @melund and @daniel-shimon to see if they have any insight on a reasonable fix.

**Comment by eugenesvk** [comment]
> sorry about the breakages

Thanks, on the bright side, as a result of troubleshooting this I've got a great ergonomic win on Windows — I can now launch scripts without an extension and with a cross-platform shebang (see the other issue linked above)! Hopefully the cc'ed devs can get there in a more correct manner
