### ISSUE TITLE
Infinite loop error for aliases calling itself (Windows)

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#4566]
This great [PR](https://github.com/xonsh/xonsh/pull/4218) doesn't seem to work on Windows, I do get the infinite loop error

## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.11.0          |
| Python           | 3.10.0          |
| PLY              | 3.11            |
| have readline    | False           |
| prompt toolkit   | 3.0.22          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.10.0          |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior

Alias should be able to call itself without entering an infinite loop

## Current Behavior

I get an `Recursive calls to "echo" alias.` exception

### Traceback (if applicable)

<details>

```
aliases['echo'] = "echo @('ok')"; echo
Traceback (most recent call last):
  File "/path/to/venv/xonsh/lib\site-packages\xonsh\procs\proxies.py", line 523, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/path/to/venv/xonsh/lib\site-packages\xonsh\aliases.py", line 217, in __call__
    execer.exec(
  File "/path/to/venv/xonsh/lib\site-packages\xonsh\execer.py", line 200, in exec
    return exec(code, glbs, locs)
  File "<exec-alias:echo>", line 1, in <module>
  File "/path/to/venv/xonsh/lib\site-packages\xonsh\built_ins.py", line 203, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/path/to/venv/xonsh/lib\site-packages\xonsh\procs\specs.py", line 899, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured, envs=envs)
  File "/path/to/venv/xonsh/lib\site-packages\xonsh\procs\specs.py", line 836, in cmds_to_specs
    spec = SubprocSpec.build(cmd, captured=captured, env=env)
  File "/path/to/venv/xonsh/lib\site-packages\xonsh\procs\specs.py", line 584, in build
    spec.resolve_binary_loc()
  File "/path/to/venv/xonsh/lib\site-packages\xonsh\procs\specs.py", line 637, in resolve_binary_loc
    raise Exception(f'Recursive calls to "{cmd0}" alias.')
Exception: Recursive calls to "echo" alias.
```

</details>

## Steps to Reproduce

Run `aliases['echo'] = "echo @('ok')"; echo` from this [PR](https://github.com/xonsh/xonsh/pull/4218)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Yeah, the logic on Windows should be reviewed distinctly and #4218 works only for Linux.
Personally I recommend to use WSL2 on Windows.

**Comment by tahir-hassan** [comment]
> Yeah, the logic on Windows should be reviewed distinctly and #4218 works only for Linux. Personally I recommend to use WSL on Windows.

@anki-code Unfortunately a lot of developers working on Windows don't have admin rights on their machine and therefore cannot install WSL themselves.  Though I can imagine that running Linux stuff through WSL is the best approach for most scenarios, I have installed miniconda3 and within it, xonsh, via Scoop, because it doesn't require admin access.

**Comment by Qyriad** [comment]
For the record, I find xonsh's relatively strong Windows support to be *extremely* helpful and one of the biggest pluses of using xonsh. As part of what I do for work I end up doing a lot of dev on all three of Linux, macOS, and Windows, including repeated fresh installs of Windows, and xonsh's low-setup (just need Python) nearly seamless native Windows support is a *huge* boon and makes the whole thing so much less painful.

I know supporting Windows is a non-trivial development effort, so I hope it's known that it is very much appreciated. Even when there are bugs it still makes for a far nicer experience than without it.

**Comment by anki-code** [comment]
I'm going to close this as user error because:
```xsh
aliases['echo']
# ['C:\\WINDOWS\\System32\\cmd.exe', '/c', 'echo']  # echo already is an alias

aliases['echo'] = "echo ok"  # is wrong because it overwrites cmd implementation 🔴 
echo
# Exception: Recursive calls to "echo" alias.  # That's right 🟢 

```
In the right case of usage it's working:
```xsh
xpip install cmdix
which ls
# C:\Users\pc\...\Scripts\ls.exe
aliases['ls'] = 'ls -l'
ls
# -rw-rw-rw- 1 0     0     10 2026-03-26 21:10 anyfile  # As expected 🟢 
```
