### ISSUE TITLE
Wrong SyntaxError for `{'A':5,6}`

### ISSUE THREAD

**Issue by yaxollum** [xonsh/xonsh#4625]
When I try to evaluate `{'A': 5,6}`:

In Xonsh:
```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/yaxollum/dev/xonsh/xonsh/ptk_shell/shell.py", line 385, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/home/yaxollum/dev/xonsh/xonsh/execer.py", line 134, in compile
    code = compile(tree, filename, mode)
ValueError: Dict doesn't have the same number of keys as values
```

In Python:
```
  File "<stdin>", line 1
    {'A': 5,6}
             ^
SyntaxError: invalid syntax
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Techcable** [comment]
Just to clarify, you're complaining specifically about the quality of the error messages here?

**Comment by yaxollum** [comment]
@Techcable yeah, here it looks like the Xonsh parser thinks the code is valid syntax and parses it into an AST, and then the Python compiler raises a ValueError

**Comment by ghost** [comment]
Is this issue still open?

**Comment by Techcable** [comment]
Yes. On the latest commit  78f91952


<img width="772" alt="image" src="https://user-images.githubusercontent.com/4615889/158039923-2aa527fb-65c5-4847-98b9-c34682db2c1b.png">


<details>
   <summary>xonfig for 78f91952 </summary>

```
+------------------+--------------------------+
| xonsh            | 0.11.0                   |
| Git SHA          | 78f91952                 |
| Commit Date      | Mar 6 13:23:34 2022      |
| Python           | 3.9.10                   |
| PLY              | 3.11                     |
| have readline    | True                     |
| prompt toolkit   | 3.0.27                   |
| shell type       | prompt_toolkit           |
| history backend  | sqlite                   |
| pygments         | 2.11.2                   |
| on posix         | True                     |
| on linux         | False                    |
| on darwin        | True                     |
| on windows       | False                    |
| on cygwin        | False                    |
| on msys2         | False                    |
| is superuser     | False                    |
| default encoding | utf-8                    |
| xonsh encoding   | utf-8                    |
| encoding errors  | surrogateescape          |
| on jupyter       | False                    |
| jupyter kernel   | None                     |
| xontrib 1        | back2dir                 |
| xontrib 2        | fish_completer           |
| xontrib 3        | jedi                     |
| xontrib 4        | term_integration         |
| RC file 1        | /Users/nicholas/.xonshrc |
+------------------+--------------------------+
```
</details>
