### ISSUE TITLE
Pattern matching not working with .xsh scripts.

### ISSUE THREAD

**Issue by Keyboard-Crasher** [xonsh/xonsh#4660]
The new (in Python 3.10) pattern matching feature does not work with `.xsh` scripts for me. I have tried this with some different scripts and have provided a minimal examples below.

## xonfig

```
$ xonfig
xonsh : 0.11.0
Python : 3.10.2
...
```
The contents of `pybox.py`:
```
import sys
print(sys.version)

match ['item']:
    case ['item']:
        print('item')
```
and `xonshbox.xsh`:
```
# xonshbox.xsh
import sys
print(sys.version)

match ['item']:
    case ['item']:
        print('item')
```
## Expected Behavior
```
$ python /path/to/pybox.py
3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
item
$ xonsh -c /path/to/xonshbox.xsh
3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
item
```

## Current Behavior
Currently only the direct Python command works and the Xonsh alternative throws a TypeError. If I comment out the match block, leaving only the imports and version checks, I receive the "right answer", namely:

```
$ xonsh -c /path/to/xonshbox.xsh
3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
```

### Traceback (if applicable)

```
$ xonsh -c /path/to/xonshbox.xsh
Traceback (most recent call last):
  File "/home/user/.virtualenvs/main/bin/xonsh", line 8, in <module>
    sys.exit(main())
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 21799, in main
    _failback_to_other_shells(args, err)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 21746, in _failback_to_other_shells
    raise err
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 21797, in main
    sys.exit(main_xonsh(args))
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 21853, in main_xonsh
    run_script_with_cache(
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 3660, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 3619, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14382, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14340, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14489, in _parse_ctx_free
    raise original_error from None
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14470, in _parse_ctx_free
    tree = self.parser.parse(
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/parsers/base.py", line 523, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/parsers/base.py", line 3459, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/parsers/base.py", line 650, in _parse_error
    raise_parse_error(msg, loc, self.xonsh_code, self.lines)
  File "/home/user/.virtualenvs/main/lib/python3.10/site-packages/xonsh/parsers/base.py", line 238, in raise_parse_error
    raise err
SyntaxError: /home/user/bin/xonshbox.xsh:4:15: ('code: \n',)
match ['item']:
```

**Comment by anki-code** [comment]
Yep, the new syntax should be ported to xonsh. PR is welcome!

**Comment by dev2718** [comment]
I plan on implementing this soon.

**Comment by gforsyth** [comment]
Hey @Keyboard-Crasher -- just to clarify what's going on here -- `xonsh` re-implements parsing (with our own additions on top) for each Python minor version.  The practical effect of this is that we tend to lag feature completeness for new grammar.  `xonsh` can _run_ on top of 3.10 right now, but it doesn't (yet) have full feature parity with 3.10

**Comment by jnoortheen** [comment]
The xonsh parser is essentially Py3.8 . There is one failing test on py3.9 (with pytest's expect failure ). 

Is it possibe to just parse the xonsh specific part alone and replace with equivalent Python code and feed it to ast ? so that the parser will be light (now most of the memory usage comes from the parser instance ) and faster maybe 

So something like 

```xsh
var = 1

echo @(var)
```

will become

```py
var = 1

run_subproc([var])
```

**Comment by Keyboard-Crasher** [comment]
Got it. Special thanks to @gforsyth for helping me get into the loop here.

**Comment by dev2718** [comment]
@Keyboard-Crasher support for the match statement was merged into main today.
