### ISSUE TITLE
XONSH_HISTORY_FILE is set to None at login, whenever xonsh is the login shell

### ISSUE THREAD

**Issue by Nimenii** [xonsh/xonsh#4674]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------------------------+
| xonsh            | 0.11.0                            |
| Python           | 3.10.2                            |
| PLY              | 3.11                              |
| have readline    | True                              |
| prompt toolkit   | 3.0.28                            |
| shell type       | readline                          |
| history backend  | json                              |
| pygments         | 2.11.2                            |
| on posix         | True                              |
| on linux         | True                              |
| distro           | arch                              |
| on wsl           | False                             |
| on darwin        | False                             |
| on windows       | False                             |
| on cygwin        | False                             |
| on msys2         | False                             |
| is superuser     | False                             |
| default encoding | utf-8                             |
| xonsh encoding   | utf-8                             |
| encoding errors  | surrogateescape                   |
| on jupyter       | True                              |
| jupyter kernel   | None                              |
| xontrib          | []                                |
| RC file 1        | /home/nimeni/.config/xonsh/rc.xsh |
+------------------+-----------------------------------+
```

</details>

## Expected Behavior

When opening a xonsh prompt, XONSH_HISTORY_FILE should be ~/.local/share/xonsh/history_json/xonsh-<some_id>.json

## Current Behavior

Upon login, XONSH_HISTORY_FILE is set to None. When I open terminal to begin xonsh, a file at ~/None is created. If zsh is the login shell then this behaviour does not occur. My current solution is to add the following line to xonshrc

```
del $XONSH_HISTORY_FILE
```

### Traceback (if applicable)

(Unsure if this is helpful.) By performing the following:
1. In xonsh, run zsh
2. In zsh, run xonsh
3. Delete the history file at ~/None
4. $ exit
This traceback is given

```
Exception ignored in atexit callback: <function _lastflush at 0x7f37be086d40>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/built_ins.py", line 506, in _lastflush
    XSH.history.flush(at_exit=True)
  File "/usr/lib/python3.10/site-packages/xonsh/history/__amalgam__.py", line 765, in flush
    hf = JsonHistoryFlusher(
  File "/usr/lib/python3.10/site-packages/xonsh/history/__amalgam__.py", line 514, in __init__
    self.dump()
  File "/usr/lib/python3.10/site-packages/xonsh/history/__amalgam__.py", line 548, in dump
    with open(self.filename, "r", newline="\n") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'None'
```

</details>

## Steps to Reproduce

1. Install xonsh
2. $ chsh -s /usr/bin/xonsh
3. Reboot

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Hey @Nimenii -- I believe this has been fixed on `main` -- can you try that out?  We will cut a new release soon with the fix, too.

**Comment by Nimenii** [comment]
Hi @gforsyth you are correct! The issue is fixed on `main`. Thank you for your reply

**Comment by gforsyth** [comment]
Great!
