### ISSUE TITLE
Failed to load xontrib jedi.

### ISSUE THREAD

**Issue by justin-f-perez** [xonsh/xonsh#4725]
## xonfig

<details>

```
$ xonfig
+------------------+-------------------------+
| xonsh            | 0.11.0                  |
| Git SHA          | 337cf25a                |
| Commit Date      | Nov 17 15:37:41 2021    |
| Python           | 3.10.2                  |
| PLY              | 3.11                    |
| have readline    | True                    |
| prompt toolkit   | 3.0.22                  |
| shell type       | prompt_toolkit          |
| history backend  | json                    |
| pygments         | 2.10.0                  |
| on posix         | True                    |
| on linux         | False                   |
| on darwin        | True                    |
| on windows       | False                   |
| on cygwin        | False                   |
| on msys2         | False                   |
| is superuser     | False                   |
| default encoding | utf-8                   |
| xonsh encoding   | utf-8                   |
| encoding errors  | surrogateescape         |
| on jupyter       | False                   |
| jupyter kernel   | None                    |
| xontrib 1        | argcomplete             |
| xontrib 2        | fzf-widgets             |
| xontrib 3        | prompt_vi_mode          |
| xontrib 4        | z                       |
| RC file 1        | /Users/jfperez/.xonshrc |
+------------------+-------------------------+
```

</details>

## Expected Behavior

> Use Jedi as xonsh’s python completer.
> 
> This xontrib is preinstalled with xonsh.
> 
> Usage:
>
> Run the following command to enable (or add it to your [.xonshrc](https://xon.sh/xonshrc.html) file to enable on startup.)
>
> `xontrib load jedi`

Expect behavior to be as described in docs

## Current Behavior

jedi is not installed? Module not found

### Traceback (if applicable)

<details>

```
$ xontrib load jedi
<xonsh-code>:1:8 - xontrib load jedi
<xonsh-code>:1:8 + ![xontrib load jedi]
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 12116, in xontribs_load
    update_context(name, ctx=ctx)
  File "/opt/homebrew/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 12072, in update_context
    modctx = xontrib_context(name)
  File "/opt/homebrew/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 12037, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xontrib/jedi.py", line 19, in <module>
    import jedi
ModuleNotFoundError: No module named 'jedi'
Failed to load xontrib jedi.
```

</details>

## Steps to Reproduce

NOTE: I enabled a few other xontribs but this error has occurred since first installation via homebrew today.
```
brew install xonsh
xonsh
xontrib load jedi
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by justin-f-perez** [comment]
I find this comment at `/opt/homebrew/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-pac
kages/xontrib/jedi.py` confusing as it seems to contradict [the documentation](https://xon.sh/xontribs.html#jedi):

```python
17  # an error will be printed in xontribs
18  # if jedi isn't installed
19  import jedi
```

**Comment by justin-f-perez** [comment]
btw I am brand new to xonsh so I'm not sure what I'm doing but I'll post anything else that seems like it could be relevant as I discover it

```shell
$ xontrib list
abbrevs             installed      not-loaded
argcomplete         installed      loaded
autovox             installed      not-loaded
bashisms            installed      not-loaded
coreutils           installed      not-loaded
distributed         installed      not-loaded
free_cwd            installed      not-loaded
fzf-widgets         installed      loaded
jedi                installed      not-loaded
mpl                 installed      not-loaded
mplhooks            installed      not-loaded
pdb                 installed      not-loaded
prompt_ret_code     installed      not-loaded
prompt_vi_mode      installed      loaded
vox                 installed      not-loaded
voxapi              installed      not-loaded
whole_word_jumping  installed      not-loaded
xog                 installed      not-loaded
z                   installed      loaded
```

**Comment by justin-f-perez** [comment]
I wonder if this is just a case of confusing wording? Is jedi-the-xontrib "pre-installed" while jedi-the-python-package not?

**Comment by jnoortheen** [comment]
Yes you are right. You have to install jedi separately with pip. The load jedi thing was the extension name.

**Comment by jnoortheen** [comment]
Please use the discussion page https://github.com/xonsh/xonsh/discussions for Q&A

**Comment by jnoortheen** [comment]
On second thought the extension should atleast give some direction on why it is not working. PRs welcome to print some info if import fails

**Comment by jnoortheen** [comment]
Closing this on behalf of #4726
