### ISSUE TITLE
Pytest fails to run on unrelated project due to inability to load xonsh plugin

### ISSUE THREAD

**Issue by Techcable** [xonsh/xonsh#4744]
## xonfig

<details>

```
+------------------+--------------------------+
| xonsh            | 0.11.0                   |
| Git SHA          | 78f91952                 |
| Commit Date      | Mar 6 13:23:34 2022      |
| Python           | 3.9.12                   |
| PLY              | 3.11                     |
| have readline    | True                     |
| prompt toolkit   | 3.0.27                   |
| shell type       | prompt_toolkit           |
| history backend  | sqlite                   |
| pygments         | 2.11.2                   |
| on posix         | True                     |
| on linux         | False                    |
| on darwin        | True                     |
| on windows       | False                    |
| on cygwin        | False                    |
| on msys2         | False                    |
| is superuser     | False                    |
| default encoding | utf-8                    |
| xonsh encoding   | utf-8                    |
| encoding errors  | surrogateescape          |
| xontrib 1        | back2dir                 |
| xontrib 2        | fish_completer           |
| xontrib 3        | term_integration         |
| RC file 1        | /Users/nicholas/.xonshrc |
+------------------+--------------------------+
```

</details>

## Expected Behavior
`pytest` should not crash
### Traceback (if applicable)

<details>
*NOTE*: This is a pytest traceback, not a xonsh traceback.

```
$ pytest heapsort.py
Traceback (most recent call last):
  File "/opt/homebrew/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/opt/homebrew/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/opt/homebrew/lib/python3.9/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/opt/homebrew/lib/python3.9/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/opt/homebrew/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/homebrew/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/homebrew/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/opt/homebrew/lib/python3.9/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/opt/homebrew/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/homebrew/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/homebrew/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "/opt/homebrew/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "/opt/homebrew/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1187, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/opt/homebrew/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'xonsh.pytest_plugin'
```

</details>

## Steps to Reproduce
Run pytest on [this `heapsort.py` file](https://gist.github.com/c411b3a550e252b1fd681e1fc1734174).

Be aware that I am using the development version of xonsh (0.11.0). It's currently the latest commit on `main`: b1fe9e49d4b0b51373fd8a5646b3a7dfe2c2aa46

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Techcable** [comment]
I just managed to fix this myself by reinstalling xonsh (running `pip install -e .` in my xonsh checkout).

If anyone else has this problem, try reinstalling.
