### ISSUE TITLE
Cannot turn off history

### ISSUE THREAD

**Issue by nagylzs** [xonsh/xonsh#4778]
There is a tutorial here: https://xon.sh/tutorial_hist.html but it seems to be wrong.

Some of the documented history commands work:

```
root@backup ~/bin # history id                                                                          
44cd56c5-f372-4597-9513-9eb4998182e9
root@backup ~/bin # history file                                                                        
/root/.local/share/xonsh/xonsh-44cd56c5-f372-4597-9513-9eb4998182e9.json
root@backup ~/bin # history info                                                                        
backend: json
sessionid: 44cd56c5-f372-4597-9513-9eb4998182e9
filename: /root/.local/share/xonsh/xonsh-44cd56c5-f372-4597-9513-9eb4998182e9.json
length: 5
buffersize: 100
bufferlength: 5
gc options: (8128, 'commands')
root@backup ~/bin #  
```

But some of them don't:

```
root@backup ~/bin # history off                                                                         
history: error: cannot convert 'off' to slice
root@backup ~/bin # history clear                                                                       
history: error: cannot convert 'clear' to slice
root@backup ~/bin # history flush                                                                       
history: error: cannot convert 'flush' to slice
root@backup ~/bin #  
```

Is this a bug?

**Comment by gforsyth** [comment]
Can you post the output of the `xonfig` command so we can see what version you're on?

**Comment by nagylzs** [comment]
It is the latest available official version on Ubuntu 20.04 LTS.

**Comment by nagylzs** [comment]
This might be unrelated, but... I left the terminal open for a while. When I came back I saw this on the screen:

```
root@backup ~ # history off
History off
root@backup ~ # Exception in thread Thread-5 (_in_load_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/history.py", line 188, in _in_load_thread
    for item in self.history.load_history_strings():
  File "/usr/lib/python3/dist-packages/xonsh/ptk_shell/history.py", line 29, in load_history_strings
    for cmd in hist.all_items(newest_first=True):
  File "/usr/lib/python3/dist-packages/xonsh/history/__amalgam__.py", line 812, in all_items
    yield from self.items()
  File "/usr/lib/python3/dist-packages/xonsh/history/__amalgam__.py", line 783, in items
    yield {"inp": item.rstrip(), "ts": tss[0]}
IndexError: string index out of range
```
It seems to be an exception in a background thread. Might not be related to the original problem, I'm not sure. This is very strange it threw an error by itself, while I was away.

**Comment by gforsyth** [comment]
We don't have control over when Ubuntu updates things and we can't backport `xonsh` to LTS ubuntu packages.  
Newer features inherently require upgrading `xonsh` to the newer version.

**Comment by nagylzs** [comment]
@gforsyth I understand that you don't have control over Ubuntu packages. But does it mean that "history off" command was never supported in xonsh 0.9 ? E.g. history could not be turned off?

**Comment by gforsyth** [comment]
correct

**Comment by gforsyth** [comment]
I'm going to close this out -- happy to continue the discussion but we aren't going to backport features.
