### ISSUE TITLE
source-bash: error: argument -l/--login: ignored explicit argument 'false'

### ISSUE THREAD

**Issue by arkhan** [xonsh/xonsh#4784]
## xonfig

<details>

```
+------------------+-----------------------------------+
| xonsh            | 0.12.2                            |
| Git SHA          | e0a0394b                          |
| Commit Date      | Apr 25 10:52:15 2022              |
| Python           | 3.9.9                             |
| PLY              | 3.11                              |
| have readline    | True                              |
| prompt toolkit   | 3.0.18                            |
| shell type       | prompt_toolkit                    |
| history backend  | sqlite                            |
| pygments         | 2.8.1                             |
| on posix         | True                              |
| on linux         | True                              |
| distro           | guix                              |
| on wsl           | False                             |
| on darwin        | False                             |
| on windows       | False                             |
| on cygwin        | False                             |
| on msys2         | False                             |
| is superuser     | False                             |
| default encoding | utf-8                             |
| xonsh encoding   | utf-8                             |
| encoding errors  | ignore                            |
| xontrib 1        | argcomplete                       |
| xontrib 2        | coreutils                         |
| xontrib 3        | direnv                            |
| xontrib 4        | fzf-widgets                       |
| xontrib 5        | pipeliner                         |
| xontrib 6        | pipeliner_parallel                |
| xontrib 7        | readable-traceback                |
| xontrib 8        | sh                                |
| xontrib 9        | z                                 |
| RC file 1        | /home/arkhan/.config/xonsh/rc.xsh |
+------------------+-----------------------------------+
```

</details>

### Traceback (if applicable)

<details>

```
usage: source-bash [-h] [-n] [-l] [--envcmd ENVCMD] [--aliascmd ALIASCMD]
                   [--extra-args EXTRA_ARGS] [-u] [-p PREVCMD] [--postcmd POSTCMD]
                   [--funcscmd FUNCSCMD] [--sourcer SOURCER] [--use-tmpfile]
                   [--seterrprevcmd SETERRPREVCMD] [--seterrpostcmd SETERRPOSTCMD]
                   [--overwrite-aliases] [--suppress-skip-message] [--show] [-d]
                   files_or_code [files_or_code ...]

source-bash: error: argument -l/--login: ignored explicit argument 'false'
Traceback (most recent call last):
  File "/gnu/store/klcqavc083236yl1j134d4xx9nd9cn79-xonsh-next-0.12.2/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 22324, in main
    args = premain(argv)
  File "/gnu/store/klcqavc083236yl1j134d4xx9nd9cn79-xonsh-next-0.12.2/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 22264, in premain
    env = start_services(shell_kwargs, args, pre_env=pre_env)
  File "/gnu/store/klcqavc083236yl1j134d4xx9nd9cn79-xonsh-next-0.12.2/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 22207, in start_services
    XSH.rc_files = xonshrc_context(
  File "/gnu/store/klcqavc083236yl1j134d4xx9nd9cn79-xonsh-next-0.12.2/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 19711, in xonshrc_context
    status = xonsh_script_run_control(
  File "/gnu/store/klcqavc083236yl1j134d4xx9nd9cn79-xonsh-next-0.12.2/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 19782, in xonsh_script_run_control
    print_exception(msg.format(filename, err), exc_info=exc_info)
TypeError: _print_exception() got an unexpected keyword argument 'exc_info'
Xonsh encountered an issue during launch
Failback to /gnu/store/klcqavc083236yl1j134d4xx9nd9cn79-xonsh-next-0.12.2/bin/xonsh
```

</details>

## Steps to Reproduce
1. install the latest version of xonsh (0.12.2)
2. install [xontrib-langenv](https://github.com/dyuri/xontrib-langenv)
3. git clone https://github.com/pyenv/pyenv.git ~/.pyenv
4. set  PYENV_ROOT envvar env["PYENV_ROOT"] = f"{env['HOME']}/.pyenv"
5. xontrib load pyenv

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Hey @arkhan -- did this work on previous versions of `xonsh`?  Or is it an issue with the xontrib?

cc @dyuri

**Comment by arkhan** [comment]
> Hey @arkhan -- did this work on previous versions of `xonsh`? Or is it an issue with the xontrib?
> 
> cc @dyuri

The error appears from version 0.12.0, with version 0.11.0 it works fine

**Comment by dyuri** [comment]
Hi, this should have been already solved: https://github.com/dyuri/xontrib-langenv/issues/7

**Comment by arkhan** [comment]
> Hi, this should have been already solved: [dyuri/xontrib-langenv#7](https://github.com/dyuri/xontrib-langenv/issues/7)

Hello, indeed the issue is solved, sorry for the false alarm.
