### ISSUE TITLE
'OSError: [Errno 9] Bad file descriptor' using coreutils

### ISSUE THREAD

**Issue by sbliven** [xonsh/xonsh#4792]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.12.1               |
| Git SHA          | cd334e44             |
| Commit Date      | Apr 15 13:10:59 2022 |
| Python           | 3.10.2               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.22               |
| shell type       | readline             |
| history backend  | json                 |
| pygments         | 2.10.0               |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| xontrib 1        | coreutils            |
| RC file          | []                   |
+------------------+----------------------+
```

</details>

## Expected Behavior

I am trying to create a complex alias with redirected stdin. As a test I created the following wrapper function for `grep`, since it's a command that accepts input either from stdin or a file:

```
def _mygrep(args, stdin=None, stdout=None, stderr=None):
    return subprocess.run(["/usr/bin/grep"]+args,  stdin=stdin, stdout=stdout, stderr=stderr).returncode
aliases['mygrep']=_mygrep
```

I expect this alias to work exactly like grep. For instance:
```
$ echo hovercraft|mygrep raft
hovercraft
```

## Current Behavior

With an empty rc file the above function works as expected. However, if I first load the coreutils xontrib I see an OSError about 50% of the time. The error prints directly to the console, so redirecting the output doesn't hide the error.

```
$ echo hovercraft|mygrep raft a>/dev/null
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 2328, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/usr/local/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 2117, in proxy_four
    return f(args, stdin, stdout, stderr)
  File "<stdin>", line 2, in _mygrep
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1804, in _execute_child
    os.close(errpipe_read)
OSError: [Errno 9] Bad file descriptor
```

Surprisingly, this behavior happens even for commands like grep that are not replaced by coreutils.

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

```
$ xonsh --no-rc
$ xontrib load coreutils
$ $XONSH_SHOW_TRACEBACK = True
$ import subprocess
$ def _mygrep(args, stdin=None, stdout=None, stderr=None):
    return subprocess.run(["/usr/bin/grep"]+args,  stdin=stdin, stdout=stdout, stderr=stderr).returncode
$ aliases['mygrep']=_mygrep
$ echo hovercraft|mygrep raft
hovercraft
$ echo hovercraft|mygrep raft
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
hovercraft
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 2328, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/usr/local/Cellar/xonsh/0.11.0/libexec/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 2117, in proxy_four
    return f(args, stdin, stdout, stderr)
  File "<stdin>", line 2, in _mygrep
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1804, in _execute_child
    os.close(errpipe_read)
OSError: [Errno 9] Bad file descriptor
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by sbliven** [comment]
@anki-code Is that related? I'm on MacOS, where #4224 doesn't seem to be an issue.
