### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'flush'

### ISSUE THREAD

**Issue by johny65** [xonsh/xonsh#4806]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.12.4               |
| Git SHA          | c3fc7edb             |
| Commit Date      | May 8 17:26:23 2022  |
| Python           | 3.10.4               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.29               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.12.0               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| xontrib          | []                   |
| RC file 1        | /home/johny/.xonshrc |
+------------------+----------------------+

```

</details>

## Expected Behavior

To exit xonsh correctly.

## Current Behavior

When I exit xonsh it throws an exception. This not happens every time, only in certain conditions.

### Traceback (if applicable)

<details>

```
Exception ignored in atexit callback: <function shutdown at 0x7fe84db6d900>
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 2182, in shutdown
    h.flush()
  File "/usr/lib/python3.10/logging/__init__.py", line 1084, in flush
    self.stream.flush()
  File "/home/johny/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 16263, in flush
    self.std.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

```

</details>

## Steps to Reproduce

I can reproduce this issue in this way:

- Start xonsh.
- `$ xonfig web`
- Press Ctrl+C to stop server.
- Press Ctrl+D to exit xonsh. The mentioned exception is thrown.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for the report @johny65 and sorry for the delay in responding!  I've put up a fix in #4812 and that should be part of the next release.
