### ISSUE TITLE
Unable to use multi-line input with backslash

### ISSUE THREAD

**Issue by Esfo** [xonsh/xonsh#4851]
## xonfig
+------------------+--------------------+
| xonsh            | 0.12.5             |
| Python           | 3.10.5             |
| PLY              | 3.11               |
| have readline    | True               |
| prompt toolkit   | 3.0.29             |
| shell type       | prompt_toolkit     |
| history backend  | json               |
| pygments         | 2.12.0             |
| on posix         | True               |
| on linux         | True               |
| distro           | arch               |
| on wsl           | False              |
| on darwin        | False              |
| on windows       | False              |
| on cygwin        | False              |
| on msys2         | False              |
| is superuser     | False              |
| default encoding | utf-8              |
| xonsh encoding   | utf-8              |
| encoding errors  | surrogateescape    |
| xontrib          | []                 |
| RC file 1        | /home/me/.xonshrc |
+------------------+--------------------+

When using multi-line input, if I remove the backslash after writing multiple lines, everything works fine. But I have to manually go back and do it, leaving it in throws errors.

Not sure if I have an incompatible version of something or what.

```
me@yup ~ [1] $ t = 4 \
............... j = 8
...............
<stdin>:1:6 - t = 4 j = 8
<stdin>:1:6 + ![t = 4 j = 8]
<stdin>:2:0 - t = 4 j = 8
<stdin>:2:0 + ![t = 4 j = 8]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 3125, in _run_binary
    p = self.cls(cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 1406, in __init__
    self.proc = proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 't'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 636, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 3107, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 3141, in _run_binary
    raise xt.XonshError(e)
xonsh.__amalgam__.XonshError: xonsh: subprocess mode: command not found: t
Did you mean one of the following?
    l:   Alias
    s:   Alias
    nt:  Alias
    tr:  Command (tr)
    [:   Command ([)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.10/site-packages/xonsh/built_ins.py", line 196, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 3575, in run_subproc
    command.end()
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 928, in end
    self._end(tee_output=tee_output)
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 947, in _end
    self._raise_subproc_error()
  File "/usr/lib/python3.10/site-packages/xonsh/procs/__amalgam__.py", line 1069, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['t', '=', '4', 'j', '=', '8']' returned non-zero exitstatus 1.

```

I tried alternating the bottom commands and I'm not sure if it's helpful, but a python print statement below would throw a different error as opposed to using echo, which reproduces the above

```
me@yup ~ $ t = 4 \
........... print('hi')
...........
<stdin>:1:6:17 - t = 4 print('hi')
<stdin>:1:6:17 + ![t = 4 print('hi'])
<stdin>:1:6 - t = 4 print('hi')
<stdin>:1:6 + ![t = 4 print('hi')]
<stdin>:1:6:17 - t = 4 print('hi')
<stdin>:1:6:17 + ![t = 4 print('hi'])
<stdin>:1:6 - t = 4 print('hi')
<stdin>:1:6 + ![t = 4 print('hi')]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14439, in _parse_ctx_free
    return _try_parse(input, greedy=False)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14349, in _try_parse
    raise original_error from None
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14330, in _try_parse
    tree = self.parser.parse(
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 507, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 3525, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 634, in _parse_error
    raise_parse_error(msg, loc, self._source, self.lines)
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 220, in raise_parse_error
    raise err
  File "<stdin>", line 1
    t = 4 print('hi')
         ^
SyntaxError: ('code: print',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14330, in _try_parse
    tree = self.parser.parse(
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 507, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 3525, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 634, in _parse_error
    raise_parse_error(msg, loc, self._source, self.lines)
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 220, in raise_parse_error
    raise err
  File "<stdin>", line 1
    ![t = 4 print('hi')]
                ^
SyntaxError: ('code: (',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 384, in _push
    code = self.execer.compile(
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14226, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14182, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14441, in _parse_ctx_free
    return _try_parse(input, greedy=True)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14360, in _try_parse
    _, sbpline = self._parse_ctx_free(
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14441, in _parse_ctx_free
    return _try_parse(input, greedy=True)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14426, in _try_parse
    raise original_error
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 14330, in _try_parse
    tree = self.parser.parse(
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 507, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 3525, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 634, in _parse_error
    raise_parse_error(msg, loc, self._source, self.lines)
  File "/usr/lib/python3.10/site-packages/xonsh/parsers/base.py", line 220, in raise_parse_error
    raise err
  File "<stdin>", line 1
    t = 4 print('hi')
         ^
SyntaxError: ('code: print',)
```

I couldn't force any different results by changing xonshrc variables, even removing the whole file still gives the issue but here it is:

```
$ALIAS_COMPLETIONS_OPTIONS_BY_DEFAULT = '1'
$AUTO_SUGGEST = '1'
$AUTO_SUGGEST_IN_COMPLETIONS = '0'
$BASH_COMPLETIONS = '/usr/share/bash-completion/completions'
$COMMANDS_CACHE_SAVE_INTERMEDIATE = '1'
$COMPLETIONS_DISPLAY = 'readline'
$COMPLETION_IN_THREAD = '1'
$COMPLETION_QUERY_LIMIT = '20'
$DYNAMIC_CWD_ELISION_CHAR = '...'
$EDITOR = 'vim'
$ENABLE_ASYNC_PROMPT = '1'
$FOREIGN_ALIASES_SUPPRESS_SKIP_MESSAGE = '1'
$MOUSE_SUPPORT = ''
$MULTILINE_PROMPT = '.'
$RAISE_SUBPROC_ERROR = '1'
$SUGGEST_COMMANDS = '1'
$SUGGEST_THRESHOLD = '3'
$THREAD_SUBPROCS = '1'
$UPDATE_COMPLETIONS_ON_KEYPRESS = '1'
$XONSH_APPEND_NEWLINE = '1'
$XONSH_CAPTURE_ALWAYS = '1'
$XONSH_COLOR_STYLE = 'one-dark'
$XONSH_CTRL_BKSP_DELETION = '1'
$XONSH_DEBUG = '1'
$XONSH_HISTORY_MATCH_ANYWHERE = '1'
$XONSH_INTERACTIVE = '1'
$XONSH_SHOW_TRACEBACK = '1'
$XONSH_STORE_STDOUT = '1'
$XONSH_SUBPROC_CAPTURED_PRINT_STDERR = '1'
$XONSH_TRACEBACK_LOGFILE = '/home/me/.xtraceback'
source-zsh "echo loading xonsh foreign shell"
```

**Comment by Esfo** [comment]
Actually, nevermind. I realized this doesn't work in pure python to begin with. I've been using other types of consoles that don't require the backslash and though it was normal functionality.

**Comment by gforsyth** [comment]
Thanks for raising this @Esfo -- we don't have a `shift + enter` keybinding but `Alt + Enter` will execute the current block regardless of cursor position.
