### ISSUE TITLE
Windows WSL2 Manjaro: Failed to load xontrib whole_word_jumping

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4856]
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.12.6               |
| Git SHA          | 5401a246             |
| Commit Date      | Jun 21 10:44:07 2022 |
| Python           | 3.10.5               |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.29               |
| shell type       | prompt_toolkit       |
| history backend  | json                 |
| pygments         | 2.11.2               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on wsl           | True                 |
| wsl version      | 2                    |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| xontrib          | []                   |
| RC file          | []                   |
+------------------+----------------------+
```

</details>

## Steps to Reproduce

I'm catching this on Manjaro in WSL2 on Windows 10:

```python
XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=1 xonsh --no-rc
xontrib load whole_word_jumping
```
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 11908, in xontribs_load
    update_context(name, ctx=ctx, full_module=full_module)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 11856, in update_context
    modctx = xontrib_context(name, full_module)
  File "/usr/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 11822, in xontrib_context
    module = importlib.import_module(spec.name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/xontrib/whole_word_jumping.py", line 20, in <module>
    import prompt_toolkit.input.win32 as ptk_win32
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/input/win32.py", line 10, in <module>
    assert sys.platform == "win32"
AssertionError
Failed to load xontrib whole_word_jumping.
```

Also:
```python
XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=1 xonsh --no-rc
import sys
sys.platform
# 'linux'
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by cunha** [comment]
it seems this has been fixed in https://github.com/xonsh/xonsh/pull/4853, but will have a look later today to test it loads on WSL and Linux and submit another PR if necessary. Sorry about the inconvenience.

**Comment by cunha** [comment]
Built `xonsh` from source including https://github.com/xonsh/xonsh/pull/4853 and tested without issues on Debian/WSL and Debian/Linux.
