### ISSUE TITLE
Emacs, dired can't `ls` a file.

### ISSUE THREAD

**Issue by veksha** [xonsh/xonsh#4892]
## xonfig

<details>

```console
$ xonfig
+------------------+---------------------+
| xonsh            | 0.13.0              |
| Python           | 3.10.5              |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.30              |
| shell type       | prompt_toolkit      |
| history backend  | json                |
| pygments         | 2.12.0              |
| on posix         | True                |
| on linux         | True                |
| distro           | void                |
| on wsl           | False               |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
| xontrib 1        | autojump            |
| RC file 1        | /home/yura/.xonshrc |
+------------------+---------------------+

```

</details>

## Expected Behavior

emacs dired must succesfully `ls` a file

## Current Behavior
`xonsh: subprocess mode: command not found: \\ls`

### Traceback (if applicable)

<details>

```console
  /home/yura:
  wildcard .zshrc
  <string>:1:0 - \\ls -d --dired -al -- .zshrc
  <string>:1:0 + ![\\ls -d --dired -al -- .zshrc]
  xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
  /home/yura/Traceback (most recent call last):
    File "/usr/lib/python3.10/site-packages/xonsh/procs/specs.py", line 473, in _run_binary
      p = self.cls(cmd, bufsize=bufsize, **kwargs)
    File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: '\\\\ls'

  /home/yura/During handling of the above exception, another exception occurred:

  /home/yura/Traceback (most recent call last):
    File "/usr/lib/python3.10/site-packages/xonsh/procs/pipelines.py", line 159, in __init__
      proc = spec.run(pipeline_group=pipeline_group)
    File "/usr/lib/python3.10/site-packages/xonsh/procs/specs.py", line 455, in run
      p = self._run_binary(kwargs)
    File "/usr/lib/python3.10/site-packages/xonsh/procs/specs.py", line 489, in _run_binary
      raise xt.XonshError(e)
  xonsh.tools.XonshError: xonsh: subprocess mode: command not found: \\ls
  Did you mean one of the following?
      ls:  Alias
      ss:  Command (ss)
      ul:  Command (ul)
      ln:  Command (ln)
    nl:  Command (nl)

```

</details>

## Steps to Reproduce
1. open emacs
2. open dired (press C-x d)
3. select some file (not dir!)

this issue can be related: https://github.com/xonsh/xonsh/issues/4112
because when I'm trying to open file as root inside Emacs I get `command not found \/bin\/sh` error.
similar kind of error.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
As mentioned in #4112 this is mostly emacs issue around POSIX expectations so I'm going to close this issue.

One moment. I believe it's possible to create xonsh RC with sometihng like this:
```xsh
aliases |= {
    r'\/bin\/bash': 'bash',
    r'\\ls': 'ls',
}
```
and when emacs will run `xonsh --rc ~/.xonshrc` and then `\/bin\/bash` or `\\ls` it will work because this is work to me:
```xsh
aliases |= {
    r'\/bin\/bash': 'bash',
    r'\\ls': 'ls',
}
\\ls
# <files>
\/bin\/bash
# bash-5.2
```

You can also create handler and replace this kind of command using [command_not_found event](https://xon.sh/events.html#on-command-not-found).
