### ISSUE TITLE
Unhandled KeyError on missing color scheme with `xonsh --no-rc`

### ISSUE THREAD

**Issue by rpdelaney** [xonsh/xonsh#4905]
## xonfig

<details>

```
[Ryans-MacBook-Pro:~] ryan% xonsh -c 'xonfig'
<xonsh-code>:1:0 - xonfig
<xonsh-code>:1:0 + ![xonfig]
+------------------+-----------------+
| xonsh            | 0.13.0          |
| Python           | 3.10.2          |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | none            |
| history backend  | sqlite          |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib          | []              |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior
xonsh should start.

## Current Behavior

<details>

```
[Ryans-MacBook-Pro:~] ryan% bash -c 'env XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=True xonsh --no-rc'
Traceback (most recent call last):
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/main.py", line 467, in main
    args = premain(argv)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/main.py", line 407, in premain
    env = start_services(shell_kwargs, args, pre_env=pre_env)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/main.py", line 355, in start_services
    XSH.shell = Shell(execer=execer, **shell_kwargs)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/shell.py", line 224, in __init__
    env=env.detype(),
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/environ.py", line 1906, in detype
    deval = detyper(val)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/tools.py", line 1240, in detype
    return x.detype()
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/environ.py", line 404, in detype
    style = self.style
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/environ.py", line 438, in style
    self._style = ansi_style_by_name(style_name)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/ansi_colors.py", line 1152, in ansi_style_by_name
    raise KeyError(f"could not find style {name!r}")
KeyError: "could not find style 'gruvbox'"
Xonsh encountered an issue during launch
Failback to /bin/csh
```

</details>

## Steps to Reproduce

I'm currently debugging my [xontrib-gruvbox](https://github.com/rpdelaney/xontrib-gruvbox) to figure out what I did wrong with packaging it that might be causing this. In the mean time, xonsh should handle this situation more gracefully.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Thanks for reporting @rpdelaney!  Potential fix up in #4906

**Comment by rpdelaney** [comment]
Thanks! In the mean time, any suggestions for how I can get a shell? I did `pip3 --isolated install --user pygments` but I still can't get in.

**Comment by gforsyth** [comment]
also install `prompt_toolkit` and that should do it

**Comment by rpdelaney** [comment]
What have I done 😓 

<details>

```
Traceback (most recent call last):
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/tokenize.py", line 809, in find_cookie
    codecs.lookup(encoding)
LookupError: unknown encoding: 38

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/execer.py", line 234, in _try_parse
    tree = self.parser.parse(
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/parsers/base.py", line 507, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/ply/ply/yacc.py", line 1065, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/lexer.py", line 454, in token
    self.beforelast, self.last = self.last, next(self._token_stream, None)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/lexer.py", line 375, in get_tokens
    "stream": tokenize(io.BytesIO(s.encode("utf-8")).readline, tolerant),
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/tokenize.py", line 1164, in tokenize
    encoding, consumed = detect_encoding(readline)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/tokenize.py", line 847, in detect_encoding
    encoding = find_cookie(second)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/tokenize.py", line 816, in find_cookie
    raise SyntaxError(msg)
SyntaxError: unknown encoding: 38

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/main.py", line 467, in main
    args = premain(argv)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/main.py", line 407, in premain
    env = start_services(shell_kwargs, args, pre_env=pre_env)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/main.py", line 353, in start_services
    _load_rc_files(shell_kwargs, args, env, execer, ctx)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/main.py", line 308, in _load_rc_files
    XSH.rc_files = xonshrc_context(
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/environ.py", line 2430, in xonshrc_context
    status = xonsh_script_run_control(
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/environ.py", line 2482, in xonsh_script_run_control
    exc_info = run_script_with_cache(filename, execer, ctx)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/codecache.py", line 167, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/codecache.py", line 125, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/execer.py", line 130, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/execer.py", line 86, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/execer.py", line 343, in _parse_ctx_free
    return _try_parse(input, greedy=False)
  File "/Users/ryan/.local/lib/python3.10/site-packages/xonsh/execer.py", line 249, in _try_parse
    if (e.loc is None) or (
AttributeError: 'SyntaxError' object has no attribute 'loc'
Xonsh encountered an issue during launch
Failback to /bin/csh
[Ryans-MacBook-Pro:~] ryan%

```

</details>

**Comment by gforsyth** [comment]
I'd recommend just blowing away the `xonsh` and `xontrib` directories in your `site-packages` and starting over
