### ISSUE TITLE
asyncio.exceptions.CancelledError -> subprocess.CalledProcessError: Command '['col', '-b']' died with <Signals.SIGINT: 2>.

### ISSUE THREAD

**Issue by rpdelaney** [xonsh/xonsh#4923]
## xonfig

<details>

```
$ xonfig
+------------------+---------------------------------------------------------+
| xonsh            | 0.13.1                                                  |
| Python           | 3.10.6                                                  |
| PLY              | 3.11                                                    |
| have readline    | True                                                    |
| prompt toolkit   | 3.0.30                                                  |
| shell type       | prompt_toolkit                                          |
| history backend  | sqlite                                                  |
| pygments         | 2.13.0                                                  |
| on posix         | True                                                    |
| on linux         | True                                                    |
| distro           | unknown                                                 |
| on wsl           | False                                                   |
| on darwin        | False                                                   |
| on windows       | False                                                   |
| on cygwin        | False                                                   |
| on msys2         | False                                                   |
| is superuser     | False                                                   |
| default encoding | utf-8                                                   |
| xonsh encoding   | utf-8                                                   |
| encoding errors  | surrogateescape                                         |
| xontrib 1        | abbrevs                                                 |
| xontrib 2        | autovox                                                 |
| xontrib 3        | vox                                                     |
| xontrib 4        | voxapi                                                  |
| xontrib 5        | whole_word_jumping                                      |
| xontrib 6        | direnv                                                  |
| xontrib 7        | argcomplete                                             |
| xontrib 8        | gruvbox                                                 |
| xontrib 9        | jedi                                                    |
| xontrib 10       | kitty                                                   |
| xontrib 11       | avox_poetry                                             |
| xontrib 12       | commands                                                |
| RC file 1        | /home/ryan/.config/xonsh/rc.xsh                         |
| RC file 2        | /home/ryan/.config/xonsh/rc.d/00-path.xsh               |
| RC file 3        | /home/ryan/.config/xonsh/rc.d/01-xontribs.xsh           |
| RC file 4        | /home/ryan/.config/xonsh/rc.d/10-aliases.xsh            |
| RC file 5        | /home/ryan/.config/xonsh/rc.d/11-aliases_coreutils.xsh  |
| RC file 6        | /home/ryan/.config/xonsh/rc.d/15-aliases_apply.xsh      |
| RC file 7        | /home/ryan/.config/xonsh/rc.d/20-abbrevs.xsh            |
| RC file 8        | /home/ryan/.config/xonsh/rc.d/21-git-abbrevs.xsh        |
| RC file 9        | /home/ryan/.config/xonsh/rc.d/22-python-abbrevs.xsh     |
| RC file 10       | /home/ryan/.config/xonsh/rc.d/23-youtube-abbrevs.xsh    |
| RC file 11       | /home/ryan/.config/xonsh/rc.d/90-greeting.xsh           |
| RC file 12       | /home/ryan/.config/xonsh/rc.d/99-cleanup.xsh            |
| RC file 13       | /home/ryan/.config/xonsh/rc.d/autovox_policy.xsh        |
| RC file 14       | /home/ryan/.config/xonsh/rc.d/color_style.xsh           |
| RC file 15       | /home/ryan/.config/xonsh/rc.d/command_shell_default.xsh |
| RC file 16       | /home/ryan/.config/xonsh/rc.d/commands.xsh              |
| RC file 17       | /home/ryan/.config/xonsh/rc.d/completion.xsh            |
| RC file 18       | /home/ryan/.config/xonsh/rc.d/env_asdf.xsh              |
| RC file 19       | /home/ryan/.config/xonsh/rc.d/env_cargo.xsh             |
| RC file 20       | /home/ryan/.config/xonsh/rc.d/env_colors.xsh            |
| RC file 21       | /home/ryan/.config/xonsh/rc.d/env_editor.xsh            |
| RC file 22       | /home/ryan/.config/xonsh/rc.d/env_gnupg.xsh             |
| RC file 23       | /home/ryan/.config/xonsh/rc.d/env_homebrew.xsh          |
| RC file 24       | /home/ryan/.config/xonsh/rc.d/env_lynx.xsh              |
| RC file 25       | /home/ryan/.config/xonsh/rc.d/env_pager.xsh             |
| RC file 26       | /home/ryan/.config/xonsh/rc.d/env_pipx.xsh              |
| RC file 27       | /home/ryan/.config/xonsh/rc.d/env_ptpython.xsh          |
| RC file 28       | /home/ryan/.config/xonsh/rc.d/env_python.xsh            |
| RC file 29       | /home/ryan/.config/xonsh/rc.d/env_wine.xsh              |
| RC file 30       | /home/ryan/.config/xonsh/rc.d/env_xonsh.xsh             |
| RC file 31       | /home/ryan/.config/xonsh/rc.d/history.xsh               |
| RC file 32       | /home/ryan/.config/xonsh/rc.d/ignore_warnings.xsh       |
| RC file 33       | /home/ryan/.config/xonsh/rc.d/keychain.xsh              |
| RC file 34       | /home/ryan/.config/xonsh/rc.d/lscolors.xsh              |
| RC file 35       | /home/ryan/.config/xonsh/rc.d/private.xsh               |
| RC file 36       | /home/ryan/.config/xonsh/rc.d/prompt.xsh                |
| RC file 37       | /home/ryan/.config/xonsh/rc.d/xonshrc.xsh               |
+------------------+---------------------------------------------------------+
```

</details>

## Expected Behavior

Do it like bash:

<details>

```console
$ bash -c './factorio --help'

Usage:
  factorio [OPTION...]

 General options:
  -h, --help                    display help
      --version                 show version information
  -v, --verbose                 enable verbose logging
  -c, --config PATH             config file to use
      --no-log-rotation         don't rotate log file
      --mod-directory PATH      Mod directory to use
      --check-unused-prototype-data
                                Print a warning for all prototype values that
                                were not accessed.
      --executable-path PATH    Override autodetected __PATH__executable.
                                Usually not needed except on very weird systems.

 Running options:
  -s, --map2scenario arg        map to scenario conversion
  -m, --scenario2map arg        scenario to map conversion
      --apply-update arg        immediately apply update package
      --create FILE             create a new map
      --map-gen-settings FILE   Map generation settings for use with
                                --create, --start-server-load-scenario or
                                --generate-map-preview. See
                                data/map-gen-settings.example.json
      --map-gen-seed SEED       Map generation seed for use with --create,
                                --start-server-load-scenario or
                                --generate-map-preview. Will override seed specified in map
                                gen settings
      --map-gen-seed-max SEED   Map generation seed for use with
                                --generate-map-preview to generate multiple previews using
                                every second seed in the interval from
                                map-gen-seed to map-gen-seed-max.
      --map-settings FILE       Map settings for use with --create or
                                --start-server-load-scenario. See
                                data/base/prototypes/map-settings.lua
      --preset arg              Name of the map generation preset to be used.
      --generate-map-preview PATH
                                Generate preview images of the map; PATH
                                should name a PNG file or end with a '/' or '\' to
                                indicate a directory.
      --generate-map-preview-random COUNT
                                Number of maps to generate with a random seed
                                using --generate-map-preview.
      --map-preview-size SCALE  Size (in pixels) of map preview (default:
                                1024)
      --map-preview-scale SCALE
                                Scale (meters per pixel) of map preview
                                (default: 1)
      --map-preview-offset X,Y  Offset of the center of the map, in meters
                                (default: 0,0)
      --noise-outputs TAG,TAG...
                                Indicate which variables of noise program to
                                output
      --slope-shading SHADEAMOUNT
                                Apply elevation shading to map preview
      --slope-shade-property SHADEPROP
                                Property to apply slope shading to (default:
                                elevation)
      --report-quantities PROTOTYPE,...
                                When generating map preview, report
                                approximate quantities of the named entity prototypes
      --threads THREADCOUNT     Number of threads to use when generating map
                                previews
      --disable-migration-window
                                Disables the gui that is shown when opening a
                                save with migrated content
      --instrument-mod arg      Name of a mod to enable Instrument Mode
      --start-server FILE       start a multiplayer server
      --start-server-load-scenario [MOD/]NAME
                                start a multiplayer server and load the
                                specified scenario. The scenario is looked for
                                inside the given mod. If no mod is given, it is
                                looked for in the top-level scenarios directory.
      --start-server-load-latest
                                start a multiplayer server and load the
                                latest available save
      --until-tick TICK         run a save until given map tick
      --benchmark FILE          load save and run benchmark
      --benchmark-ticks N       number of ticks for benchmarking. Default is
                                1000 (default: 1000)
      --benchmark-runs N        how often the number of ticks will be run,
                                map will reload after each run. Default is 1
                                (default: 1)
      --benchmark-verbose timings
                                comma separated list of timings to output
                                each tick. "all", "timestamp" as well as all
                                other values seen in the debug view are allowed
                                here. An empty string disabled verbose
                                benchmarking. (default: )
      --benchmark-sanitize      only output the final benchmark results
      --benchmark-ignore-paused
                                leaves the game paused if it was paused when
                                saved. By default the game is unpaused when a
                                benchmark starts.
      --output-perf-stats FILE  path of file to which rendering performance
                                statistics measurements should be saved.
                                Special tags {api}, {hw}, {time} and {tag} will be
                                replaced.
      --mp-connect ADDRESS      start factorio and connect to address
      --password PASSWORD       the password to use when using mp-connect (if
                                any)
      --heavy                   run the game in heavy mode if singleplayer
                                with graphics
      --load-game FILE          start Factorio and load a game in
                                singleplayer
      --load-scenario [MOD/]NAME
                                start Factorio and load the specified
                                scenario in singleplayer. The scenario is looked for
                                inside the given mod. If no mod is given, it
                                is looked for in the top-level scenarios
                                directory.
      --benchmark-graphics FILE
                                load save and run it with graphics for
                                benchmark-ticks number of ticks as normal game would
      --benchmark-frame FILE    load save and benchmark graphics rendering of
                                single frame (prepare + render) without
                                updating the game
      --debug-graphics          enables debugging layer for graphics API. If
                                DirectX is used DirectX SDK needs to be
                                installed for this to work.
      --fullscreen              start game in windowed mode (saved to
                                configuration)
      --max-texture-size N      maximal size of texture that the game can use
                                (saved to configuration). Should be power of
                                two greater than 2048
      --graphics-quality arg    accepted values: normal, low, very-low
      --video-memory-usage arg  accepted values: all, high, medium, low
      --force-graphics-preset arg
                                accepted values: very-low, low,
                                mac-with-low-ram, medium-with-low-vram, medium, high,
                                very-high, extreme
      --gfx-safe-mode           resets some graphics settings to values that
                                should work on most configurations
      --low-vram                sprites that are not put into sprite atlases
                                won't be allocated as texture objects
      --shader arg              enable/disable shader postprocessing (saved
                                to configuration)
      --disable-audio           Disable audio. Mainly for faster startup
                                during development.
      --window-size arg         Desired window resolution. For example
                                "1680x1050". Or "maximized"
      --single-thread-loading   Disables loading of sprites in multiple
                                threads.
      --cache-sprite-atlas      Enable/disable sprite atlas cache.

 Server options:
      --port N                  network port to use
      --bind ADDRESS[:PORT]     IP address (and optionally port) to bind to
      --rcon-port N             Port to use for RCON
      --rcon-bind ADDRESS:PORT  IP address and port to use for RCON
      --rcon-password PASSWORD  Password for RCON
      --server-settings FILE    Path to file with server settings. See
                                data/server-settings.example.json
      --use-server-whitelist    If the whitelist should be used.
      --use-authserver-bans     Verify that connecting players are not banned
                                from multiplayer and inform Factorio.com
                                about ban/unban commands.
      --server-whitelist FILE   Path to file with server whitelist.
      --server-banlist FILE     Path to file with server banlist.
      --server-adminlist FILE   Path to file with server adminlist.
      --console-log FILE        Path to file where a copy of the server's log
                                will be stored
      --server-id FILE          Path where server ID will be stored or read
                                from

$ 
```

</details>

## Current Behavior

<details>

```console
$ ./factorio --help  # hangs forever until SIGINT is sent
^CTraceback (most recent call last):
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/eventloop/async_generator.py", line 59, in generat
or_to_async_generator
    item = await q.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/main.py", line 468, in main
    sys.exit(main_xonsh(args))
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/main.py", line 512, in main_xonsh
    shell.shell.cmdloop()
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 401, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 369, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1034, in prompt
    return self.app.run(
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 937, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 856, in run_asyn
c
    return await _run_async2()
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 832, in _run_asy
nc2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 1051, in cancel_
and_wait_for_background_tasks
    await task
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/buffer.py", line 1912, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/buffer.py", line 1739, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/completion/base.py", line 271, in get_completions_
async
    async for completion in completer.get_completions_async(
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/completion/base.py", line 227, in get_completions_
async
    async for completion in generator_to_async_generator(
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/eventloop/async_generator.py", line 74, in generat
or_to_async_generator
    await runner_f
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/eventloop/async_generator.py", line 43, in runner
    for item in get_iterable():
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/ptk_shell/completer.py", line 58, in get_completions
    completions, plen = self.completer.complete(
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/completer.py", line 121, in complete
    return self.complete_from_context(
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/completer.py", line 272, in complete_from_context
    for comp in self.generate_completions(
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/completer.py", line 233, in generate_completions
    for comp in res:
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/completers/man.py", line 137, in completions
    for desc, opts in _parse_man_page_options(cmd).items():
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/completers/man.py", line 120, in _parse_man_page_options
    options = dict(generate_options_of(cmd))
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/completers/man.py", line 43, in generate_options_of
    out = _get_man_page(cmd)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/completers/man.py", line 32, in _get_man_page
    return subprocess.check_output(["col", "-b"], stdin=manpage.stdout, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['col', '-b']' died with <Signals.SIGINT: 2>.
Xonsh encountered an issue during launch
Failback to /bin/sh
sh-5.1$
```

</details>

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

I'm honestly not sure what Factorio is doing differently that causes this error. It's the first time I've seen it. So, I don't yet have a reproduction without Factorio, which costs 30 USD.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment]
Hi @rpdelaney, thanks for reporting! Could you please try doing the following:

1. Open a new xonsh terminal (let's call it terminal A)
2. In terminal A, run the `tty` command to get terminal A's device path (it should be something like `/dev/pts/7`).
3. In terminal A, run `./factorio --help`, which would hang as you reported
4. Open another terminal (let's call it terminal B)
5. In terminal B, use the `ps` command with the `j` and `--tty` options to get a list of jobs in terminal A. For example, if terminal A's device path were `/dev/pts/7`, then you would run
```
ps j --tty /dev/pts/7
```
Could you please post the output of that `ps` command?

Thanks!

**Comment by rpdelaney** [comment]
I can't reproduce this anymore. I'll re-open if I can :)
