### ISSUE TITLE
stderr not readable

### ISSUE THREAD

**Issue by drunkpig** [xonsh/xonsh#4935]
## xonfig

<details>
```python
#!/usr/bin/env xonsh
# -*- coding:utf-8 -*-




def test():

    out = !(ls fuccc)
    # x = out.stderr.read().decode("utf-8")
    # print(out.stdout.read())
    print(out.errors)
    if out.returncode != 0:
        x = out.stderr.read().decode("utf-8")
        print(x)
    else:
        print("good")



if __name__ == "__main__":
    test()
```
```
(shuziren) cxu@DESKTOP-T821EV3 D:\workspace\odl-final-pipeline main $ xconfig
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: xconfig
Did you mean one of the following?                
    xonfig:  Alias                                
    XONFIG:  Command (XONFIG)                     

(shuziren) cxu@DESKTOP-T821EV3 D:\workspace\odl-final-pipeline main [1] $ xonsh testerr.xsh
None
Traceback (most recent call last):
  File "testerr.xsh", line 22, in <module>
    test()                                
  File "testerr.xsh", line 14, in test    
    x = out.stderr.read().decode("utf-8") 
ValueError: I/O operation on closed file. 
(shuziren) cxu@DESKTOP-T821EV3 D:\workspace\odl-final-pipeline main [1] $

```

</details>

## Expected Behavior

the stderr should read something out like ` cannot access 'fccc': No such file or directory
 `
## Current Behavior

```python
(shuziren) cxu@DESKTOP-T821EV3 D:\workspace\odl-final-pipeline main [1] $ xonsh testerr.xsh
None
Traceback (most recent call last):
  File "testerr.xsh", line 22, in <module>
    test()                                
  File "testerr.xsh", line 14, in test    
    x = out.stderr.read().decode("utf-8") 
ValueError: I/O operation on closed file.

```

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

save my code as x.xsh
then excute a linux or windows command to run the file
# xonsh x.xsh
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment]
I think the `stdout` and `stderr` streams of a `CommandPipeline` object are only meant for xonsh's internal usage.

To read the contents of the standard error, there are two properties that you can use: `err` (blocking - waits for the command to end) and `errors` (non-blocking - does not wait for the command to end).

Also note that `returncode` is a blocking property that waits for the command to end. This means that after accessing `returncode`, you can safely assume that the command has completed.

**Comment by drunkpig** [comment]
@yaxollum It works! Thank you.

my final code is :

```python

#!/usr/bin/env xonsh
# -*- coding:utf-8 -*-
def test():

    out = !(ls fuccc)
    # x = out.stderr.read().decode("utf-8")
    # print(out.stdout.read())
    print(out.errors)
    if out.returncode != 0:
        x = out.err
        print(x)
    else:
        print("good")

if __name__ == "__main__":
    test()
```

**Comment by yaxollum** [comment]
Yeah, I agree that this should be documented better.

A related issue for stdout instead of stderr: #3394
