### ISSUE TITLE
sqlite history has problem in tmux

### ISSUE THREAD

**Issue by amacfie** [xonsh/xonsh#4944]
## xonfig

```
$ xonfig
+------------------+-----------------------------------+
| xonsh            | 0.11.0                            |
| Python           | 3.9.13                            |
| PLY              | 3.11                              |
| have readline    | True                              |
| prompt toolkit   | 3.0.28                            |
| shell type       | prompt_toolkit                    |
| history backend  | sqlite                            |
| pygments         | 2.12.0                            |
| on posix         | True                              |
| on linux         | True                              |
| distro           | unknown                           |
| on wsl           | False                             |
| on darwin        | False                             |
| on windows       | False                             |
| on cygwin        | False                             |
| on msys2         | False                             |
| is superuser     | False                             |
| default encoding | utf-8                             |
| xonsh encoding   | utf-8                             |
| encoding errors  | surrogateescape                   |
| on jupyter       | False                             |
| jupyter kernel   | None                              |
| xontrib 1        | vox                               |
| xontrib 2        | voxapi                            |
| RC file 1        | /etc/xonshrc                      |
| RC file 2        | /home/andrew/.config/xonsh/rc.xsh |
+------------------+-----------------------------------+
```
</details>

## Behavior
With `$XONSH_HISTORY_BACKEND = "sqlite"`, running tmux within `xonsh` fails. Tmux runs and xonsh starts but an error shows up. And if I try running any commands the error shows up and the command doesn't work. See traceback.

### Traceback (if applicable)

<details>

```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/nix/store/rdm31z7s8m6aaydnq949g2zql4wixsgd-python3-3.9.13/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/nix/store/rdm31z7s8m6aaydnq949g2zql4wixsgd-python3-3.9.13/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/nix/store/b57qnxpl04fajvac9zdhf3kckdfglrc3-python3.9-prompt-toolkit-3.0.28/lib/python3.9/site-packages/prompt_toolkit/history.py", line 188, in _in_load_thread
    for item in self.history.load_history_strings():
  File "/nix/store/g9x89aqqp80rcn7mjvnxh3byrichf2gm-xonsh-0.11.0/lib/python3.9/site-packages/xonsh/ptk_shell/history.py", line 29, in load_history_strings
    for cmd in hist.all_items(newest_first=True):
  File "/nix/store/g9x89aqqp80rcn7mjvnxh3byrichf2gm-xonsh-0.11.0/lib/python3.9/site-packages/xonsh/history/__amalgam__.py", line 1176, in all_items
    for inp, ts, rtn, freq, cwd in xh_sqlite_items(
  File "/nix/store/g9x89aqqp80rcn7mjvnxh3byrichf2gm-xonsh-0.11.0/lib/python3.9/site-packages/xonsh/history/__amalgam__.py", line 1046, in xh_sqlite_items
    _xh_sqlite_create_history_table(c)
  File "/nix/store/g9x89aqqp80rcn7mjvnxh3byrichf2gm-xonsh-0.11.0/lib/python3.9/site-packages/xonsh/history/__amalgam__.py", line 893, in _xh_sqlite_create_history_table
    cursor.execute(
sqlite3.DatabaseError: file is not a database
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by amacfie** [comment]
I had a tmux window open that was using `$XONSH_HISTORY_BACKEND = "json"` and I guess that was messing it up somehow because after closing that window it worked.
