### ISSUE TITLE
pip completer in versions >0.11.0 broken on Windows 

### ISSUE THREAD

**Issue by ofek** [xonsh/xonsh#4950]
## xonfig

<details>

```
$ xonfig
+------------------+-------------------------+
| xonsh            | 0.13.3                  |
| Python           | 3.10.7                  |
| PLY              | 3.11                    |
| have readline    | False                   |
| prompt toolkit   | 3.0.31                  |
| shell type       | prompt_toolkit          |
| history backend  | sqlite                  |
| pygments         | 2.13.0                  |
| on posix         | False                   |
| on linux         | False                   |
| on darwin        | False                   |
| on windows       | True                    |
| on cygwin        | False                   |
| on msys2         | False                   |
| is superuser     | False                   |
| default encoding | utf-8                   |
| xonsh encoding   | utf-8                   |
| encoding errors  | surrogateescape         |
| xontrib 1        | prompt_starship         |
| RC file 1        | C:\Users\ofekm/.xonshrc |
+------------------+-------------------------+
```

</details>

## Expected Behavior

Tab completion of files/directories works and no crashes occur

## Current Behavior

`pip install -e .\d` has no completion & `pip install -e .\datadog_checks_dev`:

### Traceback (if applicable)

<details>

```
❯ pip install -e .\datadog_checks_dev
Traceback (most recent call last):
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\__main__.py", line 3, in <module>
    main()
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\main.py", line 470, in main
    _failback_to_other_shells(args, err)
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\main.py", line 439, in _failback_to_other_shells
    raise err
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\main.py", line 468, in main
    sys.exit(main_xonsh(args))
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\main.py", line 512, in main_xonsh
    shell.shell.cmdloop()
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\ptk_shell\shell.py", line 401, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\ptk_shell\shell.py", line 369, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1034, in prompt
    return self.app.run(
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application\application.py", line 978, in run
    return loop.run_until_complete(
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application\application.py", line 891, in run_async
    await self.cancel_and_wait_for_background_tasks()
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application\application.py", line 1092, in cancel_and_wait_for_background_tasks
    await task
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\buffer.py", line 1912, in new_coroutine
    await coroutine(*a, **kw)
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\buffer.py", line 1739, in async_completer
    async for completion in self.completer.get_completions_async(
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\completion\base.py", line 271, in get_completions_async
    async for completion in completer.get_completions_async(
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\completion\base.py", line 198, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\ptk_shell\completer.py", line 58, in get_completions
    completions, plen = self.completer.complete(
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\completer.py", line 121, in complete
    return self.complete_from_context(
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\completer.py", line 272, in complete_from_context
    for comp in self.generate_completions(
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\completer.py", line 233, in generate_completions
    for comp in res:
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\completers\tools.py", line 292, in comp_based_completer
    yield from complete_from_sub_proc(
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\site-packages\xonsh\completers\tools.py", line 271, in complete_from_sub_proc
    lines = sep(output)
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 315, in split
    return list(lex)
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Users\ofekm\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 210, in read_token
    raise ValueError("No escaped character")
ValueError: No escaped character

[process exited with code 1 (0x00000001)]
```

</details>

## Steps to Reproduce

```
pip install -U xonsh[full]
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
Sorry about the breakage @ofek -- does this affect all completers or is it only the `pip` completer that is doing this?

**Comment by ofek** [comment]
Hmm, just pip

**Comment by ofek** [comment]
I'm not familiar enough with the codebase to fix

**Comment by ofek** [comment]
Has there been any update on this?

**Comment by anki-code** [comment]
This is fixed in 0.23.0
