### ISSUE TITLE
fix: improve error message for bad regex glob

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#4993]
A user on Matrix / Gitter was trying to run something like (simplified)

```xonsh
ls `*`
```

which yields
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gil/mambaforge/lib/python3.10/site-packages/xonsh/built_ins.py", line 146, in pathsearch
    o = func(s)
  File "/home/gil/mambaforge/lib/python3.10/site-packages/xonsh/built_ins.py", line 121, in regexsearch
    return reglob(s)
  File "/home/gil/mambaforge/lib/python3.10/site-packages/xonsh/built_ins.py", line 88, in reglob
    return reglob(d, parts, i=0)
  File "/home/gil/mambaforge/lib/python3.10/site-packages/xonsh/built_ins.py", line 95, in reglob
    regex = re.compile(parts[i])
  File "/home/gil/mambaforge/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/home/gil/mambaforge/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/gil/mambaforge/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/home/gil/mambaforge/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/gil/mambaforge/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/home/gil/mambaforge/lib/python3.10/sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

because it should be 
```
ls `.*`
```

I don't think that there are other situations which would raise an `re.error` with the message about "position 0", so we can probably catch that error and suggest adding a `.` to the offending regular expression.

**Comment by AkshayWarrier** [comment]
Hey! I would like to take up this issue.

**Comment by gforsyth** [comment]
Awesome!  Go for it!
