### ISSUE TITLE
threading and ujson module history error after update

### ISSUE THREAD

**Issue by pannet1** [xonsh/xonsh#4995]
```
Exception in thread Thread-13 (_in_load_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/history/json.py", line 551, in all_items
    commands = json_file.load()["cmds"]
  File "/usr/lib/python3.10/site-packages/xonsh/lazyjson.py", line 137, in load
    return self._load_or_node(offset, size)
  File "/usr/lib/python3.10/site-packages/xonsh/lazyjson.py", line 144, in _load_or_node
    val = json.loads(s)
ujson.JSONDecodeError: Unmatched '"' when decoding 'string'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/history.py", line 188, in _in_load_thread
    for item in self.history.load_history_strings():
  File "/usr/lib/python3.10/site-packages/xonsh/ptk_shell/history.py", line 28, in load_history_strings
    for cmd in hist.all_items(newest_first=True):
  File "/usr/lib/python3.10/site-packages/xonsh/history/json.py", line 552, in all_items
    except (json.decoder.JSONDecodeError, ValueError):
```

i get the above error after update. i am on Endeavor OS (which is based on arch)

## xonfig

<details>

```
$ xonfig
+------------------+------------------------+
| xonsh            | 0.13.3                 |
| Python           | 3.10.8                 |
| PLY              | 3.11                   |
| have readline    | True                   |
| prompt toolkit   | 3.0.32                 |
| shell type       | prompt_toolkit         |
| history backend  | json                   |
| pygments         | 2.13.0                 |
| on posix         | True                   |
| on linux         | True                   |
| distro           | unknown                |
| on wsl           | False                  |
| on darwin        | False                  |
| on windows       | False                  |
| on cygwin        | False                  |
| on msys2         | False                  |
| is superuser     | False                  |
| default encoding | utf-8                  |
| xonsh encoding   | utf-8                  |
| encoding errors  | surrogateescape        |
| xontrib 1        | gruvbox                |
| xontrib 2        | output_search          |
| xontrib 3        | cmd_done               |
| xontrib 4        | distributed            |
| xontrib 5        | gitinfo                |
| xontrib 6        | sh                     |
| xontrib 7        | broot                  |
| xontrib 8        | argcomplete            |
| xontrib 9        | back2dir               |
| xontrib 10       | up                     |
| xontrib 11       | mpl                    |
| xontrib 12       | abbrevs                |
| xontrib 13       | autovox                |
| xontrib 14       | hist_navigator         |
| xontrib 15       | readable-traceback     |
| xontrib 16       | coreutils              |
| xontrib 17       | prompt_vi_mode         |
| xontrib 18       | vox_tabcomplete        |
| xontrib 19       | ssh_agent              |
| xontrib 20       | onepath                |
| xontrib 21       | xlsd                   |
| xontrib 22       | vox                    |
| xontrib 23       | kitty                  |
| xontrib 24       | avox                   |
| xontrib 25       | autoxsh                |
| xontrib 26       | voxapi                 |
| xontrib 27       | powerline3             |
| xontrib 28       | z                      |
| xontrib 29       | pdb                    |
| xontrib 30       | histcpy                |
| RC file 1        | /home/pannet1/.xonshrc |
+------------------+------------------------+
```

</details>

## Expected Behavior
no error messages

## Current Behavior
when the terminal is opened i get the above error messages.

To enter debug mode, set the environment variable `XONSH_DEBUG=1` _before_ starting `xonsh`.
On Linux and OSX, an easy way to to do this is to run `env XONSH_DEBUG=1 xonsh` -->

````
<stdin>:38:15 -         source @(target)
<stdin>:38:15 +         ![source @(target)]
[(Token.Generic.Traceback, 'Traceback (most recent call last):\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"/usr/lib/python3.10/site-packages/xonsh/xontribs.py"'), (Token.Text, ', line '), (Token.Literal.Number, '226'), (Token.Text, ', in '), (Token.Name, 'xontribs_load'), (Token.Text, '\n'), (Token.Text, '    '), (Token.Name, 'update_context'), (Token.Punctuation, '('), (Token.Name, 'name'), (Token.Punctuation, ','), (Token.Text, ' '), (Token.Name, 'ctx'), (Token.Operator, '='), (Token.Name, 'ctx'), (Token.Punctuation, ','), (Token.Text, ' '), (Token.Name, 'full_module'), (Token.Operator, '='), (Token.Name, 'full_module'), (Token.Punctuation, ')'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"/usr/lib/python3.10/site-packages/xonsh/xontribs.py"'), (Token.Text, ', line '), (Token.Literal.Number, '174'), (Token.Text, ', in '), (Token.Name, 'update_context'), (Token.Text, '\n'), (Token.Text, '    '), (Token.Name, 'modctx'), (Token.Text, ' '), (Token.Operator, '='), (Token.Text, ' '), (Token.Name, 'xontrib_context'), (Token.Punctuation, '('), (Token.Name, 'name'), (Token.Punctuation, ','), (Token.Text, ' '), (Token.Name, 'full_module'), (Token.Punctuation, ')'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"/usr/lib/python3.10/site-packages/xonsh/xontribs.py"'), (Token.Text, ', line '), (Token.Literal.Number, '140'), (Token.Text, ', in '), (Token.Name, 'xontrib_context'), (Token.Text, '\n'), (Token.Text, '    '), (Token.Name, 'module'), (Token.Text, ' '), (Token.Operator, '='), (Token.Text, ' '), (Token.Name, 'importlib'), (Token.Operator, '.'), (Token.Name, 'import_module'), (Token.Punctuation, '('), (Token.Name, 'spec'), (Token.Operator, '.'), (Token.Name, 'name'), (Token.Punctuation, ')'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"/usr/lib/python3.10/importlib/__init__.py"'), (Token.Text, ', line '), (Token.Literal.Number, '126'), (Token.Text, ', in '), (Token.Name, 'import_module'), (Token.Text, '\n'), (Token.Text, '    '), (Token.Keyword, 'return'), (Token.Text, ' '), (Token.Name, '_bootstrap'), (Token.Operator, '.'), (Token.Name, '_gcd_import'), (Token.Punctuation, '('), (Token.Name, 'name'), (Token.Punctuation, '['), (Token.Name, 'level'), (Token.Punctuation, ':'), (Token.Punctuation, ']'), (Token.Punctuation, ','), (Token.Text, ' '), (Token.Name, 'package'), (Token.Punctuation, ','), (Token.Text, ' '), (Token.Name, 'level'), (Token.Punctuation, ')'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"<frozen importlib._bootstrap>"'), (Token.Text, ', line '), (Token.Literal.Number, '1050'), (Token.Text, ', in '), (Token.Name, '_gcd_import'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"<frozen importlib._bootstrap>"'), (Token.Text, ', line '), (Token.Literal.Number, '1027'), (Token.Text, ', in '), (Token.Name, '_find_and_load'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"<frozen importlib._bootstrap>"'), (Token.Text, ', line '), (Token.Literal.Number, '1006'), (Token.Text, ', in '), (Token.Name, '_find_and_load_unlocked'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"<frozen importlib._bootstrap>"'), (Token.Text, ', line '), (Token.Literal.Number, '688'), (Token.Text, ', in '), (Token.Name, '_load_unlocked'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"<frozen importlib._bootstrap_external>"'), (Token.Text, ', line '), (Token.Literal.Number, '883'), (Token.Text, ', in '), (Token.Name, 'exec_module'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"<frozen importlib._bootstrap>"'), (Token.Text, ', line '), (Token.Literal.Number, '241'), (Token.Text, ', in '), (Token.Name, '_call_with_frames_removed'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"/home/pannet1/.local/lib/python3.10/site-packages/xontrib/gitinfo.xsh"'), (Token.Text, ', line '), (Token.Literal.Number, '23'), (Token.Text, ', in '), (Token.Name, '<module>'), (Token.Text, '\n'), (Token.Text, '    '), (Token.Keyword, 'def'), (Token.Text, ' '), (Token.Name.Function, '__gitinfo_chdir'), (Token.Punctuation, '('), (Token.Name, 'olddir'), (Token.Punctuation, ':'), (Token.Text, ' '), (Token.Name.Builtin, 'str'), (Token.Punctuation, ','), (Token.Text, ' '), (Token.Name, 'newdir'), (Token.Punctuation, ':'), (Token.Text, ' '), (Token.Name.Builtin, 'str'), (Token.Punctuation, ')'), (Token.Text, ' '), (Token.Operator, '-'), (Token.Operator, '>'), (Token.Text, ' '), (Token.Keyword.Constant, 'None'), (Token.Punctuation, ':'), (Token.Text, '\n'), (Token.Text, '  File '), (Token.Name.Builtin, '"/usr/lib/python3.10/site-packages/xonsh/events.py"'), (Token.Text, ', line '), (Token.Literal.Number, '74'), (Token.Text, ', in '), (Token.Name, '__call__'), (Token.Text, '\n'), (Token.Text, '    '), (Token.Keyword, 'raise'), (Token.Text, ' '), (Token.Name.Exception, 'ValueError'), (Token.Punctuation, '('), (Token.Literal.String.Double, '"'), (Token.Literal.String.Double, 'Event handlers need a **kwargs for future proofing'), (Token.Literal.String.Double, '"'), (Token.Punctuation, ')'), (Token.Text, '\n'), (Token.Generic.Error, 'ValueError'), (Token.Text, ': '), (Token.Name, 'Event handlers need a **kwargs for future proofing'), (Token.Text, '\n')]
Failed to load xontrib gitinfo.
<stdin>:8:7 -     cd @(balloons)
<stdin>:8:7 +     ![cd @(balloons)]
<stdin>:24:12 -     command ls @(args[0:-1]) @(balloons)
<stdin>:24:12 +     ![command ls @(args[0:-1]) @(balloons)]
<stdin>:32:10 - completer add vox _vox_completer start
<stdin>:32:10 + ![completer add vox _vox_completer start]
<stdin>:624:8 -         @(["/usr/bin/env", "ls"] + args)
<stdin>:624:8 +         ![@(["/usr/bin/env", "ls"] + args)]
<stdin>:1:5 - sudo $HOME/Scripts/client/_ensite.sh
<stdin>:1:5 + ![sudo $HOME/Scripts/client/_ensite.sh]
<stdin>:1:5 - sudo $HOME/Scripts/client/_disite.sh
<stdin>:1:5 + ![sudo $HOME/Scripts/client/_disite.sh]
<stdin>:1:12:25 - source-bash bin/activate;which python
<stdin>:1:12:25 + ![source-bash bin/activate];which python
<stdin>:1:34 - ![source-bash bin/activate];which python
<stdin>:1:34 + ![source-bash bin/activate];![which python]
<xonsh-code>:1:0 - deactivate
<xonsh-code>:1:0 + ![deactivate]
<stdin>:1:3:14 - cd ~/Personal; ls -la
<stdin>:1:3:14 + ![cd ~/Personal]; ls -la
<xonsh-code>:1:17:23 - ![cd ~/Personal]; ls -la
<xonsh-code>:1:17:23 + ![ls -la]
<stdin>:1:3:20 - cd ~/Scripts/client; ls -la
<stdin>:1:3:20 + ![cd ~/Scripts/client]; ls -la
<xonsh-code>:1:23:29 - ![cd ~/Scripts/client]; ls -la
<xonsh-code>:1:23:29 + ![ls -la]
<stdin>:1:3:18 - cd ~/Programs/php; ls -la
<stdin>:1:3:18 + ![cd ~/Programs/php]; ls -la
<xonsh-code>:1:21:27 - ![cd ~/Programs/php]; ls -la
<xonsh-code>:1:21:27 + ![ls -la]
<xonsh-code>:1:0:34 - cd /run/media/pannet1/FAT32/latest; ls -la
<xonsh-code>:1:0:34 + ![cd /run/media/pannet1/FAT32/latest]
<xonsh-code>:1:35:41 - cd /run/media/pannet1/FAT32/latest; ls -la
<xonsh-code>:1:35:41 + ![ls -la]
<stdin>:1:3:17 - cd $PROJECT_DIRS; vox activate $PROJECT_DIRS
<stdin>:1:3:17 + ![cd $PROJECT_DIRS]; vox activate $PROJECT_DIRS
<stdin>:1:25 - ![cd $PROJECT_DIRS]; vox activate $PROJECT_DIRS
<stdin>:1:25 + ![cd $PROJECT_DIRS]; ![vox activate $PROJECT_DIRS]
<stdin>:1:3:19 - cd ~/.config/kitty; nvim ~/.config/kitty/kitty.conf
<stdin>:1:3:19 + ![cd ~/.config/kitty]; nvim ~/.config/kitty/kitty.conf
<stdin>:1:28 - ![cd ~/.config/kitty]; nvim ~/.config/kitty/kitty.conf
<stdin>:1:28 + ![cd ~/.config/kitty]; ![nvim ~/.config/kitty/kitty.conf]
<stdin>:1:3:19 - cd ~/.config/sxhkd; nvim ~/.config/sxhkd/sxhkdrc
<stdin>:1:3:19 + ![cd ~/.config/sxhkd]; nvim ~/.config/sxhkd/sxhkdrc
<stdin>:1:28 - ![cd ~/.config/sxhkd]; nvim ~/.config/sxhkd/sxhkdrc
<stdin>:1:28 + ![cd ~/.config/sxhkd]; ![nvim ~/.config/sxhkd/sxhkdrc]
<stdin>:1:3:19 - cd ~/.config/qtile; nvim ~/.config/qtile/config.py
<stdin>:1:3:19 + ![cd ~/.config/qtile]; nvim ~/.config/qtile/config.py
<stdin>:1:28 - ![cd ~/.config/qtile]; nvim ~/.config/qtile/config.py
<stdin>:1:28 + ![cd ~/.config/qtile]; ![nvim ~/.config/qtile/config.py]
<stdin>:1:3:28 - cd ~/.config/nvim/lua/user/; nvim .
<stdin>:1:3:28 + ![cd ~/.config/nvim/lua/user/]; nvim .
<stdin>:1:38 - ![cd ~/.config/nvim/lua/user/]; nvim .
<stdin>:1:38 + ![cd ~/.config/nvim/lua/user/]; ![nvim .]
<stdin>:1:3:18 - cd ~/.config/worm; nvim ~/.config/worm/rc
<stdin>:1:3:18 + ![cd ~/.config/worm]; nvim ~/.config/worm/rc
<stdin>:1:27 - ![cd ~/.config/worm]; nvim ~/.config/worm/rc
<stdin>:1:27 + ![cd ~/.config/worm]; ![nvim ~/.config/worm/rc]
<stdin>:1:5 - nvim ~/.xonshrc
<stdin>:1:5 + ![nvim ~/.xonshrc]
<stdin>:1:5 - tail ~/.config/nvim/lua/user/keymaps.lua -n 30
<stdin>:1:5 + ![tail ~/.config/nvim/lua/user/keymaps.lua -n 30]
<stdin>:1:5 - tail ~/.xonshrc -n 30
<stdin>:1:5 + ![tail ~/.xonshrc -n 30]
<stdin>:1:14 - kitty +kitten diff
<stdin>:1:14 + ![kitty +kitten diff]
<stdin>:1:7 - find . -type f -name 
<stdin>:1:7 + ![find . -type f -name] 
<stdin>:1:7 - find . -type d -name 
<stdin>:1:7 + ![find . -type d -name] 
<stdin>:1:14 - kitty +kitten hyperlinked_grep
<stdin>:1:14 + ![kitty +kitten hyperlinked_grep]
<stdin>:1:8 - history show all
<stdin>:1:8 + ![history show all]
<stdin>:1:17 - gromit-mpx --key 'w'
<stdin>:1:17 + ![gromit-mpx --key 'w']
<stdin>:1:4 - git difftool --no-symlinks --dir-diff
<stdin>:1:4 + ![git difftool --no-symlinks --dir-diff]
<stdin>:1:19 - lxterminal; ssh -v carrierc@ecomsense.in
<stdin>:1:19 + lxterminal; ![ssh -v carrierc@ecomsense.in]
<xonsh-code>:1:0:10 - lxterminal; ![ssh -v carrierc@ecomsense.in]
<xonsh-code>:1:0:10 + ![lxterminal]
<stdin>:1:30 - yt-dlp --concurrent-fragments 5 
<stdin>:1:30 + ![yt-dlp --concurrent-fragments 5] 
<xonsh-code>:1:0:45 - yay --devel --config /etc/pacman.old.conf --aur
<xonsh-code>:1:0:45 + ![yay --devel --config /etc/pacman.old.conf --aur]
[history.ujson] Enumerated 1 history files for 0.003
[history.ujson] Enumerated 2 history files for 0.008
..
[history.ujson] Enumerated 590 history files for 0.2
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xonsh/history/json.py", line 551, in all_items
    commands = json_file.load()["cmds"]
  File "/usr/lib/python3.10/site-packages/xonsh/lazyjson.py", line 137, in load
    return self._load_or_node(offset, size)
  File "/usr/lib/python3.10/site-packages/xonsh/lazyjson.py", line 144, in _load_or_node
    val = json.loads(s)
ujson.JSONDecodeError: Unmatched '"' when decoding 'string'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/history.py", line 188, in _in_load_thread
    for item in self.history.load_history_strings():
  File "/usr/lib/python3.10/site-packages/xonsh/ptk_shell/history.py", line 28, in load_history_strings
    for cmd in hist.all_items(newest_first=True):
  File "/usr/lib/python3.10/site-packages/xonsh/history/json.py", line 552, in all_items
    except (json.decoder.JSONDecodeError, ValueError):
AttributeError: module 'ujson' has no attribute 'decoder'. Did you mean: 'decode'?
````

**Comment by pannet1** [comment]
since, i wanted an immediate fix. i moved the history json dump to another location and both the problem vanished. sorry for the late revert. thanks @anki-code
