### ISSUE TITLE
Using Rust Python for running xonsh shell

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5082]
It looks it's possible to run xonsh using [RustPython](https://github.com/RustPython/RustPython). 

```xsh
xonsh
# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  # https://rustup.rs/
# restart shell

# Install RustPython
cargo install --features=ssl --git https://github.com/RustPython/RustPython rustpython
$PATH.append(p'~/.cargo/bin')
#rustpython -m site  # to get locations

# Install xonsh
rustpython --install-pip
rustpython -m pip install xonsh prompt-toolkit pygments

~/.local/bin/xonsh -DXONSH_SHOW_TRACEBACK=1  # or with `--no-rc` for testing
```
In case of issues report to https://github.com/RustPython/RustPython/issues

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
First try:
```xsh
xonsh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  # https://rustup.rs/
# restart shell
cargo install --features=ssl --git https://github.com/RustPython/RustPython rustpython
$PATH.append(p'~/.cargo/bin')
#rustpython -m site  # to get locations
rustpython --install-pip
rustpython -m pip install xonsh
~/.local/bin/xonsh --no-rc
# SyntaxError: match expression is not implemented yet at line 1 column 1
```
Reported - https://github.com/RustPython/RustPython/issues/4770

**Comment by anki-code** [comment]
New try for [this](https://github.com/xonsh/xonsh/issues/5082#issuecomment-1483866245):
```xsh
~/.local/bin/xonsh --no-rc --no-env
```
Result:
```xsh
Traceback (most recent call last):
  File "/Users/pc/.local/bin/xonsh", line 3, in <module>
    from xonsh.main import main
  File "/Users/pc/.local/lib/rustpython3.13/site-packages/xonsh/main.py", line 12, in <module>
    import xonsh.procs.pipelines as xpp
  File "/Users/pc/.local/lib/rustpython3.13/site-packages/xonsh/procs/__init__.py", line 1, in <module>
    from xonsh.procs import proxies  # noqa
  File "/Users/pc/.local/lib/rustpython3.13/site-packages/xonsh/procs/proxies.py", line 19, in <module>
    import xonsh.lib.lazyimps as xli
  File "/Users/pc/.local/lib/rustpython3.13/site-packages/xonsh/lib/lazyimps.py", line 7, in <module>
    from xonsh.platform import ON_DARWIN, ON_WINDOWS
  File "/Users/pc/.local/lib/rustpython3.13/site-packages/xonsh/platform.py", line 7, in <module>
    import ctypes  # noqa
  File "/Users/pc/.cargo/git/checkouts/rustpython-63090cdce5e18442/1e7a490/crates/pylib/Lib/ctypes/__init__.py", line 40, in <module>
    from _ctypes import _non_existing_function
ImportError: cannot import name '_non_existing_function'
```

Reported https://github.com/RustPython/RustPython/issues/6299

But ctypes is not the thing that is stopper. We need to just comment `import ctypes` and go forward.

**Comment by anki-code** [comment]
Nowadays RustPython team is workin on [solving issues and running xonsh](https://github.com/RustPython/RustPython/issues?q=is%3Aissue%20author%3Aanki-code).

**Comment by anki-code** [comment]
I'm going to close this issue until new tests/reports. Feel free to run xonsh with RustPython and report the issues to RustPython repository.
