### ISSUE TITLE
Unable to run python scripts without prefixing with python command on windows, WinError 193

### ISSUE THREAD

**Issue by kalyan860** [xonsh/xonsh#5109]
I have a python script named opn.py in $PATH. I can run it on any other shell by invoking opn with its arguments. For eg., 

> opn "log"

Howeever when I do this on xonsh, I get the following error. 

```
kalya@LAPTOP-Q2D6HP28 ~\scripts $ opn log
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\kalya\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\procs\pipelines.py", line 166, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalya\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\procs\specs.py", line 455, in run
    p = self._run_binary(kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalya\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\procs\specs.py", line 473, in _run_binary
    p = self.cls(cmd, bufsize=bufsize, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalya\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kalya\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by jaraco** [comment]
I have this issue also. I'm working on a demo of using `pip-run` for making standalone Python scripts (with dependencies) work on Windows. If I clone [jaraco/pip-run](/jaraco/pip-run), [set up `PATHEXT`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3#path-information) with `.PY` in it, and then attempt to run `examples/pydragon`, it works on Powershell but not on xonsh:

```Powershell
PS C:\Users\jaraco\code\jaraco\pip-run> examples/pydragon
  _________________________________________________
 /                                                 \
| Python is a programming language that lets you wo |
...
```

But invoking the same command in the same environment on xonsh fails with the reported error:

```xonsh
 ~ @ cd code/jaraco/pip-run
 pip-run main @ examples/pydragon
OSError: [WinError 193] %1 is not a valid Win32 application

```

To minimally reproduce:

1. Use the GUI or something like [jaraco.windows.enver](https://github.com/jaraco/jaraco.windows/blob/1a7f8f4ec559720aa518f749718ab9a57b48e4a7/setup.cfg#L67) to ensure `PATHEXT=.PY;...`.
2. `touch foo.py`
3. `./foo`

**Comment by anki-code** [comment]
After #6180 this is working to me:
```xsh
xpip install cmdix
# restart xonsh
mkdir ~/tmp
cd ~/tmp

echo 'print(1)' > script.py

$PATH.append($PWD)

script
# command not found

$PATHEXT.append('.py')
cd ..
script
# 1
```
