### ISSUE TITLE
`xonfig web` fails with an error

### ISSUE THREAD

**Issue by Marin-Kitagawa** [xonsh/xonsh#5110]
## xonfig
This is a fresh installation of `xonsh` on Arch Linux. I was not able to config it using `xonfig web`. It threw an error saying 
```py
AttributeError: module 'gdb' has no attribute 'Command'
```

## Expected Behavior

I must be able to edit the config file for xonsh
## Current Behavior

It throws the above error `AttributeError...`
### Traceback (if applicable)

<details>

```
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 53726)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/http/server.py", line 668, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/usr/lib/python3.10/site-packages/xonsh/webconfig/main.py", line 87, in do_GET
    route = self._get_route("get")
  File "/usr/lib/python3.10/site-packages/xonsh/webconfig/main.py", line 84, in _get_route
    return route_cls(url=url, params=params, xsh=XSH)
  File "/usr/lib/python3.10/site-packages/xonsh/webconfig/routes.py", line 91, in __init__
    self.colors = dict(xonsh_data.render_colors())
  File "/usr/lib/python3.10/site-packages/xonsh/webconfig/xonsh_data.py", line 190, in render_colors
    styles = sorted(get_all_styles())
  File "/usr/lib/python3.10/site-packages/xonsh/pygments_cache.py", line 458, in get_all_styles
    load_or_build()
  File "/usr/lib/python3.10/site-packages/xonsh/pygments_cache.py", line 325, in load_or_build
    CACHE = build_cache()
  File "/usr/lib/python3.10/site-packages/xonsh/pygments_cache.py", line 255, in build_cache
    cache["lexers"] = _discover_lexers()
  File "/usr/lib/python3.10/site-packages/xonsh/pygments_cache.py", line 112, in _discover_lexers
    for longname, _, filenames, _ in get_all_lexers():
  File "/usr/lib/python3.10/site-packages/pygments/lexers/__init__.py", line 49, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/usr/lib/python3.10/site-packages/pygments/plugin.py", line 73, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/usr/lib/python3.10/site-packages/voltron/__init__.py", line 24, in setup_env
    env = Environment(setup_logging=False,
  File "/usr/lib/python3.10/site-packages/scruffy/env.py", line 49, in __init__
    self.add(**kwargs)
  File "/usr/lib/python3.10/site-packages/scruffy/env.py", line 114, in add
    self._children[key].prepare()
  File "/usr/lib/python3.10/site-packages/scruffy/file.py", line 439, in prepare
    self.load()
  File "/usr/lib/python3.10/site-packages/scruffy/file.py", line 445, in load
    self._pm.load_plugins(self.path)
  File "/usr/lib/python3.10/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/usr/lib/python3.10/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/voltron/plugins/debugger/dbg_gdb.py", line 663, in <module>
    class GDBCommand(DebuggerCommand, gdb.Command):
AttributeError: module 'gdb' has no attribute 'Command'
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 53740)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/http/server.py", line 668, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/usr/lib/python3.10/site-packages/xonsh/webconfig/main.py", line 87, in do_GET
    route = self._get_route("get")
  File "/usr/lib/python3.10/site-packages/xonsh/webconfig/main.py", line 84, in _get_route
    return route_cls(url=url, params=params, xsh=XSH)
  File "/usr/lib/python3.10/site-packages/xonsh/webconfig/routes.py", line 91, in __init__
    self.colors = dict(xonsh_data.render_colors())
  File "/usr/lib/python3.10/site-packages/xonsh/webconfig/xonsh_data.py", line 190, in render_colors
    styles = sorted(get_all_styles())
  File "/usr/lib/python3.10/site-packages/xonsh/pygments_cache.py", line 458, in get_all_styles
    load_or_build()
  File "/usr/lib/python3.10/site-packages/xonsh/pygments_cache.py", line 325, in load_or_build
    CACHE = build_cache()
  File "/usr/lib/python3.10/site-packages/xonsh/pygments_cache.py", line 255, in build_cache
    cache["lexers"] = _discover_lexers()
  File "/usr/lib/python3.10/site-packages/xonsh/pygments_cache.py", line 112, in _discover_lexers
    for longname, _, filenames, _ in get_all_lexers():
  File "/usr/lib/python3.10/site-packages/pygments/lexers/__init__.py", line 49, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/usr/lib/python3.10/site-packages/pygments/plugin.py", line 73, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/usr/lib/python3.10/site-packages/voltron/__init__.py", line 24, in setup_env
    env = Environment(setup_logging=False,
  File "/usr/lib/python3.10/site-packages/scruffy/env.py", line 49, in __init__
    self.add(**kwargs)
  File "/usr/lib/python3.10/site-packages/scruffy/env.py", line 114, in add
    self._children[key].prepare()
  File "/usr/lib/python3.10/site-packages/scruffy/file.py", line 439, in prepare
    self.load()
  File "/usr/lib/python3.10/site-packages/scruffy/file.py", line 445, in load
    self._pm.load_plugins(self.path)
  File "/usr/lib/python3.10/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/usr/lib/python3.10/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/voltron/plugins/debugger/dbg_gdb.py", line 663, in <module>
    class GDBCommand(DebuggerCommand, gdb.Command):
AttributeError: module 'gdb' has no attribute 'Command'
----------------------------------------
```

</details>

## Steps to Reproduce

1. Install `xonsh`
2. Open `xonsh`
3. Execute `xonfig web`
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
The issue is that Xonsh's pygments cache is trying to load all installed lexers. We don't need to do that. We can try changing the behaviour to not load all the lexers and load only the necessary ones
