### ISSUE TITLE
arrows broke after keybinding shortcut

### ISSUE THREAD

**Issue by pigasus55** [xonsh/xonsh#5119]
I did keybinding [https://xon.sh/tutorial_ptk.html]()

.xonshrc:
```
from prompt_toolkit.keys import Keys
from prompt_toolkit.filters import Condition, EmacsInsertMode, ViInsertMode

@events.on_ptk_create
def custom_keybindings(bindings, **kw):

    @bindings.add(Keys.ControlW)
    ls -la
    event.cli.renderer.erase()
```

The command runs correctly after keystroke. But the arrow input becomes incorrect (^[[A^[[B^[[C^[[D) when the following command is editing. Letters, shortcuts, backspace are correctly.
![bug](https://user-images.githubusercontent.com/128574753/233128023-edec6871-fd44-4148-a799-4cab1bbd48e1.png)

The problem in debian. In ubuntu is all good.
Changed: user, root, konsole, xterm, uxterm, tty(alt-shift-F2) — the problem remains.
`reset` — helps. Before next shortcut.
If to replace an outputing command to a silent(ls → mkdir) then the problem remains.
`subprocess.run()` — helps. But it does not let to use an interactive commands as a file manager.

### Environment
<details>

```
Debian KDE
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Xonsh is from deb repository.

$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.25          |
| Python           | 3.9.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.14          |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+

I deleted it and installed from pip. The problem remains.

$ xonfig
+------------------+---------------------+
| xonsh            | 0.13.4              |
| Python           | 3.9.2               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.14              |
| shell type       | prompt_toolkit      |
| history backend  | json                |
| pygments         | 2.7.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | unknown             |
| on wsl           | False               |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
| xontrib          | []                  |
| RC file 1        | /home/user/.xonshrc |
+------------------+---------------------+



KUbuntu
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
No LSB modules are available.

$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.13          |
| Python           | 3.8.10          |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```
</details>

### Traceback

<details>

```
user@pc ~/1 $ итого 16
drwxr-xr-x  3 user user 4096 апр 19 19:41 .
drwxr-xr-x 20 user user 4096 апр 19 19:41 ..
-rw-r--r--  1 user user    2 апр 19 19:41 1.txt
drwxr-xr-x  2 user user 4096 апр 19 19:41 2
user@pc ~/1 $ ^[[C^[[Cletters are correct, but arrows ^[[A^[[B^[[C^[[D
<stdin>:1:8 - letters are correct, but arrows 
<stdin>:1:8 + ![letters are correct, but arrows] 
user@pc ~/1 $ letters are correct, but arrows
<stdin>:1:8 - letters are correct, but arrows 
<stdin>:1:8 + ![letters are correct, but arrows] 
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/xonsh/procs/specs.py", line 473, in _run_binary
    p = self.cls(cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'letters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/xonsh/procs/pipelines.py", line 166, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/user/.local/lib/python3.9/site-packages/xonsh/procs/specs.py", line 455, in run
    p = self._run_binary(kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/xonsh/procs/specs.py", line 492, in _run_binary
    raise xt.XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: letters
Did you mean the following?
    setterm:  Command (setterm)
user@pc ~/1 [1] $
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Fixed in beta xonsh 0.23.0
