### ISSUE TITLE
Not all 'xonfig styles' are registered for use with register_custom_style

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#5163]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.14.0          |
| Python           | 3.11.4          |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.38          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.15.1          |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib 1        | cd              |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior
All styles from `xonfig styles` should be available as fallbacks

## Current Behavior
Some styles like `solarized-light` can't be used with `register_custom_style`

### Traceback (if applicable)

<details>

```
traceback
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xonsh/tools.py", line 2105, in register_custom_style
    register_custom_ansi_style(name, styles, base)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xonsh/ansi_colors.py", line 1138, in register_custom_ansi_style
    base_style = ANSI_STYLES[base].copy()
                 ~~~~~~~~~~~^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xonsh/lazyasd.py", line 173, in __getitem__
    loader = self._loaders.pop(key)
             ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'solarized-light'

```

</details>

## Steps to Reproduce

- Check available styles `xonfig styles`
- Try to use `solarized-light`
```py
from builtins	import __xonsh__  # XonshSession (${...} is '__xonsh__.env')
from xonsh.tools import register_custom_style as regStyle # register custom styles
regStyle("ttt", {}, base="solarized-light")
```
- Get `KeyError: 'solarized-light'`

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by andrew222651** [comment]
Try `xonsh.pyghooks.register_custom_pygments_style`

**Comment by eugenesvk** [comment]
Thanks for the tip, if I use
`from xonsh.pyghooks import register_custom_pygments_style as regStyleP`
instead of 
`from xonsh.tools import register_custom_style as regStyle`

then I don't get the errors, though then my custom colors are ignored


```py
from xonsh.tools import register_custom_style as regStyle # register custom styles
from xonsh.pyghooks import register_custom_pygments_style as regStyleP # register custom styles
styletest = {
  "BLUE"    : "#ff0000", # red color instead of blue
}
regStyle("myname", styletest, base="default") # works, shows red
regStyleP("myname", styletest, base="default") # fails, shows blue
```
