### ISSUE TITLE
f-string with special syntax are not supported yet in py3.12

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/xonsh#5166]
check the comment and related test for more info https://github.com/xonsh/xonsh/pull/5156#discussion_r1247003673

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by sbliven** [comment]
I ran into this issue when updating xonsh via homebrew. It's particularly annoying that environment variables don't work (which I use extensively in my .xonshrc). Some examples to reproduce:

```python
$ print(f"{$HOME}")
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
RuntimeError: Unsupported fstring syntax
```
Workaround is to use pure-python versions:
```python
$ print(f"{__xonsh__.env['HOME']}")
/Users/me
```

**Comment by jnoortheen** [comment]
I have actually started working on pegen based parser here . https://github.com/jnoortheen/xonsh-parser/tree/peg_parser/peg_parser .

**Comment by rpdelaney** [comment]
I can't start xonsh 0.16.0 after upgrading to python 3.12:

<details><summary>stack trace</summary>

```
Traceback (most recent call last):
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/parsers/fstring_adaptor.py", line 58, in _patch_special_syntax
    res = pyparse(repl)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    f'keychain --quiet --absolute --dir "{$XDG_DATA_HOME}/keychain"'
                                          ^
SyntaxError: f-string: expecting a valid expression after '{'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/main.py", line 469, in main
    args = premain(argv)
           ^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/main.py", line 409, in premain
    env = start_services(shell_kwargs, args, pre_env=pre_env)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/main.py", line 355, in start_services
    _load_rc_files(shell_kwargs, args, env, execer, ctx)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/main.py", line 310, in _load_rc_files
    XSH.rc_files = xonshrc_context(
                   ^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/environ.py", line 2510, in xonshrc_context
    status = xonsh_script_run_control(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/environ.py", line 2562, in xonsh_script_run_control
    exc_info = run_script_with_cache(filename, execer, ctx)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/codecache.py", line 168, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/codecache.py", line 126, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode, filename=filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/execer.py", line 131, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/execer.py", line 87, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/execer.py", line 344, in _parse_ctx_free
    return _try_parse(input, greedy=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/execer.py", line 235, in _try_parse
    tree = self.parser.parse(
           ^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/parsers/base.py", line 509, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/parsers/base.py", line 2556, in p_string_literal
    ).run()
      ^^^^^
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/parsers/fstring_adaptor.py", line 191, in run
    self._patch_special_syntax()
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.12/site-packages/xonsh/parsers/fstring_adaptor.py", line 74, in _patch_special_syntax
    raise RuntimeError("Unsupported fstring syntax") from e
RuntimeError: Unsupported fstring syntax
Xonsh encountered an issue during launch
```
</details>

**Comment by heysokam** [comment]
Any updates or expected ETA on this?

**Comment by jnoortheen** [comment]
@anki-code since py312, it has implemented [PEP 701](https://peps.python.org/pep-0701/) affecting the current xonsh specific parsing method. `f"{$HOME}"` we need to handle cases where $env variables are inside fstrings.

**Comment by cyb3rmonk** [comment]
Is there any ongoing plan to support env vars in f-strings in Python 3.12+ ?

**Comment by elgow** [comment]
An additional syntactic sugar workaround would be adding this to your .xonshrc (or making it standard)

```xsh
class MetaEnv(type):
    def __getattr__(cls, name):
        return __xonsh__.env[name]
    def __setattr__(cls, name, value):
        __xonsh__.env[name] = value


class Env(metaclass=MetaEnv):
    pass

# Using the above class in an f-string
f'Now in dir {Env.PWD}'   #  yields 'Now in dir /home/me'  

# And it works for  things like 
f'Now in dir {Env.PWD.upper()}'   #  yields 'Now in dir /HOME/ME' 

# And the same can be used for setting env vars
Env.FOO = 'bar'
$FOO   # yields 'bar'
```

**Comment by jnoortheen** [comment]
> I have actually started working on pegen based parser here . https://github.com/jnoortheen/xonsh-parser/tree/peg_parser/peg_parser .

I no longer work on this as it tends to be slower than current PLY based parser. You could try https://github.com/jnoortheen/xonsh-rd-parser/

**Comment by anki-code** [comment]
Hello everybody! I've introduced the fix in https://github.com/xonsh/xonsh/pull/6170. Please put all hands to test it.
