### ISSUE TITLE
exec in a xonsh script fails if the script was started with exec

### ISSUE THREAD

**Issue by lexbailey** [xonsh/xonsh#5216]
I have a script called `foo` that contains a line of the form:

    exec some_program ...

I now have another script `bar` that contains this line:

    exec ./foo

What happens when I run `./bar`?

## Expected Behavior

`bar` should exec `foo`, `foo` should then exec `some_program`, and thus ultimately the current process is replaced by `some_program`

## Current Behavior

xonsh crashes with `Exception: Recursive calls to "exec" alias.`

### Traceback (if applicable)

```
user@host ~ @ env XONSH_SHOW_TRACEBACK=True ./bar
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "./foo", line 2, in <module>
    exec some_program
    
  File "/usr/lib/python3.11/site-packages/xonsh/built_ins.py", line 205, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xonsh/procs/specs.py", line 889, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured, envs=envs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xonsh/procs/specs.py", line 833, in cmds_to_specs
    spec = SubprocSpec.build(cmd, captured=captured, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xonsh/procs/specs.py", line 579, in build
    spec.resolve_binary_loc()
  File "/usr/lib/python3.11/site-packages/xonsh/procs/specs.py", line 632, in resolve_binary_loc
    raise Exception(f'Recursive calls to "{cmd0}" alias.')
Exception: Recursive calls to "exec" alias.
user@host ~ @ 
```

## Steps to Reproduce

Create the following files:

File: `foo`
```
#!/usr/bin/env xonsh
exec some_program
```

File: `bar`
```
#!/usr/bin/env xonsh
exec ./foo
```

make them both executable, run `./bar`

## Workaround

If you've hit this issue and it hasn't been fixed in your version and need a quick workaround, start your script with these lines:
```
del $__ALIAS_NAME
del $__ALIAS_STACK
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by lexbailey** [comment]
I'm happy to make a PR to fix this, but I need to know what's the "correct" fix.

I'm guessing the `__ALIAS` variables should be deleted just before the exec system call? or is the appropriate fix more sophisticated somehow?

from browsing other related issues it seems that the recursive alias detection prevents some other valid use cases.

what is the rationale for prohibiting recursion? why not allow it in a similar way to python function calls by having a large but finite call depth limit instead?

thanks.

**Comment by anki-code** [comment]
@lexbailey please try with fix:
* https://github.com/xonsh/xonsh/pull/6198

```xsh
xpip install --force-reinstall -U git+https://github.com/anki-code/xonsh@anki_fix_exec
# restart xonsh
```
