### ISSUE TITLE
Cython debugging does not work with xonsh as login shell

### ISSUE THREAD

**Issue by pguenth** [xonsh/xonsh#5218]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.14.1          |
| Python           | 3.11.5          |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.39          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | 2.16.1          |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on wsl           | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib          | []              |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## Issue

While trying to find the cause of a segmentation fault in a python/cython/c++ application with cython's version of gdb, I noticed that cygdb doesn't work as expected while xonsh is set as login shell. Instead of showing the backtrace when the segfault occurs, I get the following error inside cygdb: (minimal example to reproduce this can be found here: https://gitfront.io/r/user-5141265/cy46S2Favk8c/xonsh-cygdb-problem/)

```
(gdb) cy run test.py
[...]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/Cython/Debugger/libpython.py", line 1980, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Cython/Debugger/libpython.py", line 2427, in run
    self.finish_executing(gdb.execute('run ' + args, to_string=True))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Cython/Debugger/libpython.py", line 2147, in execute
    _execute(command, from_tty)
gdb.error: During startup program terminated with signal SIGSEGV, Segmentation fault.
Python Exception <class 'gdb.error'>: During startup program terminated with signal SIGSEGV, Segmentation fault.
Error occurred in Python: During startup program terminated with signal SIGSEGV, Segmentation fault.
```

and when asking for a backtrace, the following error comes up:

```
(gdb) cy bt
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/Cython/Debugger/libcython.py", line 125, in wrapper
    gdb.selected_frame()
gdb.error: No frame is currently selected.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/Cython/Debugger/libpython.py", line 1980, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Cython/Debugger/libcython.py", line 127, in wrapper
    raise gdb.GdbError("No frame is currently selected.")
gdb.GdbError: No frame is currently selected.
No frame is currently selected.
(gdb) bt
No stack.
```

None of this happens when bash is the login shell instead of xonsh, instead as expected:

```
Program received signal SIGSEGV, Segmentation fault.
test_cpp () at loop/loop.cpp:5
5	    *p = 1;
```

Also, retrieving the backtraces leads to the expected results. Suprisingly for me, it works even when running cydbg from inside xonsh, as long as bash is the login shell; equally the other way round: It produces the error when running bash->cydbg with xonsh as login shell.

I'm not sure if this is considered a bug or even if xonsh really is cause for the issue, but I wanted to report it somewhere just so people don't wonder about cydbg not doing what they expect like I did for quite some time. 

## Steps to Reproduce
With the MWE provided, run `python setup.py build_ext --inplace` in the repo directory (which compiles the cython/cpp code to a shared object). Then start `cydbg .` and launch the program with `cy run test.py`. I can also provide the shared object if neccessary.

**Comment by anki-code** [comment]
I'm going to close this because of no new thumb ups and this was reported long time ago. Feel free to reopen with new repeatable list of commands for reproducing the issue.
