### ISSUE TITLE
termios.error after invoking subprocess in pythonanywhere

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#5222]
I'm attempting to use xonsh on pythonanywhere.com.

I've used pipx to install xonsh:

```
pipx install 'xonsh[ptk]'
```

When I run a built-in command like `xonfig`, the process proceeds, but if I invoke a subprocess like `ls`, the shell crashes after executing the command.

Even though it says "fallback to /bin/sh", the terminal hangs unresponsive.

If I run without `ptk` (i.e. readline), the issue does not occur, so the issue may in fact lie upstream in prompt_toolkit.

For now, I'm running with readline, but I wanted to register the issue.

## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.14.1          |
| Python           | 3.9.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.39          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on wsl           | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib 1        | voxapi          |
| xontrib 2        | vox             |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior

Same as with readline (no error, no hang).

## Current Behavior

```
jaraco@blue-liveconsole11 ~ @ ls .local
bin  lib  pipx  share
Traceback (most recent call last):
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/xonsh/main.py", line 469, in main
    sys.exit(main_xonsh(args))
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/xonsh/main.py", line 513, in main_xonsh
    shell.shell.cmdloop()
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/xonsh/ptk_shell/shell.py", line 401, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/xonsh/ptk_shell/shell.py", line 369, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1024, in prompt
    return self.app.run(
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 967, in run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 881, in run_async
    return await _run_async(f)
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 732, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "/home/jaraco/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 258, in __enter__
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)
termios.error: (5, 'Input/output error')
Xonsh encountered an issue during launch
Failback to /bin/sh
```

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
I can't reproduce this on current main branch:

<img width="1078" height="772" alt="Image" src="https://github.com/user-attachments/assets/6a78dd47-0bcf-4f6c-b88d-bbacea15b315" />
