### ISSUE TITLE
Error `Bad file descriptor` in `prompt_toolkit` on ctrl+C interrupt

### ISSUE THREAD

**Issue by clstaudt** [xonsh/xonsh#5240]
xonsh has recently (supposedly after an update) started crashing on control+C interrupts. The terminal then falls back to zsh.

```python
(haystack-test) cls@clsm1ba ~/Documents/Work/Projects/Client/SubProjects/AIProductSafety/Dev/haystack-test
➤ pip install farm-haystack
^CTraceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 72, in close
    loop.run_until_complete(
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 618, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1913, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/selectors.py", line 561, in select
    kev_list = self._selector.control(None, max_ev, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/xonsh/0.14.2/libexec/lib/python3.12/site-packages/xonsh/main.py", line 469, in main
    sys.exit(main_xonsh(args))
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xonsh/0.14.2/libexec/lib/python3.12/site-packages/xonsh/main.py", line 513, in main_xonsh
    shell.shell.cmdloop()
  File "/opt/homebrew/Cellar/xonsh/0.14.2/libexec/lib/python3.12/site-packages/xonsh/ptk_shell/shell.py", line 401, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xonsh/0.14.2/libexec/lib/python3.12/site-packages/xonsh/ptk_shell/shell.py", line 369, in singleline
    line = self.prompter.prompt(**prompt_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xonsh/0.14.2/libexec/lib/python3.12/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1026, in prompt
    return self.app.run(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xonsh/0.14.2/libexec/lib/python3.12/site-packages/prompt_toolkit/application/application.py", line 998, in run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 193, in run
    with Runner(debug=debug, loop_factory=loop_factory) as runner:
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 62, in __exit__
    self.close()
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 77, in close
    loop.close()
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 104, in close
    self._close_self_pipe()
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 112, in _close_self_pipe
    self._ssock.close()
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 504, in close
    self._real_close()
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 498, in _real_close
    _ss.close(self)
OSError: [Errno 9] Bad file descriptor
Xonsh encountered an issue during launch
Failback to /bin/zsh
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by clstaudt** [comment]
I am not sure what changed for the crash to appear.

The crashing version is 

➤ xonsh.__version__
'0.14.2'

**Comment by Qyriad** [comment]
Does it happen consistently for you though?

**Comment by clstaudt** [comment]
It happens often enough to switch my shell back to fish. But not reproducible, I don't know what exactly triggers the crash.

**Comment by clstaudt** [comment]
```
➤ xonfig
+------------------+---------------------+
| xonsh            | 0.14.2              |
| Python           | 3.12.0              |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.41              |
| shell type       | prompt_toolkit      |
| history backend  | json                |
| pygments         | 2.17.2              |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
| xontrib          | []                  |
| RC file 1        | /Users/cls/.xonshrc |
+------------------+---------------------+
```

**Comment by mltucker** [comment]
I have also started getting this error after a recent update (installed via homebrew on an m1 macbook). In my case it's not the ctrl+c interrupt that seems to be the problem, but just now and then running a command (most recently `git diff HEAD` and even `ls ~/Library/Logs/Homebrew`) will just hang for 10 seconds before I cancel it with ctrl+c (though it will hang for hours if left alone). Then I'll get a similar stack trace like @clstaudt and then I'll restart xonsh.

Mostly this happened to me within tmux, but I was also able to reproduce it in a new Terminal.app window without tmux.

**Comment by mltucker** [comment]
@anki-code it's very strange because my `python --version` gives me 3.11.7 and `brew edit xonsh` says it depends on python@3.11. I see that I have both 3.11 and 3.12 installed. I can't uninstall python@3.12 since "it is required by llvm and xonsh, which are currently installed". Is there a way I can tell xonsh which python to use?

**Comment by mltucker** [comment]
@anki-code thanks! I've uninstalled xonsh from homebrew and instead now run it from conda3. I believe I'm seeing the same issue, though now it looks a bit different. Sometimes commands (most recently `git add -p`) will just hang. Ctrl+C closes the tmux window instead of quitting the process and showing the error message that @clstaudt reported above (which I used to also see). I will report back.

**Comment by mltucker** [comment]
@anki-code OK, I reproduced it again and this time recorded my screen. Just for a frame or two the error message popped up. Here's a screenshot:

<img width="614" alt="image" src="https://github.com/xonsh/xonsh/assets/312430/acb126a8-9da1-44eb-b8c3-c1c1d41e0770">

Possibly the reason the message briefly flashed and closed my terminal window is that instead of fixing my path issues, I made a script /usr/local/bin/xonsh with:

```bash
#!/bin/bash

/opt/miniconda3/bin/xonsh $@
```

Here's my xonfig, this time with python 3.11:

```
+------------------+-------------------+
| xonsh            | 0.14.4            |
| Python           | 3.11.7            |
| PLY              | 3.11              |
| have readline    | True              |
| prompt toolkit   | 3.0.42            |
| shell type       | prompt_toolkit    |
| history backend  | json              |
| pygments         | 2.17.2            |
| on posix         | True              |
| on linux         | False             |
| on darwin        | True              |
| on windows       | False             |
| on cygwin        | False             |
| on msys2         | False             |
| is superuser     | False             |
| default encoding | utf-8             |
| xonsh encoding   | utf-8             |
| encoding errors  | surrogateescape   |
| xontrib          | []                |
| RC file 1        | /Users/m/.xonshrc |
+------------------+-------------------+
```
