### ISSUE TITLE
Getting `OSError: [Errno 9] Bad file descriptor` at pretty random operations

### ISSUE THREAD

**Issue by doronz88** [xonsh/xonsh#5241]
Testing environment: macOS Sonoma 14.1.2

After a git checkout, or directory change I very randomly get the following error:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/xonsh/main.py", line 469, in main
    sys.exit(main_xonsh(args))
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/xonsh/main.py", line 513, in main_xonsh
    shell.shell.cmdloop()
  File "/opt/homebrew/lib/python3.11/site-packages/xonsh/ptk_shell/shell.py", line 401, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/xonsh/ptk_shell/shell.py", line 369, in singleline
    line = self.prompter.prompt(**prompt_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1026, in prompt
    return self.app.run(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/application/application.py", line 998, in run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 189, in run
    with Runner(debug=debug) as runner:
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 63, in __exit__
    self.close()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 77, in close
    loop.close()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 91, in close
    self._close_self_pipe()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 99, in _close_self_pipe
    self._ssock.close()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 503, in close
    self._real_close()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 497, in _real_close
    _ss.close(self)
OSError: [Errno 9] Bad file descriptor
Xonsh encountered an issue during launch
Failback to /bin/bash

The default interactive shell is now zsh.

To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$
```

Don't know how to force reproduction of this bug since it occurs very randomly at different times (but pretty often)

**Comment by doronz88** [comment]
I believe this is the only way for now, though popular packages such as IPython do require newer `prompt-toolkit`. I guess the better choice is to add this requirement for the meantime and encourage people to install `xonsh` with `pipx`.

**Comment by gforsyth** [comment]
I'll be at a computer later and can take a look. In the mean time, if someone can PR the upper pin and add a note to the docs that'll make it faster to release.

**Comment by gforsyth** [comment]
Thanks @anki-code -- merged and released 0.15.0.  Going to leave this issue open until we sort out the upstream issue or figure out what part of xonsh is tripping up prompt toolkit

**Comment by doronz88** [comment]
@gforsyth @anki-code this bug persists even after this fix - but much less
now usually the "Bad File Descriptor" exception doesn't mess with the whole shell

**Comment by gnat** [comment]
Possible to just bundle the correct version of `prompt_toolkit` inside the AppImage? Or perhaps fix `xonsh` to work with the newer `prompt_toolkit` ?

This blows up for me with a simple `echo $(ls)` lol.

**Comment by gnat** [comment]
Probably not a viable solution for the AppImage version of xonsh. See:

![image](https://github.com/xonsh/xonsh/assets/24665/de868217-9372-4661-bf14-1961f75148a6)

**Comment by gnat** [comment]
@gforsyth possible to get a tag/release for a new appimage? Thank you!

**Comment by gnat** [comment]
@anki-code No go, sadly, with 0.16 AppImage

<details>

![image](https://github.com/xonsh/xonsh/assets/24665/4b0c1821-b052-423c-ba3f-12c0031074d6)
</details>

**Comment by doronz88** [comment]
Just updated my xonsh shell. I'll update after a period of time elapsed while the bug did not re-occur (or it did)
