### ISSUE TITLE
AppImage seems to be broken

### ISSUE THREAD

**Issue by SF-300** [xonsh/xonsh#5245]
```
@ xonfig
+------------------+---------------------+
| xonsh            | 0.14.3.dev7         |
| Git SHA          | 23c50c21            |
| Commit Date      | Dec 5 10:47:54 2023 |
| Python           | 3.11.6              |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.41              |
| shell type       | prompt_toolkit      |
| history backend  | json                |
| pygments         | 2.17.2              |
| on posix         | True                |
| on linux         | True                |
| distro           | unknown             |
| on wsl           | False               |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
| xontrib          | []                  |
| RC file          | []                  |
+------------------+---------------------+
```
I neither created "~/.xonshrc" nor customized xonsh in any other way.

## Expected Behavior
Input capturing via `$(...)` is supposed to work, according to [the documentation](https://xon.sh/tutorial.html#captured-subprocess-with-and).

## Current Behavior
Xonsh crashes.
(`$[...]` seems to work fine BTW)

### Traceback (if applicable)
```@ $(ls /)
Traceback (most recent call last):
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/xonsh/main.py", line 469, in main
    sys.exit(main_xonsh(args))
             ^^^^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/xonsh/main.py", line 513, in main_xonsh
    shell.shell.cmdloop()
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/xonsh/ptk_shell/shell.py", line 401, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/xonsh/ptk_shell/shell.py", line 369, in singleline
    line = self.prompter.prompt(**prompt_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1026, in prompt
    return self.app.run(
           ^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/prompt_toolkit/application/application.py", line 998, in run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/prompt_toolkit/application/application.py", line 883, in run_async
    return await _run_async(f)
           ^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/prompt_toolkit/application/application.py", line 734, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "/tmp/.mount_xonsh-EZQuBX/opt/python3.11/lib/python3.11/site-packages/prompt_toolkit/input/vt100.py", line 258, in __enter__
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)
termios.error: (5, 'Input/output error')
Xonsh encountered an issue during launch
```
I experience the same issue both with "Ubuntu 22.04.3" (on Vmware VM) and with "CloudLinux 8.8" (on KVM).
I've tested a couple of previous xonsh AppImage versions and all of them behave the same.

## Steps to Reproduce
1. Download 0.14.3 AppImage from "Releases" page
2. Run it
3. Execute `$(ls /)` (or anything which is supposed to capture output)

The issue doesn't manifest if `xonsh --shell-type=readline` is used.
It seems that [a very similar problem](https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1123) was reported to prompt-toolkit a couple of years ago but didn't get any solution.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by SF-300** [comment]
Hey, @anki-code!

I've also tested 0.14.0.dev64 and 0.13.3. They have the same issue.
