### ISSUE TITLE
Parser fail with numerical and logical AND

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5253]
```xsh
xonfig
# xonsh 0.14.3

mkdir -p /tmp/abc /tmp/123 /tmp/a123

cd /tmp/abc && ls
# Result: empty
# Expected: empty


cd /tmp/a123 && ls
# Result: empty
# Expected: empty

# But:

cd /tmp/123 && ls
# Result: NameError: name 'cd' is not defined
# Expected: empty

echo / 123 && ls
# Result: NameError: name 'echo' is not defined
# Expected: `/ 123 ...`
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by JamesParrott** [comment]
I could recreate this in an alpine:edge container:

```
<user>@bf5102635826 / # mkdir -p /tmp/abc /tmp/123 /tmp/a123
<user>@bf5102635826 / # cd /tmp/abc && ls
<user>@bf5102635826 /tmp/abc # cd /tmp/a123 && ls
<user>@bf5102635826 /tmp/a123 # cd /tmp/123 && ls
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
NameError: name 'cd' is not defined
<user>@bf5102635826 /tmp/a123 [1] # echo / 123 && ls
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
NameError: name 'echo' is not defined
```

And with XONSH_SHOW_TRACEBACK = True:

```
<user>@bf5102635826 / # cd /tmp/123 && ls
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cd' is not defined

<user>@bf5102635826 / [1] # echo / 123 && ls
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'echo' is not defined
```

**Comment by JamesParrott** [comment]
I'm new to Xonsh.  But I believe the correct behavious would be to change the `&&` into an and.  
https://xon.sh/tutorial.html#logical-subprocess-and

These errors occur with `||` too.  And when replacing `&&` with `and`, the echo treats the and as an arg, but the cd raises a different error:

```
<user>@bf5102635826 ~ # cd /tmp/123 || ls
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cd' is not defined

<user>@bf5102635826 ~ [1] # echo /tmp/123 || ls
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'echo' is not defined
```

```
<user>@bf5102635826 ~ [1] # echo /tmp/123 and ls
/tmp/123 and
<user>@bf5102635826 ~ # cd /tmp/123 and ls
cd takes 0 or 1 arguments, not 2. An additional `-P` flag can be passed in first position to follow symlinks.
<user>@bf5102635826 ~ [1] #
```

**Comment by PodioSpaz** [comment]
I have only been able to replicate the problem when using fully qualified paths.  No problem with relative paths.

This works...
```
/🔒
❯ cd tmp/123 && ls
```

This works...
```
~
❯ cd ../../tmp/123 && ls
```

This does not...
```
/🔒
❯ cd /tmp/123 && ls
```
