### ISSUE TITLE
Case with endless loop with no way to interrupt

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5304]
Sometimes I'm facing with loops without the way to interrupt it (MacOS):

```xsh
while 1:
    xonsh -c 'date; sleep 1'
# Ctrl-C
# KeyboardInterrupt
# Ctrl-C
# KeyboardInterrupt
# Ctrl-D
# ^D
# Ctrl-C
# KeyboardInterrupt
# ...
# No way to stop it.
```

We need to add the way to stop the execution.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by JamesParrott** [comment]
If this outer loop is run in xonsh, Even if Ctrl+D quits the inner sleep process, the outer while loop will then immediately start another one.

```
while 1:
    xonsh -c 'date; sleep 1'
```

Is this a request to pass an interrupt from a xonsh process, to its calling process? 
https://xon.sh/aliases.html#eof-exit-and-quit

**Comment by JamesParrott** [comment]
I think this functionality might even already exist.  Or at the very least I can't reproduce the failure.  Admittedly it can cause the outer interactive xonsh hang, but I was able to quit the loop in MINGW64 Git Bash on Windows by simply spamming (not holding down) Ctrl+C:

```
@LAPTOP ~ @ while 1:
.........................   xonsh -c 'date; sleep 1'
.........................
Sun, Mar 17, 2024 12:01:35 PM
Sun, Mar 17, 2024 12:01:37 PM
Sun, Mar 17, 2024 12:01:39 PM

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\\.local\bin\xonsh.exe\__main__.py", line 4, in <module>
  File "C:\Users\\.local\pipx\venvs\xonsh\Lib\site-packages\xonsh\main.py", line 2, in <module>
    import argparse
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\argparse.py", line 94, in <module>

    from gettext import gettext as _, ngettext
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1138, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1078, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1612, in find_spec
  File "<frozen importlib._bootstrap_external>", line 147, in _path_stat
KeyboardInterrupt

@LAPTOP-~ @
@LAPTOP-~ @ print(_)


```
