### ISSUE TITLE
$RAISE_SUBPROC_ERROR throws an exception even if a logical OR is used 

### ISSUE THREAD

**Issue by ading2210** [xonsh/xonsh#5311]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.15.1          |
| Python           | 3.11.2          |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| history backend  | json            |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on wsl           | False           |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| xontrib          | []              |
| RC file          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior

In bash, doing `cmd || true` will ignore any errors that the command generates if `set -e` is on. I would expect that the behavior is similar in Xonsh with `$RAISE_SUBPROC_ERROR`, which is the equivalent setting.

For example:
```
user@debian:~$ bash -c "
> set -e
> false || true
> echo "success"
> "
success
```

## Current Behavior

A `subprocess.CalledProcessError` is called if any of the commands in the expression fail.

### Traceback (if applicable)

<details>

```
user@debian ~ @ $RAISE_SUBPROC_ERROR = True
user@debian ~ @ $XONSH_SHOW_TRACEBACK = True
user@debian ~ @ false || true
<xonsh-code>:1:0:6 - false || true
<xonsh-code>:1:0:6 + ![false]
<xonsh-code>:1:8:14 - false || true
<xonsh-code>:1:8:14 + ![true]
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/built_ins.py", line 206, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/procs/specs.py", line 908, in run_subproc
    return _run_specs(specs, cmds)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/procs/specs.py", line 943, in _run_specs
    command.end()
  File "/home/user/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/procs/pipelines.py", line 459, in end
    self._end(tee_output=tee_output)
  File "/home/user/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/procs/pipelines.py", line 478, in _end
    self._raise_subproc_error()
  File "/home/user/.local/pipx/venvs/xonsh/lib/python3.11/site-packages/xonsh/procs/pipelines.py", line 603, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['false']' returned non-zero exit status 1.
```

</details>

## Steps to Reproduce

1. Open xonsh
2. Run `$RAISE_SUBPROC_ERROR = True`
3. Run `false || true`

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by ading2210** [comment]
I'm aware that I can do a try-except block for this, though that still doesn't help with boolean logic being broken with subprocess return codes.

**Comment by zhuoqun-chen** [comment]
Thx @anki-code! I would love to try this package!
