### ISSUE TITLE
unthreadable(?) aliases hang when piped from or to

### ISSUE THREAD

**Issue by Qyriad** [xonsh/xonsh#5317]
I'm not totally clear on the trigger conditions here, but the xonsh built-in commands that are unthreadable (xonfig, source, trace, fg) hang when piped to or from. However callable aliases that I've defined with `@xonsh.tools.unthreadable` *don't* seem to hang, so I'm not quite sure what's going on. Some builtins that don't hang include disown, which, source-foreign, showcmd, and bg.

Neither `--no-rc` nor `$THREAD_SUBPROCS` affect this behavior.

## xonfig

<details>
```
$ xonfig
+------------------+-----------------------------------+
| xonsh            | 0.15.1                            |
| Git SHA          | da7add7b                          |
| Commit Date      | Dec 12 19:30:59 2023              |
| Python           | 3.11.8                            |
| PLY              | 3.11                              |
| have readline    | True                              |
| prompt toolkit   | 3.0.41                            |
| shell type       | prompt_toolkit                    |
| history backend  | json                              |
| pygments         | 2.17.2                            |
| on posix         | True                              |
| on linux         | True                              |
| distro           | unknown                           |
| on wsl           | False                             |
| on darwin        | False                             |
| on windows       | False                             |
| on cygwin        | False                             |
| on msys2         | False                             |
| is superuser     | False                             |
| default encoding | utf-8                             |
| xonsh encoding   | utf-8                             |
| encoding errors  | surrogateescape                   |
| xontrib          | []                                |
| RC file 1        | /etc/xonsh/xonshrc                |
| RC file 2        | /home/qyriad/.config/xonsh/rc.xsh |
+------------------+-----------------------------------+
```

</details>

## Expected Behavior

Commands like `echo foo | source` or `trace --help | rg .` should not hang.

## Current Behavior & Reproduction

In a checkout of the latest commit:
```bash
[qyriad@Yuki:~/code/builds/xonsh]$ env XONSH_DEBUG=1 python -m xonsh --no-rc -c 'echo foo | source'
<string>:1:5 - echo foo | source
<string>:1:5 + ![echo foo | source]
```

(Reproduces interactively or non-interactively).

### Traceback

From within the shell, Ctrl-C does nothing, but if executed non-interactively as above, CtrlC produces the following traceback:

<details>

```
[qyriad@Yuki:~/code/builds/xonsh]$ env XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=1 python -m xonsh --no-rc -c 'echo foo | source'
<string>:1:5 - echo foo | source
<string>:1:5 + ![echo foo | source]
^Cxonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/qyriad/code/builds/xonsh/xonsh/jobs.py", line 270, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ChildProcessError: [Errno 10] No child processes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/qyriad/code/builds/xonsh/xonsh/built_ins.py", line 206, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qyriad/code/builds/xonsh/xonsh/procs/specs.py", line 910, in run_subproc
    return _run_specs(specs, cmds)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qyriad/code/builds/xonsh/xonsh/procs/specs.py", line 943, in _run_specs
    command.end()
  File "/home/qyriad/code/builds/xonsh/xonsh/procs/pipelines.py", line 459, in end
    self._end(tee_output=tee_output)
  File "/home/qyriad/code/builds/xonsh/xonsh/procs/pipelines.py", line 467, in _end
    for _ in self.tee_stdout():
  File "/home/qyriad/code/builds/xonsh/xonsh/procs/pipelines.py", line 369, in tee_stdout
    for line in self.iterraw():
  File "/home/qyriad/code/builds/xonsh/xonsh/procs/pipelines.py", line 254, in iterraw
    task = xj.wait_for_active_job()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qyriad/code/builds/xonsh/xonsh/jobs.py", line 275, in wait_for_active_job
    return _safe_wait_for_active_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qyriad/code/builds/xonsh/xonsh/jobs.py", line 296, in _safe_wait_for_active_job
    rtn = wait_for_active_job(
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/qyriad/code/builds/xonsh/xonsh/jobs.py", line 263, in wait_for_active_job
    active_task = get_next_task()
                  ^^^^^^^^^^^^^^^
  File "/home/qyriad/code/builds/xonsh/xonsh/jobs.py", line 308, in get_next_task
    _clear_dead_jobs()
  File "/home/qyriad/code/builds/xonsh/xonsh/jobs.py", line None, in _clear_dead_jobs
KeyboardInterrupt
```

</details>

---

Any suggestions on places to start digging for this one?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Qyriad** [comment]
I would presume this is also the same root issue as #2854, #5296, #5270, #5150, and #4884

**Comment by gforsyth** [comment]
> @gforsyth could you please comment why the aliases were marked as unthreadable? If you know or you can guess.

Well outside of memory, I'm afraid.  But if they are working now with `threadable=True` we might as well change them.

I suspect some part of `ArgParserAlias` class is causing an issue here -- `echo foo | source` hanging is a bigger issue and also a more confusing one.

**Comment by gforsyth** [comment]
I would not call this a "good first issue" -- it's very deep in the internals.

**Comment by jnoortheen** [comment]
> I suspect some part of `ArgParserAlias` class is causing an issue here -- `echo foo | source` hanging is a bigger issue and also a more confusing one.

Yes that could be an issue. Especially how it keeps hold of stdin/stdout variables passed to it.

**Comment by anki-code** [comment]
From the top of my current understanding: piping from unthredable callable aliases is not supported.

The `ProcProxy` that is used to run unthredable aliases has no support for pipes.
In the nutshell the `wait()` function (with execution of alias body) will never executed in pipe.
And also there is endless loop between setting `spec` attr and waiting for spec inside `wait()`.
All of this just tell me that ProcProxy never tested in pipes.


PS: 

I've made xonsh-developer-toolkit where you can find [callias.xsh](https://github.com/anki-code/xonsh-developer-toolkit/blob/main/callias.xsh) with different types of callable aliases.

Playing with them and with [operators](https://github.com/anki-code/xonsh-cheatsheet/blob/main/README.md#operators) and with piping (e.g. `!(ca-th)`) gives complete understanding how capturing is working now in all kinds of cases.

Using this you can find failing cases. Please do not bomb issue tracker with "I see error" reports. It will be super cool if every error you see will be traced and will be formed the good logic of how this should work and why and after this the issues is very welcome.

---

I also found pretty interesting case with asking input:

```xsh
@aliases.register("mysudo")
def _mysudo():
    input("Password:")
    echo 123

mysudo | grep 1
```

I expect the behavior like `$(sudo -k echo 123 | grep 1)` where you can enter the password and then got captured `123`. But it's not working. Tracing this in IDE is very interesting.

**Comment by Qyriad** [comment]
Note for searchers: [return-command aliases](https://xon.sh/tutorial.html#alias-to-modify-command) (added in #5473) support piping and may work for your use case.

**Comment by anki-code** [comment]
The shortest workaround is to try to switch command to [`@thread`](https://xon.sh/aliases.html#thread-and-unthread)([doc](https://xon.sh/tutorial.html#threading)) e.g.
```xsh
xontrib | grep core
# Hanging (until #6165)

@thread xontrib | grep core
# coreutils  not-loaded

@thread xonfig | grep xonsh
# | xonsh                       | 0.22.8               |
# | xonsh encoding              | utf-8                |

```
