### ISSUE TITLE
`trace` without arguments raises exception

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5373]
```xsh
trace
Exception in {'cls': 'ProcProxy', 'name': None, 'func': 'trace', 'alias': 'trace', 'pid': 68079}
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/procs/proxies.py", line 842, in wait
    r = self.f(self.args, stdin, stdout, stderr, spec, spec.stack)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/procs/proxies.py", line 319, in proxy_five
    return f(args, stdin, stdout, stderr, spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/aliases.py", line 786, in trace
    return tracermain(args, stdin=stdin, stdout=stdout, stderr=stderr, spec=spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/tracer.py", line 231, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/cli_utils.py", line 649, in __call__
    result = dispatch(
             ^^^^^^^^^
  File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/cli_utils.py", line 413, in dispatch
    func = ns[_FUNC_NAME]
           ~~^^^^^^^^^^^^
KeyError: '_func_'
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
This is caused by a recent regression. The commits in https://github.dev/xonsh/xonsh/tree/main are getting committed directly.
