### ISSUE TITLE
Bug: `xthread` not found

### ISSUE THREAD

**Issue by cvoges12** [xonsh/xonsh#5522]
## Current Behavior

```console
$ xthread
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: 'xthread'
xthread: command not found
```

<detail>
```
<xonsh-code>:1:0 - xthread
<xonsh-code>:1:0 + ![xthread]
TRACE SUBPROC: (['xthread'],), captured=hiddenobject
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/nix/store/w3jmcy5z80zamcbjp3x2wx101f3p8a0n-python3-3.11.9-env/lib/python3.11/site-packages/xonsh/procs/specs.py", line 474, in _run_binary
    p = self.cls(cmd, bufsize=bufsize, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xthread'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/w3jmcy5z80zamcbjp3x2wx101f3p8a0n-python3-3.11.9-env/lib/python3.11/site-packages/xonsh/procs/pipelines.py", line 167, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/w3jmcy5z80zamcbjp3x2wx101f3p8a0n-python3-3.11.9-env/lib/python3.11/site-packages/xonsh/procs/specs.py", line 456, in run
    p = self._run_binary(kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/w3jmcy5z80zamcbjp3x2wx101f3p8a0n-python3-3.11.9-env/lib/python3.11/site-packages/xonsh/procs/specs.py", line 493, in _run_binary
    raise xt.XonshError(e) from ex
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: 'xthread'
xthread: command not found

TRACE SUBPROC: (['/etc/profiles/per-user/midirhee12/bin/starship', 'prompt', '--status=1', '--jobs=0', '--cmd-duration=89'],), captured=stdout
TRACE SUBPROC: (['/etc/profiles/per-user/midirhee12/bin/starship', 'prompt', '--status=1', '--jobs=0', '--cmd-duration=89', '--right'],), captured=stdout
```
</detail>

## Expected Behavior

For `xthread` to be found and ran.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by cvoges12** [comment]
Ah, okay. I'm on `0.15.1`. So that explains.
