### ISSUE TITLE
Playwright refuses to work without using with statements.

### ISSUE THREAD

**Issue by brokedarius** [xonsh/xonsh#5532]
![2024-06-24_05-46_1](https://github.com/xonsh/xonsh/assets/95202445/ca351ee0-fa5c-448d-b803-a88e33df1f6a)
![2024-06-24_05-51](https://github.com/xonsh/xonsh/assets/95202445/42911a53-1276-4fd8-b3af-d7e28c896283)

Current Behavior:

As you can see starting playwright from the classic python shell works fine but not in xonsh.

Traceback (if applicable):

(Included in pictures as well)

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Scripts\xonsh.exe\__main__.py", line 7, in <module>
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\main.py", line 472, in main
    _failback_to_other_shells(args, err)
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\main.py", line 441, in _failback_to_other_shells
    raise err
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\main.py", line 470, in main
    sys.exit(main_xonsh(args))
             ^^^^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\main.py", line 514, in main_xonsh
    shell.shell.cmdloop()
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\ptk_shell\shell.py", line 406, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\xonsh\ptk_shell\shell.py", line 374, in singleline
    line = self.prompter.prompt(**prompt_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1034, in prompt
    return self.app.run(
           ^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\prompt_toolkit\application\application.py", line 978, in run
    return loop.run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 629, in run_until_complete
    self._check_running()
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 588, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
sys:1: RuntimeWarning: coroutine 'Application.run_async' was never awaited

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

Expected Behavior:
Should work just like in the python shell.

xonfig:

```
+------------------+---------------------+
| xonsh            | 0.16.0              |
| Python           | 3.11.5              |
| PLY              | 3.11                |
| have readline    | False               |
| prompt toolkit   | 3.0.36              |
| shell type       | prompt_toolkit      |
| history backend  | sqlite              |
| pygments         | 2.17.2              |
| on posix         | False               |
| on linux         | False               |
| on darwin        | False               |
| on windows       | True                |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | True                |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
| xontrib          | []                  |
| RC file 1        | C:\Users\-/.xonshrc |
+------------------+---------------------+
```

**Comment by brokedarius** [comment]
Alright I will do so and let you know in a few.

**Comment by brokedarius** [comment]
I tried with the lastest version of xonsh and the prompt toolkit, I still get the same traceback as seen previously.

 ` xonsh --no-rc -st readline` like this it works but there are 2 issues: 

I lose my command history and settings not only that but pyreadline which serves as replacement for readline on windows is not working out of the box, one has to bring changes regarding collections vs collections.abc in order to make it work with python 3 which in my humble opinion could be a lot to ask from certain users who may just want to use xonsh casually.

The last possible fix by importing asyncio is not working either, here is the traceback for that one:

```
[-@-:~/Desktop─[2024-06-29]─[06:47:41]──> import asyncio
[-@-:~/Desktop─[2024-06-29]─[06:48:18]──> loop = asyncio.get_event_loop()
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 677, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

**Comment by brokedarius** [comment]
Ok you made me realize something with that asyncio stuff: I managed to fix it by installing nest_syncio and adding these 2 lines to my xonshrc ```import nest_asyncio 
nest_asyncio.apply()``` let me know if I should not do this but it seems alright?
