### ISSUE TITLE
Warnings and Exceptions on Python 3.13

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#5537]
## Current Behavior

Running xonsh under Python 3.13 emits a number of warnings and errors:

<details>

```xsh
 @ docker run -it jaraco/multipy-tox
/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/ast.py:145: DeprecationWarning: Constant.__init__ got an unexpected keyword argument 'is_raw'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  return Constant(value=s, kind="str", **kwargs)
/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:3050: DeprecationWarning: comprehension.__init__ missing 1 required positional argument: 'is_async'. This will become an error in Python 3.15.
  comp = ast.comprehension(target=targ, iter=it, ifs=[])
/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:1378: DeprecationWarning: Delete.__init__ got an unexpected keyword argument 'ctx'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  p0 = ast.Delete(
/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/ast.py:145: DeprecationWarning: Constant.__init__ got an unexpected keyword argument 'is_raw'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  return Constant(value=s, kind="str", **kwargs)
Exception ignored in: <_io.TextIOWrapper name=4 encoding='utf-8'>
Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1039, in _bootstrap_inner
    self.run()
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <_io.TextIOWrapper name=6 encoding='utf-8'>
Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1039, in _bootstrap_inner
    self.run()
OSError: [Errno 9] Bad file descriptor
  @# $XONSH_SHOW_TRACEBACK=1
  @# $XONSH_TRACE_SUBPROC=2
  @# $XONSH_DEBUG=1
  @# xonsh<xonsh-code>:1:0 - xonsh
<xonsh-code>:1:0 + ![xonsh]
  @# xonsh
<xonsh-code>:1:0 - xonsh
<xonsh-code>:1:0 + ![xonsh]
Trace run_subproc({'cmds': (['xonsh'],), 'captured': 'hiddenobject'})
0: {'cmd': ['xonsh'], 'cls': 'subprocess.Popen', 'binary_loc': '/root/.local/bin/xonsh', 'threadable': False, 'background': False}
loading xontrib 'jaraco.xonsh'
/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/ast.py:145: DeprecationWarning: Constant.__init__ got an unexpected keyword argument 'is_raw'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  return Constant(value=s, kind="str", **kwargs)
<stdin>:37:29 -         source-bash --seterrprevcmd "" /etc/profile
<stdin>:37:29 +         ![source-bash --seterrprevcmd "" /etc/profile]
<stdin>:41:13 -         source-bash @(profile)
<stdin>:41:13 +         ![source-bash @(profile)]
<stdin>:47:8 -  source @(localf)
<stdin>:47:8 +  ![source @(localf)]
<stdin>:55:5 -  git rm .hg*
<stdin>:55:5 +  ![git rm .hg*]
<stdin>:56:5 -  git commit -m "Remove Mercurial metadata"
<stdin>:56:5 +  ![git commit -m "Remove Mercurial metadata"]
<stdin>:66:5 -  git push --set-upstream origin @(head)
<stdin>:66:5 +  ![git push --set-upstream origin @(head)]
/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:3050: DeprecationWarning: comprehension.__init__ missing 1 required positional argument: 'is_async'. This will become an error in Python 3.15.
  comp = ast.comprehension(target=targ, iter=it, ifs=[])
<stdin>:78:6 -          git branch -d @(branch)
<stdin>:78:6 +          ![git branch -d @(branch)]
<stdin>:154:8 -         travis env copy -r @(get_repo_url()) TWINE_PASSWORD
<stdin>:154:8 +         ![travis env copy -r @(get_repo_url()) TWINE_PASSWORD]
<stdin>:164:8 -         travis env copy -r @(get_repo_url()) TIDELIFT_TOKEN
<stdin>:164:8 +         ![travis env copy -r @(get_repo_url()) TIDELIFT_TOKEN]
<stdin>:174:9 -         keyring get https://id.docker.com $USER | docker login --password-stdin --username $USER
<stdin>:174:9 +         ![keyring get https://id.docker.com $USER | docker login --password-stdin --username $USER]
<stdin>:200:10 -        mkdir -p @(name)
<stdin>:200:10 +        ![mkdir -p @(name)]
<stdin>:201:4 -         cd @(name)
<stdin>:201:4 +         ![cd @(name)]
<stdin>:205:8 - xontrib load vox
<stdin>:205:8 + ![xontrib load vox]
<stdin>:255:4 -         az devops project delete --yes --id @(id)
<stdin>:255:4 +         ![az devops project delete --yes --id @(id)]
<stdin>:266:6 -         http delete https://ci.appveyor.com/api/projects/$USER/@(id) 'Content-Type: application/json' Authorization:@(auth)
<stdin>:266:6 +         ![http delete https://ci.appveyor.com/api/projects/$USER/@(id) 'Content-Type: application/json' Authorization:@(auth)]
<stdin>:277:5 -                 gh api -X PATCH /repos/@(repo)/pulls/@(pr_num) -F base=main
<stdin>:277:5 +                 ![gh api -X PATCH /repos/@(repo)/pulls/@(pr_num) -F base=main]
<stdin>:288:6 -         http patch https://readthedocs.org/api/v3/projects/@(rtd_name)/ Authorization:@(auth) default_branch=main
<stdin>:288:6 +         ![http patch https://readthedocs.org/api/v3/projects/@(rtd_name)/ Authorization:@(auth) default_branch=main]
<stdin>:298:6 -         http https://readthedocs.org/api/v3/projects/ Authorization:@(auth) f'repository[url]={url}' 'repository[type]=git' name=@(name)
<stdin>:298:6 +         ![http https://readthedocs.org/api/v3/projects/ Authorization:@(auth) f'repository[url]={url}' 'repository[type]=git' name=@(name)]
<stdin>:305:5 -         git checkout master
<stdin>:305:5 +         ![git checkout master]
<stdin>:306:5 -         git pull
<stdin>:306:5 +         ![git pull]
<stdin>:307:5 -         git checkout -b main
<stdin>:307:5 +         ![git checkout -b main]
<stdin>:312:4 -         gh api -X PATCH /repos/@(repo) -F default_branch=main
<stdin>:312:4 +         ![gh api -X PATCH /repos/@(repo) -F default_branch=main]
<stdin>:313:5 -         git push origin :master
<stdin>:313:5 +         ![git push origin :master]
<stdin>:314:5 -         git branch -d master
<stdin>:314:5 +         ![git branch -d master]
<stdin>:317:5 -         git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
<stdin>:317:5 +         ![git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main]
<stdin>:323:7 -         pushd ~/p/windows-docker-machine
<stdin>:323:7 +         ![pushd ~/p/windows-docker-machine]
<stdin>:324:9 -         vagrant up 2019-box
<stdin>:324:9 +         ![vagrant up 2019-box]
<stdin>:331:7 -         pushd ~/p/windows-docker-machine
<stdin>:331:7 +         ![pushd ~/p/windows-docker-machine]
<stdin>:332:9 -         vagrant halt 2019-box
<stdin>:332:9 +         ![vagrant halt 2019-box]
/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:1378: DeprecationWarning: Delete.__init__ got an unexpected keyword argument 'ctx'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  p0 = ast.Delete(
<stdin>:346:6 -         sudo mkdir @(mount)
<stdin>:346:6 +         ![sudo mkdir @(mount)]
<stdin>:347:6 -         sudo chown $USER @(mount)
<stdin>:347:6 +         ![sudo chown $USER @(mount)]
<stdin>:350:16 -        mount_smbfs -o quarantine @(url) @(mount)
<stdin>:350:16 +        ![mount_smbfs -o quarantine @(url) @(mount)]
<stdin>:360:15 -        http -q -f -a @(auth) @(url) From=@(from_) To=@(to) Body=@(message)
<stdin>:360:15 +        ![http -q -f -a @(auth) @(url) From=@(from_) To=@(to) Body=@(message)]
<stdin>:369:5 -         git config @(key)
<stdin>:369:5 +         ![git config @(key)]
<stdin>:375:7 -         mongo mongodb.jaraco.com/admin -u jaraco -p @($(keyring get mongodb.jaraco.com/admin jaraco).strip())
<stdin>:375:7 +         ![mongo mongodb.jaraco.com/admin -u jaraco -p @($(keyring get mongodb.jaraco.com/admin jaraco).strip())]
<stdin>:384:29 -        rsync -rt --progress --info progress2 /Volumes/MEGAMI/TeslaCam tanuki.local:/shares/archive
<stdin>:384:29 +        ![rsync -rt --progress --info progress2 /Volumes/MEGAMI/TeslaCam tanuki.local:/shares/archive]
<stdin>:386:33 -                rm -r /Volumes/MEGAMI/TeslaCam/*
<stdin>:386:33 +                ![rm -r /Volumes/MEGAMI/TeslaCam/*]
<stdin>:411:4 -         cd @(by_len[0])
<stdin>:411:4 +         ![cd @(by_len[0])]
<stdin>:433:11 -        towncrier create -c @(descr.strip().rstrip('.') + '.') @(number).@(type).rst
<stdin>:433:11 +        ![towncrier create -c @(descr.strip().rstrip('.') + '.') @(number).@(type).rst]
<stdin>:434:5 -         git add newsfragments
<stdin>:434:5 +         ![git add newsfragments]
<stdin>:435:5 -         git commit --amend --no-edit
<stdin>:435:5 +         ![git commit --amend --no-edit]
<stdin>:447:6 -         http https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent x-goog-api-key:@(keyring.get_password('https://generativelanguage.googleapis.com/', 'jaraco@jaraco.com')) contents[0][role]=user f'contents[0][parts][][text]={prompt}' | jq -r .candidates[0].content.parts[0].text
<stdin>:447:6 +         ![http https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent x-goog-api-key:@(keyring.get_password('https://generativelanguage.googleapis.com/', 'jaraco@jaraco.com')) contents[0][role]=user f'contents[0][parts][][text]={prompt}' | jq -r .candidates[0].content.parts[0].text]
<xonsh-code>:308:0:2 -  gpo
<xonsh-code>:308:0:2 + ![gpo]
<xonsh-code>:325:0:2 -  popd
<xonsh-code>:325:0:2 + ![popd]
<xonsh-code>:333:0:2 -  popd
<xonsh-code>:333:0:2 + ![popd]
<stdin>:1:4 - git rev-parse --short HEAD
<stdin>:1:4 + ![git rev-parse --short HEAD]
<stdin>:1:4 - git commit -a -m '👹 Feed the hobgoblins (delint).'
<stdin>:1:4 + ![git commit -a -m '👹 Feed the hobgoblins (delint).']
<stdin>:1:4 - git commit -a -m '⚫ Fade to black.'
<stdin>:1:4 + ![git commit -a -m '⚫ Fade to black.']
<stdin>:1:4 - git commit -a -m '🧎‍♀️ Genuflect to the types.'
<stdin>:1:4 + ![git commit -a -m '🧎‍♀️ Genuflect to the types.']
<stdin>:1:4 - git commit -a -m '🚡 Toil the docs.'
<stdin>:1:4 + ![git commit -a -m '🚡 Toil the docs.']
<stdin>:1:8 - pip-run jaraco.home -- -m jaraco.home.check-traps
<stdin>:1:8 + ![pip-run jaraco.home -- -m jaraco.home.check-traps]
<stdin>:1:4 - git commit -a --amend --no-edit
<stdin>:1:4 + ![git commit -a --amend --no-edit]
<xonsh-code>:1:0 - pbcopy
<xonsh-code>:1:0 + ![pbcopy]
<xonsh-code>:1:0 - pbpaste
<xonsh-code>:1:0 + ![pbpaste]
Trace run_subproc({'cmds': (['xontrib', 'load', 'vox'],), 'captured': 'hiddenobject'})
0: {'cmd': ['xontrib', 'load', 'vox'], 'cls': 'xonsh.procs.proxies.ProcProxy', 'alias_name': 'xontrib', 'threadable': False, 'background': False}
<stdin>:1:7 - drutil eject
<stdin>:1:7 + ![drutil eject]
<stdin>:1:11 - open -n -a Firefox.app --args --no-remote --profile "~/Dropbox/AppData/Firefox/Profiles/8uzbw0yb.Liam"
<stdin>:1:11 + ![open -n -a Firefox.app --args --no-remote --profile "~/Dropbox/AppData/Firefox/Profiles/8uzbw0yb.Liam"]
/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/ast.py:145: DeprecationWarning: Constant.__init__ got an unexpected keyword argument 'is_raw'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  return Constant(value=s, kind="str", **kwargs)
Trace run_subproc({'cmds': (['which', 'brew'],), 'captured': 'object'})
0: {'cmd': ['which', 'brew'], 'cls': 'xonsh.procs.proxies.ProcProxyThread', 'alias_name': 'which', 'threadable': True, 'background': False}
Exception ignored in: <_io.TextIOWrapper name=4 encoding='utf-8'>
Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1039, in _bootstrap_inner
    self.run()
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <_io.TextIOWrapper name=6 encoding='utf-8'>
Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1039, in _bootstrap_inner
    self.run()
OSError: [Errno 9] Bad file descriptor
<stdin>:1:9 - open -na "PyCharm.app"
<stdin>:1:9 + ![open -na "PyCharm.app"]
```

</details>

These errors can be seen by running the following docker image, whose [source is here](https://github.com/jaraco/multipy-tox/blob/3526a8bfe83ad206b20398c2f142372705c5e28e/Dockerfile):

```
docker pull jaraco/multipy-tox@sha256:a8266f1bc72d4a89a34efaf719c95f521ea89664c01200bffcb16214516a3cd6
docker run -it jaraco/multipy-tox
```

If I uninstall [jaraco.xonsh](/jaraco/jaraco.xonsh) from the environment (which includes my personal shell config), the errors and warnings go away:

```xsh
  @# pipx runpip xonsh uninstall -y jaraco.xonsh<stdin>:1:5 - pipx runpip xonsh uninstall -y jaraco.xonsh
<stdin>:1:5 + ![pipx runpip xonsh uninstall -y jaraco.xonsh]
  @# pipx runpip xonsh uninstall -y jaraco.xonsh
<stdin>:1:5 - pipx runpip xonsh uninstall -y jaraco.xonsh
<stdin>:1:5 + ![pipx runpip xonsh uninstall -y jaraco.xonsh]
Trace run_subproc({'cmds': (['pipx', 'runpip', 'xonsh', 'uninstall', '-y', 'jaraco.xonsh'],), 'captured': 'hiddenobject'})
0: {'cmd': ['pipx', 'runpip', 'xonsh', 'uninstall', '-y', 'jaraco.xonsh'], 'cls': 'subprocess.Popen', 'binary_loc': '/usr/local/bin/pipx', 'threadable': False, 'background': False}
Found existing installation: jaraco.xonsh 0.7.0
Uninstalling jaraco.xonsh-0.7.0:
  Successfully uninstalled jaraco.xonsh-0.7.0
  @# xonsh<xonsh-code>:1:0 - xonsh
<xonsh-code>:1:0 + ![xonsh]
  @# xonsh
<xonsh-code>:1:0 - xonsh
<xonsh-code>:1:0 + ![xonsh]
Trace run_subproc({'cmds': (['xonsh'],), 'captured': 'hiddenobject'})
0: {'cmd': ['xonsh'], 'cls': 'subprocess.Popen', 'binary_loc': '/root/.local/bin/xonsh', 'threadable': False, 'background': False}

                                                        Welcome to the xonsh shell 0.17.0                                                         

                                       ~ Nice indeed. Everything's accounted for, except your old shell. ~                                        

--------------------------------------------------------------------------------------------------------------------------------------------------

                                  Create ~/.xonshrc file manually or use xonfig to suppress the welcome message                                   

Start from commands:
  xonfig web         # Run the configuration tool in the browser to create ~/.xonshrc 
  xonfig tutorial    # Open the xonsh tutorial in the browser

--------------------------------------------------------------------------------------------------------------------------------------------------

root@9eb32f1b5cc9 / @#
```

If I exit that subshell, then `touch ~/.xonshrc` to suppress the welcome message, I encounter yet another error updating the cache:

```
  @# touch ~/.xonshrc<stdin>:1:6 - touch ~/.xonshrc
<stdin>:1:6 + ![touch ~/.xonshrc]
  @# touch ~/.xonshrc
<stdin>:1:6 - touch ~/.xonshrc
<stdin>:1:6 + ![touch ~/.xonshrc]
Trace run_subproc({'cmds': (['touch', '/root/.xonshrc'],), 'captured': 'hiddenobject'})
0: {'cmd': ['touch', '/root/.xonshrc'], 'cls': 'subprocess.Popen', 'binary_loc': '/usr/bin/touch', 'threadable': False, 'background': False}
  @# xonsh<xonsh-code>:1:0 - xonsh
<xonsh-code>:1:0 + ![xonsh]
  @# xonsh
<xonsh-code>:1:0 - xonsh
<xonsh-code>:1:0 + ![xonsh]
Trace run_subproc({'cmds': (['xonsh'],), 'captured': 'hiddenobject'})
0: {'cmd': ['xonsh'], 'cls': 'subprocess.Popen', 'binary_loc': '/root/.local/bin/xonsh', 'threadable': False, 'background': False}
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
  File "/root/.local/bin/xonsh", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/main.py", line 501, in main
    args = premain(argv)
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/main.py", line 443, in premain
    start_services(shell_kwargs, args, pre_env=pre_env)
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/main.py", line 374, in start_services
    _load_rc_files(shell_kwargs, args, env, execer, ctx)
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/main.py", line 329, in _load_rc_files
    XSH.rc_files = xonshrc_context(
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/environ.py", line 2553, in xonshrc_context
    status = xonsh_script_run_control(
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/environ.py", line 2614, in xonsh_script_run_control
    exc_info = run_script_with_cache(filename, execer, ctx)
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/codecache.py", line 178, in run_script_with_cache
    update_cache(ccode, cachefname)
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/codecache.py", line 100, in update_cache
    print_warning(
  File "/root/.local/share/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/tools.py", line 1013, in print_warning
    traceback.print_stack()
update_cache: Cache file is not writable: /root/.local/share/xonsh/xonsh_script_cache/root/_.xonshrc.cpython-313
Set $XONSH_CACHE_SCRIPTS=0, $XONSH_CACHE_EVERYTHING=0 to disable cache.
```

## Expected Behavior

Execution is clean as on Python 3.12.

## xonfig

<details>

```xsh
+-----------------------------+----------------------+
| xonsh                       | 0.17.0               |
| Git SHA                     | 5332d755             |
| Commit Date                 | Jun 18 08:47:50 2024 |
| Python                      | 3.13.0               |
| PLY                         | 3.11                 |
| have readline               | True                 |
| prompt toolkit              | 3.0.47               |
| shell type                  | prompt_toolkit       |
| history backend             | json                 |
| pygments                    | 2.18.0               |
| on posix                    | True                 |
| on linux                    | True                 |
| distro                      | ubuntu               |
| on wsl                      | False                |
| on darwin                   | False                |
| on windows                  | False                |
| on cygwin                   | False                |
| on msys2                    | False                |
| is superuser                | True                 |
| default encoding            | utf-8                |
| xonsh encoding              | utf-8                |
| encoding errors             | surrogateescape      |
| xontrib 1                   | vox                  |
| xontrib 2                   | voxapi               |
| xontrib 3                   | jaraco.xonsh         |
| RC file                     | []                   |
| UPDATE_OS_ENVIRON           | False                |
| XONSH_CAPTURE_ALWAYS        | False                |
| XONSH_SUBPROC_OUTPUT_FORMAT | stream_lines         |
| THREAD_SUBPROCS             | True                 |
| XONSH_CACHE_SCRIPTS         | True                 |
+-----------------------------+----------------------+
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
1. I can't reproduce this on beta xonsh 0.23.0.

2. I read this issue as "I have something! Read my shitty TRACE!". Please do not use TRACE or DEBUG they have no useful info but they flood the real output. Using $XONSH_SHOW_TRACEBACK is enough in most cases.

3. Next time please tell us clear: what you're doing, what you get, how to reproduce this.
