### ISSUE TITLE
Xonsh auto-complete on Windows searches for `file.exe`

### ISSUE THREAD

**Issue by doronz88** [xonsh/xonsh#5683]
## Current Behavior

When trying to initiate auto-complete on windows platforms, xonsh throws the following exception:

<details>

```xsh
Traceback (most recent call last):
  File "C:\Users\doron\dev\xonsh\xonsh\procs\specs.py", line 530, in _run_binary
    p = self.cls(cmd, bufsize=bufsize, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doron\dev\xonsh\xonsh\procs\posix.py", line 99, in __init__
    self.proc = proc = subprocess.Popen(
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\doron\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\doron\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\doron\dev\xonsh\xonsh\procs\pipelines.py", line 177, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doron\dev\xonsh\xonsh\procs\specs.py", line 512, in run
    p = self._run_binary(kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doron\dev\xonsh\xonsh\procs\specs.py", line 557, in _run_binary
    raise xt.XonshError(e) from ex
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: 'file'
Did you mean the following?
    time:  Alias
```

</details>

The completions do eventually show, but with this exception.

## Expected Behavior

Autocomplete as normal, without trying to exec `file.exe` when it does not exist in PATH.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Found the bug. It's actually in xontrib-argcomplete:

```python
Traceback (most recent call last):
  File "C:\Users\doron\dev\xonsh\xonsh\completer.py", line 193, in generate_completions
    out = func(*old_completer_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doron\pipx\venvs\xonsh\Lib\site-packages\xontrib\argcomplete.py", line 66, in _xontrib_argcomplete_completer
    file_type = _get_subproc_output(['file', '--mime-type', '--brief', file], debug).strip()
```

**Comment by doronz88** [comment]
https://github.com/anki-code/xontrib-argcomplete/issues/11
