### ISSUE TITLE
`xonsh` crashes on startup on Mac OS when installed with `uv` because of `readline`

### ISSUE THREAD

**Issue by ilyagr** [xonsh/xonsh#5693]
This likely has to do with the special Python distributions that `rye` and `uv` use, 
see e.g. https://rye.astral.sh/guide/toolchains/cpython/ . `xonsh` fails to realize
it's supposed to use `libedit`, which is (supposedly) installed on that Python.

## Current Behavior

```console
$ uname -a
Darwin macaw.local 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:52 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6020 arm64 arm Darwin
$ uv tool install xonsh --python-preference only-managed  # --python-preference to make reproduction more reliable, this often happens by default
Resolved 1 package in 74ms
Installed 1 package in 10ms
 + xonsh==0.18.3
Installed 4 executables: xonsh, xonsh-cat, xonsh-uname, xonsh-uptime
$ xonsh
Traceback (most recent call last):
  File "/Users/ilyagr/.local/share/uv/tools/xonsh/lib/python3.12/site-packages/xonsh/main.py", line 511, in main
    args = premain(argv)
           ^^^^^^^^^^^^^
  File "/Users/ilyagr/.local/share/uv/tools/xonsh/lib/python3.12/site-packages/xonsh/main.py", line 452, in premain
    start_services(shell_kwargs, args, pre_env=pre_env)
  File "/Users/ilyagr/.local/share/uv/tools/xonsh/lib/python3.12/site-packages/xonsh/main.py", line 379, in start_services
    XSH.shell = Shell(execer=execer, **shell_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyagr/.local/share/uv/tools/xonsh/lib/python3.12/site-packages/xonsh/shell.py", line 263, in __init__
    self.shell = self.construct_shell_cls(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyagr/.local/share/uv/tools/xonsh/lib/python3.12/site-packages/xonsh/shell.py", line 225, in construct_shell_cls
    return cls(**kwargs)
           ^^^^^^^^^^^^^
  File "/Users/ilyagr/.local/share/uv/tools/xonsh/lib/python3.12/site-packages/xonsh/shells/readline_shell.py", line 336, in __init__
    setup_readline()
  File "/Users/ilyagr/.local/share/uv/tools/xonsh/lib/python3.12/site-packages/xonsh/shells/readline_shell.py", line 99, in setup_readline
    if (not ON_CYGWIN) and (not ON_MSYS) and (not readline.__file__.endswith(".py")):
                                                  ^^^^^^^^^^^^^^^^^
AttributeError: module 'readline' has no attribute '__file__'. Did you mean: '__name__'?
Xonsh encountered an issue during launch.
Please report to https://github.com/xonsh/xonsh/issues
Failback to /bin/dash
$ ^D
```

## Workaround

`uv tool install xonsh[full]` works

**Comment by JamesParrott** [comment]
Looks like there have been issues with this in the past. https://xon.sh/platform-issues.html#macos-osx

Does this work?:

```
uv tool install --with gnureadline xonsh
```

If this is not a compatibility issue from PyOxidizer bundling in third party deps and not setting `__file__`, then to make Xonsh more robust the check ought not to assume the __file__ attr is there.  

There is a simple list of readline compatible libraries too.  It wouldn't be hard to insert libedit appropriately, whenever the conditions are met that mean xonsh is "supposed to use libedit", nor to introduce conditional deps.

https://github.com/xonsh/xonsh/blob/31170c2dafdec1c3208b566a6359da9f1a1b9842/xonsh/shells/readline_shell.py#L76

If a test was added to the Github Actions matrix that reproduced this https://github.com/xonsh/xonsh/actions/runs/11012987823 (e.g. by installing with uv as well as pip) then those of us without iMacs would be able to work on it.

**Comment by ilyagr** [comment]
`uv tool install --with gnureadline xonsh` works.

If I run `xonsh` with Apple's Python on a Mac, `xonsh` tells me it's using `libedit` and recommends reinstalling with `xonsh[full]`. However, this does not work for `uv`'s managed python.

**Comment by knirch** [comment]
### Attribute error

`AttributeError: module 'readline' has no attribute '__file__'. Did you mean: '__name__'?`

This happens when the module is built-in. You can see this via

```py
>>> 'readline' in sys.builtin_module_names
True
```

### ON_DARWIN
You probably also want to address the `if uses_libedit and ON_DARWIN:` test later on, as it's not limited to darwin.

### postcmd errors on libedit

The `ReadlineShell.postcmd` uses `readline.set_pre_input_hook` which is not a guaranteed method;
>readline.set_pre_input_hook([function])
> Set or remove the function invoked by the rl_pre_input_hook callback of the underlying library. If function is specified, it will be   used as the new hook function; if omitted or None, any function already installed is removed. The hook is called with no arguments after the first prompt has been printed and just before readline starts reading input characters. **_This function only exists if Python was compiled for a version of the library that supports it._**

### Reading default config 

Noted that I got `OSError: [Errno -1] Unknown error -1`. This happens when the underlying code can't read the configuration. Which for libedit happens if no config is present, or being fed invalid data. 

```py
if (not ON_WINDOWS) and (not os.path.isfile(inputrc_name)):
    inputrc_name = "/etc/inputrc"
```
will feed gnureadline config to libedit if present.

`readline.read_init_file()`
- libedit will look for `$HOME/.editrc`
- gnureadline will look for `environ[INPUTRC]`, `$HOME/.inputrc` and `/etc/inputrc`

gnureadline; without /etc/inputrc and ~/.inputrc present (python3.11)
```
>>> import readline
>>> readline.read_init_file()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory
>>> readline.read_init_file("/dev/urandom")
>>> readline.read_init_file("/dev/null")
>>>
```
libedit; without ~/.editrc present (python3.13)
```
>>> import readline
>>> readline.read_init_file()
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    readline.read_init_file()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
OSError: [Errno -1] Unknown error -1
>>> readline.read_init_file("/dev/urandom")
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    readline.read_init_file("/dev/urandom")
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
OSError: [Errno -1] Unknown error -1
>>> readline.read_init_file("/dev/null")
>>>
```
libedit raises OSError on random crap in the file
gnureadline seems to be fine with random data, but errors will appear on stderr;

```
$ cat ff.py
import readline
readline.read_init_file()
print("hi.")
$ echo "set silly off" > example
$ INPUTRC=$PWD/example python3.11 ff.py
readline: /tmp/xonsh/example: line 1: silly: unknown variable name
readline: /tmp/xonsh/example: line 1: silly: unknown variable name
hi.
$
```

Eeerh, this is snowballing. Just wanted to comment about the missing `__file__` as I ran into it as well. Hope some of this is helpful.

Cheers! (xonsh looks neat, I should give it a spin (with prompt_toolkit so I get the correct idea :D))

**Comment by balupton** [comment]
> May be [this comment](https://github.com/xonsh/xonsh/issues/5830#issue-2989665654) can help:
> 
> > Using `uv tool install xonsh --with prompt-toolkit` then `uv tool run xonsh` does not produce this crash/exit behaviour, it works as expected.

Works for me.

The earlier `uv tool install 'xonsh[full]'` would fail with:

```
      cc: error: no such file or directory: 'readline/libreadline.a'
      cc: error: no such file or directory: 'readline/libhistory.a'
      error: command '/Library/Developer/CommandLineTools/usr/bin/cc' failed with exit code 1

      hint: This usually indicates a problem with the package or the build environment.
```

**Comment by Phaiax** [comment]
The cause for the crash (`AttributeError: module 'readline' has no attribute '__file__'. Did you mean: '__name__'?`) on MacOS's python is probably the same as in #6068, namely that the readline module was a built-in version and not available as a shared library.

The linked PR #6069 will fix this. 

If it doesn't crash anymore, the generic and very helpful libedit compatability message will be shown on this MacOS setup again:

```
******************************************************************************
libedit detected - readline will not be well behaved, including but not limited to:
   * crashes on tab completion
   * incorrect history navigation
   * corrupting long-lines
   * failure to wrap or indent lines properly

It is highly recommended that you install gnureadline, which is installable with:
     xpip install gnureadline
******************************************************************************
OSError: [Errno -1] Unknown error -1
xonsh: could not load readline default init file.

                                                              Welcome to the xonsh shell 0.22.1                                                               
```
