### ISSUE TITLE
can use multiple jump in ssh 

### ISSUE THREAD

**Issue by sae13** [xonsh/xonsh#5709]
hey hi 
I have ssh config like this:
```
Host devOps
	HostName 172.16.180.27
	BindAddress 172.16.6.250

Host apps66
	HostName 10.1.254.66
	ProxyJump devOps


host estelam
	Hostname 172.16.90.97
	ProxyJump devApp01
	LocalForward 0.0.0.0:9091 127.0.0.1:9091
	ServerAliveInterval 60
```

now when I try to ssh to elastic I`m getting error

```

/sda1/home/saeb
❯ ssh elastic
<stdin>:1:4 - ssh elastic
<stdin>:1:4 + ![ssh elastic]
Trace run_subproc({'cmds': (['atuin', 'history', 'start', '--', 'ssh elastic'],), 'captured': 'stdout'})
0: {'cmd': ['atuin', 'history', 'start', '--', 'ssh elastic'], 'cls': 'subprocess.Popen', 'binary_loc': '/usr/bin/atuin', 'threadable': False, 'background': False}
Trace run_subproc({'cmds': (['ssh', 'elastic'],), 'captured': 'hiddenobject'})
0: {'cmd': ['ssh', 'elastic'], 'cls': 'subprocess.Popen', 'binary_loc': '/usr/bin/ssh', 'threadable': False, 'background': False}
<string>:1:5 - exec ssh -W '[10.1.254.160]:22' apps66
<string>:1:5 + ![exec ssh -W '[10.1.254.160]:22' apps66]
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
  File "/bin/xonsh", line 33, in <module>
    sys.exit(load_entry_point('xonsh==0.17.0', 'console_scripts', 'xonsh')())
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/main.py", line 512, in main
    sys.exit(main_xonsh(args))
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/main.py", line 563, in main_xonsh
    exc_info = run_code_with_cache(
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/codecache.py", line 226, in run_code_with_cache
    update_cache(ccode, cachefname)
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/codecache.py", line 100, in update_cache
    print_warning(
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/tools.py", line 960, in print_warning
    traceback.print_stack()
update_cache: Cache file is not writable: /home/saeb/.local/share/xonsh/xonsh_code_cache/eca953a92dd5425d415687bcb184b726.cpython-312
Set $XONSH_CACHE_SCRIPTS=0, $XONSH_CACHE_EVERYTHING=0 to disable cache.
Trace run_subproc({'cmds': (['exec', 'ssh', '-W', '[10.1.254.160]:22', 'apps66'],), 'captured': 'hiddenobject'})
0: {'cmd': ['exec', 'ssh', '-W', '[10.1.254.160]:22', 'apps66'], 'cls': 'xonsh.procs.proxies.ProcProxyThread', 'alias_name': 'exec', 'alias': <xonsh.cli_utils.ArgParserAlias object at 0x7f77eeede450>, 'threadable': True, 'background': False}
<string>:1:5 - exec ssh -W '[10.1.254.66]:22' devOps
<string>:1:5 + ![exec ssh -W '[10.1.254.66]:22' devOps]
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
  File "/bin/xonsh", line 33, in <module>
    sys.exit(load_entry_point('xonsh==0.17.0', 'console_scripts', 'xonsh')())
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/main.py", line 512, in main
    sys.exit(main_xonsh(args))
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/main.py", line 563, in main_xonsh
    exc_info = run_code_with_cache(
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/codecache.py", line 226, in run_code_with_cache
    update_cache(ccode, cachefname)
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/codecache.py", line 100, in update_cache
    print_warning(
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/tools.py", line 960, in print_warning
    traceback.print_stack()
update_cache: Cache file is not writable: /home/saeb/.local/share/xonsh/xonsh_code_cache/2f3ee22b52a2648f96dd91896841fbf9.cpython-312
Set $XONSH_CACHE_SCRIPTS=0, $XONSH_CACHE_EVERYTHING=0 to disable cache.
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/built_ins.py", line 211, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/procs/specs.py", line 1090, in run_subproc
    specs = cmds_to_specs(cmds, captured=captured, envs=envs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/procs/specs.py", line 1020, in cmds_to_specs
    spec = SubprocSpec.build(cmd, captured=captured, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/procs/specs.py", line 649, in build
    spec.resolve_binary_loc()
  File "/home/saeb/.local/lib/python3.12/site-packages/xonsh/procs/specs.py", line 749, in resolve_binary_loc
    raise Exception(f'Recursive calls to "{cmd0}" alias.')
Exception: Recursive calls to "exec" alias.
Connection closed by UNKNOWN port 65535
Connection closed by UNKNOWN port 65535
Trace run_subproc({'cmds': (['atuin', 'history', 'end', '--exit', '255', '--duration', '331230640', '--', '0192a8bf3c9478a3b7d4ab2bd2c999e4', ('>', '/dev/null'), ('2>&1',)],), 'captured': 'hiddenobject'})
0: {'cmd': ['atuin', 'history', 'end', '--exit', '255', '--duration', '331230640', '--', '0192a8bf3c9478a3b7d4ab2bd2c999e4', '>', '/dev/null', '2>&1'], 'cls': 'subprocess.Popen', 'binary_loc': '/usr/bin/atuin', 'threadable': False, 'background': False}
Trace run_subproc({'cmds': (['/usr/bin/starship', 'prompt', '--status=255', '--jobs=0', '--cmd-duration=331'],), 'captured': 'stdout'})
0: {'cmd': ['/usr/bin/starship', 'prompt', '--status=255', '--jobs=0', '--cmd-duration=331'], 'cls': 'xonsh.procs.posix.PopenThread', 'binary_loc': '/usr/bin/starship', 'threadable': True, 'background': False}
Trace run_subproc({'cmds': (['/usr/bin/starship', 'prompt', '--status=255', '--jobs=0', '--cmd-duration=331', '--right'],), 'captured': 'stdout'})
0: {'cmd': ['/usr/bin/starship', 'prompt', '--status=255', '--jobs=0', '--cmd-duration=331', '--right'], 'cls': 'xonsh.procs.posix.PopenThread', 'binary_loc': '/usr/bin/starship', 'threadable': True, 'background': False}

/sda1/home/saeb
❯



```

**Comment by g33kex** [comment]
I'm having the same issue, I think it's related to #5216
Xonsh seems to disallow subsequent exec calls, even if they do not lead to infinite depth recursion.

If your default shell is set to xonsh, the issue also happens even if you run the ssh command from a new bash shell.

A temporary fix is to start your SSH command with $SHELL set to "/bin/bash" so that exec runs in bash:
```python
 with @.env.swap(SHELL="/bin/bash"):
    ssh elastic
```

**Comment by anki-code** [comment]
@sae13 @g33kex please try with fix:
* https://github.com/xonsh/xonsh/pull/6198

```xsh
xpip install --force-reinstall -U git+https://github.com/anki-code/xonsh@anki_fix_exec
# restart xonsh
```
