### ISSUE TITLE
Infinite recursion error when loading a devenv 

### ISSUE THREAD

**Issue by cswimr** [xonsh/xonsh#5758]
## Current Behavior

When loading specifically a dotnet [`devenv`](https://devenv.sh) flake, Xonsh encounters an infinite recursion error. I considered reporting this to the xonsh-direnv repository, but judging from the traceback, the infinite recursion is occurring in Xonsh code. If this turns out to be a xonsh-direnv issue, apologies for opening the issue here.

Traceback (if applicable):

<details>

```xsh
Traceback (most recent call last):

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/events.py", line 183, in fire

    rv = handler(**kwargs)

         ^^^^^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xontrib/direnv.xsh", line 26, in __direnv_chdir

    __direnv()

    

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xontrib/direnv.xsh", line 12, in __direnv

    __xonsh__.env[k] = v

    

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/environ.py", line 2297, in __setitem__

    self._set_item(key, val)

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/environ.py", line 2318, in _set_item

    deval = detyper(val)

            ^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 1351, in env_path_to_str

    return os.pathsep.join(x)

           ^^^^^^^^^^^^^^^^^^

  File "<frozen _collections_abc>", line 1026, in __iter__

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 223, in __getitem__

    return _expandpath(self._l[item])

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 147, in _expandpath

    return expand_path(path, expand_user=expand_user)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 126, in expand_path

    s = expandvars(s)

        ^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 2484, in expandvars

    value = str(val) if detyper is None else detyper(val)

                                             ^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 1351, in env_path_to_str

    return os.pathsep.join(x)

           ^^^^^^^^^^^^^^^^^^

  File "<frozen _collections_abc>", line 1026, in __iter__

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 223, in __getitem__

    return _expandpath(self._l[item])

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 147, in _expandpath

    return expand_path(path, expand_user=expand_user)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 126, in expand_path

    s = expandvars(s)

        ^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 2484, in expandvars

    value = str(val) if detyper is None else detyper(val)

                                             ^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 1351, in env_path_to_str

    return os.pathsep.join(x)

           ^^^^^^^^^^^^^^^^^^

  File "<frozen _collections_abc>", line 1026, in __iter__

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 223, in __getitem__

    return _expandpath(self._l[item])

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 147, in _expandpath

    return expand_path(path, expand_user=expand_user)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/2r2m4g63zc051ahpclzpb4mwpmm8fl0j-python3-3.12.7-env/lib/python3.12/site-packages/xonsh/tools.py", line 126, in expand_path

    s = expandvars(s)

        ^^^^^^^^^^^^^
```
Trimmed traceback, full traceback available at https://csw.im/code/53ZQ2M.py (it is over 10,000 lines)

</details>

## Expected Behavior

The devenv flake should activate without problems. Here's a video example of it doing so with two other languages:
[UAJL0w.webm](https://github.com/user-attachments/assets/b182598b-b506-4a6e-8454-a2acf2176d72)

## xonfig

<details>

```xsh
+-----------------------------+----------------------------+
| xonsh                       | 0.19.0                     |
| Python                      | 3.12.7                     |
| PLY                         | 3.11                       |
| have readline               | True                       |
| prompt toolkit              | 3.0.48                     |
| shell type                  | prompt_toolkit             |
| history backend             | json                       |
| pygments                    | 2.18.0                     |
| on posix                    | True                       |
| on linux                    | True                       |
| distro                      | unknown                    |
| on wsl                      | False                      |
| on darwin                   | False                      |
| on windows                  | False                      |
| on cygwin                   | False                      |
| on msys2                    | False                      |
| is superuser                | False                      |
| default encoding            | utf-8                      |
| xonsh encoding              | utf-8                      |
| encoding errors             | surrogateescape            |
| xontrib 1                   | sh                         |
| xontrib 2                   | direnv                     |
| xontrib 3                   | clp                        |
| RC file 1                   | /etc/xonsh/xonshrc         |
| RC file 2                   | /etc/xonsh/rc.d/aliases.py |
| RC file 3                   | /etc/xonsh/rc.d/colors.py  |
| UPDATE_OS_ENVIRON           | True                       |
| XONSH_CAPTURE_ALWAYS        | False                      |
| XONSH_SUBPROC_OUTPUT_FORMAT | stream_lines               |
| THREAD_SUBPROCS             | True                       |
| XONSH_CACHE_SCRIPTS         | True                       |
+-----------------------------+----------------------------+
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by cswimr** [comment]
Opened an issue at https://github.com/74th/xonsh-direnv/issues/25
