### ISSUE TITLE
; kills xonsh

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#763]
```
xonshmaster=🐚 ;Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/execer.py", line 150, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/parsers/base.py", line 284, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/parsers/base.py", line 2299, in p_error
    column=p.lexpos))
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/parsers/base.py", line 379, in _parse_error
    raise err
SyntaxError: <xonsh-code>:1:0: ('code: ;',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/xonsh", line 6, in <module>
    sys.exit(xonsh.main.main())
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/main.py", line 236, in main
    shell.cmdloop()
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shell.py", line 112, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shell.py", line 81, in singleline
    display_completions_in_columns=multicolumn)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shortcuts.py", line 104, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/interface.py", line 353, in run
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/eventloop/posix.py", line 150, in run
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/terminal/vt100_input.py", line 373, in feed
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/terminal/vt100_input.py", line 292, in _input_par
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/terminal/vt100_input.py", line 325, in _call_hanr
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/interface.py", line 830, in feed_key
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/key_binding/input_processor.py", line 172, in fey
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/key_binding/input_processor.py", line 144, in _ps
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/key_binding/input_processor.py", line 187, in _cr
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/key_binding/registry.py", line 32, in call
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/key_bindings.py", line 110, in multiline_carriage_return
    carriage_return(b, event.cli)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/key_bindings.py", line 55, in carriage_return
    elif not current_line_blank and not can_compile(b.document.text):
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/key_bindings.py", line 80, in can_compile
    locs=builtins.__xonsh_ctx__)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/execer.py", line 94, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/execer.py", line 69, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/execer.py", line 191, in _parse_ctx_free
    lexer=self.parser.lexer)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/tools.py", line 147, in subproc_toks
    tok = toks[-1]
IndexError: list index out of range
```

and after that xonsh has died. In 0.2.6 (which is using readline, not prompt_toolkit), it gives the same error but doesn't die. 

Also, the traceback isn't starting on a new line.

**Comment by gforsyth** [comment]
Confirmed.  Same issue on my end, although my traceback _does_ start on a new line...

**Comment by scopatz** [comment]
To be fair this will kill Python too.  Interestingly, this is an index error in `subproc_toks()`

**Comment by gforsyth** [comment]
Yeah, the `SEMI` gets `pop()`ed and then it goes boom.

**Comment by lucasicf** [comment]
Doesn't kill Python 3.4 for me. It gives the same "invalid syntax" error whereas xonsh gives "list index out of range"

**Comment by scopatz** [comment]
So @lucasicf I think all that needs to happen here is that a `xonsh.tools.subproc_toks()` needs to check if there is an empty list after the list, and if so return None.

**Comment by lucasicf** [comment]
Thanks @scopatz I'm working on it

**Comment by lucasicf** [comment]
After I fixed the `tools.subproc_toks()` problem (returns None on only [';']), now `execer._parse_ctx_free()` tries to call `subproc_toks()` after `xonsh.parsers.v35.parse()` returns `SyntaxError`.

It happens in both 3.4 and 3.5 versions of Python.

I'll try to solve that as well. But if anyone of you have any idea I'd appreciate :)

```
Traceback (most recent call last):
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/execer.py", line 148, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/parsers/base.py", line 285, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2302, in p_error
    column=p.lexpos))
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/parsers/base.py", line 380, in _parse_error
    raise err
SyntaxError: <xonsh-code>:1:0: ('code: ;',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/linojosa/.virtualenvs/xonsh-dev/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.7', 'console_scripts', 'xonsh')()
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/main.py", line 239, in main
    shell.cmdloop()
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 111, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 80, in singleline
    display_completions_in_columns=multicolumn)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py", line 104, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 370, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 150, in run
    t()
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 373, in feed
    self._input_parser.send(c)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 292, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 325, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 899, in feed_key
    self._active_cli.input_processor.feed_key(key_press)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 172, in feed_key
    self._process_coroutine.send(key_press)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 144, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 187, in _call_handler
    handler.call(event)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/key_binding/registry.py", line 33, in call
    return self.handler(event)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/key_bindings.py", line 132, in multiline_carriage_return
    carriage_return(b, event.cli)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/key_bindings.py", line 55, in carriage_return
    elif not current_line_blank and not can_compile(b.document.text):
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/key_bindings.py", line 102, in can_compile
    locs=builtins.__xonsh_ctx__)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/execer.py", line 92, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/execer.py", line 67, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/execer.py", line 190, in _parse_ctx_free
    if sbpline.lstrip().startswith('$[$['):
AttributeError: 'NoneType' object has no attribute 'lstrip'
```

**Comment by lucasicf** [comment]
Illustrating the partial solution:

https://github.com/lucasicf/xonsh/commit/5aa97def723fc11a0c09386efe3e83c5bd0fb58e

**Comment by scopatz** [comment]
Sorry I missed this for so long @lucasicf!  Can you open a PR, please?  That really helps us keep track of these things.

**Comment by lucasicf** [comment]
Sure

https://github.com/scopatz/xonsh/pull/813

**Comment by scopatz** [comment]
Also see #891

**Comment by laerus** [comment]
This is fixed on current master
